### ISSUE TITLE
Allow default values for user.home

### ISSUE THREAD

**Issue by dcermak** [OSInside/kiwi#1025]
## Problem description

The `user` xml entry has the mandatory attribute `home`, however in most cases `/home/$username` is a sensible default. Would that be worth adding?

## Steps to reproduce the behavior

config.xml:

``` XML
<?xml version="1.0" encoding="utf-8"?>

<image schemaversion="6.9" name="JeOS-Tumbleweed">
  <users>
    <user password="this_is_soo_secure" name="me" groups="users" pwdformat="plain" />
    <user password="$1$wYJUgpM5$RXMMeASDc035eX.NbYWFl0" home="/root" name="root" groups="root"/>
  </users>

</image>
```

This will trigger an error, but for ordinary users `/home/me` is the expected home directory.

## OS and Software information
+ KIWI version: git master

**Comment by schaefi** [comment]
Sounds useful to me. Thanks

On a side note, please do not set prio flags. David and myself prioritize tasks, time and effort regularly and work on the p1 tasks, followed by p2. tasks marked as bug can cause a side track to get something fixed. Everything else gets a new prio once we are done with the other stuff.

Hope you don't mind I'll check off the prio you set, even though I would agree with the setting. Thanks

**Comment by dcermak** [comment]
> On a side note, please do not set prio flags. David and myself prioritize tasks, time and effort regularly and work on the p1 tasks, followed by p2. tasks marked as bug can cause a side track to get something fixed. Everything else gets a new prio once we are done with the other stuff.

Ups, sorry about that. I thought I'd just indicate by that, that this is not really a serious issue and more "nice to have".
