### ISSUE TITLE
"type=oem installpxe=true" resulting tarball compression is useless

### ISSUE THREAD

**Issue by seife** [OSInside/kiwi#1032]
## Problem description
When building an OEM image for PXE deployment (type=oem, installpxe=true), the result is a tarball:

    LimeJeOS-Leap-15.0.x86_64-1.15.0.install.tar.xz

which contains:

    -rw-r--r-- root/root        84 2019-03-28 14:39 LimeJeOS-Leap-15.0.append
    -rw-r--r-- root/root  31332092 2019-03-28 14:39 LimeJeOS-Leap-15.0.initrd
    lrwxrwxrwx root/root         0 2019-03-28 14:39 LimeJeOS-Leap-15.0.kernel -> pxeboot.kernel
    -rw-r--r-- root/root        45 2019-03-28 14:39 LimeJeOS-Leap-15.0.md5
    -rw-r--r-- root/root 192571296 2019-03-28 14:34 LimeJeOS-Leap-15.0.xz
    -rw-r--r-- root/root  37434560 2019-03-28 14:41 pxeboot.initrd.xz
    -rw-r--r-- root/root   7028944 2019-03-28 14:39 pxeboot.kernel

Almost everything in there is already heavily compressed, so the tarball compression just wastes time and CPU power, but does not really provide significant size savings.

## OS and Software information
+ KIWI version: current git master
+ Operating system: openSUSE Leap 15.0
+ OBS version: 

Caution: interactions with OBS need to be observed when changing this :-), but maybe obs is just using the result from "kiwi result bundle", then it might be easy.

**Comment by schaefi** [comment]
This one needs permissions by the OBS team, just set the feedback flag to not forget this

**Comment by schaefi** [comment]
@adrianschroeter any thoughts on this one ? Thanks

**Comment by adrianschroeter** [comment]
OBS is just using the bundle function.

A change here should be doable, just some external scripts need to be adapted. But we have no PXE product builds afaik.

**Comment by schaefi** [comment]
ok thanks Adrian. This is now on the todo list and we are working on it

**Comment by rpasche** [comment]
Maybe just archive it (to a tarball) but without compression. It would be quick (just seconds) and you still have only one file which contains everything.
