### ISSUE TITLE
pxe image with compressed flag bundles both result files

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi#1039]
## Problem description

Originally reported in https://bugzilla.suse.com/show_bug.cgi?id=1086257

> I have compressed PXE image

```
<type image="pxe" boot="netboot/suse-SLES12" compressed="true" .... </type>
```

> After building there are both compressed and uncompressed images.
> Then kiwi --bundle-build creates a tarball that contain both these files,
> so the size is at least doubled.

## Expected behaviour

Only keep the compressed variant if the compressed flag is set

**Comment by schaefi** [comment]
This change needs approval by the OBS team, setting the feedback flag to not forget

**Comment by schaefi** [comment]
@adrianschroeter any thoughts on this one ? Thanks

**Comment by schaefi** [comment]
This is on the todo list and we are working on it.

**Comment by davidcassany** [comment]
I don't see this issue happening in KIWI-NG, I just see it in former KIWI. I just did a PR for it there: OSInside/kiwi-legacy#678
