### ISSUE TITLE
Automate the creation of the documentation for the functions.sh methods

### ISSUE THREAD

**Issue by dcermak** [OSInside/kiwi#1060]
## Problem description

The documentation of the available functions provided by `.kconfig` in `config.sh` and `images.sh` is maintained manually in the sphinx documentation. Unsurprisingly, it has suffered quite a bit rot and **a lot** of the documented functions are nowhere to be found in the KIWI repository.

I therefore propose to use an external shell script documentation tool and link to the output of such a tool from sphinx. The result will not be as nice to look at as the current solution, but there will be less discrepancies between the documentation and the available functions.

**Comment by schaefi** [comment]
We prefer to have documentation other than api docs to be written and reviewed manually.

Sorry
