### ISSUE TITLE
Manual install of kiwi dracut packages breaks the system

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi#1103]
## Problem description

__From QA__

In reference to: https://bugzilla.suse.com/show_bug.cgi?id=1136444

During some of our (maintenance QA testing) it occured that people installed dracut-kiwi-* on testing system. This triggers regeneration of initrd, which is then not usable for booting system (and errors received are far from helpfull).

Situation when user, in good faith can install package, which without any warning can render system unusable seems rather suboptimal.

**Comment by schaefi** [comment]
I see the risk. But I don't see a good solution. Actually if you build a live image as one example the dracut-kiwi-live package must be installed in the system and also belongs there.

If you install dracut-kiwi-live on a system that should not be a live system it's gonna be a problem on boot. But the rootfs from a pure content perspective is not any different.

Thus it would be hard to clearly identify when the install would be a mistake and when it's really needed.

This applies to other kiwi dracut modules as well.

One solution could be to introduce a new dracut option e.g rd.kiwi which must be set for any kiwi dracut module to actually operate. kiwi when building an image would then set the option but standard systems out there would most probably don't have this setting. Thus the installation of dracut-kiwi-* packages would not harm the system unless they also specify rd.kiwi in their bootloader config

Thoughts ?

**Comment by davidcassany** [comment]
Just to make it explicit, we are talking about installing `dracut-kiwi-*` in the host right? If so I am really curious to know more about the details, as I could not reproduce it on my VMs. In any case I agree that probably we should have some strategy to prevent to accidentally use kiwi dracut modules in an unrelated context.

> One solution could be to introduce a new dracut option e.g rd.kiwi which must be set for any kiwi dracut module to actually operate. kiwi when building an image would then set the option but standard systems out there would most probably don't have this setting. Thus the installation of dracut-kiwi-* packages would not harm the system unless they also specify rd.kiwi in their bootloader config

I am fine with this solution, even I believe this is already kind of implicit. I just had a look to the `dracut-kiwi-live` module and, up to my understanding, it doesn't do anything unless the kernel command line includes something like `root=live:CDLABEL=*` or `root=live:AOEINTERFACE=*`. Ok, it is not as explicit as `rd.kiwi`, but it still makes me wonder how it could happen that `dracut-kiwi-live` package installed in a host (I tested it with a SLE-15 VM without having any issue) could rebuild the initrd into an inconsistent state.

Alternatively, what if we find some strategy to just do not include the modules in the initrd by default. What if in `check()` function of `module-setup.sh` we include some kiwi specific test like the existence of `/.profile` (`/.profile` is part of the build tree but not part of the resulting image root) or something similar (it could be a specific file flag just for this purpose).

The problem with this approach (if it is actually a problem) is that if we need to rebuild the initrd including kiwi modules later on after the firstboot, as they would be deactivated by default (but I'd consider it a very rare case and it could be easily worked around by adding the flag file).

Thoughts?

**Comment by Conan-Kudo** [comment]
Gating with `rd.kiwi.*` options probably makes sense for each of the modules. A simple `rd.kiwi` is likely not enough, but could be a start.

**Comment by schaefi** [comment]
@davidcassany has a way better idea to address this.

* kiwi dracut modules returns 255 in the check function. This means they are only integrated if they are required

* kiwi will be modified to call dracut always with the modules it needs: --add ...

That way users can install any kiwi dracut modules but it will not hurt
