### ISSUE TITLE
Looking for a way to set fscreateoptions for type=vmx images

### ISSUE THREAD

**Issue by dirkmueller** [OSInside/kiwi#1109]
## Problem description

I would like to customize the filesystem creation flags in my image. the usecases are for example (all ext4 as a filesystem, but this might exist in other filesystems as well, but those are less relevant to me): 

* set the default data journalling mode to writeback. While this appears to be settable via fsmountoptions="data=writeback", it actually isn't settable that way because it needs to be set in the initrd prior remounting the root fs on boot, and that isn't propagating there. Setting the default journalling mode at create achives that transparently.

* set the default journal size creation flags. Initially ext4 creates a very small journal, but it might make sense for an image that is going to be resized to specify the journal size already from the start. 

* set the flag to turn off journal on creation of ext4 filesystems. This is useful for throwaway ci jobs, where we don't want to suffer through the performance overhead of handling journalling. 

## Expected behaviour

I expect something like this:
```

    <type
        image="vmx"
        filesystem='ext4'
        bootloader='grub2'
        format='qcow2'
        vga="normal"
        boottimeout="1"
        fsmountoptions='acl,noatime,nobarrier'
        fscreateoptions='^has_journal'
        >
      <size unit='G' additive='false'>10</size>
    </type>
```

I would expect this to be passed down to **mkfs.ext4 -O ^has_journal** ... correspondingly. in order to handle journal size (which is -J) it might be a good idea to allow further options to be embedded there via

```
        fscreateoptions='-J 512MB -O ^has_journal'
```

**Comment by dcermak** [comment]
I like this idea and would actually need this to build SLE 12 based images from Tumbleweed. There I have the problem that e2fsprogs is recent enough to support the metadata-checksum feature, which is **not** supported by SLE-12 kernels (and the resulting image exits into a emergency shell, because it cannot mount the root partition). Dirk's idea would allow me to set `fscreateoptions='^metadata_csum'` and the issue would be solved.

**Comment by dcermak** [comment]
I've dug around in the code base and it appears that something like this was actually partially implemented in 27d13c555323d663977086e6d9d24021219d27fd by @schaefi.

The only part that is really missing is to take the data from a XML option and pass it on to `VolumeManager`. I've created a draft that does that in 272adb47671b6caa425023cf91f2de56bc45bf3c (still needs some tests).

**Comment by schaefi** [comment]
This is now on the todo list. Thanks Dan for starting the work. I'll checkout the branch you did and see what needs to be done to complete the implementation

**Comment by dcermak** [comment]
Cool!

My branch is unfortunately totally useless. I tried to pass the information along to `VolumeManager`, but that did not have the desired result: the flags don't get added to `mkfs.$MY_FS`.

**Comment by schaefi** [comment]
@dirkmueller part of the August sprint. So this one will be done soon. Further details on what is planned can be found here:

* https://github.com/OSInside/kiwi/projects/1

**Comment by dirkmueller** [comment]
Thanks!
