### ISSUE TITLE
BootLoaderConfigGrub2.write in EFI live images is called too late?

### ISSUE THREAD

**Issue by aplanas** [OSInside/kiwi#1112]
## Problem description

I am creating a JeOS based live image, that I expect that will work in UEFI and BIOS systems.

The image can be found here:

https://build.opensuse.org/package/show/home:aplanas:Images/openSUSE-Tumbleweed-JeOS

The logs can be found here:

https://build.opensuse.org/build/home:aplanas:Images/images/x86_64/openSUSE-Tumbleweed-JeOS:Live/_log

Investigating a jeos-firstboot issue (https://github.com/openSUSE/jeos-firstboot/pull/52), we were expecting `/etc/sysconfig/bootloader` to be present in every case, but the previous image shows that the file is missing.

Debugging kiwi I found that the `setup_sysconfig_bootloader()`, called by `BootLoaderConfigGrub2.write()` is called when the LiveOS/squashfs.img is already present, and in the `/tmp/.../live-media.XXXXXX/` directory only contains:

- EFI/
- LiveOS/
- boot/

This makes in `setup_sysconfig_bootloader` that `os.path.exists(sysconfig_bootloader_location)` do not exists anymore, and the bootloader file is not created.

I am not able to see if this is a bug or not, as the check itself suggest that is expected that the directory is not present, and the final ISO can be booted properly in EFI and BIOS systems.

## Expected behaviour

I would expect that the file `/etc/sysconfig/bootloader` is present in the media.

**Comment by schaefi** [comment]
Makes a lot sense to me and looks like a bug

**Comment by davidcassany** [comment]
@aplanas from what I understand you expect to have this file inside the squashfs container right?

**Comment by aplanas** [comment]
@davidcassany the problem, as I see, is that when the function to create `/etc/sysconfig/bootloader` is called, the tree is already gone and `LiveOS/squashfs.img` was already present.

But yes, I the expectation is that this method is called before in the EFI live image configuration, so this file is present as in the rest of configurations.

For an example of a XML where this is happening check the issue post.
