### ISSUE TITLE
Provide a vagrant_setup() shell script for use in config.sh

### ISSUE THREAD

**Issue by dcermak** [OSInside/kiwi#1127]
## Problem description

Vagrant has certain expectations towards the layout of the boxes, namely:
- the user `vagrant` exists, has passwordless sudo rights and it's password is `vagrant`
- ssh is running
- the [vagrant insecure key](https://github.com/hashicorp/vagrant/blob/master/keys/vagrant.pub) is in `/home/vagrant/.ssh/authorized_keys`.
- (optional, but usually the case) a shared folder is set up in `/vagrant/`

The necessary steps are explained in the kiwi docs, but currently every box creator has to apply them themselves. I think we should provide a shell script for usage in `config.sh` that will apply these settings.

I've had a function like that in the original PR that added virtualbox vagrant support, but that got rejected. I'm asking for that to be reconsidered, since such a function would be useful for most people. Those who have different requirements, will likely know that and won't use it.

**Comment by schaefi** [comment]
After discussing this with David we came to the conclusion that we don't want to have another shell script entry point in kiwi. It should be enough for users to see this documented as it is right now

Sorry

**Comment by dcermak** [comment]
I would humbly re-request this to be reconsidered: we are seeing a few additional folks building vagrant boxes and since the vagrant setup is essentially the same thing for every box, I see great value in this being provided by kiwi upstream. Because currently every vagrant box on OBS just copies the same functions into their config.sh, which is imho not a great state.

This is a really simple change, I'd be more than happy to send a PR myself.

**Comment by schaefi** [comment]
@dcermak sounds great, we are happy to review your pull request ;)
