### ISSUE TITLE
Add --add-bootstrap-package option

### ISSUE THREAD

**Issue by nadvornik** [OSInside/kiwi#1151]
When kiwi builds images against SUSE Manager repositories, it has to use SUSE Manager SSL certificate. For bootstrap phase it uses the certificate from host system, there is not a problem.
Then it tries to download packages from chroot and it fails with error like this:

```
DEBUG: 16:49:27 | system: Retrieving package Mesa-libglapi0-18.0.2-6.28.x86_64 (1/190), 140.6 KiB (190.3 KiB unpacked)
DEBUG: 16:49:27 | system: Retrieving: Mesa-libglapi0-18.0.2-6.28.x86_64.rpm [error]
DEBUG: 16:49:27 | system: Abort, retry, ignore? [a/r/i/...? shows all options] (a): a
DEBUG: 16:49:27 | system: Abort, retry, ignore? [a/r/i/...? shows all options] (a): a
ERROR: 16:49:27 | KiwiInstallPhaseFailed: System package installation failed: Download (curl) error for 'https://slepos-virt-53.suse.cz/rhn/manager/download/sles12-sp4-pool-x86_64/getPackage/Mesa-libglapi0-18.0.
2-6.28.x86_64.rpm?eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NjM4OTc1MzgsImlhdCI6MTU2Mzg5MzkzOCwibmJmIjoxNTYzODkzODE4LCJqdGkiOiJLXzR3aHE4c1hjZG5LZ19aVFI4bkh3Iiwib3JnIjoxLCJvbmx5Q2hhbm5lbHMiOlsic2xlLW1hbmFnZXItdG9vbHMxMi11
cGRhdGVzLXg4Nl82NC1zcDQiLCJzbGUtbWFuYWdlci10b29sczEyLXBvb2wteDg2XzY0LXNwNCIsInNsZXMxMi1zcDQtcG9vbC14ODZfNjQiLCJzbGVzMTItc3A0LXVwZGF0ZXMteDg2XzY0Il19.qtdRm1s1xoyQWjoFu7d89WlwnucDE3R5TZBpJV-VeD4':
Error code: Curl error 60
Error message: SSL certificate problem: unable to get local issuer certificate
```

As a workaround we currently ask users to add the rpm package with the certificate to bootstrap section in config.xml. This works, but every image needs to be modified.

Adding the package from commandline (by a wrapper script) would improve user experience.
The existing --add-package option can't be used because it fails earlier.

Would it be possible to add new --add-bootstrap-package option?

**Comment by schaefi** [comment]
I think this would be a good enhancement
