### ISSUE TITLE
Build based on another image

### ISSUE THREAD

**Issue by ggardet** [OSInside/kiwi#1152]
I think it is not possible yet, but maybe I am missing something?

I would like to build an image based on another one. 
My use case is for armv7 images where most images are the same, except they have different u-boot binaries installed on a partition and/or dd'ed at specific offset (outside partitions) to support various boards.
Currently we need to do a full rebuild for each board. 
Is there a mean to have a generic image and use it as a base and just install u-boot, and maybe rebuild the initrd with required modules?

**Comment by schaefi** [comment]
If you build in obs there is currently no concept for base images, except you are building containers

If you build locally you can re-use the rootfs as follows:

```
kiwi-ng system build --description ... --target-dir /my-image

... perform modifications on the rootfs in /my-image/build/image-root

kiwi-ng system build --description ... --allow-existing-root --target-dir /my-image
```

So this safes you from re-creating the entire rootfs all the time and reduces the build time.

BUT

I do not advise to do this. If you build the image from scratch you know, this is my build it is valid for this arm board, it has been proven to work there and it forms a full build for one purpose. Like in development when we go with a single responsibility per class and loosely coupling. From my experience the same applies to image builds. Yes you can do a lot to increase the performance of a build but the price you pay is high if only one single part of the "make the build fast" magic fails at some point

The performance increase for re-using the root tree is also not as much as the performance win if you run on machines that are fast in compression. You can also experiment with options to the xz
compressor which has quite some performance impact if you would accept less powerful compression results. In /etc/kiwi.yml

```
xz:
    - options: ...
```

Does this makes sense ?

Thanks

**Comment by schaefi** [comment]
Also building in memory only and on machines with fast I/O increases the build time a lot.
The bottleneck on building images is mostly in compression and I/O

**Comment by ggardet** [comment]
Thanks for your feedback. 
Yes, `xz` compression take a long time. I will have a look at `xz` options.

**Comment by schaefi** [comment]
I'll hope it's ok to close this one. Feel free to open another issue if there is room for performance tweaks that needs code changes. Thanks
