### ISSUE TITLE
LiveCD does not boot without video card

### ISSUE THREAD

**Issue by mook-as** [OSInside/kiwi#1153]
## Problem description

When a LiveCD is booted on a (virtual) machine with no video card, ISOLinux hangs on boot.

## Expected behaviour

Have some way to disable the ISOLinux menu so that boot can proceed

## Steps to reproduce the behaviour

1. Create a Live CD (Possibly with `bootloader_console="serial"`, it does not matter)
2. Attempt to boot in a VM (I used libvirt/kvm) with no video card (no `<video>` / `<graphics>` elements).
3. LiveCD does not boot, uses one core at 100%.

## Additional infomation
* Adding `console=ttyS0,115200` on the `kernelcmdline=` does not help, as it does not get to the kernel at all.
* Using direct kernel boot works fine (once it gets to the kernel, booting can continue).
* Patching [isolinux.py] to add neither `self.ui_theme` nor `self.ui_plain` fixes the issue.

Unfortunately, there is no step late enough that I might be able to munge `isolinux.cfg` manually; `images.sh` appears to run after the target root fs is built, but before the ISO layout.

I wanted to do this to try to make a boot2docker image for minikube; their [kvm config] does not have video cards.  (The GPU stuff at the end is for PCI passthrough for GPU computing, not actual video output, as far as I can tell.)

[isolinux.py]: https://github.com/OSInside/kiwi/blob/v9.17.15/kiwi/bootloader/template/isolinux.py#L178-L184
[kvm config]: https://github.com/kubernetes/minikube/blob/v1.2.0/pkg/drivers/kvm/domain.go#L32

## OS and Software information
+ KIWI version: 9.17.15 (RPM: python3-kiwi 9.17.15-lp150.2.20.10)
+ Operating system: openSUSE Leap 15.0
+ OBS version: N/A

**Comment by Conan-Kudo** [comment]
Could you please try an [up to date version from here](https://software.opensuse.org//download.html?project=Virtualization%3AAppliances%3ABuilder&package=python-kiwi)?

**Comment by mook-as** [comment]
Hi! Yes, using the version from obs://Virtualization:Appliances:Builder does not appear to make a difference.
Currently on: python3-kiwi-9.18.9-lp150.1.1.x86_64
Same symptoms: one CPU core busy, no output (on serial port).
`isolinux.cfg` still contains `ui menu.c32`.

**Comment by schaefi** [comment]
Hi, just looking at the issue we are wondering why you still see that when building with 9.18.x
Could you share your image description with us such that we can reproduce it better ?

**Comment by mook-as** [comment]
Of course! My image description is over on [f0rmiga/opensuse-minikube-image](https://github.com/f0rmiga/opensuse-minikube-image/blob/07cb1f685eb2a62940c0e6ff5c57ade9e41c6c8a/description/config.xml).  I build the whole thing via `make build-in-docker` in the top level (though I [patch out the UI bit](https://github.com/f0rmiga/opensuse-minikube-image/blob/07cb1f685eb2a62940c0e6ff5c57ade9e41c6c8a/Dockerfile#L16-L17) as a workaround until this get resolved).

Ideally I'd be able to move that to OBS later, but that's further down the roadmap :grin:

**Comment by schaefi** [comment]
@mook-as going to work on this one now. I will implement it in a way that if you set

```
bootloader_console="serial"
```

no "ui" setup will be written to the isolinux config file. I think this is the expected behavior.
Please advise when wrong :)

Thanks

**Comment by schaefi** [comment]
@mook-as would be great if you can give #1250 a review. Thanks
