### ISSUE TITLE
BootImageBase.is_prepared returns wrong type

### ISSUE THREAD

**Issue by dcermak** [OSInside/kiwi#1175]
## Problem description

`BootImageBase.is_prepared` ([kiwi/boot/image/base.py:153](https://github.com/OSInside/kiwi/blob/master/kiwi/boot/image/base.py#L153)) is documented to return a boolean, but it actually returns a list. Which part is correct, the documentation or the code?

This issue didn't get caught by the tests, because they all either mock `is_prepared` to return a boolean or they mock `os.listdir` to return a boolean (the latter is incorrect). Also, `if List` is a valid expression in python and checks whether the list is not empty, so maybe that is the actual intention of the code?

**Comment by schaefi** [comment]
> Which part is correct, the documentation or the code?

The docs, it should behave like that. I will fix this. Also the test are really poor. We even mock the wrong return for the listdir. Shame on me
