### ISSUE TITLE
kiwi-overlay issues (testing vmx and oem with overlayroot="true")

### ISSUE THREAD

**Issue by davidcassany** [OSInside/kiwi#1184]
## Problem description

Found some issues with overlayroot.

1. Building a disk image with overlayroot causes a squashed file system creation of the root-tree twice. The first one is just used to estimate the size of the squashed partition, the second one is the one producing the squashed system that will actually be part of the disk. This procedure is waste of CPU cycles. **Nice to have, it is not actually causing any functional issue**

2. ~~If the disk is not configured with a boot partition the overall build is likely to fail.~~ fixed in #1188

3. ~~We are missing the use of `-wildcards` flag to properly exclude some files (e.g. `/boot/*`).~~ fixed in #1188

4. kiwi-overlay and kiwi-repart modules are incompatible, even it is clearly stated in kiwi.rnc that overlayroot is a valid option for OEM. The issue I see is that kiwi-overlay mounts the `/run/overlayfs` in dracut-initqueue.service, however the repart tries to repart the partition in dracut-pre-mount.service that happens after. Also `kiwi-repart` is not capable to understand `root=overlay:<dev>`, as it seams to not skip the `overlay` part and runs something like:

```bash
[ ! -e "overlay:/dev/disk/by-uuid/adfaads" ]
```

to verify if the device is present or not.

## Expected behaviour

`overlayroot="true"` works fine in most/all allowed combinations in schema. That leads to the questions of: 

1. _which are the supported use cases of `overalyroot="true"`?_
2. _Is there a better strategy to estimate the squashed partition size without having to squash twice?_

I am wondering how different is a vmx (or oem) without a bootpartition comparted to hybrid ISO, both using grub, both based over a squashed filesystem with an overlay rw partition. Probably narrowing the uses of overlayroot makes sense here.

## Steps to reproduce the behaviour

Add `overlayroot="true"` in this [vmx type](https://github.com/OSInside/kiwi-descriptions/blob/2646e86fe3e5d1f917a28e7c572df99727403bfd/suse/x86_64/suse-leap-15.1-JeOS/config.xml#L24) and build it.

## OS and Software information
+ KIWI version: master
+ Operating system: Leap 15.1

**Comment by schaefi** [comment]
> I am wondering how different is a vmx (or oem) without a bootpartition comparted to hybrid ISO,
> both using grub, both based over a squashed filesystem with an overlay rw partition.

The difference is only in the layout. The partition table of a hybrid ISO is embedded into the ISO header. If we deploy on persistent storage e.g a USB stick we create the read-write partition on first boot. In a vmx image that partition already exists and will just be resized. The process to add a partition entry in the table of the ISO header is outside any standard. This can work but doesn't have to. Overall the deployment of a standard disk image that uses an overlay technology is considered more stable than doing this in an ISO.

**Comment by davidcassany** [comment]
> > I am wondering how different is a vmx (or oem) without a bootpartition comparted to hybrid ISO,
> > both using grub, both based over a squashed filesystem with an overlay rw partition.
> 
> The difference is only in the layout. The partition table of a hybrid ISO is embedded into the ISO header. If we deploy on persistent storage e.g a USB stick we create the read-write partition on first boot. In a vmx image that partition already exists and will just be resized. The process to add a partition entry in the table of the ISO header is outside any standard. This can work but doesn't have to. Overall the deployment of a standard disk image that uses an overlay technology is considered more stable than doing this in an ISO.

Yes makes sense. All in all I found yet another issue in overlay root images devoted to mksquash flags. In order to make `-e /boot/*` (to exclude the `/boot` contents) we are missing the `-wildcards` flag, otherwise mksquasfs won't expand the wildcards and treat them as part of the filename :P 

Only this with the current status should solve most of the failing cases. That was quite hidden since sometimes it was just working thanks to the small overhead we add in partition size calculation.

We definitely require an integration test for overlayroot.

**Comment by davidcassany** [comment]
@schaefi do we actually support or pretend to support kiwi-overlay in OEM images? This is far from working and I have doubts this is something we want to support. Some relevant parts of kiwi-overlay should be refactored to make it work together with kiwi-repart (and not sure if some tweaks would be required in the repart module too).

**Comment by schaefi** [comment]
> @schaefi do we actually support or pretend to support kiwi-overlay in OEM images? This is far from working and I have doubts this is something we want to support.

Hmm, actually I thought the only difference between a normal oem deployment is the resize of the read-write partition instead of the root partition. I also remember that I have tested this, but it's long time ago

**Comment by schaefi** [comment]
@davidcassany as you are working on that issue I was so free and assigned your name to it :)

The test-image-overlayroot as well as the other issues you mentioned seems to be addressed. Is there more that needs to be done here ?

I leave it up to you to decide the right time when this one can be closed

Thanks

**Comment by davidcassany** [comment]
@schaefi No I don think this is done. Points 1 and 4 are still valid.

I haven't tried OEM images with overlay since I wrote the issue and I doubt anything changed meanwhile. Thus kiwi-overlay module remains incompatible with kiwi-repart module, according to my tests. I am not sure this is something easy to solve in kiwi-overlay scope only.

Regarding the duplicated call of mksquashfs I can't see a way of solving it without a relevant refactor of the disk builder. So I guess it is just safer to assume this duplicated mksquashfs call as part of the trade-off between having a simple stable code and optimized code.
