### ISSUE TITLE
userpermissions are not fixed in config.sh

### ISSUE THREAD

**Issue by jpwidera** [OSInside/kiwi#1190]
## Problem description
Calling config.sh in the preparation does not fix user permissions.

## Expected behaviour
User permissions are set correctly

## Steps to reproduce the behaviour
Create a file, not belonging to the user and put it to root/home/$USERNAME/

## OS and Software information
+ KIWI version: 9.18.10
+ Operating system: SUSE Leap 15.0

**Comment by davidcassany** [comment]
I could not reproduce this issue... It is just working fine for me. I tried using a `root/home/user1/test_file` as plain files in my project and also tried making a tarball out of it `root.tar.gz`. In both cases the `/home/user1` folder had correct permissions and the same with the `/home/user1/test_file`.

calling something like

```
#======================================
# Set user permissions
#--------------------------------------
baseSetupUserPermissions
```

just worked fine.

**Comment by jpwidera** [comment]
Strange, what if you manually write the command from #1191 like:
```shell
usern=user1
group=user
dir=/home/user1
chown -c -R "${usern}:${group} ${dir}/*"
```
Mine respond (Leap 15.0) to it is:
```
linux-sach:/home/wera/self-installer # chown -c -R "${usern}:${group} ${dir}/*"
chown: missing operand after ‘user1:user /home/user1/*’
Try 'chown --help' for more information.
```
