### ISSUE TITLE
The full disk encryption configuration is not surviving initrd rebuilds

### ISSUE THREAD

**Issue by davidcassany** [OSInside/kiwi#1192]
## Problem description

An image that is configured with an encrypted root including /boot includes a `/.root.keyfile` in initrd to let dracut/systemd decrypt the root and mount it without asking the password (this password as already asked by grub2 in a previous stage). However, once the image is deployed if there is a rebuild of the initrd (due to a kernel or dracut update, for instance) this file is not included in it, causing the boot process to ask the password twice.

## Expected behaviour

A rebuild of the intird does not affect the boot mechanism. KIWI should follow a procedure as the one described in https://en.opensuse.org/SDB:Encrypted_root_file_system. It should add a dracut configuration file to tell dracut to include the `/.root.keyfile`. This way following initrd rebuilds will include it and do not require the luks password to mount root.

## Steps to reproduce the behaviour

Create VMX with full disk encryption, boot it and run `dracut -f` as root, then reboot.

**Comment by schaefi** [comment]
Uh you are right. When I did the implementation that part was overlooked. Thanks much for pointing it out :+1:
