### ISSUE TITLE
[closed] dracut module 'kiwi-live' 

### ISSUE THREAD

**Issue by peter-kl** [OSInside/kiwi#1199]
## Problem description
Not sure if this is a build problem or a calamares (3.2.13-30.1) situation but I have the same result running **dracut -f** and **sudo mkinitrd** after I tried to install the live iso:

>  sudo mkinitrd
Creating initrd: /boot/initrd-5.2.11-1-default
dracut: Executing: /usr/bin/dracut --logfile /var/log/YaST2/mkinitrd.log --force /boot/initrd-5.2.11-1-default 5.2.11-1-default
findmnt: can't read (null): No such file or directory
dracut: dracut module 'caps' will not be installed, because command 'capsh' could not be found!
dracut: dracut module 'dmraid' will not be installed, because command 'dmraid' could not be found!
dracut: dracut module 'multipath' will not be installed, because it's in the list to be omitted!
dracut: dracut module 'stratis' will not be installed, because command 'stratisd-init' could not be found!
dracut: dracut module 'cifs' will not be installed, because command 'mount.cifs' could not be found!
dracut: dracut module 'iscsi' will not be installed, because command 'iscsi-iname' could not be found!
dracut: dracut module 'iscsi' will not be installed, because command 'iscsiadm' could not be found!
dracut: dracut module 'iscsi' will not be installed, because command 'iscsid' could not be found!
findmnt: can't read (null): No such file or directory
dracut: dracut module 'nfs' will not be installed, because command 'rpc.statd' could not be found!
dracut: dracut module 'nfs' will not be installed, because command 'mount.nfs' could not be found!
dracut: dracut module 'nfs' will not be installed, because command 'mount.nfs4' could not be found!
dracut: dracut module 'biosdevname' will not be installed, because command 'biosdevname' could not be found!
dracut: dracut module 'kiwi-live' cannot be found or installed.
Generating  /boot/initrd-5.2.11-1-default targets failed

> dracut: Executing: /usr/bin/dracut -f
findmnt: can't read (null): No such file or directory
dracut: dracut module 'caps' will not be installed, because command 'capsh' could not be found!
dracut: dracut module 'dmraid' will not be installed, because command 'dmraid' could not be found!
dracut: dracut module 'multipath' will not be installed, because it's in the list to be omitted!
dracut: dracut module 'stratis' will not be installed, because command 'stratisd-init' could not be found!
dracut: dracut module 'cifs' will not be installed, because command 'mount.cifs' could not be found!
dracut: dracut module 'iscsi' will not be installed, because command 'iscsi-iname' could not be found!
dracut: dracut module 'iscsi' will not be installed, because command 'iscsiadm' could not be found!
dracut: dracut module 'iscsi' will not be installed, because command 'iscsid' could not be found!
findmnt: can't read (null): No such file or directory
dracut: dracut module 'nfs' will not be installed, because command 'rpc.statd' could not be found!
dracut: dracut module 'nfs' will not be installed, because command 'mount.nfs' could not be found!
dracut: dracut module 'nfs' will not be installed, because command 'mount.nfs4' could not be found!
dracut: dracut module 'biosdevname' will not be installed, because command 'biosdevname' could not be found!
dracut: dracut module 'kiwi-live' cannot be found or installed.

## OS and Software information
+ KIWI version: 
dracut-kiwi-live 9.18.12-1.1
+ Operating system:
 tumbleweed x86-64

**Comment by davidcassany** [comment]
hi @peter-kl, 

I have some doubts about the context. You are speaking of installing the live iso. What this it means? KIWI builds live iso's, making them capable to run a fresh installation of an OS to a host is out of the scope of KIWI (builds the system it doesn't play the role of an installer), I guess this is performed by Calamares in your case and configuring the installer is up to the image developer. 

I assume the dracut call is failing and thus not creating the initrd. When is it happening? during the installation from the iso to the host?

My guess is that for some reason you are pulling the dracut configuration of the live iso (which includes the kiwi-live module) to the system you are trying to installl. The kiwi-live module is provided by the package `dracut-kiwi-live` and it is required for the live iso to boot, but is definitely not needed for a non-live regular system that boots from a disk.

So, if I understood your situation correctly, you need to make sure your installer is not using the ISO specific dracut configuration on the installed host. This configuration is in `/etc/dracut.conf.d/02-livecd.conf`.

**Comment by schaefi** [comment]
I'm also pretty much confused. If we are talking about creating a live iso image check out the example from here:

* https://github.com/OSInside/kiwi-descriptions/blob/master/suse/x86_64/suse-tumbleweed-JeOS/config.xml

The kiwi-live dracut module is provided by the dracut-kiwi-live rpm package

**Comment by peter-kl** [comment]
Hi,
Ok the live Iso it's great and working fine the problem is to do with the instalation in the hd, of course I have the dracut-kiwi-live package installed that is why I do not understand the error message 
> dracut module 'kiwi-live' cannot be found or installed.

In the `/etc/dracut.conf.d/02-livecd.conf`  the only line I got is `omit_dracutmodules+=" multipath "`
So I think I'm need to closed this issue in kiwi.
Thanks

**Comment by peter-kl** [comment]
Hello,
So I was just updating an one year long iso and I was able to, using this calamares version, install it without any problems using the same configs.
Maybe something went wrong during the process of iso creation.
Check that in with more time-
Thanks.

**Comment by kevinsmia1939** [comment]
Hello there,
I have similar problem using calamares in live ISO build on KIWI. I think we might have the same problem, but since you close the issue, I assume the problem is gone for you? 

I am building live ISO based in kiwi with calamares as live installer.

`02:43:43 [0]: Starting job "dracut" 
02:43:43 [1]: Job file "/usr/lib64/calamares/modules/dracut/main.py" 
02:43:43 [1]: Job "dracut" (doc) -> "Starts routine to create initramfs. It passes back the exit code" 
02:43:43 [0]: Running "chroot" ("/tmp/calamares-root-ynln0amm", "dracut", "-f") 
02:43:44 [0]: Finished. Exit code: 1 
02:43:44 [0]: Target cmd ("dracut", "-f") 
02:43:44 [0]: Target out "dracut: Executing: /usr/bin/dracut -f\ndracut: dracut module 'caps' will not be installed, because command 'capsh' could not be found!\ndracut: dracut module 'multipath' will not be installed, because it's in the list to be omitted!\ndracut: dracut module 'stratis' will not be installed, because command 'stratisd-init' could not be found!\ndracut: dracut module 'biosdevname' will not be installed, because command 'biosdevname' could not be found!\ndracut: dracut module 'kiwi-live' cannot be found or installed." 
02:43:44 [0]: Installation failed: 
02:43:44 [0]: - message: "Failed to run dracut on the target" 
02:43:44 [0]: - details: "The exit code was 1" 
02:43:44 [0]: Calamares will quit when the dialog closes. 
02:43:44 [1]: FinishedPage::setUpRestart() 
02:46:04 [8]: Shutting down Calamares... 
02:46:04 [8]: Finished shutdown. `

**Comment by peter-kl** [comment]
Hello 
It's solved please check [calamares issues 1245](https://github.com/calamares/calamares/issues/1245)
**Resume:** we need to run a script that deletes `/etc/dracut.conf.d/02-livecd.conf` using the _shellprocess_ module before the dracut module in the `/etc/calamares/settings.conf`
Thanks.
