### ISSUE TITLE
add option to show output of config.sh

### ISSUE THREAD

**Issue by Finkregh** [OSInside/kiwi#1205]
## Problem description
i'd like to see the output of config.sh w/o enabling debug and getting too much output

## Expected behaviour
only see output of config.sh

## Steps to reproduce the behaviour
build any image

## OS and Software information
+ KIWI version: 9.17.15
+ Operating system: SLES 15.0
+ OBS version: -

**Comment by davidcassany** [comment]
This suggested feature does not convince me, honestly.

Adding a new flag to specifically only output the config.sh stdout and stderr looks like an ad-hoc solution for a very specific demand. The config.sh is easily readable in the build logs, I agree that it comes with quite some other information but it is not interleaved with anything else, thus once found the config.sh call line, getting the config.sh output is a straight read from that line.

> i'd like to see the output of config.sh w/o enabling debug and getting too much output

Is this a scrolling back on the console buffer sort of problem? What's the problem on getting more information than just config.sh? 

I don't think it is hard to find this script ouput in logs. KIWI logs are absolutely lineal, it is not a multi threaded application that interleaves stuff from several procedures at the time.

Note that using `--logfile=` will place logs to a custom location, those logs include debug information regardless of `--debug` flag usage (this only applies in stdout). Thus you can still run kiwi without debug flag, getting a reduced stdout, and read the full logs after the build for analysis, including the config.sh output.

**Comment by schaefi** [comment]
In addition to that, if you add

```
set -x
```

to your config.sh script you will get very detailed log information in the kiwi log file in case your script fails.

If you need explicit log information from your custom config.sh you also have the ability to set

```
exec 2>>some-log-file
```

So you are in a shell environment that already provides many features to log information

Thus and together with what David said I think there is no need for kiwi to add more

Hope that makes sense to you too

Thanks

**Comment by lorenzen-b1** [comment]
thanks for the answers, i still think it should be possible to get something from `config.sh` directly to kiwis' stdout :)
