### ISSUE TITLE
resize_filesystem: boot failure even if filesystem check is successful

### ISSUE THREAD

**Issue by archiecobbs** [OSInside/kiwi#1209]
## Problem description

If you've configured kiwi to auto-expand the root partition to fill all available after install (a great feature, and the default for OEM builds), then `90kiwi-repart/kiwi-repart-disk.sh` will get installed into `/usr/lib/dracut/modules.d`.

On first boot, this dracut module causes the partition resize to occur. On subsequent boots, the module executes but otherwise doesn't do anything.

However, during every execution (even when doing "nothing") the `check_filesystem` function is executed:
```
function check_filesystem {
    local device=$1
    test -n "${device}" || return
    local check_fs
    local fstype
    fstype=$(probe_filesystem "${device}")
    case ${fstype} in
    ext2|ext3|ext4)
        check_fs="e2fsck -p -f ${device}"
    ;;
    btrfs)
        check_fs="btrfsck ${device}"
    ;;
    xfs)
        check_fs="xfs_repair -n ${device}"
    ;;
    *)
        # don't know how to check this filesystem
        warn "Don't know how to check ${fstype}... skipped"
        return
    ;;
    esac
    info "Checking ${fstype} filesystem on ${device}..."
    if ! eval "${check_fs}"; then
        die "Failed to check filesystem"
    fi
}
```
In our case we have an `ext4` filesystem, so the command executed is `e2fsck -p -f ${device}`.

According to the function above, if `e2fsck` exits with any value other than zero, then the boot of the system fails and the system halts.

However, certain non-zero exit values are considered normal for `e2fsck` and should not cause the boot of the entire system to fail. Quoting the `e2fask(8)` man page:
```
EXIT CODE
       The exit code returned by e2fsck is the sum of the following conditions:
            0    - No errors
            1    - File system errors corrected
            2    - File system errors corrected, system should
                   be rebooted
            4    - File system errors left uncorrected
            8    - Operational error
            16   - Usage or syntax error
            32   - E2fsck canceled by user request
            128  - Shared library error
```

In particular:
* An exit value of 1 should not be treated as a fatal error, as this is by far the most likely exit value after a simple power failure where the system reboots and successfully repairs the unclean shutdown (note exit value zero will never occur in this situation).
* An exit value of 2 should result in a reboot

As a result of handling all non-zero values as "fatal error", kiwi puts the system in a state where a random power failure will cause the next boot to fail. The system will then hang in a powered-on but shutdown state. The only way to remedy this situation is by physical access to the server and sysadmin rebooting it. This failure mode is particularly egregious when the system is installed at a remote location and/or where Linux sysadmin expertise is not available.

Note: I've investigated `e2fsck` but not the other filesystem checkers; they probably have similar differentiated exit values which should be considered by this script.

## Expected behavior

After the first boot, the system should behave as if no resize ever occurred and boot successfully after a simple power failure.

## Steps to reproduce the behavior

1. Build system with kiwi that auto-expands root partition
2. Boot system up for the first time and let the system settle
3. Pull the power cord
4. Plug power cord back in
5. System will fail to boot with error "Failed to check filesystem". Instead, it should boot up successfully as it would if auto-expand were not used.

## OS and Software information
+ KIWI version: 9.17.14
+ Operating system: openSUSE Leap 15.0
+ OBS version:

**Comment by schaefi** [comment]
Thanks for the very detailed report. I think you are completely right. If the boot of the system has corrected fs errors and exits with 1 this should not be considered an error.

We are looking into this. Thanks

**Comment by schaefi** [comment]
@archiecobbs Hi, would be great of you can take a look at #1211 
Thanks

**Comment by archiecobbs** [comment]
@schaefi #1211 looks fine to me.

Ideally, this module would truly "do nothing" (not even a filesystem check) if no resize was necessary. This would ensure that, once the resize is complete, the behavior of the system truly matches the normal behavior, however it may change in the future.

For example, if the filesystem check fails here we halt the system, whereas you might have your system configured to normally drop into single-user mode if that happens. So this module is still changing the expected behavior.

But is may not be possible to make that determination on an unclean filesystem (chicken vs. egg situation)... I don't know how to ask a filesystem "how big are you, and if we tried to resize you would that be redundant"?

Just a thought. Thanks for addressing this issue.

**Comment by schaefi** [comment]
> Ideally, this module would truly "do nothing" (not even a filesystem check) if no resize was 
necessary. 

yes the module is actually only need on first boot to run this operation once. What you can do after first boot is run dracut again in hostonly mode. This will not include the kiwi part and also reduce the initrd size to only needed modules. I have this configured in some of my images as systemd oneshot service which just calls dracut on first boot

>But is may not be possible to make that determination on an unclean filesystem (chicken vs. egg >situation)

right, that's not so easy
