### ISSUE TITLE
Invalid warning about exposed port using "12356/tcp"

### ISSUE THREAD

**Issue by rhafer** [OSInside/kiwi#1217]
## Problem description

When using `<port number="12345/tcp"/>` to explicitly expose a tcp port in a container I get this warning:

```
./kiwi/xml_parse.py:5076: UserWarning: Value "b'11211/tcp'" does not match xsd pattern restrictions: [['^(\\d+$|^\\d+/(udp$|^tcp))$']]
  warnings_.warn('Value "%s" does not match xsd pattern restrictions: %s' % (value.encode('utf-8'), self.validate_portnum_type_patterns_, ))
```
To me the pattern used for validation here looks somewhat fishy.

## Expected behaviour

Kiwi should accept  `<port number="12345/tcp"/>`

## OS and Software information
+ KIWI version:  9.18.13
+ Operating system: Tumbleweed
+ OBS version: -

**Comment by davidcassany** [comment]
Have you verified if beyond the warning is it actually making applying the configuration?

**Comment by toabctl** [comment]
The build seems to work. See https://build.opensuse.org/package/live_build_log/home:tbechtold:openstack-containers:j2gen:SLE_15_SP1/memcached-image/images/x86_64 for an example log

**Comment by davidcassany** [comment]
Correct, this is what I expected. The values are still being passed to kiwi and we can see a correct `umoci` call in logs. Anyway I agree that we should find a way to get rid of this annoying warnings.

**Comment by davidcassany** [comment]
Currently awaiting feedback on #1230 and the generateDS issue.
