### ISSUE TITLE
Allow turning off CoW for spare_part

### ISSUE THREAD

**Issue by Vogtinator** [OSInside/kiwi#1233]
`/var` should have CoW turned off, which was previously achieved with

`<volume name="var" copy_on_write="false"/>`

Now the image is using `spare_part="5G" spare_part_mountpoint="/var" spare_part_fs="btrfs" spare_part_is_last="true"` though, where it's not possible to set it using `chattr +C` between filesystem creation and rsync.

**Comment by schaefi** [comment]
right, makes sense to me
