### ISSUE TITLE
setup USED_FS_LIST in /etc/sysconfig/storage

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi#1234]
## Problem description

There is a non obvious relation between libzypp and yast/libstorage. The latter writes USED_FS_LIST into /etc/sysconfig/storage which allows libzypp to pull in file system specific packages:

https://github.com/openSUSE/libzypp/blob/f707b97f716c8aca930e3bcc63ca80fd28f38668/zypp/sat/detail/PoolImpl.cc#L628

eg if you have a btrfs partition it would automatically pull in btrfsprogs, without the actual need to hardcode a list of package (btrfsprogs is still hardcoded in yast but that's a different story).

So I think it makes sense to set that value also in images we produce with kiwi,  just to make sure we catch any extra packages in repos that we do not explicitly preinstall.

## Expected behaviour

kiwi extends the currently written ```/etc/sysconfig/storage``` file by a new entry like:

USED_FS_LIST="btrfs vfat xfs iso9660"

**Comment by schaefi** [comment]
Bugzilla reported:

* https://bugzilla.suse.com/show_bug.cgi?id=1149544

**Comment by davidcassany** [comment]
I have concerns with this issue. I doubt this is actually in use.

I can't trace it in `libstorage-ng` neither in `yast2-storage-ng`. I have this setting on my TW laptop, but not in my Leap host neither in any of the fresh installations of TW I did today (using ext4, btrfs and btrfs + xfs as home). So I am not sure we should support it, neither I found anywhere the mechanics of this variable, I don't know how we should set it, hardcode it only for btrfs?

@lnussel do you know more details about this setting? I could see the libzypp reading it, but I could not actually find what is feeding it and how should we determine it's content.

**Comment by schaefi** [comment]
Hmm, interesting ```requiredFilesystems``` is called as part of a namespace callback if the IdType is set to NAMESPACE_FILESYSTEM.

I looked for a call in that direction in zypper, libzypp, yast, libstorage and libstorage-ng sources and couldn't find one. However that might be a poor search because looking up callbacks is not so easy because they can be constructed. So as long as we don't understand if this is actually really in use somewhere we should not maintain it in kiwi.

Moving to the backlog until it's clear how this is being used

Thanks

**Comment by schaefi** [comment]
The YaST storage developers confirmed that there is no implementation that uses it
