### ISSUE TITLE
implement WSL appx support

### ISSUE THREAD

**Issue by lnussel** [OSInside/kiwi#1235]
appx files are  used to deliver Linux distributions for WSL. Appx files are essentially zip files that contain an exe and some xml files, as well as a tarball of a Linux system. The latter part is what kiwi can already create. Just the wrapping missing. There's a [tool](https://github.com/facebook/fb-util-for-appx) to generate the appx. As a first step kiwi could simply call that tool. What we actually need is only the blocklist calculation though, so could be implemented directly in python later too.

See also https://lizards.opensuse.org/2019/10/09/opensuse-wsl-images-in-obs/

**Comment by lnussel** [comment]
maybe we can have a call so I walk you through and answer questions right away

**Comment by davidcassany** [comment]
> maybe we can have a call so I walk you through and answer questions right away

That's appreciated, give us some time to digest the basics before getting into very specific details. Is there any time frame? We are currently handling our priorities and incoming developments on a monthly basis in the [KIWI project](https://github.com/OSInside/kiwi/projects/1).

**Comment by lnussel** [comment]
Well, such metrics could maybe be provided by PM as I don't know the big picture of products. From an engineering perspective you can see in the aforementioned link that the current method to build an image using kiwi, then have a hook that generates a spec file to wrap the image in an rpm so an aggregate can move the package back the standard repo just to repackage as appx is a bit long winded :-) Also slightly hard to explain to anyone who wants to contribute. Seems natural to me to avoid those fragile hacks by having kiwi call the appx tool directly.

**Comment by schaefi** [comment]
I'm writing mge an e-mail to get more feedback on the business case here. Will come back with feedback soon

**Comment by schaefi** [comment]
@lnussel I don't know much about the windows subsystem for linux so forgive me the stupid question. If I have a docker container that is packaged as an appx, how is this considered to run on Windows if the WSL feature was activated on Windows ? I thought docker is needed to run the container. I'm surely missing the details. Thanks

**Comment by lnussel** [comment]
Not sure where the idea with the docker container comes from :-) Maybe because we're reusing some of the hacks and hooks for kiwi that were originally created to repackage docker containers produced by kiwi as rpms.

The use case here really is to take an operating system tree, pack it in a tarball. Then combine with an exe file and some meta data to produce a file called "appx". That's like a setup.exe in pre appstore Windows times.
Anyways, as I offered before I'd be happy to clarify questions in a call, turnaround times might be quicker.

**Comment by schaefi** [comment]
ok, thanks for clarification, that magic exe file is probably part of the windows subsystem for linux and allows to run linux binaries ?

>Anyways, as I offered before I'd be happy to clarify questions in a call, turnaround times might be >quicker.

yes you are right. Let me wait for mge's response and then I'd appreciate a short call together with David to put us all on the right page. Thanks

**Comment by schaefi** [comment]
ok, had a conversation with product management and there is a clear interest to broaden the support for containers. The appx "format" as it can be created with  fb-util-for-appx looks like a container format to me which is created from a root tarball. Looking at:

* https://build.opensuse.org/package/view_file/Virtualization:WSL/wsl-appx/wsl-appx.spec?expand=1

seems to populate that. Thus I suggest a new kiwi image type:

```xml
<type image="wsl"   .../>
```

Feedback welcome. Thanks

**Comment by davidcassany** [comment]
`image="wsl"` looks good to me.

I am just slightly concerned about the tooling https://gitlab.suse.de/cbosdonnat/wsl-app, I can see this was mostly handled in SLE12-SP3/Leap 42.3 era, I remember helping Cedric to get up to the current status to build root-tree tarballs for WSL images. I am wondering if this `wsl-app` is still alive and maintained, as all the few commits it has are from two years ago.

Anyway, would be nice to get some example on how use the tooling to create an appx image from a root-tree tarball. I guess @lnussel can help us on that regard, it would be fine having a sync call.

**Comment by lnussel** [comment]
The gitlab thing is old, check https://github.com/OSInside/kiwi/issues/1235#issuecomment-541624044 as I mentioned in a  previous comment.

**Comment by schaefi** [comment]
As a followup from the call we had with Ludwig I suggest the following:

1. On the kiwi XML level

  ```xml
  <type image="wsl" metadata_path="..."/>
  ```
  
  The metadata_path describes the path on the host where we can find the AppxManifest.xml
  and maybe other data that will be provided by a package. kiwi will handle the data there
  appropriately such that the appx tool can use it

2. The kiwi-requires package will be extended by a sub package:

    ```
    %package -n kiwi-image-wsl-requires
   Summary:        KIWI - buildservice host requirements for wsl images
   Group:             System/Management
   Provides:         kiwi-image:wsl
   Requires: ...
    ```

    @lnussel maybe you can fill in the needed packages

3. In kiwi we implement a class to to create the appx file. In a first step we do not add validation 
    tests on the result. In a second step we can thing of adding a validation that all files referenced in 
    the XML files of the appx are part of the archive

This is my understanding of the process. Feedback welcome

Thanks

**Comment by davidcassany** [comment]
Yes this is what I understood too.

Regarding the `metadata_path` attribute this will point to a directory containing the files needed for a distro? So it could be used with something like `metadata_path="/usr/share/wsl-meta/leap_15.1"` and KIWI gets the launcher and the xml manifest from that directory.

**Comment by lnussel** [comment]
> As a followup from the call we had with Ludwig I suggest the following:
> 
>     1. On the kiwi XML level
>        ```
>        <type image="wsl" metadata_path="..."/>
>        ```

This would also require tags to tell which packages to require on the host that  populate `metadata_path`. The `kiwi-image-wsl-requires` is not sufficient for that purpose as the metadata packages are image specific.

>     2. The kiwi-requires package will be extended by a sub package:
>        ```
>        %package -n kiwi-image-wsl-requires
>        Summary:        KIWI - buildservice host requirements for wsl images
>        Group:             System/Management
>        Provides:         kiwi-image:wsl
>        Requires: ...
>        ```
>        @lnussel maybe you can fill in the needed packages. This package will allow obs to pull in all required packages needed to create the appx

That would be `fb-util-for-appx`

**Comment by schaefi** [comment]
>This would also require tags to tell which packages to require on the host that populate >metadata_path. The kiwi-image-wsl-requires is not sufficient for that purpose as the metadata >packages are image specific.

I thought that this information could be part of the prjconf in obs. Am I correct that all the packages will install their data into the same place ? This is why I thought one metadata path is enough to get all information from one place.

The problem I see with adding the package information into the XML description is that there is no code in obs that picks that up and actually install it on the worker host

Thoughts ?

**Comment by lnussel** [comment]
> > This would also require tags to tell which packages to require on the host that populate metadata_path. The kiwi-image-wsl-requires is not sufficient for that purpose as the metadata packages are image specific.
> 
> I thought that this information could be part of the prjconf in obs. Am I correct that all the packages will install their data into the same place ? This is why I thought one metadata path is enough to get all information from one place.

So far we only build one WSL image per OBS project so the approach would work technically right now.  Seems to be counter intuitive for someone who branches the kiwi build in OBS to edit the prjconf in case different meta data is desired though

> The problem I see with adding the package information into the XML description is that there is no code in obs that picks that up and actually install it on the worker host

Well, that could be requested I guess :)

**Comment by lnussel** [comment]
> Yes this is what I understood too.
> 
> Regarding the `metadata_path` attribute this will point to a directory containing the files needed for a distro? So it could be used with something like `metadata_path="/usr/share/wsl-meta/leap_15.1"` and KIWI gets the launcher and the xml manifest from that directory.

That's what I had in mind, yes.

**Comment by schaefi** [comment]
>So far we only build one WSL image per OBS project so the approach would work technically right >now. Seems to be counter intuitive for someone who branches the kiwi build in OBS to edit the >prjconf in case different meta data is desired though

agreed. For a first implementation I think this would be ok. In a second step we can go and have a conversation with the obs team to agree on a feature such that they read the package information and act on it. When building with kiwi outside obs we use the information to validate that the host has this packages installed. We need to think more deeply how this information should be expressed in the kiwi XML description. In the obs context the packages can be installed but outside of it kiwi will not change the host, thus it will only use it to validate if they exist. I was thinking of something like:

```xml
<buildhost>
    <requires_package>X</requires_package>
</buildhost>
```

In kiwi this will be a validation step we currently don't have but would be generically useful. obs could in addition read and fulfill it.

Thoughts ?

**Comment by schaefi** [comment]
> > Yes this is what I understood too.
> > Regarding the `metadata_path` attribute this will point to a directory containing the files needed for a distro? So it could be used with something like `metadata_path="/usr/share/wsl-meta/leap_15.1"` and KIWI gets the launcher and the xml manifest from that directory.

and whatever else is there. I consider this directory as trusted source and would take whatever is in there into account

**Comment by lnussel** [comment]
> ```
> <buildhost>
>     <requires_package>X</requires_package>
> </buildhost>
> ```
> 
> In kiwi this will be a validation step we currently don't have but would be generically useful. obs could in addition read and fulfill it.

Sounds good and is basically what rpmbuild does too. It doesn't install packages but complains if requirements are not fulfilled.

**Comment by davidcassany** [comment]
> I was thinking of something like:
> 
> ```
> <buildhost>
>     <requires_package>X</requires_package>
> </buildhost>
> ```

I am not so sure, I wonder how this will work in cross distro builds, where the host and the image are not equivalent. Specially hard if package manager used by the host is not the same used by the image. Obviously this would not be a problem in OBS. Wouldn't it be possible to require just the file from an RPM perspective, thus translate `metadata_path="/usr/share/wsl-meta/leap_15.1"` to something like `Require: /usr/share/wsl-meta/leap_15.1` in OBS.

Alternatively we could also consider that all those wsl meta packages include something like `Provides: wsl-manifest` and require it in `kiwi-requires-image-wsl`, then OBS would only complain of having a choice if more than one package providing it is available within each repository stack. Including a `Prefer: some-wsl-package` on repository basis sounds reasonable to me. Specially if it is only needed when multiple providers are available for the given repository stack (it shouldn't happen that often if those package mostly include os-release like data).

Anyway I agree with @schaefi that the first step is adding the `metadata_path` and the image type in KIWI solve the requirement in OBS manually in prjconf, once having it, lets decide for any next step.

**Comment by lnussel** [comment]
:+1:
