### ISSUE TITLE
Refactor logging validation in tests

### ISSUE THREAD

**Issue by davidcassany** [OSInside/kiwi#1244]
## Problem description

Within the pytest module for python >= 3.4 there is the `caplog` fixture that can easily be used to capture log and validate the messages that were appended in logs.

So, instead of `@patch(kiwi.logger.log.warning)` and the associated `mock_warn` variable we could use directly the `caplog` fixture in tests and do something like:

```python
def test_setup_install_boot_images_efi_secure_boot(..., caplog):
  # The actual tests code
  # ...
  warn_msg = 'Running fallback setup for shim secure boot efi image'
  assert warn_msg in caplog.text
```

There should be no need to patch logging methods, just capturing the records should be enough.

**Comment by davidcassany** [comment]
@schaefi This what I thought it would be a better way to validate logs, the good thing of it is that it would be transparent to the logger code, just the messages would matter. So if we refactor logging system the tests should still pass unless the actual messages are modified. Also `caplog` and `capsys` pytest fixture include other utilities that could be handy, I just did a very quick test as in the example.

**Comment by schaefi** [comment]
yes definitely better :+1:

**Comment by schaefi** [comment]
@davidcassany I have started to refactor this in my spare time.

See the branch refactor_logging
