### ISSUE TITLE
gfxterm not found on Fedora EFI system

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi#1254]
## Problem description

When booting a Fedora appliance in EFI mode the error message:

```
error: ../../grub-core/commands/terminal.c:138:terminal `gfxterm' isn't found.
```

is shown. This results in a broken terminal up to the point when the kernel takes over the console initialization. The gfxterm grub module is installed in the system at ```/boot/grub2/x86_64-efi```.

**Comment by schaefi** [comment]
The problem does not appear on bios boot

**Comment by schaefi** [comment]
Something has changed, I can no longer reproduce this problem. I rebuild the appliance against the latest Fedora 30 repos including updates and the resulting image worked.

I guess something on the updates part has fixed it

**Comment by thmeyer** [comment]
The latest [ubuntu focal description](https://github.com/OSInside/kiwi-descriptions/tree/master/ubuntu/x86_64/ubuntu-focal) seems to produce this error, when booting in efi mode:
https://streamable.com/9f3wlg

**Comment by schaefi** [comment]
I'm working on this one today, building focal now using boxbuild and see if I can reproduce it

**Comment by thmeyer** [comment]
As mentioned on matrix:
> I only found this because virtualbox shows the message for long enough. It only appears for a very short duration when using real hardware

**Comment by schaefi** [comment]
Hmm, ok I experimented with this issue the whole day long and I can't find why this complain exists. It's very hard to debug this because in my kvm based tests the issue is shown half a second before the grub menu and everything else shows up and is also working as expected in graphics mode.

I tested building an image with ```bootloader_console="serial"``` and in that mode the "error" is not displayed. This is not much of a surprise but it also tells me the error seems to be a false positive. if gfxterm would be non-functional there wouldn't be any graphics but I see them.

Another weird thing is that I have to press the "Esc" key before the grub menu is shown. If you don't press any key the system just boots after the timeout is done without showing a menu. Maybe this is a feature on grub or the default grub setup on Ubuntu. Not sure though

Overall pretty mystery and I have no solution available to the error message.

I'm leaning towards closing this as a "wontfix"

Feedback welcome 

Thanks

**Comment by phillxnet** [comment]
@schaefi Re:

> Another weird thing is that I have to press the "Esc" key before the grub menu is shown. If you don't press any key the system just boots after the timeout is done without showing a menu. Maybe this is a feature on grub or the default grub setup on Ubuntu. Not sure though

I'm pretty sure this is default behaviour (and a grub setting) in Ubuntu as I recall having to do the same on some Ubuntu installs.

**Comment by schaefi** [comment]
@phillxnet ok, thanks much for the feedback, so this part works as designed ;)

**Comment by schaefi** [comment]
Oh I think I found the problem

**Comment by schaefi** [comment]
@phillxnet I've created a pull request which I think should fix the issue. Could you be so kind and test the patch in your local environment ? See #1703 for details. Thanks much

**Comment by phillxnet** [comment]
@schaefi Well done, however I'm afraid I'm travelling at the moment and the only setup I have to test with is a build env for our project that is based only on openSUSE images. Not fedora or Ubuntu. Plus I've no UEFI hardware to hand to test that bit 'for real'. Sorry to be letting the side down on this one.

I don't think our kiwi-ng config exercises this bug as described.
https://github.com/rockstor/rockstor-installer
given it's openSUSE host and targets.
