### ISSUE TITLE
baseStripFirmware copies only *.txt files

### ISSUE THREAD

**Issue by ggardet** [OSInside/kiwi#1256]
## Problem description
When building a JeOS image in OBS for RPi3, only *.txt firmware files are presents.
See https://bugzilla.suse.com/show_bug.cgi?id=1155155 for details.

## Expected behaviour
Required firmware should be installed.

## Steps to reproduce the behaviour
Check build log: https://build.opensuse.org/package/live_build_log/openSUSE:Factory:ARM:Live/JeOS:JeOS-raspberrypi3.aarch64/images/aarch64
Build config: https://build.opensuse.org/package/show/openSUSE:Factory:ARM:Live/JeOS:JeOS-raspberrypi3.aarch64

## OS and Software information
+ KIWI version: 9.18.16
+ Operating system: openSUSE Tumbleweed
+ OBS version: openSUSE OBS

**Comment by schaefi** [comment]
Apart from the reported issue I found some inconsistencies in your config.sh script:

* suseRemovePackagesMarkedForDeletion

   Delete that, all package deletions are handled in kiwi code natively

* baseStripFirmware

   Delete that, you are running with initrd_system="dracut". The entire method only makes sense as part of a custom boot image (initrd) description. Once you deleted that line this issue will also be resolved. Even though I'm sure you are right with your observations. The firmware strip only exists for compatibility with custom boot image descriptions

* suseConfig

  is a noop you can delete that too

Thanks

**Comment by schaefi** [comment]
But 9.18.16 has it, so I wonder what happened

**Comment by schaefi** [comment]
TW: created request id 743848

**Comment by ggardet** [comment]
> * baseStripFirmware
>   Delete that, you are running with initrd_system="dracut". The entire method only makes sense as part of a custom boot image (initrd) description. Once you deleted that line this issue will also be resolved. Even though I'm sure you are right with your observations. The firmware strip only exists for compatibility with custom boot image descriptions

It does strip firmware files on rootfs as well, that's why it is used here.

**Comment by schaefi** [comment]
> #1063 is about missing *.txt whereas this one is about only *.txt.

ok sorry I didn't looked close enough

> It does strip firmware files on rootfs as well, that's why it is used here.

Hmm, ok. I thought the firmware package was splitted into some light and full version. I think it would be more stable to prevent the stripping code. In the context of kiwi this method only existed to keep the custom initrd smaller. There is not much testing of the method and I think it has potential to break with any structure change of the firmware files and how they are provided.

We will take a look.

Thanks

**Comment by bugfinder** [comment]
well, since recently the kernel modules are compressed with xz
all the code in functions.sh needs fixing to also allow for ".ko.xz" in addition to ".ko"

**Comment by bugfinder** [comment]
please see https://github.com/OSInside/kiwi/pull/1257

**Comment by schaefi** [comment]
@ggardet Rudi fixed it. I will submit staging packages next. So if you want to see the change effective you can use the Virt:App:Staging repo in your path: v9.18.30
