### ISSUE TITLE
Please document <package name=/> takes non-names

### ISSUE THREAD

**Issue by mook-as** [OSInside/kiwi#1260]
Hello!  This is a report requested on Matrix.

## Problem description
[The documentation](https://osinside.github.io/kiwi/working_with_kiwi/xml_description.html#the-package-element) does not clearly document that `<package name=""/>` takes things that are not names.

In my case (running on openSUSE/zypper on OBS), `<package name="/usr/bin/dumb-init"/>` worked for me (as long as I have a repo that container a package with `Provides: /usr/bin/dumb-init` in the RPM spec).

## Expected behaviour
Document how to write `<packages/>` elements that pull in dependencies via things other than package names.

## Steps to reproduce the behaviour
Read the [documentation](https://osinside.github.io/kiwi/working_with_kiwi/xml_description.html#the-package-element).

## OS and Software information
+ KIWI version: 9.17.15-lp151.1.1 (on OBS)
+ Operating system: openSUSE Leap 15.1
+ OBS version: 2.11~alpha.20191112T141018.f43864e078 (build.opensuse.org)

## Additional information
My build log, which is probably irrelevant for you:
```
[   69s] [ INFO    ]: 22:14:47 | --> collection type: onlyRequired
[   69s] [ INFO    ]: 22:14:47 | --> package: /usr/bin/dumb-init
[   69s] [ INFO    ]: 22:14:47 | --> package: bosh-job-nats-nats
[   69s] [ INFO    ]: 22:14:47 | --> package: bosh-job-nats-smoke-tests
[   69s] [ DEBUG   ]: 22:14:47 | EXEC: [chroot /usr/src/packages/KIWI-docker/build/image-root zypper --non-interactive --pkg-cache-dir /var/cache/kiwi/packages --reposd-dir /var/cache/kiwi/zypper/repos --solv-cache-dir /var/cache/kiwi/zypper/solv --cache-dir /var/cache/kiwi/zypper --raw-cache-dir /var/cache/kiwi/zypper/raw --config /tmp31q7nu9i install --auto-agree-with-licenses --no-recommends /usr/bin/dumb-init bosh-job-nats-nats bosh-job-nats-smoke-tests]
[   69s] [ INFO    ]: Processing: [                                        ] 0%[ DEBUG   ]: 22:14:47 | system: Loading repository data...
[   70s] [ DEBUG   ]: 22:14:47 | system: Reading installed packages...
[   70s] [ DEBUG   ]: 22:14:48 | system: '/usr/bin/dumb-init' not found in package names. Trying capabilities.
[   70s] [ DEBUG   ]: 22:14:48 | system: Resolving package dependencies...
```

**Comment by Conan-Kudo** [comment]
This is only true for the DNF and Zypper package managers, and it only works as long as the package exists. If the OBS project configuration doesn't have a `FileProvides` stanza to translate it, then the package will just be missing.

This will not work on non-RPM package managers, as that's generally not a feature there...

**Comment by davidcassany** [comment]
I guess we could just expose that the value of `<package name="...">` will be just bypassed to the package manager, thus whatever the selected package manager supports is a candidate to be a good value.
