### ISSUE TITLE
security.selinux error while building a vagrant box

### ISSUE THREAD

**Issue by DattoDaveOps** [OSInside/kiwi#1270]
## Problem description
selinux throws error during rsync operation while installing bootstrap packages:
```
[ INFO    ]: 09:04:03 | Installing bootstrap packages
[ INFO    ]: 09:04:03 | --> collection type: onlyRequired
[ INFO    ]: 09:04:03 | --> package: apt-get
[ INFO    ]: 09:04:03 | --> package: grub2
[ INFO    ]: 09:04:03 | --> package: initramfs-tools
[ INFO    ]: 09:04:03 | --> package: linux-generic
[ ERROR   ]: 09:04:39 | KiwiDebootstrapError: KiwiCommandError: rsync: stderr: rsync: rsync_xal_set: lsetxattr("/home/dmccheyne/git/lego_local/kiwi-test/lego1/proc","security.selinux") failed: Operation not supported (95)
rsync: rsync_xal_set: lsetxattr("/home/dmccheyne/git/lego_local/kiwi-test/lego1/sys","security.selinux") failed: Permission denied (13)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1189) [sender=3.1.3]
, stdout: (no output on stdout)
[ INFO    ]: 09:04:39 | Cleaning up SystemPrepare instance
```

## Expected behaviour
Bootstrap Packages are installed and `kiwi-ng prepare` continues

## Steps to reproduce the behaviour
.kiwi file attached, Fresh Fedora 30 install, dnf install kiwi-ng
`sudo kiwi-ng --profile="virtualbox" system  prepare --description=. --root="./root"`

## Workaround
Disabled selinux, build completed successfully.

## OS and Software information
+ KIWI version: KIWI (next generation) version 9.18.31
+ Operating system: Fedora 30
+ OBS version: 

[kiwi-vagrant.zip](https://github.com/OSInside/kiwi/files/3869621/kiwi-vagrant.zip)

**Comment by davidcassany** [comment]
This must be related to some SELinux policy fedora has by default, I also faced this issue on a Fedora 29 VM I have, however it went smooth over my openSUSE Leap host, where there is no SELinux at all.

Also note that crossing distros is always tricky and should be avoided whenever possible, mostly because it raises this sort of incompatibilities. If you build ubuntu form an ubuntu host you'll have a better experience and any required tool will behave as expected.

Between I found an unrelated issue in our current master that effects ubuntu builds, gonna provide fix asap.

**Comment by davidcassany** [comment]
OK I had a second look at it and found another bug related with the debootstrap process.

We should not call rsync over '/proc' and '/sys' doesn't make sense, just bind mount, which is already the case. Gonna provide a PR for this issue.

However excluding those folder popped up another issue :disappointed: Apparently in Fedora `/bin` and `/sbin` are no longer part of the `PATH`. Thus you should append `/bin` and `/sbin` in PATH before running kiwi, ubuntu expects those to be part of the path. Core tools are in `/bin` and `/sbin`.

**Comment by Conan-Kudo** [comment]
@DattoDaveOps This might also be fixable by simply ensuring the `usrmerge` package is installed in the bootstrap phase. That makes it so it has a UsrMerged filesystem tree where those top level directories are symlinks to places in `/usr`.

**Comment by Conan-Kudo** [comment]
> However excluding those folder popped up another issue 😞 Apparently in Fedora `/bin` and `/sbin` are no longer part of the `PATH`. Thus you should append `/bin` and `/sbin` in PATH before running kiwi, ubuntu expects those to be part of the path. Core tools are in `/bin` and `/sbin`.

@DattoDaveOps This might also be fixable by simply ensuring the usrmerge package is installed in the bootstrap phase. That makes it so it has a UsrMerged filesystem tree where those top level directories are symlinks to places in /usr.
