### ISSUE TITLE
aarch64 live images fail to boot when booted from USB in qemu

### ISSUE THREAD

**Issue by ggardet** [OSInside/kiwi#1271]
## Problem description
As reported here: https://bugzilla.opensuse.org/show_bug.cgi?id=1157354
openSUSE aarch64 live images do not boot from USB (drop to grub shell) whereas they boot fine when set as hdd boot.

## Expected behaviour
Media should boot fine from USB.

## OS and Software information
+ KIWI version: 9.18.31
+ Operating system: Tumbleweed
+ OBS version: build.opensuse.org

**Comment by ggardet** [comment]
The problem is `grub.cfg` is missing from the fat filesystem `(cd0,msdos2)/efi/boot/`

**Comment by ggardet** [comment]
@davidcassany https://github.com/OSInside/kiwi/pull/1258#issuecomment-550279999 it looks like you should add `grub.cfg` on fat partition.

**Comment by davidcassany** [comment]
> @davidcassany [#1258 (comment)](https://github.com/OSInside/kiwi/pull/1258#issuecomment-550279999) it looks like you should add `grub.cfg` on fat partition.

Gonna run some tests and try to verify this fixes the issue. Would you mind testing the build when ready?

**Comment by ggardet** [comment]
> Gonna run some tests and try to verify this fixes the issue. Would you mind testing the build when ready?

I will happily test your builds.

**Comment by davidcassany** [comment]
@ggardet  I have an image building in https://build.opensuse.org/package/show/home:dcassany:branches:openSUSE:Factory:ARM:ToTest/livecd-tumbleweed-kde including a patch to add the grub.cfg as you suggested. Not sure I picked the same image that is actually failing on openQA, I hope that at least is good enough for the test.

**Comment by ggardet** [comment]
> @ggardet I have an image building in https://build.opensuse.org/package/show/home:dcassany:branches:openSUSE:Factory:ARM:ToTest/livecd-tumbleweed-kde including a patch to add the grub.cfg as you suggested. Not sure I picked the same image that is actually failing on openQA, I hope that at least is good enough for the test.

This build does work properly!
