### ISSUE TITLE
aarch64 JeOS images fail on 2nd boot - dropping to dracut shell

### ISSUE THREAD

**Issue by ggardet** [OSInside/kiwi#1274]
## Problem description
aarch64 JeOS images fail on 2nd boot - dropping to dracut shell because `systemd-fsck-root` failed with a dependency error.
See https://bugzilla.opensuse.org/show_bug.cgi?id=1156681
And openQA error: https://openqa.opensuse.org/tests/1093595#step/firstrun/4

If I revert python-kiwi to version 9.18.16, I cannot reproduce the problem.

## Expected behaviour
2nd should be fine

## Steps to reproduce the behaviour
Boot aarch64 JeOS once, reboot, 2nd boot is broken due to `systemd-fsck-root` dependency error

## OS and Software information
+ KIWI version: 9.18.31
+ Operating system: openSUSE Tumbleweed
+ OBS version: build.opensuse.org

**Comment by ggardet** [comment]
Looks like the same as https://github.com/OSInside/kiwi/pull/1269

**Comment by ggardet** [comment]
We need to push current Virtualization:Appliances:Builder/python-kiwi to Factory very soon to fix this.

**Comment by schaefi** [comment]
yes this is fixed with #1269 

The Builder project already has this published
