### ISSUE TITLE
Search for grub2-mkconfing tool in wrong paths

### ISSUE THREAD

**Issue by davidcassany** [OSInside/kiwi#1276]
## Problem description

The method kiwi/bootloader/config/grub2._get_grub_mkconfig_tool` from should be looking for the tool at the appropriate chroot instead of the current host, as this tool is only usedo chrooted environments. This not causing problems as long as the host distro and the image distro use the same tool path, however, when this is not the case the code fails.

## Expected behaviour

The `grub2-mkconfig` should be verified within the image root, not host root.

## Steps to reproduce the behaviour

Build an Ubuntu image from an openSUSE host and KIWI will fail trying to call `grub2-mkconfig` when it should be calling `grub-mkconfig`.

## OS and Software information
+ KIWI version: master
+ Operating system: openSUSE host / Ubuntu image
+ OBS version:

**Comment by davidcassany** [comment]
@schaefi I marked that one as refactoring because I think we could code it in a way that we convert/move the code from `kiwi/system/root_bind.move_to_root` to a static method in `kiwi/path` that actually just translates paths to a new root. Then this method could be used in `root_bind.move_to_root` (to keep the API as it was), but also used to manipulate the `PATH` environment variable.

**Comment by schaefi** [comment]
good catch and you are completely right. Apart from refactoring this is also a bug.
