### ISSUE TITLE
centos7 and dnf

### ISSUE THREAD

**Issue by christiansetzer** [OSInside/kiwi#1285]
## Problem description
in my image xml I used yum for packagemanager but when trying to build it searches for dnf which is not in the default repos anymore

## Expected behaviour
use yum

## OS and Software information
+ KIWI version:  9.18.35
+ Operating system: cenots7
+ OBS version:

**Comment by Conan-Kudo** [comment]
You need the CentOS Extras repo enabled for CentOS 7. You can see this in the example description we have: https://github.com/OSInside/kiwi-descriptions/blob/master/centos/x86_64/centos-07.0-JeOS/config.xml
