### ISSUE TITLE
UnicodeEncodeError in setup.py building Centos7 image on Centos7

### ISSUE THREAD

**Issue by christiansetzer** [OSInside/kiwi#1290]
## Problem description
I got the following error building a Centos7 Image on Centos7

> [ DEBUG   ]: 16:00:12 | EXEC: [rpm --root /cache/centos/build/image-root -qa --qf %{NAME}|%{EPOCH}|%{VERSION}|%{RELEASE}|%{ARCH}|%{DISTURL}|%{LICENSE}\n --dbpath /var/lib/rpm]
[ ERROR   ]: 16:00:13 | Unexpected error:
Traceback (most recent call last):
  File "/usr/local/bin/kiwi", line 11, in <module>
    load_entry_point('kiwi==9.19.5', 'console_scripts', 'kiwi-ng')()
  File "/usr/local/lib/python3.6/site-packages/kiwi/kiwi.py", line 66, in main
    App()
  File "/usr/local/lib/python3.6/site-packages/kiwi/app.py", line 35, in __init__
    task_class().process()
  File "/usr/local/lib/python3.6/site-packages/kiwi/tasks/system_build.py", line 276, in process
    result = image_builder.create()
  File "/usr/local/lib/python3.6/site-packages/kiwi/builder/disk.py", line 184, in create
    result = disk.create_disk()
  File "/usr/local/lib/python3.6/site-packages/kiwi/builder/disk.py", line 491, in create_disk
    self.target_dir
  File "/usr/local/lib/python3.6/site-packages/kiwi/system/setup.py", line 511, in export_package_list
    self._export_rpm_package_list(filename)
  File "/usr/local/lib/python3.6/site-packages/kiwi/system/setup.py", line 1009, in _export_rpm_package_list
    os.linesep.join(sorted(query_call.output.splitlines()))
**UnicodeEncodeError: 'ascii' codec can't encode character '\xa9' in position 3272: ordinal not in range(128)**
[ INFO    ]: 16:00:13 | Cleaning up BootImageDracut instance
[ INFO    ]: 16:00:13 | Cleaning up FileSystemXfs instance
[ DEBUG   ]: 16:00:13 | EXEC: [mountpoint -q /tmp/kiwi_mount_manager.vecue0m5]

## Expected behaviour
build would be successful

Quick solution was

changing line **1007** in **/usr/local/lib/python3.6/site-packages/kiwi/system/setup.py**
from
`with open(filename, 'w') as packages:`
to
`with open(filename, 'w', encoding="utf-8") as packages:`

## Steps to reproduce the behaviour
Do not know
## OS and Software information
+ KIWI version: 9.19.5
+ Operating system: Centos7
+ OBS version:

**Comment by schaefi** [comment]
Thanks, I guess you are building with py2.x right ?

Your solution suggestion sounds great to me. We will fix that.

**Comment by christiansetzer** [comment]
I installed kiwi with pip3. The modules are located under 3.6. I think the builder is python3.6.

**Comment by schaefi** [comment]
ok, thanks. I'll prepare a patch

**Comment by schaefi** [comment]
@christiansetzer ok PR is out, would be great if you can have a short look, thanks much

**Comment by christiansetzer** [comment]
For me the code looks ok since it is pretty much the same as I did. I could not figure out why this has happened in the first place though. Few days ago centos7 builds were just fine with the same setup.
