### ISSUE TITLE
Renew SLES code base

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi#1292]
**SLE12-SP5**

Update kiwi to the latest code base
https://github.com/SUSE/kiwi_sle12/ SP5 branch

**SLE15-SPX**

Update kiwi to the latest code base in December 2019
before FCS
https://github.com/SUSE/kiwi_sle15/ SP1 branch

**Comment by davidcassany** [comment]
@schaefi I do not plan to update the SP2 branch, this is confusing IMHO, specially if I am not going to submit it to SUSE:SLE-15-SP2. I believe we should just submit to SLE-15-SP1:Update and SLE-15:Update (given there is already a kiwi 9.18.16 there). Then probably we can discuss with maintenance if it makes sense keeping both SP1 and SP0. But I would not submit it to SP2, thus I would not create  SP2 branch in kiwi_sle15. 

Does it make sense?

**Comment by schaefi** [comment]
yes makes a lot sense :+1:

**Comment by schaefi** [comment]
SLES12-SP5 submission is done:

* created request id 207210

**Comment by schaefi** [comment]
Created a follow up request for SLE12 -SP5 to fix #1297 

* created request id 207259

**Comment by davidcassany** [comment]
Created SLE15 submissions:

* SLE-15:Update id 207355
* SLE-15-SP1:Update id 207356

**Comment by schaefi** [comment]
Thanks David, the submissions looks very good. All automatic checks accepted

**Comment by schaefi** [comment]
So far there is no planned release date set on the requests. Once we know about it, it can be shared here and the issue gets closed. Setting the feedback label.

**Comment by aosthof** [comment]
> SLES12-SP5 submission is done:
> 
> * created request id 207210

Tracked now in Maintenance Incident #13515: https://smelt.suse.de/incident/13515/
Planned release date is 2020-01-06

**Comment by aosthof** [comment]
> * 207259

Maintenance seems not to be aware of this request yet, iiuc this one should supersede 207210. I've informed the maintenance team by mail and copied you.

**Comment by aosthof** [comment]
> Created SLE15 submissions:
> 
> * SLE-15:Update id 207355
> * SLE-15-SP1:Update id 207356

Both are not assigned to a maintenance incident yet, I'd ping the maintenance team next week if it wouldn't make it into a MI by then yet.

**Comment by davidcassany** [comment]
Just revoked SLE15 submissions because of #1301, I'll prepare a resubmission for SLE12-SP5

**Comment by davidcassany** [comment]
Created submissions to include #1302 and #1303 

* SLE-15:Update 208525
* SLE-15-SP1:Update 208526
* SLE-12-SP5:Update 208527

**Comment by Conan-Kudo** [comment]
@davidcassany @schaefi Is it actually okay to do this? At least for SLE 12, refreshing _totally_ to the latest versions means that they get the YUM -> DNF change, and there's no possible way for that to continue working. You'd need to stop at the point before that and cherry pick from there.

**Comment by Conan-Kudo** [comment]
Or I guess alternatively, revert the YUM -> DNF change for SLE 12 because I can't get DNF properly working on SLE 12 (missing backports to rpm 4.11 in SLE 12 that exist in RHEL 7).

**Comment by schaefi** [comment]
@Conan-Kudo thanks for bringing this up. I discussed the issue with the product management team and there is no expectation or goal to make sle12 a platform to build Fedora/RHEL images. kiwi should always be able to build on distro X for distro X. The cross distro support is a plus but if not possible like in this case customers still have the chance to build in a container or in obs. If none of them will work for the customer we have to find a solution.

sle12 with SP5 is at the end of its lifetime, with the update we wanted to take the opportunity to get an up to date code base into the sle12 stream because it fixes many other issues at various ends. Loosing the cross distro support is a disadvantage I'm willing to risk

> I can't get DNF properly working on SLE 12 (missing backports to rpm 4.11 in SLE 12 that exist in > RHEL 7).

yes and that's perfectly fine for me. I'm sure if rpm on sle12 would be renewed like we try with the builder there would have been a chance to get all this running. However I don't see much motivation from people in the sle12 area to keep the enterprise product "modern". That on the other side should not cause us to be blocked or put into time intensive merge strategies.

Hope this makes sense

**Comment by schaefi** [comment]
Finally all requests have a maintenance incident ID now and a planned release date (or got already released)

SUSE:SLE-15-SP1:Update: 2020-02-11
SUSE:SLE-15:Update:         2020-02-10
SUSE:SLE-12-SP5:Update: 2020-01-06

**Comment by schaefi** [comment]
done
