### ISSUE TITLE
Custom dracut modules are required to be called as their KIWI counterpart

### ISSUE THREAD

**Issue by davidcassany** [OSInside/kiwi#1300]
## Problem description

It is not possible to build an image not including the required dracut modules since 07ea23a4. Having the options of building images without including the kiwi specific dracut modules is no longer possible as they are explicitly included within the dracut call.

In case the user aims to provide alternate dracut modules for oem repart or oem dump she/he is forced to overwrite the kiwi provided module by a custom one. Thus it is no possible to tell kiwi to just use a different module. They have to be called as the original ones, e.g. `kiwi-dump`.

This is not big issue as it is still possible to provide custom modules by overwriting the ones provided by kiwi. However, it feels like a limitation having to do so as in that case it would not be possible to hypothetically install both modules in some host, even I can't imagine a situation where this could actually happen at the moment.

## Expected behaviour

It is possible to disable the dracut modules runtime checks and build an oem image without having to explicitly include the dracut modules provided by kiwi (`kiwi-dump` and `kiwi-repart`).  

Probably they should be requested in initrd only if they are available on the root tree. The runtime checks already ensure the user is not missing them by mistake.

## Steps to reproduce the behaviour

Disable runtime checks for dracut modules and try to build an oem image with `installpxe` and without the package `dracut-kiwi-oem-dump`. When creating the PXE initrd the build process is going to fail.

Adding some `omit_dracutmodules+=" module "` does not work, because any configuration file options can be overwritten from the command line.

## OS and Software information
+ KIWI version: 9.19.7

**Comment by schaefi** [comment]
When I was talking to Jellyfrog on the Riot change I also got pointed to that. He wanted to replace the oem-dump with his own code and can only do that if he names the module the "oem-dump" because that's how we call dracut. So yes would be good to provide users more flexibility here

**Comment by davidcassany** [comment]
Yes agree, some more flexibility here is interesting, specially from a PXE perspective this quite relevant, as we should expect users to provide or use their own custom magic in such cases.

I am also wondering if we should step back and also rethink if a solution for that could be also somehow related to #1298. The approach we have now for creating PXE initrds (`installpxe="true"`) is nice in the sense that is simple and one can get it working on a simple test environment without having to setup something complex, however I can imagine that the requirements of the kernel and initrd for PXE boot might differ quite a lot from image being deployed depending on the environment, probably it is just not even tight to a single image, etc. 

Just wild thinking, but, wouldn't it make sense having some strategy to create generic PXE boot that could be used to deploy _any_ image? I know most if it is already possible, but not obvious, this also relates with #1262. Probably we just need some more flexibility in few specific aspects and some good examples.
