### ISSUE TITLE
armv6/7 images broken on dracut initrd

### ISSUE THREAD

**Issue by ggardet** [OSInside/kiwi#1308]
## Problem description
Since update to kernel 5.4, armv6/7 images are broken on dracut initrd because `(no output on stdout)` is print instead of the kernel version:
```
[ 2324s] [ INFO    ]: 05:43:01 | Creating generic dracut initrd archive
[ 2324s] [ DEBUG   ]: 05:43:01 | EXEC: [kversion /usr/src/packages/KIWI-oem/build/image-root/boot/zImage-5.4.7-1-default]
[ 2324s] [ DEBUG   ]: 05:43:01 | EXEC: [chroot /usr/src/packages/KIWI-oem/build/image-root dracut --verbose --no-hostonly --no-hostonly-cmdline --xz --install /.profile --add  kiwi-repart  --install /config.partids openSUSE-Tumbleweed-ARM-JeOS-efi.armv7l-2020.01.08.initrd.xz (no output on stdout)]
```
Full build log: 
https://build.opensuse.org/package/live_build_log/openSUSE:Factory:ARM:Live/JeOS:JeOS-efi-pxe/images/armv7l

## OS and Software information
+ KIWI version: 9.19.8
+ Operating system: openSUSE Tumbleweed
+ OBS version: build.opensuse.org

**Comment by ggardet** [comment]
The kernel update causing this is: https://build.opensuse.org/request/show/760237
`x86_64` and `aarch64` are not affected, apparently.

**Comment by ggardet** [comment]
@dirkmueller suggests a problem with `kversion`.

**Comment by ggardet** [comment]
Related bugzilla: https://bugzilla.opensuse.org/show_bug.cgi?id=1160536

**Comment by schaefi** [comment]
yes once the kernel is a zImage kversion can't read the data from the header anymore. I'd like to get rid of kversion and probably extract the version string from the file name.

**Comment by ggardet** [comment]
> yes once the kernel is a zImage kversion can't read the data from the header anymore. I'd like to get rid of kversion and probably extract the version string from the file name.

It was already a zImage previously.

**Comment by schaefi** [comment]
but we probably also had the other file around to fetch the version info ? anyway I'm looking how we can make that more stable since there is no control over any changes in that direction it has potential to break again and again

**Comment by ggardet** [comment]
> but we probably also had the other file around to fetch the version info ? 

I have no idea. Which files are checked?

**Comment by schaefi** [comment]
vmlinux-*.gz / vmlinuz-* are all candidates that works. Those files do not have the decompressor code compiled in. formats like zImage have the decompressor code compiled in and could have been compressed with any compression algorithm. The simple kversion program I wrote cannot handle those formats. I guess the change you observe now is exactly that

**Comment by ggardet** [comment]
> vmlinux-_.gz / vmlinuz-_ are all candidates that works.

There are `vmlinux-*.xz` now.

**Comment by schaefi** [comment]
yes I think I added gzip/bzip to kversion. Can you test:

```
kversion /boot/vmlinux-*.xz
```

Does that return something useful ?

Thanks

**Comment by ggardet** [comment]
`kversion vmlinux-5.4.7-1-default.xz` returns nothing with kiwi 9.19.8.

**Comment by schaefi** [comment]
ok, I'll come up with a patch. Thanks for the details

**Comment by schaefi** [comment]
@ggardet would be great if you can take a look too... sensitive code part ;)

**Comment by ggardet** [comment]
> @ggardet would be great if you can take a look too... sensitive code part ;)

LGTM :)
