### ISSUE TITLE
/usr/lib/rpm/macros.d/macros.kiwi-bootstrap-config in every layer

### ISSUE THREAD

**Issue by Vogtinator** [OSInside/kiwi#1316]
When building a derived docker image, the `/usr/lib/rpm/macros.d/macros.kiwi-bootstrap-config` file is in all layers with the same content. It should be enough to just reuse the one in the lowest layer.

**Comment by davidcassany** [comment]
I believe it should be enough if we just make sure that we do not overwrite any already existing `/usr/lib/rpm/macros.d/macros.kiwi-bootstrap-config ` file, so that if the base image already provides it it won't be rewritten during the derived one build.

**Comment by davidcassany** [comment]
I just did some tests and I could not reproduce this issue, in fact, none of the images I looked at includes the `macros.kiwi-bootstrap-config` file. I can't see the file in `registry.opensuse.org/opensuse/tumbleweed:latest` (neither in a derived image of it) and I could not also see the file in our docker tests from `Virtualization:Appliances:Images:Testing_x86:suse`.

@Vogtinator could you point me to an image facing this issue?

**Comment by Vogtinator** [comment]
Yes, it looks like the file is now deleted during build:

```[  113s] [ DEBUG   ]: 09:36:23 | EXEC: [rm -r -f /usr/src/packages/KIWI-docker/build/image-root/usr/lib/rpm/macros.d/macros.kiwi-bootstrap-config]```

The directory still exists in the upper layer though, which is probably due to mtime changes. This can be avoided by not creating the file needlessly AFAICT.

You can see the issue on https://build.opensuse.org/package/show/openSUSE:Templates:Images:Tumbleweed/openSUSE-Tumbleweed-Container-kiwi

**Comment by davidcassany** [comment]
I doubt we can do much in that case... which tool are you using for evaluating the layers content? `container-diff`, `dive`, some other? I'll test if ensuring that no empty macros file creation help, but I doubt we can do much more. Those macros are required to ensure cross distro builds are possible.

Also I noticed that your derived image includes a  `bootstrap`  section, which IMHO should not be there. If you are using a base image, in general, this is already bootstrapped, thus no need to bootstrap again (so avoid the rpm bootstrap macros). I believe in only very specific use cases might have sense to boostrap a derived image.

**Comment by Vogtinator** [comment]
> I doubt we can do much in that case... which tool are you using for evaluating the layers content? container-diff, dive, some other? I'll test if ensuring that no empty macros file creation help, but I doubt we can do much more. Those macros are required to ensure cross distro builds are possible.

Ark, so just a plain archive viewer to look at the individual layer tarballs.

> Also I noticed that your derived image includes a bootstrap section, which IMHO should not be there. If you are using a base image, in general, this is already bootstrapped, thus no need to bootstrap again (so avoid the rpm bootstrap macros). I believe in only very specific use cases might have sense to boostrap a derived image.

We have base images which do not include zypper, rpm, etc., but instead only busybox-based binaries, those can only use bootstrap as uninstalling zypper later is not possible (https://github.com/OSInside/kiwi/issues/915).
