### ISSUE TITLE
Add support for powerPC disk images

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi#1325]
## Problem description

IBM Cloud systems are ppc64le based and boots through KVM. At the moment kiwi can't build
images for this target for several reasons which needs individual investigations each. We got a testing system from Mike Friesenegger which allows to run tests. This issue should be used as reference for all problem we will find.

## Expected behaviour

- [x] ppc64le supported for vmx image types
- [x] optional boot from real hardware if available
- [x] at least one integration test exists for the platform

**Comment by Conan-Kudo** [comment]
We should make sure ppc64le works for both Fedora and openSUSE...

**Comment by schaefi** [comment]
>    We should make sure ppc64le works for both Fedora and openSUSE...

I agree completely. Nothing we do should be distro exclusive. From the current
patch, do you see anything that limits it to a certain distro ?

I would love to also test on Fedora(ppc64le) but so far couldn't
come up with an easy way to setup a machine for testing. At the moment
I got a test system for sle12 setup by one of my colleagues who has
access to hardware

Thanks

**Comment by Conan-Kudo** [comment]
@schaefi If you have a Fedora account and become a packager, you can use the Fedora dev/test resources for non-x86 arches: https://fedoraproject.org/wiki/Test_Machine_Resources_For_Package_Maintainers

**Comment by schaefi** [comment]
Thanks, actually something I wanted to do some time ago. Done now. I did not join a group since I couldn't find something matching (imaging, virtualization, pubcloud) or similar does not exist. Also I do not maintain a fedora package so far. Maybe we clarify this elsewhere ? JFI: username is "osinside" :) all other attempts were taken

**Comment by Conan-Kudo** [comment]
@schaefi Even `schaefi`?

**Comment by Conan-Kudo** [comment]
@schaefi there is a cloud group, it's part of the Fedora Server WG: https://fedoraproject.org/wiki/Server

**Comment by schaefi** [comment]
> @schaefi Even `schaefi`?

yes

**Comment by schaefi** [comment]
I'm just reading to how this all works. For getting access to machines I think you have to be part
of the packager team: https://fedoraproject.org/wiki/SIGs/Package_Review

I'm thinking to become kind of a co maintainer to the kiwi2 package as you maintain it for Fedora if I got that all right.. but need to read all the joining information first

**Comment by Conan-Kudo** [comment]
@schaefi That's weird, because I looked up `schaefi` and it said it didn't exist...

**Comment by schaefi** [comment]
I could imagine after some trials the page also timed out... not sure

**Comment by Conan-Kudo** [comment]
@schaefi You should try again, but you'll need to change the email address associated with `osinside` first before trying.

**Comment by schaefi** [comment]
Latest change also made real power8 hardware to boot

**Comment by schaefi** [comment]
I got confirmation from IBM that also the SLES build images worked fine for them. This completes the implementation. We need to update kiwi in SLES to get the updates from Virtualization:Appliances into the SUSE namespace. We track this as a combined effort next
