### ISSUE TITLE
Documentation: OEM PXE boot images, .append and .config.bootoptions

### ISSUE THREAD

**Issue by aplanas** [OSInside/kiwi#1346]
## Problem description

The OEM documentation is describing how to configure the boot server, but there are some mismatches with the current status:

* For the boot system image is referencing the .config.bootoptions file:

```
scp LimeJeOS-Leap-15.1.x86_64-1.15.1.config.bootoptions PXE_SERVER_IP:/srv/tftpboot/image/
```

As today, this file is not present under this name, but with the `pxeboot.` prefix, that indicate that is part of the initial pxeboot process:

```
pxeboot.LimeJeOS-Leap-15.1.x86_64-1.15.1.config.bootoptions
```

There is also a new file, with extension `.append`, and there is missing documentation about where this file belongs, and where needs to be copied.

```
LimeJeOS-Leap-15.1.x86_64-1.15.1.append
```

## Steps to reproduce the behaviour

Untar this one: https://download.opensuse.org/repositories/systemsmanagement:/yomi/images_pxe/

**Comment by schaefi** [comment]
Partially fixed in #1365

**Comment by schaefi** [comment]
We need to restructure the documentation in order to address this issue best

1. The following two chapters needs to be moved into its own category

    * https://osinside.github.io/kiwi/working_with_images/pxe_client_configuration.html
    * https://osinside.github.io/kiwi/building/build_pxe_root_filesystem.html

    I suggest to move it under a new category named "Build PXE images for the kiwi legacy netboot infrastructure"

2. We should write a new chapter that covers the basics of "Build KMR images" where KMR stands for Kernel., Machine and Initrd

The names are still to be changeable :-)

**Comment by schaefi** [comment]
This is related to #1262
