### ISSUE TITLE
JeOS: wrong order: /boot/grub2/arm64-efi specified before /boot

### ISSUE THREAD

**Issue by ggardet** [OSInside/kiwi#1349]
## Problem description
`findmnt --verbose --verify` reports issue with mounts in /boot
See bug report for details: https://bugzilla.opensuse.org/show_bug.cgi?id=1164310

## Expected behaviour
`/boot` should probably be declared before `/boot/grub2/arm64-efi`

## Steps to reproduce the behaviour
Boot a JeOS image built with btrfs and run `findmnt --verbose --verify`.

## OS and Software information
+ KIWI version: 9.19.16
+ Operating system: openSUSE Tumbleweed
+ OBS version: build.opensuse.org

**Comment by ggardet** [comment]
The problem seems to be due to `/boot` being a separate partition. When I drop the separate partition to just use a btrfs `/` partition, there is no problem anymore.

**Comment by davidcassany** [comment]
Right, I managed to reproduce this behavior, even I doubt this is a sane configuration. In any cas KIWI looks like is not properly ordering fstab entries. Gonna check it.

**Comment by schaefi** [comment]
I guess /boot/grub2/arm64-efi is specified as a subvolume.

I made a patch for volumes order in #1317. Can you double check if you built with a kiwi version that had this fix and if not check if it solves your problem ?

Thanks

**Comment by schaefi** [comment]
> KIWI version: 9.19.16

according to that information the patch should be effective... so maybe yet another ordering problem

**Comment by schaefi** [comment]
In ```def _write_generic_fstab``` you can see that /boot is added after the volumes. Thus if the volume setup defines a boot volume the order is wrong :(

The extra boot partition should be added before the volumes
