### ISSUE TITLE
If snapshots are enabled, a /boot partition should be disabled by default

### ISSUE THREAD

**Issue by Vogtinator** [OSInside/kiwi#1351]
Currently even if btrfs and snapshots are enabled, it creates a separate partition for `/boot` unless `bootpartition="false"` is explicitly set.

For snapshots and rollbacks to work properly, `/boot` has to be part of the snapshots, so can't be on a separate partition. The default should be adjusted.

**Comment by Conan-Kudo** [comment]
I'm not sure if that makes sense. Most distributions do not have the SUSE boot to snapshot patches (since nobody is upstreaming them in GRUB), so in most cases, `/boot` _needs_ to be a separate partition. Is it really that painful to set the flag for SUSE/openSUSE images?

I'd be willing to support changing the default if the boot to snapshot feature was actually present in upstream GRUB, but for now, I think it makes sense to keep the default as-is.

**Comment by Vogtinator** [comment]
Using snapshots with `/boot` on a separate partitions can't work. The kernel is part of `/boot` while the modules are part of the snapshot, which means modules which aren't built-in or in the initrd can't be loaded and the system is likely unusable.

The issue I have is that currently it's not clearly visible to image maintainers how broken their (open)SUSE image is - until they want to rollback.

So what I propose is that at least in the btrfs + snapshot enabled case `/boot` is by default a subvolume. For the "most distributions" you're referencing, snapshots are not enabled by default, so for those the behaviour would be unchanged.

**Comment by Conan-Kudo** [comment]
@Vogtinator It can, because it has the same effect as has having `/boot` as a subvolume. You do that so that it isn't snapshotted with the rest of `/`.

**Comment by Vogtinator** [comment]
Erm, of course I meant `/boot` is by default part of `/` and neither a subvolume nor snapshot.

**Comment by Conan-Kudo** [comment]
@Vogtinator so you want a way for `/boot` to be a subvolume (and _not_ a partition) when snapshots are enabled?

**Comment by Vogtinator** [comment]
> @Vogtinator so you want a way for /boot to be a subvolume (and not a partition) when snapshots are enabled?

No - I want that by default `/boot` is neither a snapshot nor a subvolume if `btrfs_root_is_snapshot` is set to true, unless requested otherwise.
