### ISSUE TITLE
curl error 60 with repo selfsigned cert

### ISSUE THREAD

**Issue by danja95** [OSInside/kiwi#1355]
## Problem description
I have trouble to build a image, when repo is only reachable over a self signed https connection. there is no other possible way to do this.

## Expected behaviour
curl should use certs from <builddir>/chroot/etc/ca-bundle.pem so it can download packages.
it is verifyed that my self signed cert is in that path.

## Steps to reproduce the behaviour
Goto Suse Manager and try to build a image.

## OS and Software information
+ KIWI version: 7.04.53
+ Operating system: SUSE SLES12 SP5
+ OBS version: not installed.

## Log
<builddir>/chroot/.log
Retrieving: busybox-1.21.1-3.3.x86_64.rpm ...............................error
Download (curl) error for 'https://suma.bogus/rhn/manager/download/sles12-sp4-pool-x86_64/getPackage/NULL/<other string>/busybox-1.21.1-3.3.x86_64.rpm?<long string>':
Error code: Curl error 60
Error message: SSL certificate problem: unable to get local issuer certificate

**Comment by schaefi** [comment]
I think this issue targets more on the suse manager side. iirc suse manager code handles the repos. Next I see you are using kiwi v7.x.x which is the legacy kiwi version in maintenance mode. If this is something that needs kiwi's attention the right repo would be here: https://github.com/OSInside/kiwi-legacy

Please double check with the suse manager team first. Thanks much
