### ISSUE TITLE
system provided editbootinstall script

### ISSUE THREAD

**Issue by lnussel** [OSInside/kiwi#1366]
## Problem description

Several ARM image builds contain editbootinstall scripts for specific boards like rpi or pine. Looks like so far those files have to be next to the kiwi file ie can't be packaged, therefore get duplicated all over the place.
eg

https://build.opensuse.org/package/show/openSUSE:Factory/openSUSE-MicroOS
https://build.opensuse.org/package/show/openSUSE:Factory/kiwi-templates-JeOS
https://build.opensuse.org/package/show/home:duwe:Teres-I/Teres-I-image
which seem to be subsets of scripts in
https://build.opensuse.org/package/show/openSUSE:Factory:ARM:Live/JeOS

## Expected behaviour

either allow to specify an absolute path or alternatively try a global location on the host if the script cannot be found in the current directory.

**Comment by schaefi** [comment]
The editbootinstall and editbootconfig attributes allows to run the given scripts as root at a certain stage of the bootloader configuration. They exist only to manage bootloader configurations that are very specific or even board specific like on arm. By no means this usually pretty bad code of this scripts should be packaged or taken by kiwi from some other place than the image description.

The code of these scripts belongs to the image description and that's where the author of the image descriptions should maintain it. If you place image descriptions in git and work with obs source services such duplication can be avoided.

There are also other scripts named config.sh and images.sh which belongs to the image description and for which the same applies. I know people copy obs image descriptions and also copy the mistakes of rotten code but we will not allow to source information that belongs to the image description from any other place.

I'm sorry
