### ISSUE TITLE
Support optional package installation

### ISSUE THREAD

**Issue by aaannz** [OSInside/kiwi#1383]
## Problem description

There is a new package in SLE15SP2, which was not present in SLE15 and SLE15SP1 (plymouth-plugin-label-ft).
I would like to have a way to specify in the config.xml that this package should be installed if is available, but if it is not available it is safe to ignore it.

So that I can use the same image template for the SLE15SP1 and SLE15SP2 versions.

## Expected behaviour

Some way to specify package installation is optional, like:
```xml
<packages>
  <package name="plymouth-plugin-label-ft" optional="true" />
</packages>
```

**Comment by davidcassany** [comment]
Honestly I am not sure about this feature.

I understand your use case, however the gap between different code stream might be huge and thus different image descriptions required, we can't prevent that in KIWI. Note that now this is just this package, but then later on something else will raise and probably not that simple as installing or not a package.

Then I am also wondering why is actually this package is not a dependency of something else so probably there are changes to solve that at packaging level. I imagine that whatever requires it on SLE15-SP2 does not require it on SLE15-SP1.

Anyway, what you are after it is already possible by using profiles. I'd suggest to use a profile for SLE15-SP1 and another one for SLE15-SP2. This way you can influence the package list for each profile.

```
<packages type="image" profiles="SLE15-SP2">
  <package name="plymouth-plugin-label-ft">
</packages>
```

With the above the packages listed under `SLE15-SP2` profile will only be applied for that profile together with all the packages that are not filtered by any profile.

Are you building on OBS? profiles can be applied there too by configuring the `_multibuild` config file and some other little details.

**Comment by aaannz** [comment]
Profiles is the right idea in this case, you are right. This option slipped my mind.

> Are you building on OBS?

Unfortunately not, I'm using SUMA to build kiwi images and there is not yet support to call different profiles, but that is on us.

**Comment by davidcassany** [comment]
> Profiles is the right idea in this case, you are right. This option slipped my mind.

Great, then I am closing this issue. Feel free to reopen if needed or ask for help if in doubt.

**Comment by Vogtinator** [comment]
I'd also argue that "optional dependencies" are a misfeature as it makes image building nondeterministic.

The proper way to solve the particular issue with `plymouth-plugin-label-ft` would be to have it required by a pattern depending on `0%{?sle_version} >= 150200`. That way image dependencies can be set "programatically".

**Comment by aaannz** [comment]
Sorry to hijack the space.

>  The proper way to solve the particular issue with plymouth-plugin-label-ft would be to have it required by a pattern depending on 0%{?sle_version} >= 150200. That way image dependencies can be set "programatically".

What patterns do you have in mind? We don't have/install any custom patterns in our images ( see https://github.com/SUSE/manager-build-profiles/tree/master/OSImage ), only base-minimal_base and gnome.
As `plymouth-plugin-label-ft` for some reason ended in PackageHub for 15 and 15SP1, SLE does not need it. I doubt they are willing to add it to some base SLE pattern. It is relevant so far only for our retail images as we need to print important information for users when accepting salt minion keys.

**Comment by Vogtinator** [comment]
> What patterns do you have in mind? We don't have/install any custom patterns in our images ( see https://github.com/SUSE/manager-build-profiles/tree/master/OSImage ), only base-minimal_base and gnome.

You'd create and use a pattern of your own for this.

> As plymouth-plugin-label-ft for some reason ended in PackageHub for 15 and 15SP1, SLE does not need it. I doubt they are willing to add it to some base SLE pattern. It is relevant so far only for our retail images as we need to print important information for users when accepting salt minion keys.

How ironic, given that literally the ONLY reason plymouth was marked as mandatory for SLE was the ability to show text. Please raise this topic.
