### ISSUE TITLE
Add configurable GRUB serial settings

### ISSUE THREAD

**Issue by nickhuber** [OSInside/kiwi#1401]
## Problem description

The GRUB serial speeds are always set to 9600 baud. from

        self.header_serial = dedent('''
            serial --speed=9600 --unit=0 --word=8 --parity=no --stop=1
        ''').strip() + os.linesep

in bootloader/template/grub2.py

## Expected behaviour

The GRUB serial speeds should be configurable in the XML configuration.

## Steps to reproduce the behaviour

Make an ISO with ``console=ttyS0,115200n8`` on the kernelcmdline, and fail to see the GRUB menu because of the mismatched serial settings

## OS and Software information
+ KIWI version: 9.20.5
+ Operating system: Fedora 31
+ OBS version: N/A

**Comment by schaefi** [comment]
yes you are right, we should make this more configurable

**Comment by jloeser** [comment]
Would it make sense to introduce a bootloader element with respective attributes?

```
<type image="oem" bootloader="grub2" ...>
  <bootloader speed="115200" parity="false" ... timeout="0"/>
  ...
```
(this could also tackle https://github.com/OSInside/kiwi/issues/1404)

Alternatively we could use the kernel's parameter format:
```
console=         ...
                        Use the specified serial port.  The options are of
                        the form "bbbbpnf", where "bbbb" is the baud rate,
                        "p" is parity ("n", "o", or "e"), "n" is number of
                        bits, and "f" is flow control ("r" for RTS or
                        omit it).  Default is "9600n8".
```
```
<... bootloader_serial="115200n8" ...>
```

The former one looks more promising to me - but I am not that familiar with this XML scheme stuff. What's your guy's opinion on that?

**Comment by davidcassany** [comment]
What I am wondering if it makes sense to use different parameters for the kernel command line and bootloader. Should we force them to be equivalent? If so I'd say that probably the best option is parsing the `kernelcmdline` and use the `console=` definition from there if present, if not use the current defaults.

But if there is not need to enforce serial console to be equivalent in kernel command and the bootloader I'd say we can add a new attribute to set if for the bootloader. I like the idea to use the kernel notation because I'd say users are already quite familiar with it and in most cases I'd say they want the kernel paramters to be equivalent with the bootloader paramters.

To me the real question is if we want to enforce the bootloader serial configuration to match whatever is configured within the kernel command line. At first sight looks like there is no need, but I also can't the use case of having them different. I find it cumbersome for users having to specify it twice even it doesn't look that bad and I'd say it is easy to understand.

```
<type image="iso" bootloader_console="serial" bootloader_serial="115200n8" kernelcmdline="console=ttS0,115200n8">
```

@schaefi do you have any thoughts about it?

**Comment by schaefi** [comment]
I think you both have good points. @jloeser also mentioned #1404 which requires a similar change. I think the type section already has too many attributes and some of them really belongs into a subsection. However if we go that route the changes will be not small and we also need an XSLT transformation.

What we should not do imho is to divide the bootloader settings into attributes scope. ``` speed="115200" parity="false"``` This is nice from a readers point of view but I know that bootloaders have no schema or specs for parameters. They change whatever they like without keeping an eye on formatting. For us this means we would introduce a format that we have to maintain no matter how parameters will change on the bootloader implementation. The risk to run into a situation that the existing attributes doesn't allow to map them into a bootloader setting exists and it will end in a mess on our side which I'd like to avoid. From that perspective I would prefer ```bootloader_serial="115200n8"``` as @davidcassany mentioned.

Ideally we could describe this in a new subsection like this

```xml
<bootloader name="grub2" console="serial" serial_line="115200n8" timeout="10"/>
```

This also allows us to set schema tron rules to differentiate allowed attributes per loader
For example on s390 there is zipl

```xml
bootloader name="zipl" targettype="CDL|LDL"/>
```

We would be able to handle all bootloader relevant settings in a new subsection which I think would make sense

Thoughts ?

**Comment by schaefi** [comment]
There are the following attributes in type that imho belongs to bootloader

* bootloader_console
* boottimeout
* zipl_targettype

For those we need a transformation, this is possible via XSLT

**Comment by davidcassany** [comment]
> We would be able to handle all bootloader relevant settings in a new subsection which I think would make sense

Yes I think this makes complete sense. Then I'd say we could eventually split the work in two different items. First one, refactor the current schema to a new one with the bootloader section, new schema version. Then once this is done, address this current issue by adding a new attribute (`serial_line` looks good to me) into the boolader section. I think it is clear we want to use the same notation used for the kernel parameters, hopefully this won't change much or often over time.

**Comment by schaefi** [comment]
I agree, let me try to come up with the refactoring change, my xslt is rusty and needs some training :)

**Comment by schaefi** [comment]
Looking into this now
