### ISSUE TITLE
Refactor disk resize

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi#1406]
## Problem description

The current way to resize the disk is based on parted for machines with GPT and MSDOS tables. We put on parted because one tool could handle both table types. However using parted requires us to calculate start/end addresses ourselves and pass them along as parameters. Apart from the fact that this code in the initrd is very sensitive it should imho also be not the job of the resize code. I'd like to see the tooling to be able to validate size information properly which can be done with tools written for the dedicated partition tables, e.g gdisk for GPT and fdisk for msdos. The way the kiwi oem-repart module contains the partition size requests is already in form that allows easy consumption by those tools.

Also the distinguished partition tools have code to handle different types of storage disks that do not have a real C/H/S layout like it's the case for SSD's, SD cards, USB sticks and so on. The virtual C/H/S mapping is something parted does not deal well with.

For other architectures like s390 kiwi already runs into an extra thread that uses fdasd. Thus the concept to use a dedicated partitioner depending on the disk table type is already in place.

The meta format kiwi uses to describe the requested size information should not be changed. Only the tooling that validates that information and I expect the resulting code to be much smaller and more straight forward.

**Comment by Vogtinator** [comment]
> However using parted requires us to calculate start/end addresses ourselves and pass them along as parameters.

Yup, but something like "end of disk" could be written as `100%` instead.

> Also the distinguished partition tools have code to handle different types of storage disks that do not have a real C/H/S layout like it's the case for SSD's, SD cards, USB sticks and so on. The virtual C/H/S mapping is something parted does not deal well with.

That's easily avoided by not using `cyl` or `chs` though.

**Comment by schaefi** [comment]
I'm starting to work on this now
