### ISSUE TITLE
Allow replacing packages in derived images

### ISSUE THREAD

**Issue by Vogtinator** [OSInside/kiwi#1407]
If you have a base image like `opensuse/busybox` which includes `busybox-findutils` and similar and derive from it, it can be necessary to replace it with the full `findutils` if some package depends on it. Currently it's not possible to remove a package before installing others or even uninstall a package together with installing another one.

Just installing `findutils` results in a conflict as nothing tells `zypper` that removing `busybox-findutils` is ok.

Ugly workaround:

```
<package name="--"/>
<package name="-busybox-findutils"/>
<package name="findutils"/>
```

OBS treats `-foo` as "ignore foo" and kiwi just passes it verbatim as `zypper install -- -busybox-findutils findutils` which results in the proper replacement operation.

**Comment by thkukuk** [comment]
Since busybox does not contain a full RPM implementation, we are working only with the bootstrap section:

  <packages type="bootstrap">
    <package name="weave-kube"/>
    <package name="--"/>
    <package name="-busybox-findutils"/>
  </packages>

So a solution it must work with this.

**Comment by schaefi** [comment]
@Vogtinator stupid question, why do you need "--" prior the "-busybox-findutils findutils" ?

In kiwi the schema also supports something like this

```xml
<packages type="image"/>
    <ignore name="busybox-findutils"/>
    <package name="findutils"/>
</packages>
```

On the zypper level this leads to the option ```zypper al ...```

Does this solve the problem ? or is this more on the obs resolver side ?

Thanks

**Comment by thkukuk** [comment]
On Mon, Apr 20, Marcus Schäfer wrote:

> On the zypper level this leads to the option zypper al ...
> 
> Does this solve the problem ? or is this more on the obs resolver side ?

We don't need to lock a package, we need to remove it.
So no, it does not solve the problem.
The "--" is required sine zypper will assume else that 
"-busybox-findutils" is the "-b" option.

-- 
Thorsten Kukuk, Distinguished Engineer, Senior Architect SLES & MicroOS
SUSE Software Solutions Germany GmbH, Maxfeldstr. 5, 90409 Nuernberg, Germany
Managing Director: Felix Imendoerffer (HRB 36809, AG Nürnberg)

**Comment by schaefi** [comment]
ok thanks

**Comment by schaefi** [comment]
ok we have a plan how to support you best with that such that you can specify:

```xml
<package name="-busybox-findutils"/>
<package name="findutils"/>
```

in any section you need it
