### ISSUE TITLE
kiwi sets GRUB_DISTRIBUTOR again

### ISSUE THREAD

**Issue by lnussel** [OSInside/kiwi#1416]
## Problem description

kiwi sets GRUB_DISTRIBUTOR /etc/default/grub

## Expected behaviour

kiwi not setting GRUB_DISTRIBUTOR, that behavior was disabled previously:
https://bugzilla.suse.com/show_bug.cgi?id=1032119&GoAheadAndLogIn=1
by commit
https://github.com/OSInside/kiwi/commit/295a7faaf3c485d4bd9e49638b9b113a41050cde

however https://github.com/OSInside/kiwi/commit/162d5c9a4120860c49e7c0de36bef838123bd28d introduced it again

## Steps to reproduce the behaviour

Build openSUSE:Leap:15.2:MicroOS/openSUSE-MicroOS, it produces a grub menu that says "openSUSE MicroOS" instead of "openSUSE MicroOS 15.2":
https://openqa.opensuse.org/tests/1247233#step/disk_boot/1

## OS and Software information
+ KIWI version: python3-kiwi-9.20.5-lp152.1.1.x86_64
+ Operating system: Leap 15.2
+ OBS version: ?

**Comment by schaefi** [comment]
I think it was added back because grub2-mkconfig uses it. many references available in /usr/sbin/grub2-mkconfig. So if this is obsolete why is there code in grub2-mkconfig handling it ?

**Comment by schaefi** [comment]
Can this really be safely removed or do we need to add yet another check for a grub2-mkconfig feature. All this is a mess across distributions really a pita

**Comment by lnussel** [comment]
grub2-mkconfig creates a proper string based on /etc/os-release if GRUB_DISTRIBUTOR is not set. That is just fine so a yast install does not set GRUB_DISTRIBUTOR.
