### ISSUE TITLE
Kiwi failed to create a 32-bit VDI from a raw disk image

### ISSUE THREAD

**Issue by pasccom** [OSInside/kiwi#1438]
## Problem description
Kiwi could not create a 32-bit VDI image. This occured first when using Kiwi in a chroot on a 64-bit host , but I reproduced the issue with a local `osc build` on another image.
In the second case Kiwi fails with (I cut out the lines of no interest to the problem):
```
[  305s] [ INFO    ]: 19:04:56 | Creating vdi Disk Format
[  305s] [ DEBUG   ]: 19:04:56 | EXEC: [qemu-img convert -f raw /usr/src/packages/KIWI-vmx/OpenSUSE-Tumbleweed-Kiwi.i686-0.1.raw -O vdi /usr/src/packages/KIWI-vmx/OpenSUSE-Tumbleweed-Kiwi.i686-0.1.vdi]
[  305s] [ DEBUG   ]: 19:04:56 | EXEC: Failed with stderr: qemu-img: Could not open '/usr/src/packages/KIWI-vmx/OpenSUSE-Tumbleweed-Kiwi.i686-0.1.raw': Could not open '/usr/src/packages/KIWI-vmx/OpenSUSE-Tumbleweed-Kiwi.i686-0.1.raw': No such file or directory
[  305s] , stdout: (no output on stdout)
[  305s] [ ERROR   ]: 19:04:56 | KiwiCommandError: qemu-img: stderr: qemu-img: Could not open '/usr/src/packages/KIWI-vmx/OpenSUSE-Tumbleweed-Kiwi.i686-0.1.raw': Could not open '/usr/src/packages/KIWI-vmx/OpenSUSE-Tumbleweed-Kiwi.i686-0.1.raw': No such file or directory
[  305s] , stdout: (no output on stdout)
[  305s] [ INFO    ]: 19:04:56 | Cleaning up BootImageDracut instance
[  305s] [ INFO    ]: 19:04:56 | Cleaning up BootImageDracut instance
[  305s] [ INFO    ]: 19:04:56 | Cleaning up BootImageDracut instance
[  306s] 
[  306s] host.domain failed "build OpenSUSE-Tumbleweed-Kiwi.kiwi" at Mon May 11 19:04:57 UTC 2020.
[  306s] 
```
## Expected behaviour
Kiwi should convert the raw disk image into a VDI.

## Steps to reproduce the behaviour
I think creating a 32-bit VDI image will always fail (see below the results of my investigations).

## OS and Software information
+ KIWI version: 9.20.9
+ Host operating system: OpenSUSE Leap 15.1 64-bit (up to date 11/05/2020)
+ Build host (used by `osc build`): OpenSUSE Tumbleweed 32-bit (up to date 11/05/2020)
+ OBS version: 0.168.2 (`osc --version`)

## My understanding
Despite what it says a raw disk image is created, but it is named `OpenSUSE-Tumbleweed-Kiwi.ix86-0.1.raw` and not `OpenSUSE-Tumbleweed-Kiwi.i686-0.1.raw` as expected by `qemu-img`.
I think this is due to the fact that https://github.com/OSInside/kiwi/blob/947b741748ea0d5d0df8da26337bbb7070f7fdee/kiwi/storage/subformat/base.py#L50 uses directly `platform.arch()` whereas https://github.com/OSInside/kiwi/blob/14ee5ecbb7953de9cbfb099c21faf31f4da64de1/kiwi/builder/disk.py#L72-L74 modifies this value for i586 and i686 architectures.
The two should be in sync, if I am not mistaken. Maybe it would be worth doing a function and not using directly `platform.machine()`, because I saw a lot of lines identical to the second one all over kiwi code.

**Comment by schaefi** [comment]
going to work on this one now, also including the suggested refactoring. We call this platform.machine() really too often
