### ISSUE TITLE
Kiwi failed when attempting to include APT repositories

### ISSUE THREAD

**Issue by pasccom** [OSInside/kiwi#1439]
## Problem description
Kiwi failed, when trying to add APT repositories (with priorities) in image. Unfortunately, I do not have the error log and I cannot reproduce right now since I patched the bug (see below).

## Expected behaviour
Kiwi should be able to include APT repositories in image even with priorities.

## Steps to reproduce the behaviour
Try to include (with `imageinclude`) APT repositories (with priorities) in an image.

## OS and Software information
+ KIWI version: 9.18.16
+ Operating system: OpenSUSE Leap 15.1 (up to date 11/05/2020)
+ OBS version: Not relevant

## Root cause
The problem is in the following function:
https://github.com/OSInside/kiwi/blob/14ee5ecbb7953de9cbfb099c21faf31f4da64de1/kiwi/repository/apt.py#L105-L115 At line 112, it uses the path `self.manager_base` and the repository gets added whereas at line 114, it uses the path `self.root_dir`. I think it should be `self.manager_base` as well: I tested it and this works.

**Comment by davidcassany** [comment]
@pasccom thanks much again for the detailed report, I am trying to get it fixed
