### ISSUE TITLE
Kiwi cannot set keys for APT repositories

### ISSUE THREAD

**Issue by pasccom** [OSInside/kiwi#1440]
## Problem description
As discussed in the mailing list, Kiwi cannot add keys for APT repositories. 

## Expected behaviour
Kiwi should be able to add keys for APT repositories

## Steps to reproduce the behaviour
Add keys on the command line when building an image based on Debian as follows
```
sudo kiwi --debug --color-output --type=vmx system build --description=KiwiJeOS-Debian-Buster --target-dir=/tmp/KiwiJeOS-Debian-Buster --signing-key KiwiJeOS-Debian-Buster/keys/debian-10-key.asc --signing-key KiwiJeOS-Debian-Buster/keys/obs.key
```
You should get the following error just after `debootstrap`
```
[ DEBUG   ]: 22:02:52 | EXEC: [debootstrap --no-check-gpg --variant=minbase --components=main,contrib,non-free buster /tmp/KiwiJeOS-Debian-Buster/build/image-root.debootstrap http://deb.debian.org/debian/]
[ WARNING ]: 22:04:02 | Extended attributes not supported for target: /tmp/KiwiJeOS-Debian-Buster/build/image-root
[ DEBUG   ]: 22:04:02 | EXEC: [rsync -a -H /tmp/KiwiJeOS-Debian-Buster/build/image-root.debootstrap/ /tmp/KiwiJeOS-Debian-Buster/build/image-root]
[ DEBUG   ]: 22:04:03 | EXEC: [chroot /tmp/KiwiJeOS-Debian-Buster/build/image-root apt-key add KiwiJeOS-Debian-Buster/keys/debian-10-key.asc]
[ DEBUG   ]: 22:04:03 | EXEC: Failed with stderr: E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
, stdout: (no output on stdout)
[ DEBUG   ]: 22:04:03 | EXEC: [rm -r -f /tmp/KiwiJeOS-Debian-Buster/build/image-root.debootstrap]
[ ERROR   ]: 22:04:03 | KiwiDebootstrapError: KiwiCommandError: chroot: stderr: E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
, stdout: (no output on stdout)
```

## OS and Software information
+ KIWI version:  9.18.16
+ Operating system: OpenSUSE Leap 15.1
+ OBS version: Not relevant

## Root cause
Using `apt-key` to register the keys to apt just after `debootstrap`ing does not work since it requires `gnupg` which is not installed by `deboostrap`.

## Workaround
I solved the issue by preloading the keys in `/var/cache/kiwi/apt-get/trusted.gpg` (which is again a keyring in `gnupg1` format).

### First solution
Implement the workaround in Kiwi.
### Second solution
Install `gnupg` using `debootstrap` APT configuration before using `apy-key`.

**Comment by davidcassany** [comment]
Thanks @pasccom for the all these details on APT, this is much appreciated. I am having a look at it.

**Comment by davidcassany** [comment]
> I solved the issue by preloading the keys in /var/cache/kiwi/apt-get/trusted.gpg (which is again a keyring in gnupg1 format).

@pasccom how did you create the trusted keyring? I have been trying several commands options with `gnugpg 2.2` and I could not manage to get a keyring that apt-get supports. Do you have any hint? Or did you use `apt-key add` to create it?

If I manage to find a nice way to create this keyring using `gpg` command I believe this could be a nice option. I like this approach of manually creating the keyring before calling debootstrap because this is quite parallel to what is done for rpm based package manager.

**Comment by pasccom** [comment]
Oh, I am really sorry I forgot to include the code...  
I used `gnupg` (I am on OpenSUSE and I do not have `apt`).

Here is the code:
```bash
# This line comes from apt-key:
GPG_ARGS=(--no-options --no-default-keyring --no-auto-check-trustdb --trust-model always --keyring "$KIWI_APT_CACHE/trusted-keybox.gpg")
# I include the keys in the image (sub-folder keys) which avoids long command lines:
for key in $(ls "$DESC_PATH/keys/"); do
    # This will create a keybox
    gpg --import "${GPG_ARGS[@]}" --ignore-time-conflict  "$DESC_PATH/keys/$key"
done
# This transforms a keybox in a keyring:
gpg --export ${GPG_ARGS[@]} --yes --output "$KIWI_APT_CACHE/trusted.gpg"
rm "$KIWI_APT_CACHE"/trusted-keybox.gpg*
```
Source: https://stackoverflow.com/questions/51300627/apt-rejects-keyrings-in-etc-apt-trusted-gpg-d-on-ubuntu-18-04 

NB: I don't think this will work for `debootstrap` since it uses only the keyring provided in the command lines (but you can provide the keyring you created on the command line.

**Comment by davidcassany** [comment]
Thanks much! Gonna work on this.

> NB: I don't think this will work for `debootstrap` since it uses only the keyring provided in the command lines (but you can provide the keyring you created on the command line.

Well, this is also one of the reasons to make use of this approach, because I can create the keyring before calling debootstrap and then pass it to debootstrap on the command line. Then use the keys also at bootstrap.

**Comment by pasccom** [comment]
> Thanks much! Gonna work on this.

You are welcome!

> Well, this is also one of the reasons to make use of this approach, because I can create the keyring before calling debootstrap and then pass it to debootstrap on the command line. Then use the keys also at bootstrap.

Yes, I wrote my message in a hurry and I did not understand you planned to do that, even though this was the only reasonable option. I only wanted to be sure I was clear enough about `debootstrap`.

I had a look at the commit (only the source files, not the unit tests) and it look like exactly the solution I desired when I rose the issue :-)
