### ISSUE TITLE
EFI builds for Fedora in OBS do not include the correct root device

### ISSUE THREAD

**Issue by davidcassany** [OSInside/kiwi#1454]
## Problem description

Fedora 30 OEM image (Disk flavor) of the integration test does not use the correct `root=` kernel parameter at boot when using UEFI firmware. This is happening because at build time there is a file `/EFI/fedora/grubenv` that gets populated by `grub-mkconfig` with the following values:

```
# GRUB Environment Block
kernelopts=root=/dev/mapper/loop0p4 ro
```

## Expected behaviour

`root=` option includes the actual root UUID. The `/dev/mapper/loop0p4` is just to loop device that was mounted at build time, thus this is only valid at build time.

## Steps to reproduce the behaviour

Download the OEM image from the Fedora integration tests and run it with

```
qemu-kvm -m 2048 -hda VMX-Fedora-30.0.x86_64-1.30.1-Disk-Build5.1.raw -bios /usr/share/qemu/ovmf-x86_64-ms.bin
```

## OS and Software information
+ KIWI version: v9.20.16 (current master)
+ Operating system: 
+ OBS version:

**Comment by schaefi** [comment]
fixed with #1455. The commit message used "Fixes Issue #..." and that way of saying it does not auto close the issue. Therefore closing manually now
