### ISSUE TITLE
Proposal: bash to sh?

### ISSUE THREAD

**Issue by isbm** [OSInside/kiwi#1464]
If one builds a system with a busybox, then Bourne Shell isn't there, but Almquist Shell. How is the idea to substitute hardcoded `bash` all over the place with `sh` and fix the inconsistencies, if any? ("works on my laptop" TM tho, at the moment). For SUSE world, `/usr/bin/sh` is anyway a symlink to `/bin/bash`, in Debian, howerver, to `dash` (Debian Almquist Shell).

I am not sure this needs to be explicitly configurable, as the mere purpose is to simply run commands. But it gets problematic if coreutils aren't there.

Mostly to @schaefi :wink:

**Comment by schaefi** [comment]
I think the invocations in kiwi we do with bash can also be done with any other shell. This would cover the following parts in code:

* ./solver/repository/base.py
* ./storage/disk.py
* ./package_manager/pacman.py
* ./package_manager/dnf.py
* ./iso_tools/base.py
* ./system/setup.py
* ./system/size.py
* ./utils/compress.py
* ./archive/cpio.py
* ./archive/tar.py
* ./bootloader/config/grub2.py
* ./bootloader/config/zipl.py
* ./partitioner/msdos.py
* ./container/oci.py
* ./defaults.py

There are the following places where I'm concerned if changes will have some negative side effects:

* ./config/functions.sh
   helper functions for shell scripts and it is assumed they use bash

* ./system/shell.py
   call out a script using bash

* ./system/profile.py
   read and export variable settings, not sure if that's handled the same for all shells. I know e.g tcsh does strange things with variables

Overall I'm pro to be not bash specific but I'd like to avoid introducing bugs. From your environment did you have identified where things fails ? if so we can start with those and go in small steps

Thoughts ?

**Comment by schaefi** [comment]
Another area for the shell is dracut. All dracut modules are written using bash. If you look through /usr/lib/dracut/modules.d you see almost all modules to run with "#!/bin/bash". If your environment runs without bash it will be hard to create a dracut initrd because even dracut itself runs with "#!/bin/bash --norc". But all of that can be adapted on other distributions

**Comment by isbm** [comment]
Actually! With [this PR](https://github.com/OSInside/kiwi/pull/1465) I could successfully kill Bash with Busybox and still have dracut & co (you don't need dracut at runtime anyway). So maybe this Issue we can actually close, as long as https://github.com/OSInside/kiwi/pull/1465 is in (after final polishing, rgiht now it is just WiP).
