### ISSUE TITLE
Provide live persistent partition creation dracut module as extension to dmsquash/livenet

### ISSUE THREAD

**Issue by davidcassany** [OSInside/kiwi#1470]
Kiwi-live dracut module mostly was coded in order to provide overlayfs support for live ISOs, as since not long ago, dmsquash module was missing overlayfs support. In addition to simple overlyfs support kiwi-live also provides the possibility of creating a new partition to place a persistent overlay partition. This is only happening if the device geometry allows to do so, meaning there is some empty space left unpartitioned on the device.

Currently, dmsquash supports overlayfs, however it is still missing the partition creation procedure, which is is reasonable as dmsquash is meant to be really  generic and kiwi-live is meant to be used only within the KIWI scope. This card is to discuss about the position of `kiwi-live` module in the future and its relationship with `dmsquash`. More specific, we are wondering if there is a chance that dmsquash can be used in a way that kiwi-live as it is of today is no longer needed.

dmsquash provides many  other functions, like remote deployments via livenet, that are not possible with kiwi-live. Thus if there is a possibility to use dmsquash to provide the same user experience as using `kiwi-live` this would be a great advance as we would be capable to embrace new features like ISO PXE boot deployed in some persistent device, etc.

Given that the only piece missing for dmsquash we are wondering how hard would it be to provide whatever is missing with an additional tiny module or by adding such a feature to some existing module. This would allow us to fade out kiwi-live module little by little and minimize even more the KIWI specific code at boot time.

**Comment by Conan-Kudo** [comment]
I think this is worth discussing with @danimo and @haraldh from dracut, because it may be possible to have upstream dracut extend its functionality enough to completely obsolete our module.

**Comment by schaefi** [comment]
From our perspective the upstream dmsquash module covers all features the kiwi module has (and more) except for the code that is able to create a persistent write partition. I think it would be good if we can drop the kiwi module in favor of the dmsquash module but add another dracut module that is only capable of creating a write partition. That dracut module could also be send upstream.

The two modules would need to pass along information. We had a short conversation how to let dracut modules exchange information. At this point some further investigations are needed.

Overall what are your thoughts about this ?

**Comment by danimo** [comment]
I would be happy to help with integrating the missing features into upstream dracut's dmsquash.

**Comment by Conan-Kudo** [comment]
I'd love to see this happen. Once we have all the functionality in upstream dracut, we should have a conversation with @lnykryn about getting it backported in RHEL 8, if at all possible. That would allow us to look at making KIWI 10 cut off SLE 12 and RHEL 7, simplifying the support matrix.

**Comment by iammattcoleman** [comment]
I've written a dracut module that sets up a persistence partition when booting on writable media with free space. It uses the kernel command line parameters defined in `dracut.cmdline(7)` and adds Kiwi's `rd.live.overlay.cowfs` parameter, matching Kiwi's support for ext4 and XFS in the `hybridpersistent_filesystem` attribute.

Here's a repository containing a Kiwi image description that builds a barebones Ubuntu live ISO that uses my dracut `create-overlay` module:

https://github.com/iammattcoleman/overlay-test

That's definitely just a demo to start the discussion. I have a few fixes on my local system that I haven't pushed to that repository yet. This is my first attempt at a dracut module, so I appreciate all the feedback I can get.

Eventually, I'd like to get it into dracut, directly. If that doesn't work out, I'll release it as a standalone package. I've got some internal project deadlines to meet before I can focus on doing a proper job of releasing this.

**Comment by schaefi** [comment]
@davidcassany Would be great if you have a free slot to look into this, thanks in advance

**Comment by iammattcoleman** [comment]
The new module, `dmsquash-live-autooverlay`, has been merged into dracut:
https://github.com/dracutdevs/dracut/commit/a3c67d27e75223bb45df19f850d246ced9a09938

**Comment by Conan-Kudo** [comment]
This is also being backported in RH/Fedora:

* Fedora: https://src.fedoraproject.org/rpms/dracut/pull-request/26
* RHEL 9: https://github.com/redhat-plumbers/dracut-rhel9/pull/52
