### ISSUE TITLE
Centos8 Support as build host

### ISSUE THREAD

**Issue by christiansetzer** [OSInside/kiwi#1488]
## Problem description
Bootstrap on Centos8 when trying to build a Centos7 image, is using Centos8 packages

## Expected behaviour
should use the repositories as specified in the config.xml
## Steps to reproduce the behaviour
[config.xml](https://paste.ubuntu.com/p/rkmhVhYfXJ/)
[image-root.log](https://paste.ubuntu.com/p/8SgBd5q6hV/)

command executed
`sudo kiwi-ng --debug --color-output system build --description=/images/imgusr/git/xxx-images-azure-centos7 --target-dir /cache`

## OS and Software information
+ KIWI version: 9.21.0
+ Operating system:  Centos 8 (latest updates at the time of opening the issue)
+ OBS version:

**Comment by schaefi** [comment]
very strange. Have you tried deleting cache information:

```
$ rm -rf /var/cache/kiwi
$ kiwi-ng ....
```

Does this make a difference ?

**Comment by schaefi** [comment]
kiwi creates the repos for dnf below ```/var/cache/kiwi/dnf/...``` can you check what is written there ?

Thanks

**Comment by christiansetzer** [comment]
My guess the first problem is that there is no option for release version. If you take a look at the log, you will notice that el8 rpm are getting installed. I tried it on the CLI with --releasever and only then Centos7 Repos are getting used from the config.xml file. Still Centos8 repos are getting cached as well, even with the release version set to 7.

As requested the content of the /var/cache/kiwi/dnf directory.

> [root@xxximagebuild03 kiwi]# cd dnf/
[root@xxximagebuild03 dnf]# ls
cache  pluginconf  repos
[root@xxximagebuild03 dnf]# ls cache/
centos-7-066e70ca044b5060              centos-7-plus-filenames.solvx                      centos8-x86_64-epel-2962dfc0f009d62a
centos-7-azure-19810376a778d427        centos-7-plus.solv                                 centos8-x86_64-epel-filenames.solvx
centos-7-azure-agent-639228cd4603e01e  centos-7-scl-6cf8150bd14714e3                      centos8-x86_64-epel.solv
centos-7-azure-agent-filenames.solvx   centos-7-scl-filenames.solvx                       centos8-x86_64-epel-updateinfo.solvx
centos-7-azure-agent.solv              centos-7-sclo-1c7b833d16983290                     centos8-x86_64-extras-28f91108a0ab02ba
centos-7-azure-filenames.solvx         centos-7-sclo-filenames.solvx                      centos8-x86_64-extras-filenames.solvx
centos-7-azure.solv                    centos-7-sclo.solv                                 centos8-x86_64-extras.solv
centos-7-epel-66057a1d4a1928c0         centos-7-scl.solv                                  centos8-x86_64-filenames.solvx
centos-7-epel-filenames.solvx          centos-7.solv                                      centos8-x86_64-icinga-4ab812511aa7d13b
centos-7-epel.solv                     centos-7-updates-24bd5e75e4f05c7c                  centos8-x86_64-icinga-filenames.solvx
centos-7-epel-updateinfo.solvx         centos-7-updates-filenames.solvx                   centos8-x86_64-icinga.solv
centos-7-extras-88d9cc29fb82cf66       centos-7-updates.solv                              centos8-x86_64-xxx-00b82db54a9e25ad
centos-7-extras-filenames.solvx        centos8-x86_64-14497ef03ec86d37                    centos8-x86_64-xxx-filenames.solvx
centos-7-extras.solv                   centos8-x86_64-appstream-updates-fc93fd5c69137a4e  centos8-x86_64-xxx.solv
centos-7-filenames.solvx               centos8-x86_64-appstream-updates-filenames.solvx   centos8-x86_64.solv
centos-7-nodejs8-8fb520176110e341      centos8-x86_64-appstream-updates.solv              expired_repos.json
centos-7-nodejs8-filenames.solvx       centos8-x86_64-baseos-updates-e99c4b48856fbba5     kiwi-next-generation-11f2a1a9ec09e51d
centos-7-nodejs8.solv                  centos8-x86_64-baseos-updates-filenames.solvx      kiwi-next-generation-filenames.solvx
centos-7-plus-7ecb523fd35a829b         centos8-x86_64-baseos-updates.solv                 kiwi-next-generation.solv
[root@xxximagebuild03 dnf]# ls pluginconf/
priorities.conf
[root@xxximagebuild03 dnf]# ls repos/
centos-7-azure-agent.repo  centos-7-epel.repo    centos-7-nodejs8.repo  centos-7.repo       centos-7-scl.repo      kiwi-next-generation.repo
centos-7-azure.repo        centos-7-extras.repo  centos-7-plus.repo     centos-7-sclo.repo  centos-7-updates.repo

**Comment by schaefi** [comment]
Thanks for the details

@Conan-Kudo does this sound familiar to you ? kiwi indeed never set --releasever to the dnf call. To get that into the equation I think we would need a new attribute in the repository element

Not sure but I think I remember a discussion about releasever which ended with that it's not needed, but that was before centos8. Things might have changed ?

Thanks

**Comment by christiansetzer** [comment]
On friday I was also trying to build a centos8 image on the same centos8 box. Just a heads up, but I guess there are more todo's here. There are problems with the modular repos.

[centos8 image-root.log](https://paste.ubuntu.com/p/GVT4hvgkQW/)

**Comment by davidcassany** [comment]
@christiansetzer I could not reproduce this behavior in the CentOS 8 we have. To me it looks like you have something in your host messing with dnf configuration that collides with KIWI. I see this line in your logs

`This system is receiving updates from Red Hat Satellite or Spacewalk server`

I am not familiar with Red Had registered boxes thus I don't really know how repositories are set in that context, but couldn't it be that there is some sort of underlying plugin that adds repositories depending on the registration you have?

@Conan-Kudo probably you have a clue about what does it mean?

In our CentOS 8 I could not reproduce this behavior and I managed to build CentOS 7 and CentOS 8 smoothly.

**Comment by Conan-Kudo** [comment]
This is the Spacewalk plugin provided by Spacewalk/Uyuni/SUSE Manager interfering with the usage of DNF in kiwi. One way we could solve this is by ensuring that we pass `--disableplugin=spacewalk` to the DNF commandline everywhere?

**Comment by Conan-Kudo** [comment]
Incidentally, I'm pretty sure similar problems would happen with other package managers using the `rhn`/`spacewalk` plugins (APT, Zypper), so we'd probably want to handle that properly...

**Comment by christiansetzer** [comment]
I am currently not sure on how to proceed here. I will have to talk to my coworkers about that issue and the findings. I will post an update on Wednesday.

**Comment by davidcassany** [comment]
That's interesting, I am surprised this the first time we get this issue reported.

> One way we could solve this is by ensuring that we pass --disableplugin=spacewalk to the DNF commandline everywhere? Mock does this for similar reasons: rpm-software-management/mock@e6676a6

I am wondering why not `--noplugins`. Do we need or support any DNF plugin in KIWI, I'd say not. Need to figure out if similar flags are available in APT and Zypper.

**Comment by Conan-Kudo** [comment]
The only reason I'm not saying universally no is because some plugins (e.g. Facebook's `pkgtorrent` plugin) add protocol support to YUM/DNF, and that could be a problem if local repositories definitions are broken because the protocol support was disabled.

**Comment by christiansetzer** [comment]
You guys should keep in mind that spacewalk development has been discontinued since end of May this year. So whatever you do, there will be probably no new version and raises the question if any work to fix this is justified.

**Comment by Conan-Kudo** [comment]
Uyuni is forked from Spacewalk, and SUSE Manager is based on that. The APT, DNF, and Zypper plugins for Spacewalk are supported through the Uyuni project via SUSE or the community.

The reports of Spacewalk's demise are greatly exaggerated. 😉

**Comment by christiansetzer** [comment]
We discussed this internally. There would be a possibility to move to Uyuni in the future. For now, I will remove Spacewalk integration from my build-hosts. If @davidcassany is correct that will solve my problem for now. Since I have to move the server to another network segment for this, I will get back to issue the earliest next Monday, where I have planned a change for the IP address change. I will post an update if the builds are successful after that, without Spacewalk.

**Comment by christiansetzer** [comment]
My build servers are now moved to the new network. I removed them as Spacewalk Clients. The build for centos7 is now successful. Will verify Centos 8 later.

**Comment by schaefi** [comment]
:+1: thanks for the feedback

**Comment by christiansetzer** [comment]
Centos 8 build for Azure on Centos 8 VM  as build server is now verified from my side. I will close the issue now. If you follow up on the Spacewalk integration or Uyuni, we may still be interested in this in the future.
