### ISSUE TITLE
Different blkid output on Arch Linux and Debian causes ISO to be unbootable

### ISSUE THREAD

**Issue by Zentibel** [OSInside/kiwi#1489]
Referencing previous issue:
https://github.com/OSInside/kiwi-descriptions/issues/69

## Problem description
blkid on debian and arch linux spits out different output than what is expected.
Therefore the uuid string is formatted wrong, which leads to the image being unbootable.
## Expected behaviour
Boot
## Steps to reproduce the behaviour
Create any arch linux or debian ISO.
## OS and Software information
+ KIWI version: KIWI (next generation) version 9.21.2
+ Operating system: Arch Linux
+ OBS version: ?

**Comment by davidcassany** [comment]
I just confirmed that this is a regression on all ISOs (at least I saw it on Ubuntu and openSUSE in addition), there must be something wrong in the kiwi-live module.

**Comment by Zentibel** [comment]
Thanks for fixing this! Interesting that you saw it on OpenSUSE as well because OS ISOs booted fine for me.
