### ISSUE TITLE
Custom scripts and their scope

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi#1497]
## Problem description

In kiwi we allow customers to create scripts that are called at different stages in the build process:

- config.sh: at the end of the root tree creation
- images.sh: at the beginning of the image creation
- disk.sh: for virtual disk based images, after the sync of the root tree and inside of the fully mounted root

We document when those scripts run but kiwi does not pretend a scope for this scripts even though their
runtime environment can be different. @isbm brought up an issue that it would be good to "keep things segregated"
between "defines my OS" and "Configure my system".

So the idea which we want to discuss here is if we want to give the image description more structure such that
the layout of the description provides the suggested segregation ?

**Comment by schaefi** [comment]
Here are Bo's initial thoughts about this:

From @isbm 

This is purely "keep things segregated". Maybe it is better to do even this layout division:

* Entities, that are part of permanent description.
* Configuration
* Volatile, transient data

So:

* Description:
   * config.xml
   * root/
* Configuration:
   * config.sh
   * disk.sh
   * (other .sh)
   * some-playbook.yaml
* Volatile, transient data:
   * pile of executable modules in any form, coming from outside
   * random tools, unrelated to the very image itself, but they do their usual job equally anywhere

Something like that. So you know that you put stuff in transiend data and it is guaranteed be executed in the baked system and guaranteed will be fully removed and you do not need to hack around.

**Comment by schaefi** [comment]
@isbm I hope I summarized and used the correct comments from issue at #1487. If you see things missing or want to add additional information please don't hesitate to add them. Thanks much

**Comment by isbm** [comment]
Yes, essentially three areas of "image setup":

1. What? (overall layout, output expectations)
2. How? (tweaks, adjustments, definitions)
3. What's needed? (tools that need to modify image, but do not need to be on the image)

You can update the comments above and remove this one, if needed.

**Comment by davidcassany** [comment]
I was thinking about this issue the other day and I like the idea of discussing the image description (or definition) to better organize it in some better defined areas (like in the @isbm and @scheafi comments above). I think these are interesting ideas to better organize the image description itself in terms of documentation and potentially in terms of file structure (probably there should be `config` and `transient` subfolders in image descriptions). Only thing that I would be probably concern about is the idea of having a 

> pile of executable modules in any form, coming from outside

Not sure if this makes reference to some sort of drop in concept, if so I am not that much in favor of that. I would just include include certain hook points inside `configuration` area (like `config.sh`, `disk.sh`, `image.sh`, etc) but do not directly execute in KIWI anything that is given in a drop in folder, I believe it doesn't make much sense in this case for image description. I'd be more in favor of an explicit execution of tools, modules or whatever scripted in some configuration script (`config.sh`, `disk.sh`...). The drop in concept to me looks nice in situations when you want to distribute something that might behave different depending on the execution environment, use case, etc. Dracut is a nice example of this, IMHO it makes sense there, but for an image description I don't see it, as I want it explicit, static without having to know, guess or debug some implicit execution criteria.

Beyond this concern I think this discussion of how to organize and document the image description makes sense to me.

**Comment by schaefi** [comment]
Given the last comment from David and also the knowledge that @isbm has currently no urgent handle on this I will close this issue until we have a more specific route to go
