### ISSUE TITLE
Refactor Factory Classes

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi#1498]
## Problem description

The way Factories are implemented in kiwi is from a strong typed API perspective
questionable and can be done more clear and stable like it was done in #1495 

In addition to the FileSystem factory the following other factory classes needs
adaption:

- [x] builder
- [x] boot/image
- [x] bootloader/config
- [x] bootloader/install
- [ ] container
- [ ] container/setup
- [x] filesystem
- [ ] iso_tools
- [x] markup
- [ ] oci_tools
- [x] package_manager
- [x] partitioner
- [x] repository
- [x] solver/repository
- [x] storage/subformat
- [x] system/root_import
- [x] volume_manager

**Comment by schaefi** [comment]
Let's commit for the September sprint on the following:

- [ ] builder
- [ ] boot/image
- [ ] bootloader/config
- [ ] bootloader/install

**Comment by schaefi** [comment]
Starting with builder today...

**Comment by davidcassany** [comment]
Lets continue with

- [ ] solver/repository
- [ ] storage/subformat
- [ ] system/root_import
- [ ] volume_manager

for october/november

**Comment by schaefi** [comment]
@davidcassany I'm taking over the first two now

**Comment by schaefi** [comment]
Done for this sprint, moving it back to the backlog. We will touch base on this in the next sprint again

**Comment by davidcassany** [comment]
Lets continue with:

- [ ] markup
- [ ] package_manager
- [ ] partitioner
- [ ] repository

**Comment by schaefi** [comment]
Starting with the first two markup and package_manager

**Comment by schaefi** [comment]
@davidcassany  Going to address the other two as well since you are busy with dracut code

**Comment by schaefi** [comment]
done for this sprint. Next time we work on this we will complete it, yay

**Comment by davidcassany** [comment]
Let's continue and finalize the task with:

- [ ] container
- [ ] container/setup
- [ ] iso_tools
- [ ] oci_tools
- [ ] package_manager

**Comment by davidcassany** [comment]
I start to work on this last set of factory classes
