### ISSUE TITLE
VM could not boot with image=vmx, filesystem="ext3" and <systemdisk>

### ISSUE THREAD

**Issue by koteswara-kelam** [OSInside/kiwi#1507]
## Problem description
While building ova image I saw that LVMs got created:
[ INFO    ]: 19:27:52 | --> volume LVRoot with 51200 MB
[ DEBUG   ]: 19:27:52 | --> running "lvcreate -Zn -L 51200 -n LVRoot vgroup"
[ DEBUG   ]: 19:27:52 | EXEC: [lvcreate -Zn -L 51200 -n LVRoot vgroup]
[ DEBUG   ]: 19:28:42 | --> running "vgscan --mknodes" to create missing nodes
[ DEBUG   ]: 19:28:42 | EXEC: [vgscan --mknodes]
[ DEBUG   ]: 19:29:52 | EXEC: [mkfs.ext3 -L ROOT /dev/vgroup/LVRoot]
[ INFO    ]: 19:29:54 | --> volume centos-home with 48128 MB
[ DEBUG   ]: 19:29:54 | --> running "lvcreate -Zn -L 48128 -n centos-home vgroup"
[ DEBUG   ]: 19:29:54 | EXEC: [lvcreate -Zn -L 48128 -n centos-home vgroup]
[ DEBUG   ]: 19:30:24 | --> running "vgscan --mknodes" to create missing nodes
[ DEBUG   ]: 19:30:24 | EXEC: [vgscan --mknodes]
[ DEBUG   ]: 19:31:35 | EXEC: [mkfs.ext3 /dev/vgroup/centos-home]
[ DEBUG   ]: 19:31:36 | EXEC: [mountpoint -q /tmp/kiwi_volumes.0_fp8b0j]
[ DEBUG   ]: 19:31:36 | EXEC: [mount -o defaults /dev/vgroup/LVRoot /tmp/kiwi_volumes.0_fp8b0j]
[ DEBUG   ]: 19:31:36 | EXEC: [mkdir -p /tmp/kiwi_volumes.0_fp8b0j//home]
[ DEBUG   ]: 19:31:36 | EXEC: [mountpoint -q /tmp/kiwi_volumes.0_fp8b0j//home]
[ DEBUG   ]: 19:31:36 | EXEC: [mount -o defaults /dev/vgroup/centos-home /tmp/kiwi_volumes.0_fp8b0j//home]
[ DEBUG   ]: 19:31:36 | EXEC: [blkid /dev/vgroup/LVRoot -s PARTUUID -o value]
But when I deploy ova, vm boot is stopped with following error:

**dracut initqueue timeout - stating timeout scripts
Cloud not boot
blk_update_request: I/O error, dev fd0, sector 0**

Description file: config.xml:

    <preferences>
        <version>1.2.0</version>
        <packagemanager>yum</packagemanager>
        <bootsplash-theme>charge</bootsplash-theme>
        <locale>en_US</locale>
        <keytable>us</keytable>
        <timezone>UTC</timezone>
        <rpm-check-signatures>true</rpm-check-signatures>
        <type image="iso" flags="overlay" hybrid="true" firmware="uefi" hybridpersistent_filesystem="ext4" hybridpersistent="true"/>
        <type image="vmx" primary="true" filesystem="ext3" kernelcmdline="rhgb no_timer_check console=tty0 console=ttyS0,115200 net.ifnames=0 biosdevname=0" bootloader="grub2" firmware="uefi">
            <systemdisk name="vgroup">
                <volume name="@root" size="50G"/>
                <volume name="centos-home" size="47G" mountpoint="/home"/>
            </systemdisk>
        </type>

        <type image="oem" initrd_system="dracut" filesystem="ext3" installiso="true" bootloader="grub2" firmware="uefi">
            <oemconfig>
                <oem-systemsize>2048</oem-systemsize>
                <oem-swap>true</oem-swap>
                <oem-swapsize>200</oem-swapsize>
                <oem-multipath-scan>false</oem-multipath-scan>
            </oemconfig>
        </type>
    </preferences>
    <users>
        
        <user password="!!" home="/root" name="root" groups="root"/>
    </users>
    <repository type="rpm-md" alias="kiwi-next-generation" priority="1">
        <source path="obs://Virtualization:Appliances:Staging/CentOS_7"/>
    </repository>
    <repository type="rpm-md" alias="Fedora-EPEL7">
        <source path="http://download.fedoraproject.org/pub/epel/7/x86_64"/>
    </repository>
    <repository type="rpm-md" alias="CentOS7-Extras">
        <source path="http://mirror.centos.org/centos-7/7/extras/x86_64"/>
    </repository>
    <repository type="rpm-md" alias="CentOS7-Updates">
        <source path="http://mirror.centos.org/centos-7/7/updates/x86_64"/>
    </repository>
    <repository type="rpm-md" alias="CentOS7">
        <source path="http://mirror.centos.org/centos-7/7/os/x86_64"/>
    </repository>
    <packages type="image">
        <namedCollection name="core"/>
        <namedCollection name="console-internet"/>
        <package name="syslinux"/>
        <package name="grub2"/>
        <package name="kernel"/>
        <package name="plymouth-theme-charge"/>
        <package name="open-vm-tools"/>
    </packages>
    <packages type="iso">
        <package name="dracut-kiwi-live"/>
    </packages>
    <packages type="oem">
        <package name="dracut-kiwi-oem-repart"/>
        <package name="dracut-kiwi-oem-dump"/>
    </packages>
    <packages type="bootstrap">
        <package name="filesystem"/>
        <package name="basesystem"/>
        <package name="yum-plugin-priorities"/>
        <package name="nextgen-yum4"/>
        <package name="grub2-efi-x64-modules"/>
        <package name="grub2-efi-x64"/>
        <package name="shim-x64" arch="x86_64"/>
    </packages>
</image>
## OS and Software information
+ KIWI version: 
+ Operating system: Centos
+ OBS version:

**Comment by schaefi** [comment]
Your image does not contain lvm2. That makes it impossible for dracut to include the required lvm tools to boot an LVM based system. Add the following to your image description to fix this:

```
<package name="lvm2"/>
```

Please note it's not a responsibility of the appliance builder to check if required components according to the setup of the type gets installed into the image. We can't do this because there is no open standard that defines package names, tool names, etc across the distributions. Thus to make sure all you need is installed in your image is a task of the author of the image description. That just to explain why kiwi doesn't have an early check for this condition

Thanks
