### ISSUE TITLE
XFS filesystem created with corrupt superblock

### ISSUE THREAD

**Issue by christiansetzer** [OSInside/kiwi#1509]
## Problem description
I moved from Centos7 as build server to Centos8, because of the repository structure. There is no real error that kiwi produces and the vhdfixed file for Azure is created. But when I try to deploy a VM I get the following error

> "details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"OSProvisioningTimedOut\",\r\n \"message\": \"OS Provisioning for VM 'xxx-efi-vm' did not finish in the allotted time. The VM may still finish provisioning successfully. Please check provisioning state later. Also, make sure the image has been properly prepared (generalized).\\r\\n *

I also have to add, that I tried
- firmware=efi
- firmware=uefi
and the classic one. I thought that the error had something to do with me missing to set the hyper-v gen1 or gen2 setting. Both do not work

## Expected behaviour
At least deployment should finish. The created VM does not even boot up.

## Steps to reproduce the behaviour
[image-root.log](https://paste.ubuntu.com/p/wb6s7RwYGW/)
[config.xml](https://paste.ubuntu.com/p/SbMBB6Sgg9/)

After the image is created:
- azcopy for upload
- az disk create
- az image create
- az sig image-version create

The VM is deployed from a shared image gallery. After that the above error comes up

## OS and Software information
+ KIWI version: 9.21.0
+ Operating system: Centos 8 (latest updates as of creation date of issue)
+ OBS version:

**Comment by schaefi** [comment]
I don't think this is a kiwi problem. We are building for azure with that kiwi version as follows:

```xml
<type image="vmx" filesystem="xfs" bootloader="grub2" bootloader_console="serial" boottimeout="1" kernelcmdline="earlyprintk=ttyS0 console=ttyS0 rootdelay=300 net.ifnames=0 dis_ucode_ldr scsi_mod.use_blk_mq=1" devicepersistency="by-uuid" formatoptions="force_size" format="vhd-fixed" bootpartition="true" bootpartsize="1024" efipartsize="512" firmware="efi">
    <size unit="M">30720</size>
</type>
```

There are many constraints Azure requires for their vhds. The above type setup covers all of them. Also the 30GB size is a must have.

For registration you have to upload the .raw.xz file via "az storage blob upload". The upload must be a block storage upload. From the registered blob you need to create an image. That will then also boot as we do the same every day :)

Again all of this is not really a kiwi issue.

Let us know how it goes

**Comment by schaefi** [comment]
Also the created vhdfixed image can be smoke tested with kvm locally first. It has too boot. If it does not boot in your VM you don't need to upload it to Azure. For efi boot test I use "kvm -bios /usr/share/qemu/ovmf-x86_64.bin"

**Comment by schaefi** [comment]
If it does not boot in efi mode it might be related to https://github.com/OSInside/kiwi/pull/1510

**Comment by christiansetzer** [comment]
My non-efi SLES15SP1 images build already work and are running on Azure VM's, which were build on SLES15. And they were created with the same type configuration and the same upload procedure. I will try your other settings and test, but I guess if you say that this is not a kiwi issue, it probably is not. I will get back to this, if not before my vacation next week, then mid-august.

**Comment by schaefi** [comment]
Of course I could be wrong and it is an issue with kiwi. I just know that the azure images as we build them for the suse distros work. Maybe it's really related to the fix in #1510. That is a vendor fix that applies to centos and rhel only, so we would not see it in suse. If you have a free spot you can locally patch your kiwi with this small change and see if it makes a difference.

Thanks for your help. We keep this open until you find some time to take a look at it :)

**Comment by christiansetzer** [comment]
The problem is somehow solved. After fixing my problems with the Azure serial console, the VM's did not boot up because of a corrupt xfs superblock, which lead to a read-only root filesystem. The workaround for this was to switch to ext4 as root filesystem for now. A coworker just suggested the possibility that the Centos8 xfs version on my build host might cause the problem in the centos7 image. I will try and verify building a Centos8 image now with xfs. If this would work, that really might be the problem.

Will give an update on this shortly and close the issue after that.

**Comment by schaefi** [comment]
Thanks for the feedback, we'll wait until you find the time

**Comment by christiansetzer** [comment]
The Centos8 Image-Build is not successful .. I get a strange error and the kernel cannot be loaded. Since I do not have time now and Centos8 has no priority I will get back to this later.

The Error I am getting is:

> error: ../../grub-core/fs/fshelp.c:258:file 
error: ../../grub-core/loader/i386/pc/linux.c:413:you need to load the kernel
