### ISSUE TITLE
Docu Site links to wrong page

### ISSUE THREAD

**Issue by B1Sandmann** [OSInside/kiwi#1520]
## Problem description
The "Next" button at the bottom of https://osinside.github.io/kiwi/building_images/build_kis.html links to https://osinside.github.io/kiwi/working_with_images.html however the sidebar strongly suggests that one should continue with https://osinside.github.io/kiwi/building_images.html#image-types and the following sub-points of the https://osinside.github.io/kiwi/building_images.html# page

## Expected behaviour
The next page links to https://osinside.github.io/kiwi/building_images.html#image-types 

If it's only possible to link to subpages of building-images it might be worth to make `Images Types`, `Images Results` etc. in its own page(s).

**Comment by schaefi** [comment]
Actually that "Next" button behavior is not under our control. It's created by the read-the-docs theme used with the sphinx docs. It always links to the next toplevel chapter. The chapter structure at this point is:

  * Building Images for Supported Types
  * Working with Images

I agree from a readers perspective it's misleading when using the Next button. I'll restructure this part
