### ISSUE TITLE
Error message: Could not resolve host: download.opensuse.org

### ISSUE THREAD

**Issue by LinuxbuzzSoftware** [OSInside/kiwi#1522]
## Problem description

When trying to create an ISO image with the KIWI, I get an error involving cURL. For example:

```
ERROR: 15:52:35 | KiwiInstallPhaseFailed: System package installation failed: Download (curl) error for 'http://download.opensuse.org/repositories/home:/regataos/openSUSE_Tumbleweed/x86_64/Mesa-libglapi0-20.1.3-1144.1.x86_64.rpm':
Error code: Connection failed
Error message: Could not resolve host: download.opensuse.org

Problem occurred during or after installation or removal of packages:
Installation has been aborted as directed.
Please see the above error message for a hint.
```

Previously, everything worked perfectly well. I ran the command `curl http://download.opensuse.org/repositories/home:/regataos/openSUSE_Tumbleweed/x86_64/Mesa-libglapi0-20.1.3-1144.1.x86_64.rpm` on the terminal and received the following output:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="http://ftp2.nluug.nl/os/Linux/distr/opensuse/repositories/home:/regataos/openSUSE_Tumbleweed/x86_64/Mesa-libglapi0-20.1.3-1144.1.x86_64.rpm">here</a>.</p>
<hr>
<address>Apache/2.4.43 (Linux/SUSE) Server at download.opensuse.org Port 80</address>
</body></html>
```

However, when I execute the `curl` command on the terminal with the `--location` (follow redirects) option together with the same link to download the package, I am successful and the error no longer happens. Does anyone have any idea what can be done to fix the problem?

## Expected behaviour
The packages would be downloaded to start the installation and generate the ISO image. 

## Steps to reproduce the behaviour
Just try to create an ISO image with KIWI in openSUSE on your personal computer. I am trying to create a Live Linux (CD/DVD ISO).

## OS and Software information
+ KIWI version: 9.21.3
+ Operating system: OpenSUSE Leap 15.1

**Comment by schaefi** [comment]
> Could not resolve host: download.opensuse.org

That could have several reasons:

* a hiccup of the server. I guess a simply retry does not change the behavior and it fails every time ?
* a problem in DNS resolving inside of the new root tree. You can test this as follows:

  ```
  chroot /path/to/the/current/kiwi/created/root/tree
  curl ...
  ```

Can you reproduce the problem that way somehow ?

**Comment by LinuxbuzzSoftware** [comment]
Hello, thank you very much for answering me.

I've made several attempts, even now I have openSUSE Leap 15.2 installed with the latest version of Kiwi that I found (available in the Virtualization:Appliances:Builder repository).

Okay. I'm going to do what you told me and check if there are any problems involving DNS.

**Comment by LinuxbuzzSoftware** [comment]
When checking for a problem with DNS resolution within the new root tree, I get the following:

`curl: (6) Could not resolve host: download.opensuse.org`

Although I still have no idea how to solve this, I will put some network related packages in the "bootstrap" section to see if I can fix the problem.

**Comment by LinuxbuzzSoftware** [comment]
This does not seem to be a problem involving the openSUSE server, since when running the `curl google.com` command, for example, the same error happens.

I also used older versions of the curl (libcurl4), zypper and libzypp packages with openSUSE Leap 15.1, still to no avail.

**Comment by LinuxbuzzSoftware** [comment]
This problem not only runs with the openSUSE server, but with whatever the URL. For example:

```
chroot /path/to/the/current/kiwi/created/root/tree bash
curl ww.google.com
```

Apparently, as everything is now, a user cannot create images on his personal computer with openSUSE (I'm not sure if it affects other Linux distributions) with the Kiwi tool.

However, as other people do not seem to be experiencing this on their personal computers (since they have not yet given feedback), it is understood that this is only a local and isolated problem. So please, if you are also experiencing this problem, it is important that you give feedback (if everything is working perfectly well for you in a similar scenario, it is also worth giving feedback here).

**Comment by LinuxbuzzSoftware** [comment]
@schaefi  Thanks to the help of Antônio Medeiros, leader of the Linux Kamarada project, I managed to find a solution to the problem. It turns out that the `download.opensuse.org` domain now points to the nearest mirror. So, from now on it may be necessary to add host information (such as the IP address) in the `/etc/hosts` file so that Kiwi on the desktop can download and install packages normally.

I used the nslookup command to get the IP address (for example: `nslookup download.opensuse.org`). For example, so that everything goes right for me, I had to add the following to my `/etc/hosts` file:

```
195.135.221.140 opensuse.org
195.135.221.134 download.opensuse.org
195.135.221.157 downloadcontent.opensuse.org
200.236.31.10 opensuse.c3sl.ufpr.br
145.220.21.40 ftp2.nluug.nl
134.76.12.6 ftp.gwdg.de
195.135.221.140
195.135.221.134
195.135.221.157
200.236.31.10
145.220.21.40
134.76.12.6
```

Obviously, this can vary, depending on the country where the user lives. Well, I hope I helped with this information.

**Comment by LinuxbuzzSoftware** [comment]
I continued with my tests and managed to trace this problem to the file `/etc/nsswitch.conf` of the new root tree created by KIWI to generate the ISO image. So what I did to solve this problem was to add to the file nsswitch.conf, available in the new root tree, the following:

```
#
# /etc/nsswitch.conf
#
# An example Name Service Switch config file. This file should be
# sorted with the most-used services at the beginning.
#
# Valid databases are: aliases, ethers, group, gshadow, hosts,
# initgroups, netgroup, networks, passwd, protocols, publickey,
# rpc, services, and shadow.
#
# Valid service provider entries include (in alphabetical order):
#
#	compat			Use /etc files plus *_compat pseudo-db
#	db			Use the pre-processed /var/db files
#	dns			Use DNS (Domain Name Service)
#	files			Use the local files in /etc
#	hesiod			Use Hesiod (DNS) for user lookups
#	nis			Use NIS (NIS version 2), also called YP
#	nisplus			Use NIS+ (NIS version 3)
#
# See `info libc 'NSS Basics'` for more information.
#
# Commonly used alternative service providers (may need installation):
#
#	ldap			Use LDAP directory server
#	myhostname		Use systemd host names
#	mymachines		Use systemd machine names
#	mdns*, mdns*_minimal	Use Avahi mDNS/DNS-SD
#	resolve			Use systemd resolved resolver
#	sss			Use System Security Services Daemon (sssd)
#	systemd			Use systemd for dynamic user option
#	winbind			Use Samba winbind support
#	wins			Use Samba wins support
#	wrapper			Use wrapper module for testing
#
# Notes:
#
# 'sssd' performs its own 'files'-based caching, so it should generally
# come before 'files'.
#
# WARNING: Running nscd with a secondary caching service like sssd may
# 	   lead to unexpected behaviour, especially with how long
# 	   entries are cached.
#
# Installation instructions:
#
# To use 'db', install the appropriate package(s) (provide 'makedb' and
# libnss_db.so.*), and place the 'db' in front of 'files' for entries
# you want to be looked up first in the databases, like this:
#
# passwd:    db files
# shadow:    db files
# group:     db files

passwd:		compat
group:		compat
shadow:		compat
# Allow initgroups to default to the setting for group.
# initgroups:	compat

hosts:  	files mdns_minimal [NOTFOUND=return] dns
networks:	files dns

aliases:	files usrfiles
ethers:		files usrfiles
gshadow:	files usrfiles
netgroup:	files nis
protocols:	files usrfiles
publickey:	files
rpc:		files usrfiles
services:	files usrfiles

automount:	files nis
bootparams:	files
netmasks:	files

```

So that the contents of the file could be modified at the right time to the content presented above (to allow the download of packages normally as it should happen) I had to create a new package for the bootstrap session.
With that, I also no longer need to modify the contents of the `/etc/hosts` file, as I showed earlier.

So, to sum it all up, the problem was with the contents of the /etc/nsswitch.conf file.

**Comment by schaefi** [comment]
Thanks for the details. That's very valuable information. I wonder why we don't see this to be a problem in a more global way. Actually this is the only report I know about where this issue occurs.

I think there is little we can do from the appliance builder side 

@davidcassany Your feedback is appreciated too.

Thanks

**Comment by schaefi** [comment]
Thanks much for all the details, we will keep this as a history for others
