### ISSUE TITLE
Strict versioned RPM dependency on dracut-kiwi-lib for dracut-kiwi-oem-* packages

### ISSUE THREAD

**Issue by deacomm** [OSInside/kiwi#1529]
Some of the dracut-kiwi-* RPM packages currently have a simple "dracut-kiwi-lib" dependency, without specifying exact version of the package. 

During an image build, this would pull in the dracut-kiwi-lib package of any version, should there be multiple versions of this package available in configured repositories (usually highest version available), thus potentially breaking dracut-kiwi functionality with incompatible code.

The RPM packages which depend on dracut-kiwi-lib should therefore specify the exact version of the lib package in their dependencies instead.

**Comment by davidcassany** [comment]
Starting to work on this one
