### ISSUE TITLE
Serious issue with squashfs and kernel 5.8.0

### ISSUE THREAD

**Issue by geckolinux** [OSInside/kiwi#1531]
Hi there, I'm fighting with a really weird issue. I've been building ISOs with Kiwi for years. I use a VPS running openSUSE 15.2 and whatever is the latest version of Kiwi to build live ISOs based on Tumbleweed or Leap 15.2. My most recent successful builds based on Tumbleweed were on 2020-07-29. But during the past week I have tried to build ISOs based on the Kiwi descriptions that I saved from that last date, and I haven't changed them. The ISOs generate successfully and they boot, but the wallpaper PNG that I placed as an overlay in `/usr/share/backgrounds` results in an input/output error when trying to access it, and while trying to do so dmesg complains about bad blocks in the squashfs. I then noticed that most (but not all) of the other images that were placed in `/usr/share/backgrounds` are also corrupt and/or only partially load. When trying to copy the `/usr/share/backgrounds` directory to the overlay filesystem in `~/` via the terminal in fails with input/output errors, and the GUI file manager throws an "Error splicing file".

I have repeated this bug multiple times with many different VPS instances on two different VPS platforms. It only occurs with ***ISOs*** generated with Kiwi, whereas raw images are fine. And this bug only very recently started appearing on my newly generated Tumbleweed-based ISOs, whereas newly generated Leap-based ISOs are fine. I will also attach a Kiwi description generated from the http://download.opensuse.org/history/20200807/tumbleweed snapshot, before kernel 5.8.0 appeared, which does not exhibit this bug. I'm almost sure that this is the culprit, but I'd appreciate it if someone more knowledgeable could confirm it:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=93e72b3c612adcaca13d874fcc86c53e6c8da541

I attached a build log in this thread:
https://groups.google.com/g/kiwi-images/c/TKYofcuUxxA

[Kiwi description with Tumbleweed 20200807, NO BUG](https://github.com/OSInside/kiwi/files/5079259/Kiwi_NO-BUG.tar.gz)

[Kiwi description with latest Tumbleweed and kernel 5.8.0, squashfs bugs](https://github.com/OSInside/kiwi/files/5079265/Kiwi_BUGGY.tar.gz)

**Comment by geckolinux** [comment]
https://bugzilla.opensuse.org/show_bug.cgi?id=1175308

**Comment by geckolinux** [comment]
I just tested the latest official openSUSE Tumbleweed daily ISO too, with similar issues.

**Comment by LinuxbuzzSoftware** [comment]
I am also experiencing a similar problem. After the ISO image is created, some files compressed with .tar.xz that come by default within the ISO cannot be accessed. The KDE Plasma Ark application tells me that these files are corrupted.

I am generating the ISO image with Linux Kernel 5.8.1. I will do more tests to see if the problem that is happening to me is related to the new Linux Kernel.

**Comment by schaefi** [comment]
Hi, thanks much for all the testing. We can keep this open as a tracker

**Comment by schaefi** [comment]
Thanks much, I'll set a label to classify the history of this issue. I suggest we keep this open until TW has the fix. Current kernel is kernel-default-5.8.0-1.1. I expect this to be fixed with 5.8.2 and onward

**Comment by schaefi** [comment]
Hi, the current kernel in TW is 5.8.12, thus should have been solved, correct ?

**Comment by geckolinux** [comment]
Yes, I can confirm that the issue is now solved. Thanks!
