### ISSUE TITLE
baseCleanMount is not compatible with set -e

### ISSUE THREAD

**Issue by Vogtinator** [OSInside/kiwi#1536]
It's good practice to use `set -e` in `config.sh` and related scripts to ensure that there is no silent breakage.
However, that breaks the call to `baseCleanMount` at the end:

```
[  111s] + baseCleanMount
[  111s] + for path in /proc/sys/fs/binfmt_misc /proc /dev/pts /sys
[  111s] + '[' -d /proc/sys/fs/binfmt_misc ']'
[  111s] + umount /proc/sys/fs/binfmt_misc
[  111s] 
[  111s] [ INFO    ]: 11:26:51 | Cleaning up SystemPrepare instance
```

Full log: https://build.opensuse.org/package/live_build_log/home:favogt:kiwisete/kiwi-templates-JeOS:kvm-and-xen/openSUSE_Tumbleweed/x86_64

**Comment by davidcassany** [comment]
Thanks the report I'd say we could eventually get rid of `baseMount` and `baseCleanMount` and deprecate these methods, with current kiwi this shouldn't be required any longer.

@schaefi I see no reason to keep them. I would just turn them into log message that warns the user this is deprecated and safe to remove from the scripts. Does it makes sense to you?

**Comment by Vogtinator** [comment]
> Thanks the report I'd say we could eventually get rid of baseMount and baseCleanMount and deprecate these methods, with current kiwi this shouldn't be required any longer.

Indeed, I don't actually know why it was still called. This issue was probably caused by having `baseCleanMount` without a preceding `baseMount`. It seems like it's been that way forever, a bug carried over multiple generations of maintainers.

**Comment by schaefi** [comment]
going to work on this
