### ISSUE TITLE
SUSE12 SP4 image creation fails at 33%

### ISSUE THREAD

**Issue by IT-Guy-1973** [OSInside/kiwi#1537]
## Problem description
I am trying to create a SUSE12 SP4 image for Azure using KIWI. Each time I run the below command it hangs at 33%.

KIWI-Master:~ # kiwi-ng --type vmx system build --description kiwi-descriptions/suse/x86_64/SUSE12 --target-dir /tmp/myimage12

There is no error. It hangs infidelity.

[ INFO    ]: 04:02:20 | --> package: ca-certificates
[ INFO    ]: 04:02:20 | --> package: ca-certificates-mozilla
[ INFO    ]: 04:02:20 | --> package: cracklib-dict-full
[ INFO    ]: 04:02:20 | --> package: filesystem
[ INFO    ]: 04:02:20 | --> package: glibc-locale
[ INFO    ]: 04:02:20 | --> package: zypper
[ INFO    ]: Processing: [#############                           ] 33%

## OS and Software information
+ KIWI version: 
python3-kiwi-9.20.5-3.21.3.x86_64

+ Operating system: 

KIWI-Master:~ # cat /etc/os-release
NAME="SLES"
VERSION="15-SP2"
VERSION_ID="15.2"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP2"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp2"

+ OBS version:

**Comment by IT-Guy-1973** [comment]
This is the logfile output.

KIWI-Master:/tmp/myimage12/build # tail -f image-root.log
DEBUG: 04:02:32 | bootstrap: warning: /tmp/myimage12/build/image-root/var/cache/kiwi/packages/SUSE_Linux_Enterprise_Server_for_SAP_Applications_x86_64:SLES12-SP4-Updates/x86_64/libsemanage1-2.5-9.3.1.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 39db7c82: NOKEY
DEBUG: 04:02:32 | bootstrap: Retrieving package krb5-1.12.5-40.37.7.x86_64 (59/83), 577.0 KiB (  1.8 MiB unpacked)
DEBUG: 04:02:32 | bootstrap: Retrieving: krb5-1.12.5-40.37.7.x86_64.rpm [done]
DEBUG: 04:02:32 | bootstrap: (59/83) Installing: krb5-1.12.5-40.37.7.x86_64 [............done]
DEBUG: 04:02:32 | bootstrap: Additional rpm output:
DEBUG: 04:02:32 | bootstrap: warning: /tmp/myimage12/build/image-root/var/cache/kiwi/packages/SUSE_Linux_Enterprise_Server_for_SAP_Applications_x86_64:SLES12-SP4-Updates/x86_64/krb5-1.12.5-40.37.7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 39db7c82: NOKEY
DEBUG: 04:02:32 | bootstrap: Retrieving package libtasn1-6-4.9-3.10.1.x86_64 (60/83),  45.2 KiB ( 74.6 KiB unpacked)
DEBUG: 04:02:32 | bootstrap: Retrieving: libtasn1-6-4.9-3.10.1.x86_64.rpm [done]
DEBUG: 04:02:32 | bootstrap: (60/83) Installing: libtasn1-6-4.9-3.10.1.x86_64 [......done]
DEBUG: 04:02:32 | bootstrap: Additional rpm output:

**Comment by IT-Guy-1973** [comment]
[image-root.log](https://github.com/OSInside/kiwi/files/5153899/image-root.log)

**Comment by IT-Guy-1973** [comment]
I tried changing the repositories from SMT to ISO. Tried multiple times. Each occasion is would retrieve some amount of packages and hang indefinitely.   In the case here is is hanging at (60/83). In other occasions it was (65/83) and so on. So I figured it was not related to packages not been retrieved.

Regards,
Niranjan

**Comment by davidcassany** [comment]
strange error... never seen in before, at glance looks like if the installation requires some sort of interaction that zypper is not properly handling, but this is just a mere guess :thinking: I did a run of SLES-SP4 JeOS on my Leap 15.1 host and it just worked fine out of the box. Would it be possible for you to share the description XML file (or the relevant parts of it: repositories, packages list and `<type>` section for vmx)?

Regarding the environment I have to note that building SLE-12-SP4 images in a SLE-15-SP2 host is a non supported scenario. It doesn't mean it's known to fail, it means this is not tested and there are no guarantees it works. Basically from a SLE-15-SPx box we support building SLE-15-SPx images, as the gap between the host and the image grows we can't guarantee this is functional. SLE12 series against SLE15 series is quite a huge gap. So I'd strongly recommend to build SLE12-SPx images from a SLE12 host.

**Comment by IT-Guy-1973** [comment]
@davidcassany ,

Thank you for your reply. I will share the requested files shortly. You mention here that  "SLE-12-SP4 images in a SLE-15-SP2 host is a non supported scenario". Where did you get that information? Is it somewhere in the documentation? Also, where can I find the "config.xml" files for SUSE12 SP4 JeOS images?

Regards,
Niranjan

**Comment by IT-Guy-1973** [comment]
@davidcassany I have attached the config.xml file here. The file name is config-text.txt.

[config-text.txt](https://github.com/OSInside/kiwi/files/5156287/config-text.txt)

**Comment by IT-Guy-1973** [comment]
@davidcassany Can you please tell me where it is getting this list of 83 rpms? Is it coming from the following section?

 <packages type="bootstrap">
    <package name="filesystem"/>
    <package name="ca-certificates"/>
    <package name="ca-certificates-mozilla"/>
    <package name="cracklib-dict-full"/>
    <package name="glibc-locale"/>
  </packages>

Regards,
Niranjan

**Comment by IT-Guy-1973** [comment]
@davidcassany @schaefi 

I tried to install "kiwi-ng" on SUSE12 SP4. However, it is not available for SUSE12 SP4. 

See below:

https://download.opensuse.org/repositories/Virtualization:/Appliances:/Builder/

There is no SUSE 12 SPxx version available.

Regards,
Niranjan

**Comment by IT-Guy-1973** [comment]
@davidcassany 

Can you please provide me the steps you followed to create the SUSE12SP4 JeOS image? Like you said I was able to past the initial issue by running the KIWI built on a SUSE 12 server however I am running into the following dependency issues.

DEBUG: 01:13:00 | system: Resolving package dependencies...
DEBUG: 01:13:00 | system: 78 Problems:
DEBUG: 01:13:00 | system: Problem: nothing provides python(abi) = 3.6 needed by azure-cli-2.0.45-4.22.noarch
DEBUG: 01:13:00 | system: Problem: nothing provides python(abi) = 3.6 needed by azure-cli-acr-2.1.4-4.22.noarch
DEBUG: 01:13:00 | system: Problem: nothing provides python(abi) = 3.6 needed by azure-cli-acs-2.3.2-4.22.noarch
DEBUG: 01:13:00 | system: Problem: nothing provides python(abi) = 3.6 needed by azure-cli-appservice-0.2.3-4.22.noarch
DEBUG: 01:13:00 | system: Problem: nothing provides python(abi) = 3.6 needed by azure-cli-backup-1.2.1-4.22.noarch
DEBUG: 01:13:00 | system: Problem: nothing provides python(abi) = 3.6 needed by azure-cli-batch-3.3.3-4.22.noarch
DEBUG: 01:13:00 | system: Problem: nothing provides python(abi) = 3.6 needed by azure-cli-billing-0.2.0-4.22.noarch
DEBUG: 01:13:00 | system: Problem: nothing provides python(abi) = 3.6 needed by azure-cli-cdn-0.1.1-4.22.noarch


Regards,
Niranjan

**Comment by schaefi** [comment]
I think this issue got fixed

The problem was that azure-cli required a python3-humanfriendly package which got accidentally dropped by suse maintenance. The package has been re-added meanwhile and as far as I understood this fixed the reported issue here.

If this is not the case please open again including details. Thanks
