### ISSUE TITLE
Creating a SUSE12SP4 Image for Azure using KIWI

### ISSUE THREAD

**Issue by IT-Guy-1973** [OSInside/kiwi#1540]
## Problem description

I am getting the following error attempting to create a SUSE12 SP4 image for Azure.

DEBUG: 01:13:00 | system: Resolving package dependencies...
DEBUG: 01:13:00 | system: 78 Problems:
DEBUG: 01:13:00 | system: Problem: nothing provides python(abi) = 3.6 needed by azure-cli-2.0.45-4.22.noarch
DEBUG: 01:13:00 | system: Problem: nothing provides python(abi) = 3.6 needed by azure-cli-acr-2.1.4-4.22.noarch
DEBUG: 01:13:00 | system: Problem: nothing provides python(abi) = 3.6 needed by azure-cli-acs-2.3.2-4.22.noarch
DEBUG: 01:13:00 | system: Problem: nothing provides python(abi) = 3.6 needed by azure-cli-appservice-0.2.3-4.22.noarch
DEBUG: 01:13:00 | system: Problem: nothing provides python(abi) = 3.6 needed by azure-cli-backup-1.2.1-4.22.noarch
DEBUG: 01:13:00 | system: Problem: nothing provides python(abi) = 3.6 needed by azure-cli-batch-3.3.3-4.22.noarch
DEBUG: 01:13:00 | system: Problem: nothing provides python(abi) = 3.6 needed by azure-cli-billing-0.2.0-4.22.noarch
DEBUG: 01:13:00 | system: Problem: nothing provides python(abi) = 3.6 needed by azure-cli-cdn-0.1.1-4.22.noarch

What is the solution to this issue?

## OS and Software information

SUSE12 SP4

+ KIWI version: 

 python2-kiwi   

+ Operating system: 
+ OBS version:

**Comment by schaefi** [comment]
Hi, please report the dependency issue of azure-cli to John Paul Adrian Glaubitz <adrian.glaubitz@suse.com>. He is the maintainer of the azure-cli package and can help you solving the python deps. Please note kiwi is a user of repos and packages and not the tool that can fix dependency issues that comes with the repo setup you have used.

Because of that there is little to nothing we can do in the kiwi code to solve this issue. You can CC me to the message you might want to send to Adrian so I can assist in the mail thread when needed.

Hope this makes sense to you too. Thanks

**Comment by IT-Guy-1973** [comment]
Hello Adrian,
I have been trying to create SUSE15 SP1 and SUSE12 SP4 images for Azure using kiwi-ng. 

It has not been easy so far as there are a lot of dependency issues for packages although I have provided all the available repositories (SUSE official repos from SCC)  for the two SUSE versions in the config.xml file. I was (finally) able to create a SUSE15 SP1 image that worked on Azure using KIWI but still could not for SUSE12 SP4. 
For SUSE 12 SP4 it is looking for a "python3-humanfriendly" package that is not available in any of the SUSE12 SP4 repos that SUSE provides officially on any of their repositories. Therefore, I downloaded this python package from OpenSUSE but then after that it is giving me the below dependency.
"nothing provides python(abi) = 3.6 needed by python-pssh-2.3.1-22.1.noarch"




I am creating the "config.xml" file for these SUSE versions by running "machinery" and creating a KIWI profile on a Azure marketplace image. 
SUSE12:~ # machinery export-kiwi --kiwi-dir=/source/kiwi localhost
Then I use that "config.xml" file to get the list of packages for my image. 
However, when I run the command to build the image it gives me errors on dependencies one after the other. Never ending. But I have added all available repositories SUSE has to offer.
I will attach the config.xml here for the SUSE12 SP4. 
Please let me know if you have a "config.xml" file that includes a minimum set of packages I could use to build my images for SUSE12 SPX and SUSE 15 SPX. Maybe the marketplace images I am using to create my "config.xml" have more packages than what is needed.
I have open multiple cases with SUSE support and Microsoft Azure but no one at SUSE or Microsoft has able to help me so far. 
I have also attached the log for the image build.
Thank you for your support,
Regards,Niranjan


    On Saturday, September 5, 2020, 11:16:16 AM MST, Marcus Schäfer <notifications@github.com> wrote:  
 
 


Hi, please report the dependency issue of azure-cli to John Paul Adrian Glaubitz adrian.glaubitz@suse.com. He is the maintainer of the azure-cli package and can help you solving the python deps. Please note kiwi is a user of repos and packages and not the tool that can fix dependency issues that comes with the repo setup you have used.

Because of that there is little to nothing we can do in the kiwi code to solve this issue. You can CC me to the message you might want to send to Adrian so I can assist in the mail thread when needed.

Hope this makes sense to you too. Thanks

**Comment by IT-Guy-1973** [comment]
Hello Adrain,

Can you please help us resolve these issues?

We just need the repo names and a config.xml file to create SUSE12 images on Azure.

Right now as we see it the cloud repositories in SUSE does not provide the packages needed to create images using KIWI for Azure.

Regards,
Niranjan

**Comment by IT-Guy-1973** [comment]
Hello Marcus,

Adrian is not responding.

Can you please let me know who else is there to support us on this request?

Thank you,
Regards,
Niranjan

From: Hettiwatte, Niranjan
Sent: Wednesday, September 9, 2020 10:37 AM
To: 'Niranjan Hettiwatte'; OSInside/kiwi; OSInside/kiwi; adrian.glaubitz@suse.com
Cc: Author; marcus.schaefer@gmail.com
Subject: RE: [OSInside/kiwi] Creating a SUSE12SP4 Image for Azure using KIWI (#1540)

Hello Adrain,

Can you please help us resolve these issues?

We just need the repo names and a config.xml file to create SUSE12 images on Azure.

Right now as we see it the cloud repositories in SUSE does not provide the packages needed to create images using KIWI for Azure.

Regards,
Niranjan

**Comment by IT-Guy-1973** [comment]
Hello Niranjan!

On 9/11/20 5:38 AM, Niranjan.Hettiwatte@Virtustream.com wrote:
> Adrian is not responding.
> 
> Can you please let me know who else is there to support us on this request?

Apologies, I missed that mail, probably because it said "Kiwi" in the subject
which is normally not my field of work.

I'll have a look today.

Adrian
