### ISSUE TITLE
Kiwi OEM resizing breaks root partition

### ISSUE THREAD

**Issue by Vogtinator** [OSInside/kiwi#1543]
Originally reported on https://lists.opensuse.org/opensuse-kubic/2020-09/msg00018.html

The OEM image has the partitions aligned at 512B sectors, but the target device can have a vastly different optimal I/O size.
This means that when deleting and recreating the partition, sfdisk aligns it differently and so it becomes useless.

Kiwi has to ensure that the start of the partition stays the *exact* same, no matter the alignment.
In addition, using a higher alignment by default (4kiB or 1MiB) would improve performance outside of virtual disks.

**Comment by schaefi** [comment]
I see. I think that was the reason why we used fixed start_sector assignment when parted was still the tool to run the repart operation. I'll come up with a fix next
