### ISSUE TITLE
LimeJeOS should be replaced

### ISSUE THREAD

**Issue by vmoutoussamy** [OSInside/kiwi#1544]
## Problem description
There is a lot of LimeJeOS reference in the documentation and I think we should rename it openSUSE JeOS.

LimeJeOS is not used anymore by the openSUSE community, at least I don't find it in https://software.opensuse.org/distributions/leap but I see openSUSE JeOS images, AND no entry https://en.opensuse.org/LimeJeos but https://old-en.opensuse.org/LimeJeos, AND https://www.google.com/search?hl=en&q=limejeos%20suse is a time traveling to 2008.

## Expected behaviour
openSUSE JeOS instead of LimeJeOS

Since I'm more familiar with the regular SUSE doc structure and format, could you please let me know how should I proceed to replace LimeJeOS by openSUSE JeOS?

**Comment by schaefi** [comment]
Actually a good idea. Here is how I think this could work and I really appreciate your help:

1. Adapt the name attribute in all kiwi example descriptions in the following repository and create a PR for review:
    https://github.com/OSInside/kiwi-descriptions

2. Adapt the documentation that references example descriptions here:
    https://github.com/OSInside/kiwi/blob/master/doc/source/conf.py

    We use a template to reference the example for the purpose of the documentation

    ```
    '{exc_image_base_name}': 'LimeJeOS-Leap-15.1',
    ```

    If you change all descriptions to use openSUSE-JeOS in a common way the change for the docs should be a straight forward
    pull request

The documentation rendering process is automated. So once the PRs has been merged there is nothing more you need to care for.

Does this makes sense ?

Thanks much

**Comment by schaefi** [comment]
If you consider to take over this task it would be fantastic. In this case feel free to set yourself as assignee. If you want us to do it we will pick it up for the next sprint(October)

**Comment by schaefi** [comment]
@davidcassany your opinion about this change is appreciated too. The term LimeJeOS was an invention at the time we created the SUSE Studio project. All of it is gone now so nobody will understand why we use this name. From that perspective it would be good to name the examples according to the distribution.

**Comment by vmoutoussamy** [comment]
Ok, I'll try to do this myself, please assign this issue to me because I don't think I have the permission to do it myself ; ). 
FYI, I have also edit your wiki page https://en.opensuse.org/Portal:KIWI/FAQ#Q:_Is_there_an_appliance_that_contains_Kiwi.3F to remove LimeJeOS.

**Comment by schaefi** [comment]
> Ok, I'll try to do this myself, please assign this issue to me 

Thanks much, done now. I also sent a triage invitation which should make working with the repo a bit easier. Let me know when more permissions are needed

> FYI, I have also edit your wiki page

The wiki is outside of our control. Many information there is wrong or outdated. But thanks for also looking into this space.
We maintain the upstream documentation from which also the SUSE docs are created under documentation.suse.com exclusively. All other source of docs and faq's is maintained by other groups... and I think I don't know all of them ;)

**Comment by davidcassany** [comment]
Thanks much @vmoutoussamy  for checking and verifying this sort of details, this is very much appreciated. 

>  https://www.google.com/search?hl=en&q=limejeos%20suse is a time traveling to 2008

Yey, this more or less time were I got introduced to KIWI and Studio for the first time as community user. My early days in Linux hacking :) I always liked that LimeJeOS name (pronounced as _lime juice_). I am gonna miss it. Anyway, I agree that if this no longer being used in Studio and/or its derivatives and the term is mostly abandoned we should also move forward and be consistent. I agree we should name our examples in clearer way, I am even considering if using  `openSUSE JeOS` is not confusing. Given that our examples are not the sources of the actual `openSUSE JeOS` images that are being distributed.

I guess this is up to you @vmoutoussamy, I like the substitution of `LimeJeOS` to `openSUSE_JeOS` as you suggested, so if you think this is not confusing I am absolutely happy with this change.

**Comment by vmoutoussamy** [comment]
> Thanks much @vmoutoussamy for checking and verifying this sort of details, this is very much appreciated.
> 
> > https://www.google.com/search?hl=en&q=limejeos%20suse is a time traveling to 2008
> 
> Yey, this more or less time were I got introduced to KIWI and Studio for the first time as community user. My early days in Linux hacking :) I always liked that LimeJeOS name (pronounced as _lime juice_). I am gonna miss it. Anyway, I agree that if this no longer being used in Studio and/or its derivatives and the term is mostly abandoned we should also move forward and be consistent. I agree we should name our examples in clearer way, I am even considering if using `openSUSE JeOS` is not confusing. Given that our examples are not the sources of the actual `openSUSE JeOS` images that are being distributed.
> 
> I guess this is up to you @vmoutoussamy, I like the substitution of `LimeJeOS` to `openSUSE_JeOS` as you suggested, so if you think this is not confusing I am absolutely happy with this change.

ooohhh now I see. 
First, yes I really liked the name JeOS since the beginning and right now I'm trying to find way to bring it back to the spotlight but try to narrow it down to the official openSUSE and SLES JeOS images. 

And for instance the configuration [suse-leap-15.2-JeOS/config.xml](https://github.com/OSInside/kiwi-descriptions/blob/master/suse/x86_64/suse-leap-15.2-JeOS/config.xml)  is not what I would consider as JeOS since it is something different from **[openSUSE:Leap:15.2:Images/kiwi-templates-JeOS/JeOS.kiwi](https://build.opensuse.org/package/view_file/openSUSE:Leap:15.2:Images/kiwi-templates-JeOS/JeOS.kiwi?expand=1). Especially regarding the FS choice! Ext4 and btrfs respectively. 

I thought this was just a matter of documentation but now it's more interesting. IMHO there is two choices: 

1. Update config.xml to make it similar to JeOS.kiwi, then keep the name openSUSE_JeOS,
2. Don't touch any kiwi-descriptions but rename LimeJeOS by something more neutral like "openSUSE_minimal", "openSUSE_appliance" or "openSUSE_oem" ?!

I know 1. might be too big as a change, but I would be really interested by it and really opened for discussion.
What do you guys think?  @davidcassany @schaefi 

[1] https://github.com/OSInside/kiwi-descriptions/blob/master/suse/x86_64/suse-leap-15.2-JeOS/config.xml
[2] https://build.opensuse.org/package/view_file/openSUSE:Leap:15.2:Images/kiwi-templates-JeOS/JeOS.kiwi?expand=1

**Comment by davidcassany** [comment]
Regarding the options you suggest I absolutely fine by renaming our examples to something like `openSUSE_minimal` or `openSUSE_appliance`.

Note that those image descriptions are used for example purposes, so they are simple and not meant to be used inside OBS. I am noting that because the official JeOS images include profiles and some OBS metadata so I'd consider them to be cryptic to anyone learning or starting to work with KIWI. So making our examples to look closer to the current distributed JeOS is something we could do, however I doubt we could ever consider using the same sources. So, even if we now trying to align our examples to current JeOS images I doubt there is much gain from an example perspective and also there will not be any guarantee that our examples match JeOS criteria and/or evolution.

All in all what I mean is that think the keeping these two things separate might be best from a maintenance perspective and also probably the best in terms of not confusing the KIWI examples with the maintained JeOS images.

@vmoutoussamy does it makes sense to you?

**Comment by vmoutoussamy** [comment]
@davidcassany I agree!

I would highly recommend to use openSUSE_appliance, since the first section of our documentation talk about the "appliance concept" ; ). 

https://documentation.suse.com/kiwi/9/single-html/kiwi/#the-appliance-concept

So I'll try to do the s/openSUSE_JeOS/openSUSE_appliance/g

**Comment by vmoutoussamy** [comment]
and https://github.com/OSInside/kiwi-descriptions/pull/77
