### ISSUE TITLE
Wrong grub2 installation in Ubuntu Focal

### ISSUE THREAD

**Issue by davidcassany** [OSInside/kiwi#1547]
## Problem description

OEM images of Ubuntu Focal complain with a `can't find command save_env` error on boot, after about 10 seconds of this error msg pressing any key triggers the boot to continue normally. 

Apparenlty this might be caused by a wrong `grub-install` call. In fact in KIWI for any x86 architecture we use the `--target i386-pc`, however `x86_64-efi` (for x86_64 architectures) seams to be required for Ubuntu. I have no idea about how Ubuntu differs from other distros on that regard, but being on x86_64 with en EFI/UEFI setup using `x86_64-efi` definitely looks like the correct target. I am wondering why we are not seeing this issue in other distros. 

So after boot the effected image I can simply run

`$ grub-install --target x86_64-efi --boot-directory /boot /dev/sda`

and this solves the issue. Moreover I verified that if a reinstall grub again with:

`$ grub-install --target i386-pc --boot-directory /boot /dev/sda`

brings back the reported problem. Note that the grub configuration files were not touched in any case, thus I assume the grub config files generated by KIWI are correct.

## Expected behaviour

OEM image boots without error messages and `press any key to continue` interactive messages.

## Steps to reproduce the behaviour

Boot the OEM image for the UBUNTU integration test.

**Comment by schaefi** [comment]
Urks, this looks like a generic problem to me. I think I have a small patch to fix this and will send it as PR. Also the unit tests are bad and actually shows the problem
