### ISSUE TITLE
Boot fails on images with separate /boot partition

### ISSUE THREAD

**Issue by Vogtinator** [OSInside/kiwi#1553]
On Leap 15.1, booting fails: https://openqa.opensuse.org/tests/1386592

This is because `/EFI/boot/grub.cfg` on the ESP contains

```
set prefix=(${root})//grub2
configfile (${root})/boot/grub2/grub.cfg
```

As `$root` points to the boot partition here, the `/boot` part is wrong. grub2-install itself uses `source "${prefix}/grub.cfg"`, which should work here as well AFAICT.

**Comment by davidcassany** [comment]
I could reproduce it, I am having look
