### ISSUE TITLE
Functional testing of integration tests

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi#1555]
in the past and in several different situation we would have been in a better position if a functional test of an image, meaning
an image that is actually really booted, would have existed before we release.

Recently we saw it on grub2 and secure boot and the changes the people did. Result: GCE images broken for secure boot.
Consequence: A bug in a hurry, testing of the fix, starting a new release, keeping fingers crossed nothing else broke due to
the hurry.

For me this is a situation that becomes more and more inacceptable and we should put on a system that does automated functional tests of our integration test images

**Comment by dcermak** [comment]
openQA could definitely provide some of the necessary features for the kiwi test builds:
- it can launch arbitrary VMs and boot from virtual machine disk images
- tests can be partitioned into individual steps that can be combined into test suites (e.g. have a different boot up workflow for isos and virtual machine disks but run the same tests once the VM is up and running)
- it can provide a comprehensive overview of one full test run of all test suites belonging to a single build, e.g. https://openqa.opensuse.org/tests/overview?distri=microos&distri=opensuse&version=Tumbleweed&build=20200915&groupid=1
- openQA can be run locally as well, so all tests or just a subset of them can be re-executed locally if desired
- there are already some kiwi tests on in the SLE tests, we could leverage these for even less work

on the other hand, openQA lacks in the following regard:
- there are no public instances like with travis or github actions: we'd either have to host our own or use openqa.opensuse.org (provided that the o3 maintainers agree). In any case, it would mean that the test cases will **not** be part of this repository.
- Triggering builds automatically from OBS is afaik not that straight forward. However, as this would be probably intended for a weekly verification run (?) a manual trigger would be definitely doable via a script.
- openQA only really supports qemu as a backend. Other types of virtualization can be used by relying on nested virtualization, but that is a huge pain in the backside as nested virtualization adds so many problems.

**Comment by dcermak** [comment]
Another advantage of openQA is the ability to run tests on a plethora of architectures: o3 for executes tests on x86, aarch64 and ppc64. In theory there are also s390x runners, but none of the tests executed in the last months made it, so I assume that the runner has been dead for a while now.

**Comment by schaefi** [comment]
There is also a system called kanku: https://kanku.suse.de

The downside is there seems to be no obs/osc integration and the test recipes cannot be taken from a source service

**Comment by schaefi** [comment]
For running tests there is also SUSE-Enceladus/img-proof which is used in openQA to run the tests on instances in the public cloud. It access machines via ssh so in theory it can be used for any system that has ssh access

**Comment by dcermak** [comment]
Maybe we should first compile a list of hard and soft requirements?

**Comment by schaefi** [comment]
yes good point. Mandatory from my perspective is:

* ability to maintain the test receipts in a git repo, at best the repo here
* ability to use a public api to fetch test results
* ability to use a public api to run tests individual or on schedule

**Comment by dcermak** [comment]
> yes good point. Mandatory from my perspective is:
> 
>     * ability to maintain the test receipts in a git repo, at best the repo here

openQA can do this. Having the tests in this repo would require extra hops, but the opensuse tests are stored in https://github.com/os-autoinst/os-autoinst-distri-opensuse

> 
>     * ability to use a public api to fetch test results

This should definitely be doable with openQA out of the box.

> 
>     * ability to use a public api to run tests individual or on schedule

This can be done with openQA (and in this case I actually know how ;-) )

**Comment by schaefi** [comment]
That sounds promising. I'll take a look at the link you posted

**Comment by schaefi** [comment]
@Conan-Kudo are you aware of other systems to perform functional boot tests ? iirc at dato you also put on tests in that area ?

**Comment by dcermak** [comment]
> That sounds promising. I'll take a look at the link you posted

Don't get scared by the fact that most of it is perl ;-). Also, grasping how openQA tests are structure, written and schedule takes a lot of time and patience, so please don't get discouraged because it doesn't make any sense initially (it took me a longer time than I care to admit to even grasp the basic concepts)

**Comment by Conan-Kudo** [comment]
@schaefi We wrote our own Python-based apparatus to do this at Datto that can be invoked from our GitLab CI based system. It's not public, but I could probably ask about it and see what the state of things are.

**Comment by schaefi** [comment]
@dcermak Thanks for the details I looked into the following test:

* https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/tests/boot/boot_to_desktop.pm

The part I did not understand: How can the image to use for this test be selected ? So in fact which image does this test use ?

> ability to use a public api to run tests individual or on schedule
> This can be done with openQA (and in this case I actually know how ;-) )

That sounds very promising. So can you give me some details ? A howto, an api doc or something that allows us to start with. The first stupid question would be on credentials. So it's a service, how can it be accessed ?

Thanks much

**Comment by schaefi** [comment]
Probably this one here: https://github.com/os-autoinst/openQA/blob/master/docs/Installing.asciidoc

**Comment by schaefi** [comment]
But all this looks more like how do I setup my own openQA service... this is not what we want

**Comment by dcermak** [comment]
Marcus Schäfer <notifications@github.com> writes:

> @dcermak Thanks for the details I looked into the following test:
>
> * https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/tests/boot/boot_to_desktop.pm
>
> The part I did not understand: How can the image to use for this test be selected ? So in fact which image does this test use ?

Yeah, you're getting into the more intricate and "fun" parts of openQA ;-).

What you found is a single test, that is part of a test suite (a
combination of variables & tests). Which image is actually used for a
test suite can be tweaked via variables. These are usually set in either
the test suite or more often as part of the job groups.

All of this probably makes no sense at all to you, as getting into this
took me a very long time. Maybe it would make sense to schedule a short
video call or something along those lines where I can show you the
basics? Writing it all down is going to take ages unfortunately :(

>
>> ability to use a public api to run tests individual or on schedule
>> This can be done with openQA (and in this case I actually know how ;-) )
>
> That sounds very promising. So can you give me some details ? A howto, an api doc or something that allows us to start with. The first stupid question would be on credentials. So it's a service, how can it be accessed ?
>

The API is sorta-kinda documented if you access a non-existent route on
openqa, e.g. https://openqa.opensuse.org/not_found but that does not
contain much of a documentation tbh.

I have so far been only really using the `openqa-client` binary using
the `isos post` route, which is used to schedule a test suite run. Afaik
the scheduled tests' status can be also queried via the API, but
unfortunately I don't know how exactly. (And there is also a python
based client: https://github.com/os-autoinst/openQA-python-client)

Authentication is handled via an API key & secret, that have to be
obtained from your openQA instance
(e.g. https://openqa.opensuse.org/api_keys) and put into
~/.config/openqa/client.conf or /etc/openqa/client.conf.

**Comment by davidcassany** [comment]
@schaefi @dcermak I am getting a bit late to the party... Regarding the requirements I fully agree of what @schaefi already mentioned in https://github.com/OSInside/kiwi/issues/1555#issuecomment-694214178, I would only add (I know this is getting into another level of detail) the possibility to script something similar/equivalent to:

```
# 1 fetch the OBS image and uncompress it if needed
# 2 create a virtuak disk image of certain specified size
# 3 dd an image to the created disk
# 4 boot the image
# 5 login the image
# 6 run commands/scripts on the logged system
```

I am just mentioning it because I remembered that a while a go we had some problems due to compressed images and openQA (there were issues to uncompress some disk image). So the above are the basic steps that I think we might need at some point. I am mostly concerned about steps 1~3, the rest should be relatively simple I think if our images are prepared for non interactive ssh logins.

**Comment by dcermak** [comment]
David Cassany Viladomat <notifications@github.com> writes:

> @schaefi @dcermak I am getting a bit late to the party... Regarding the requirements I fully agree of what @schaefi already mentioned in https://github.com/OSInside/kiwi/issues/1555#issuecomment-694214178, I would only add (I know this is getting into another level of detail) the possibility to script something similar/equivalent to:
>
> ```
> # 1 fetch the OBS image and uncompress it if needed

This should be doable by using `repotype: staticlinks` on OBS and
setting the variable HDD_1_URL or HDD_1_DECOMPRESS_URL (see
https://open.qa/docs/#_asset_handling) in openQA.

> # 2 create a virtuak disk image of certain specified size
> # 3 dd an image to the created disk

openQA can do both of these pretty automatically. If I am not mistaken,
then the size of the disk image is set via the variable `HDDSIZEGB`.

> # 4 boot the image
> # 5 login the image
> # 6 run commands/scripts on the logged system
> ```
>
> I am just mentioning it because I remembered that a while a go we had some problems due to compressed images and openQA (there were issues to uncompress some disk image). So the above are the basic steps that I think we might need at some point. I am mostly concerned about steps 1~3, the rest should be relatively simple I think if our images are prepared for non interactive ssh logins.

Indeed, 4 to 6 are very simple to pull off with openQA.

**Comment by schaefi** [comment]
Summary on what has been done so far:

* We decided to create an extra repo to manage the perl based tests and the scheduler for running the tests
  https://github.com/OSInside/kiwi-functional-tests

* The git repo from above contains a very very simple test that runs against a live image integration test. The result is here:
   https://openqa.opensuse.org/tests/1430717

* In openQA scheduling a job is connected with assigning an image. Therefore we need to create a map that defines which
  integration test should run which tests. For example
  
  ```python
      functional_test_map = {
          'https://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/Testing_x86:/suse/images/iso/openSUSE-Tumbleweed.x86_64.iso': 'boot'
      }
  ```

  maybe more information needs to be placed in the map

* For scheduling the tests I used the openqa-cli tool. We need to decided if we want to use the python client for writing
   a simple job scheduler or if we do this just via shell and the commands. For the scheduler we need to agree on an algorithm.
   Shall this be just periodically run or should we trigger by events. All still to be discussed

**Comment by schaefi** [comment]
What needs to be done first is to rename the integration test images such that their names are unique and meaningful. This is required because scheduling a job requires to provide a reference to the built integration test image. openQA copies this image into its own cache and therefore its urgently needed to choose a name that does not match with any other image openQA has in its cache. I suggest to start any name with:

* kiwi-test-...

**Comment by schaefi** [comment]
As part of the current sprint I will work on:

[ ] - the rename of integration test images
[ ] - create a kiwi group in openQA for the tests

**Comment by schaefi** [comment]
We have a good understanding of what and how we want to achieve this. All followup action will be done in an extra
repository:

    https://github.com/OSInside/kiwi-functional-tests/issues

Thanks for the kick off from here
