### ISSUE TITLE
Overlayfs write folder is placed in path with limited resources

### ISSUE THREAD

**Issue by davidcassany** [OSInside/kiwi#1558]
## Problem description

Apparently the `/run/overlayfs` is not a good folder for storing the overlayfs in Live systems as systemd limits the capacity of `/run` folder to 20% of the overall RAM. 

This issue tracks [boo#1176709](https://bugzilla.opensuse.org/show_bug.cgi?id=1176709):

> 
> openQA test in scenario opensuse-Tumbleweed-GNOME-Live-x86_64-gnome-live@64bit fails in
> [zypper_in](https://openqa.opensuse.org/tests/1398257/modules/zypper_in/steps/12)
> 
> Kiwi stores the overlayfs in /run/overlayfs - which, taking systemd 246 into account, is not a good place.
> 
> systemd 246 limits /run to 20% of the RAM, under the premise that 'run' is not supposed to host large files, but should only reference small runtime-related files. /tmp is limited to 50% of RAM (as it used to be)
> 

## Expected behaviour

Overlyfs is storage is not that scrictly constrained on memory, 20% seams to be clearly limited for live images such desktop environments.

## Steps to reproduce the behaviour

Can be seen on resource hungry Live images such as Tumbleweed GNOME or such with 2GB of RAM.

**Comment by DimStar77** [comment]
NOTE: 'no limit' is probably not a good solution, as overlayfs by default is in RAM, so RAM size is a limiting factor which we should not exhaust.

Earlier versions of systemd did not impose this limit on /run, which resulted in ~ 50% of RAM being available (so on our 2GB openQA workers, 1GB). The 'easy way out' would be to use /tmp, which is now explicitly limited to 50% of RAM by systemd (same as before, just made explicitly). or kiwi could mount an own tmpfs with a limit defined on its own.

**Comment by davidcassany** [comment]
> NOTE: 'no limit' is probably not a good solution, as overlayfs by default is in RAM, so RAM size is a limiting factor which we should not exhaust.

Well yes, you got a point here, probably better limiting it than just miserably running completely out of RAM and let it crash in an unexpected ways.
