### ISSUE TITLE
Arch Linux EFI boots fail

### ISSUE THREAD

**Issue by davidcassany** [OSInside/kiwi#1559]
## Problem description

On Arch Linux images EFI boot is not working as expected. In short the grub.cfg patch that decides weather to use `linuxefi` or `linux` command is applied despite the `linuxefi` module was not found and in consequece not included in the `grub2-mkimage` command.

For completion I believe there are two tighty related but different issues here:

1 Check if there are prebuilt efi images for Arch, if so check if the path can be nicely included in the efi image lookup path in KIWI.

2 Make sure the patch that includes `linuxefi` usage is not applied when the command `linuxefi` is not available.

For the second this looks more like a generic issue rather than Arch specific.

Probably this is a side effect of 988404ff9f, the criteria on the grub version was probably not suited. I'd say that if we can validate that there is the actual `linuxefi` command somehow this should be the preferred criteria to apply the patch or not.

For for the notes but probably some decision criteri like in https://github.com/OSInside/kiwi/blob/c2f7d7fade8e1ecb97527c3bf7930a2e61432839/kiwi/bootloader/config/grub2.py#L817-L818 could prevent applying the patch when no linuxefi available, needs further verification.

## Expected behaviour

Arch Linux EFI images boot on EFI environments.

## Steps to reproduce the behaviour

Make use of the VMX build of the integration tests for Arch Linux. At boot time it fails trying to run `linuxefi`, which is not there for Arch. Editing to boot entry at boot time to switch `$linux` to the actual command `linux` solves the issue.

**Comment by Vogtinator** [comment]
Note that `linuxefi` is no longer necessary on openSUSE/SLE grub 2.04 packages, so just reintroducing the version check would probably work as well.

**Comment by schaefi** [comment]
@davidcassany thanks for the fix. I updated the service file on obs to also fetch the editbootinstall_arch.sh script.

**Comment by Vogtinator** [comment]
What about this?

> Note that linuxefi is no longer necessary on openSUSE/SLE grub 2.04 packages, so just reintroducing the version check would probably work as well.

**Comment by davidcassany** [comment]
@Vogtinator yes this is correct, however the 2.04 check was removed as part of the fix for bsc#1175729 and bsc#1176134 in 988404ff9f04384c3efb53644e69d520c022c03c. I don't remember the whole discussion there was back then, but IIRC the conclusion was that even beyond grub2  >= 2.04 using linuxefi was the preferred choice for SUSE.

As we see it now, trying to keep the linuxefi vs linux for a cross distro code is a real pain.  Since we now have no complaints from most of the distros we support and given we have no complaints nor demands on Arch we agree we can leave that as a non supported feature for the time being, knowing where the issue is and how to hotfix it.

**Comment by Vogtinator** [comment]
> @Vogtinator yes this is correct, however the 2.04 check was removed as part of the fix for bsc#1175729 and bsc#1176134 in 988404f. I don't remember the whole discussion there was back then, but IIRC the conclusion was that even beyond grub2 >= 2.04 using linuxefi was the preferred choice for SUSE.

AFAIU, the conclusion of bsc#1176134 is that `linuxefi` is actually obsolete already as of grub 2.04 in Leap, as the `linux` command does the same if necessary. I'm not sure what the current state of that is though.
