### ISSUE TITLE
dcounter option -l does not work

### ISSUE THREAD

**Issue by nadvornik** [OSInside/kiwi#1579]
## Problem description

The recent change in dcounter breaks option handling:

https://github.com/OSInside/kiwi/blame/master/tools/dcounter.c#L25

```strncpy (prefix, *(argv+1), strlen(prefix));```

prefix is set to zeros, so strlen(prefix) is also zero, so nothing is copied.

**Comment by schaefi** [comment]
Hi, you are soo right and I'm soo stupid. Sorry that should not have happened. Would you be so kind to double check on the fix in #1584. Thanks much
