### ISSUE TITLE
problem creating oem image on Ubuntu 20.04

### ISSUE THREAD

**Issue by mitja-suncic** [OSInside/kiwi#1582]
## Problem description
I keep getting the "KiwiTypeNotFound: build type oem not found in [<kiwi.xml_parse.description object at 0x7fc8029ced90>]" error when attempting to create an Ubuntu oem image on Ubuntu 20.04.1 LTS (Focal Fossa) OS. 
The following commands return an error:
a) oem media type explicitly specified in the command line.
root@<hostname>:~ # kiwi-ng --type=oem system build --description=<path_to_kiwi-descriptions_repo>/kiwi-descriptions/ubuntu/x86_64/ubuntu-focal/ --target-dir=/tmp/my_img
[ INFO    ]: 15:11:07 | Loading XML description
[ INFO    ]: 15:11:07 | Support for XML markup available
[ ERROR   ]: 15:11:07 | KiwiTypeNotFound: **build type oem not found in** [<kiwi.xml_parse.description object at 0x7fc8029ced90>]
The same happens with the following command invocation:
root@<hostname>:~# kiwi-ng --type oem system build --description=<path_to_kiwi-descriptions_repo>/kiwi-descriptions/ubuntu/x86_64/ubuntu-focal/ --target-dir=/tmp/my_img

b) oem media type not specified in the command line.
root@<hostname>:~# kiwi-ng system build --description=/home/mitjasuncic/repos/kiwi-descriptions/ubuntu/x86_64/ubuntu-focal/ --target-dir=/tmp/my_img
[ INFO    ]: 15:31:57 | Loading XML description
[ INFO    ]: 15:31:57 | Support for XML markup available
[ ERROR   ]: 15:31:57 | KiwiTypeNotFound: **No build type defined in** [<kiwi.xml_parse.description object at 0x7efeec736430>]

The config XML file contains the oem definition in both cases above and looks like the following:
```
<preferences profiles="Disk">
        <type image="oem" filesystem="ext4" initrd_system="dracut" firmware="efi" installiso="true">
            <oemconfig>
                <oem-swap>true</oem-swap>
                <oem-device-filter>/dev/ram</oem-device-filter>
                <oem-multipath-scan>false</oem-multipath-scan>
            </oemconfig>
        </type>
    </preferences>
```
The ISO definition has been commented out from the config file.
I can **successfully create iso images**.

## Expected behaviour
Should be able to create an oem image with the following command (as documented in the Kiwi NG documentation):
kiwi-ng --type=oem system build --description=/home/mitjasuncic/repos/kiwi-descriptions/ubuntu/x86_64/ubuntu-focal/ --target-dir=/tmp/my_img

## Steps to reproduce the behaviour
1. Install kiwi with pip3 on Ubuntu 20.04.1 LTS (Focal Fossa) operating system as root user:
root@<hostname>:~# pip3 install kiwi
2. Download the example XML image configurations from Github:
https://github.com/OSInside/kiwi-descriptions
3. Create an Ubuntu ISO image by explicitly specifying the image type:
kiwi-ng --type=iso system build --description=/home/mitjasuncic/repos/kiwi-descriptions/ubuntu/x86_64/ubuntu-focal/ --target-dir=/tmp/my_img
After the image has been successfully created, remove the /tmp/my_img directory
4. Create an Ubuntu ISO image without explicitly specifying the image type:
root@<hostname>:~# kiwi-ng system build --description=/home/mitjasuncic/repos/kiwi-descriptions/ubuntu/x86_64/ubuntu-focal/ --target-dir=/tmp/my_img
After the image has been successfully created, remove the /tmp/my_img directory.
5. Comment out the ISO media configuration in the /home/mitjasuncic/repos/kiwi-descriptions/ubuntu/x86_64/ubuntu-focal/config.xml file.
6. Attempt to create an oem type media:
root@<hostname>:~# kiwi-ng --type=oem system build --description=<path_to_kiwi-descriptions_repo>/kiwi-descriptions/ubuntu/x86_64/ubuntu-focal/ --target-dir=/tmp/my_img
The command should fail with the following erroe:
[ ERROR   ]: 15:11:07 | KiwiTypeNotFound: **build type oem not found in** [<kiwi.xml_parse.description object at 0x7fc8029ced90>]

## OS and Software information
+ KIWI version: KIWI (next generation) version 9.21.17
+ Operating system: Ubuntu 20.04.1 LTS (Focal Fossa)
+ Python version: Python 3.8.5 (default, Jul 28 2020, 12:59:40)
+ OBS version: -

**Comment by schaefi** [comment]
I see your image definition is embedded into a profile named "Disk" but at call time of kiwi-ng I don't see that this profile got selected. Without having the profile selected the description (as far as I can see it) does not provide an oem image type and that's where the error message comes from.

I assume the following call should work better for you:

```
kiwi-ng --type=oem --profile Disk system build --description ... --target-dir ...
```

Does this make a difference ?

If yes and you want this profile to be imported if no --profile option was set you can also specify that in the
XML description in the <profiles> section via the import attribute. There should be something like this

```xml
<profiles>
        <profile name="Disk" description="..." import="true"/>
</profiles>
```

If the import is set to true for the Disk profile you don't have to provide it on the commandline

Let me know if that helps

Thanks

**Comment by mitja-suncic** [comment]
Hello @schaefi ,

Thank your for the quick response and your help!
You are correct, I was invoking the CLI tool without the required --profile flag. 
Using the command that you've provided has solved the issue and I have now successfully built an OEM image on my Ubuntu machine.
This issue can now be closed. 
Thanks again!

Kind regards,
Mitja
