### ISSUE TITLE
kiwi-dump-image.sh get_disk_list output is not parsed correctly in get_selected_disk

### ISSUE THREAD

**Issue by dstiles314** [OSInside/kiwi#1588]
## Problem description
get_selected_disk() is used to display to the user all available disks but does only shows the first and fourth disks, skipping the second and third installed disks.

I believe this bug was introduced with commit 4780f444e535b129820d38977f44ea1f20ac4d71.  The list_item return value was changed from "disk size status" TO "disk size"
```
-     list_items="${list_items} ${disk_device} ${disk_size} ${item_status}"
-     item_status=off
+     list_items="${list_items} ${disk_device} ${disk_size}"
```

Testing has shown that changing $((count %3)) to $((count % 2)) in the below subroutine does resolve this issue.
```
        for entry in ${disk_list};do
            if [ $((count % 3)) -eq 0 ];then
                device_array[${device_index}]=${entry}
                device_index=$((device_index + 1))
            fi
            count=$((count + 1))
        done
```

list_items is a space separated list of the disks and size of the disk. e.g. "/dev/sda 500G /dev/sdb 250G /dev/sdc 750G /dev/sdd 50G"
Currently this routine is setting device_index= "/dev/sda 250G /dev/sdd"
The correct result should be device_index= "/dev/sda /dev/sbd /dev/sdc /dev/sdd"

## Expected behaviour
get_selected_disk() should correctly parse all disks in disk_list=$(get_disk_list)

## Steps to reproduce the behaviour
This will happen on every system with two or more disks installed.

## OS and Software information
+ KIWI version: 9.20.5
+ Operating system: leap15.2
+ OBS version:

**Comment by schaefi** [comment]
Uhm, thanks much for catching this one. That sounds like a bad bug

**Comment by schaefi** [comment]
going to send a PR with your suggested solution, makes perfect sense to me. Thanks
