### ISSUE TITLE
debian: wrong "distribution" used for bootstrap stage

### ISSUE THREAD

**Issue by Josua-SR** [OSInside/kiwi#1593]
## Problem description

When building a Debian system with kiwi from multiple repositories that especially refer to multiple values of the "distribution" field in repository urls, kiwi will call debootstrap with the repository value of the last specified repsoitory, rather than a (configurable?) base.

```
[ ERROR   ]: 15:41:03 | KiwiDebootstrapError: debootstrap script for buster/updates distribution not found
[ INFO    ]: 15:41:03 | Cleaning up SystemPrepare instance
```

## Expected behaviour

debootstrap will be called for the base distribution, e.g. "buster".
Personally I'd like a way for declaring this value, e.g. by
```
<packages type="bootstrap" distribution="buster">
...
</packages>
```

or perhaps mark the repository for bootstrapping
```
<repository type="apt-deb" distribution="buster-updates" components="main non-free" repository_gpgcheck="true" bootstrap="true">
        <source path="http://deb.debian.org/debian"/>
</repository>
```

## Steps to reproduce the behaviour

Sample config.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<image name="sr-imx6">
        <description type="system">
                <author>Josua Mayer</author>
                <contact>support@solid-run.com</contact>
                <specification>text</specification>
        </description>
        <preferences>
                <version>0.1</version>
                <packagemanager>apt-get</packagemanager>
                <type image="ext4"/>
                <keytable>us-intl</keytable>
                <timezone>CET</timezone>
                <locale>en_GB</locale>
                <rpm-check-signatures>true</rpm-check-signatures>
        </preferences>
        <users>
                <user name="root" groups="root" pwdformat="plain" password="linux" home="/root"/>
                <user name="debian" groups="debian" pwdformat="plain" password="debian" home="/home/debian"/>
        </users>
        <repository type="apt-deb" distribution="buster" components="main non-free" repository_gpgcheck="true">
                <source path="http://deb.debian.org/debian"/>
        </repository>
        <repository type="apt-deb" distribution="buster-updates" components="main non-free" repository_gpgcheck="true">
                <source path="http://deb.debian.org/debian"/>
        </repository>
        <repository type="apt-deb" distribution="buster/updates" components="main non-free" repository_gpgcheck="true">
                <source path="http://security.debian.org/"/>
        </repository>
        <packages type="bootstrap">
                <!-- additional, packages for debootstrap -->
                <package name="apt-transport-https"/>
                <package name="busybox"/>
                <package name="ca-certificates"/>
                <package name="curl"/>
                <package name="locales"/>
                <package name="initramfs-tools"/>
                <package name="systemd-sysv"/>
        </packages>
        <packages type="image">
                <!-- system packages: debian -->
                <package name="alsa-utils"/>
                <package name="command-not-found"/>
                <package name="connman"/>
                <package name="i2c-tools"/>
                <package name="iw"/>
                <package name="linux-image-armmp"/>
                <package name="mtd-utils"/>
                <package name="nano"/>
                <package name="ntfs-3g"/>
                <package name="openssh-server"/>
                <package name="pciutils"/>
                <package name="psmisc"/>
                <package name="rfkill"/>
                <package name="usbutils"/>
                <package name="wget"/>
        </packages>
</image>
```

## OS and Software information
+ KIWI version: KIWI (next generation) version 9.21.17
+ Operating system: openSUSE Leap 15.2
+ OBS version: -

**Comment by schaefi** [comment]
In the current implementation the last repository that includes the distribution attribute is used for the debootstrap tool.
In your case you this would need to re-order the repo list to achieve what you want

I agree this is not intuitive. We will have a conversation how to make this more explicit and clear for users

**Comment by schaefi** [comment]
@davidcassany my suggestion to solve this issue would be to make the repo used for bootstrapping an explicit setup in the config file.

* Add a new attribute to the XML schema only allowed for type="apt-deb"

   ```
   <repository type="apt-deb" ... used_for_debootstrap="true|false"/>
   ```

* Add a runtime check to make sure used_for_debootstrap is used only once because debootstrap can only use one repo afaik ?
  Checking this can hardly be done on the schema level, thus I suggest to create a runtime check in kiwi for it

* Change the kiwi code that calls debootstrap to take the configured repo or the last one in the list as before to avoid a behavior change

Thoughts

**Comment by davidcassany** [comment]
> @davidcassany my suggestion to solve this issue would be to make the repo used for bootstrapping an explicit setup in the config file.
> 
>     * Add a new attribute to the XML schema only allowed for type="apt-deb" (schematron rule)
>       ```
>       <repository type="apt-deb" ... use_for_debootstrap="true|false"/>
>       ```
> 
>     * Add a runtime check to make sure `use_for_debootstrap` is used only once because debootstrap can only use one repo afaik ?  Checking this can hardly be done on the schema level, thus I suggest to create a runtime check in kiwi for it
> 
>     * Change the kiwi code that calls debootstrap to take the configured repo or the last one in the list as before to avoid a behavior change
> 
> 
> Thoughts

Good this all makes sense to me. I like it.

**Comment by Josua-SR** [comment]
@davidcassany Thanks for solving this, I finally got around to trying, and like the solution :)
