### ISSUE TITLE
[question] update image

### ISSUE THREAD

**Issue by peter-kl** [OSInside/kiwi#1594]
Hello

This is a question I have.

Just build an image but find out I missed  a package that is creating some bugs. How to update the image adding just that package. Command:
```
kiwi-ng system update --root=/path/to/built/root
[--add-package=<name>...]
```
Is this it or I need to run the normal command again:
```
sudo kiwi-ng --type iso system build \
     --description /home/<user>/xxx-vy \
     --target-dir /home/<user>/tmp/Image
```
+ Operating system: opensuse leap 15.2

**Comment by peter-kl** [comment]
Create an image from a previously prepared image root directory:
`kiwi-ng system create --root=<directory>  --target-dir=<directory>   [--signing-key=<key-file>...]`

**Comment by schaefi** [comment]
> How to update the image adding just that package

In addition to what Peter said

```
kiwi-ng system update --root /path/to/built/root --add-package joe
kiwi-ng system create --root /path/to/built/root --target-dir /tmp/mytarget
```

The first command you pointed out was the right one to add/delete packages from an existing image root tree. The same set of repos as you used it in the image description when you build that image the first time is used. If the package in question lives somewhere else you need to update the repo list manually in: /path/to/built/root/image/config.xml before you call the "system update" command

As a side note:
In any case it's advisable that you make this action permanent in your image description. The update command modifies the root tree and if you just re-create the image from your image description it will not lead to the same result until you make the modifications a part of the image description.

Hope this helps
