### ISSUE TITLE
bash-completion does not recognize files with suffix

### ISSUE THREAD

**Issue by olafhering** [OSInside/kiwi#1603]
`/usr/share/bash-completion/bash_completion` does not recognize completion addons if they end end with a suffix, like `kiwi-ng.sh`.

````bash
    for dir in "${dirs[@]}"; do
        [[ -d $dir ]] || continue
        for compfile in "$cmd" "$cmd.bash" "_$cmd"; do
````
I think `kiwi-ng.sh` must be installed as `kiwi`.

**Comment by schaefi** [comment]
Hi, are you referring to

%{_usr}/share/bash-completion/completions/kiwi-ng.sh

There should be at the end of the file something like

```
complete -F _kiwi -o default kiwi
complete -F _kiwi -o default kiwi-ng
```

and that imho completes for both.

On a short test it still completes on my system but I have to double check

**Comment by schaefi** [comment]
I can confirm you are right, it does not complete with kiwi-ng.sh, but it does with kiwi-ng :)

will fix it. Thanks
