### ISSUE TITLE
Invalid regexp in _fix_grub_root_device_reference

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi#1607]
## Problem description

There is a critical problem with the regular expression applied in _fix_grub_root_device_reference.
The code from here:

```python
grub_config = re.sub(
    r'(root=.*?=[a-zA-Z0-9:\.-]+)|(root={0})'.format(
        boot_options.get('root_device')
    ),
    '{0}'.format(self.root_reference),
    grub_config
)
```

is expected to match the conditions

1. root=LOCAL-KIWI-MAPPED-DEVICE
2. root=.*(lazy)=ANY-LINUX-BY-ID-VALUE

It does that but some other information gets lost. See the following input source

```
        linux   /boot/vmlinuz-5.3.18-lp152.47-default root=/dev/mapper/loop0p1  nomodeset console=ttyS0 console=tty0

                linux   /boot/vmlinuz-5.3.18-lp152.47-default root=UUID=88e4b42d-38e3-4188-8050-145c65547a97  nomodeset console=ttyS0 console=tty0
                linux   /boot/vmlinuz-5.3.18-lp152.47-default root=UUID=88e4b42d-38e3-4188-8050-145c65547a97
```

creates the following diff

```
--- foo2        2020-11-04 12:13:57.064291710 +0000
+++ foo 2020-11-04 12:10:45.351241359 +0000
@@ -1,4 +1,4 @@
-       linux   /boot/vmlinuz-5.3.18-lp152.47-default root=UUID=88e4b42d-38e3 console=tty0
+       linux   /boot/vmlinuz-5.3.18-lp152.47-default root=/dev/mapper/loop0p1  nomodeset console=ttyS0 console=tty0
 
-               linux   /boot/vmlinuz-5.3.18-lp152.47-default root=UUID=88e4b42d-38e3  nomodeset console=ttyS0 console=tty0
-               linux   /boot/vmlinuz-5.3.18-lp152.47-default root=UUID=88e4b42d-38e3  
+               linux   /boot/vmlinuz-5.3.18-lp152.47-default root=UUID=88e4b42d-38e3-4188-8050-145c65547a97  nomodeset console=ttyS0 console=tty0
+               linux   /boot/vmlinuz-5.3.18-lp152.47-default root=UUID=88e4b42d-38e3-4188-8050-145c65547a97 
```

For some reason parts of the matching lines are missing

**Comment by davidcassany** [comment]
I would restrict more the regex with something like `r'(root=[a-zA-Z0-9:\.-]*?=[a-zA-Z0-9:\.-]+)|(root={0})'.format(boot_options.get('root_device'))`

The problem is with `(root=.*?=[a-zA-Z0-9:\.-]+)`. The first part of `.*?` matches spaces thus it can eventually match strings like `root=UUID=88e4b42d-38e3 console=ttyS0`

**Comment by schaefi** [comment]
yes that .*? pattern is lazy but matches spaces so the shortest match can be longer than expected if more options with an equal sign are part of the line. I'm so stupid. Will come up with a patch next
