### ISSUE TITLE
Centos8 with xfs not producing bootable image.

### ISSUE THREAD

**Issue by mottsen** [OSInside/kiwi#1611]
## Problem description
CentOS 8 image built with xfs filesystem fails to boot.  Same settings for an ext4 system boots successfully.

The gets to grub, but grub fails to find vmlinuz.  If you drop to the grub command line and manually point to the vmlinuz and initrd file, you can get the system to fully boot.  Once I booted the system, I ran grub2-mkconfig, but was still unsuccessful in getting the image to boot.  There are two profiles in the xml, Virtual-ext4 and Virtual-xfs the only different being the filesystem type for the image.  The Virtual-ext4 boots successfully without issue, only the Virtual-xfs image is affected.

## Expected behaviour
Image boots successfully.

## Steps to reproduce the behaviour
Build using the attached config.xml.

Image was tested on a kvm host built on ubuntu 18.04.

## OS and Software information
+ KIWI version: python3-kiwi-9.20.5-lp152.4.1.x86_64 
+ Operating system: openSUSE Leap 15.2
+ OBS version: 
[config.zip](https://github.com/OSInside/kiwi/files/5490417/config.zip)

**Comment by mottsen** [comment]
A teammate suggested trying the same image, but as uefi boot.  I updated the image to include the grub2-efi-x64, grub2-efi-x64-modules, and grub2-pc packages.  The resulting image gave the same behaviour when booting efi and bios style boot on the same KVM host.  I did not test ext4 as uefi boot.

**Comment by schaefi** [comment]
Can you please try if building the image in the universal box (Fedora system) makes any difference ? This can be tested as follows:

```
$ pip install kiwi-boxed-plugin
$ kiwi-ng --profile Virtual-xfs system boxbuild --box universal -- --description \
          your-path-to-the-description --target-dir /tmp/mytest
```

I'm asking because if that works the issue points to the grub tooling and we have a better start position. We can do this builds tests with the attached information too, but it will take some time until we get to it.

Thanks

**Comment by mottsen** [comment]
I performed a box build using the universal image and got the same results where the vm fails to boot.  This time when I drop to the grub command line and manually point to vmlinuz and initrd I don't get a full successful system boot.

**Comment by schaefi** [comment]
Thanks for testing this. I'll try to reproduce

**Comment by schaefi** [comment]
I tested the build in the universal box and it worked for me under certain conditions:

```
CentOS Linux 8 (Core)
Kernel 4.18.0-193.28.1.el8_2.x86_64 on an x86_64

localhost login: root
Password: 
Last login: Thu Nov 12 22:16:02 on tty1
[root@localhost ~]# df /
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/sda4        2087916 1501696    586220  72% /
[root@localhost ~]# blkid /dev/sda4
/dev/sda4: LABEL="ROOT" UUID="0b488415-44ae-48c3-ba0a-106c6082af29" TYPE="xfs" PARTLABEL="p.lxroot" PARTUUID="157696f8-2e75-4a4d-ab46-883e348c2af5"
```

**Comment by schaefi** [comment]
The problem as I think is the following:

1. kiwi by default creates an extra boot partition when using XFS. That extra boot partition is missing the "boot -> ." link which 
    makes the generated grub config to fail because it still references files with the /boot prefix. For that I have prepared a 
    patch. You can circumvent this issue if you add the following attribute in your XML description

    ```xml
    <type ... bootpartition="false"/>
    ```

    Rebuild your image using the universal box and it should boot because /boot and / lives on the same partition.
    I assume this will also fix it when you build without boxbuild
