### ISSUE TITLE
OEM Image boot issue when using lvm on multipath device on physical hardware(works on VM)

### ISSUE THREAD

**Issue by ksanjeet** [OSInside/kiwi#1618]
## Problem description
On an HPE synergy 480 gen10 server I am trying to deploy the image. This server has 2local disks and 3 multipathed LUNs from SAN. The OS needs to be deployed on one of the SAN LUN. I am filtering out the local disk using rd.kiwi.oem.maxdisk kernel parameter. 
When booting up it hangs with following logs visible on the console(I am also attaching the screenshot).
- dracut-pre-mount: WARNING -  Not using device /dev/sdX for PV <UUID>
- dracut-pre-mount: WARNING -  PV <UUID>  prefers device /dev/sdX because device seen first
- dracut-pre-mount: WARNING -  PV <UUID>  prefers device /dev/mapper/mpathX because device is in dm-subsystem
- dracut-pre-mount: WARNING -  PV <UUID>  prefers device /dev/mapper/mpathX because device is used by LV
- dracut-pre-mount: Insufficient free space: 2552 extent needed, but only 18 available
- dracut-pre-mount: Warning: Requested size cannot be reached!
- dracut-pre-mount: Removed: /etc/systemd/system/systemd-fsck-root.service
- Dependency failed for file system check on /dev/disk/by-uuid/<UUID>
- Dependency failed for /sysroot
- Dependency failed for Initrd root file system
![img1](https://user-images.githubusercontent.com/4103920/98920963-c1fbee00-24f6-11eb-998c-ee72b032ab7f.png)

## Expected behaviour
It should boot into the installed system

## OS and Software information
+ KIWI version: python3-kiwi-9.21.7-3.24.2-x86_64
+ Operating system: SLES 15SP2
+ OBS version:

**Comment by schaefi** [comment]
I think this should have been fixed with #1641. Could you upgrade to python3-kiwi v9.22.1 and let us know how things are going ?

Thanks much

**Comment by ksanjeet** [comment]
The issue didn't appear after I used synergy drivers specifically the driver for qlogic HBA. 

Closing this issue.
