### ISSUE TITLE
Build fails for RHEL7 OEM image using "bios" firmware......works with "uefi"

### ISSUE THREAD

**Issue by ksanjeet** [OSInside/kiwi#1637]
## Problem description

I am using centos7 kiwi tools for creating rhel7 oem images. If I use "uefi" as the firmware type then the build succeeds. If I use "bios" then although I see a "raw" image getting created but the ISO file is not created. I have not tested the raw image. 
The only visible error in the output is:

```
KiwiCommandError: chroot: stderr: Installing for i386-pc platform
grub2-install: error: cannot rename the file /boot/grub2/grubenv.new to /boot/grub2/grubenv: No such file or directory
,stdout: (no output on stdout)
```

## Expected behaviour

ISO image should be built

## Steps to reproduce the behaviour

In the config.xml use "bios" as the firmware for OEM type of image

## OS and Software information

+ KIWI version: python3-kiwi-9.21.26-1.1.x86_64
+ Operating system: SLES 15Sp2
+ OBS version:

**Comment by ksanjeet** [comment]
It seems the issue maybe related to https://github.com/OSInside/kiwi/issues/1611 . When I put "bootpartition=false" in <type ../> ..the issue resolves for me. I amusing xfs partitions aswell.

**Comment by schaefi** [comment]
Hmm, our centos7 integration test with uefi enabled completes successfully. See here:

* https://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/Testing_x86:/centos/images_CentOS7/

Could you double check the image description from here:

* https://github.com/OSInside/kiwi/blob/master/build-tests/x86/centos/test-image-live-disk-v7/appliance.kiwi

if you are installing all uefi required packages:

```
<package name="grub2-efi-x64-modules" arch="x86_64"/>
<package name="grub2-efi-x64" arch="x86_64"/>
<package name="shim-x64" arch="x86_64"/>
```

Thanks

**Comment by schaefi** [comment]
I know centos7 is not rhel7 but we should make sure the basics from a packaging perspective are set correctly. Thanks

**Comment by schaefi** [comment]
> It seems the issue maybe related to #1611 . When I put "bootpartition=false" in <type ../> ..the issue resolves for me. I amusing xfs partitions aswell.

The issue there however was seen at boot time and not at build time. But a good point to check and make sure if the bootpartition setting has an impact. I hope not :)

**Comment by schaefi** [comment]
Any news on this one ?

**Comment by ksanjeet** [comment]
I convinced my customer to use "uefi" instead. I am not testing with "bios" now.

We can close this issue. Thanks for the help.
