### ISSUE TITLE
Allow custom swap volume name setup

### ISSUE THREAD

**Issue by ksanjeet** [OSInside/kiwi#1638]
## Problem description
Currently swap volume name is fixed. User wants to standardize the swap volume name but it doesn't seem to be configurable.

## Expected behaviour
One should be able to define the swap volume name.
Allow custom root volume name setup

## OS and Software information
+ KIWI version: python3-kiwi-9.21.26
+ Operating system: SLES15SP2
+ OBS version:

**Comment by schaefi** [comment]
working on this now
