### ISSUE TITLE
/var/run is not linked to ../run

### ISSUE THREAD

**Issue by snowliuping** [OSInside/kiwi#1643]
## Problem description
When I used kiwi to create a centos docker image, I found that /var/run in the docker image was linked to /run instead of ../run.
/var/run soft link file that linked /run is created in the _create_base_links function of the kiwi/system/root_init.py file，/var/run linking to /run is not what I want，because after filesystem rpm package is installed, a /var/run soft link will be created that linked to ../run

## Expected behaviour
lrwxrwxrwx.  1 root root     6 Apr 10  2020 run -> ../run

## Steps to reproduce the behaviour
config.xml is listed as below:
<?xml version="1.0" encoding="utf-8"?>

<image schemaversion="6.2" name="IMAGE_NAME">
    <description type="system">
        <author>liu</author>
        <contact>liu</contact>
        <specification>liu docker image</specification>
    </description>
    <preferences>
        <type image="docker" container="os131">
            <machine>
                <vmdisk/>
                <vmnic interface="eth0" mode="veth"/>
            </machine>
        </type>
        <version>1.0.0</version>
        <packagemanager>yum</packagemanager>
        <rpm-check-signatures>false</rpm-check-signatures>
        <rpm-force>true</rpm-force>
        <locale>en_US</locale>
        <keytable>us.map.gz</keytable>
        <hwclock>utc</hwclock>
    </preferences>

    <repository type="rpm-md" alias="OS">
            <source path="dir:///opt/repos"/>
    </repository>

    <packages type="image" patternType="plusRecommended">
        <package name="basesystem"/>
        <package name="bash"/>
        <package name="yum"/>
        <package name="net-tools"/>        
        <package name="coreutils"/>
        <package name="euleros-release"/>
        <package name="rootfiles"/>
        <package name="security-tool"/>
        <package name="systemd"/>
    </packages>
    <packages type="bootstrap" patternType="plusRecommended">
         <package name="filesystem"/>
         <package name="openssl-libs"/>
         <package name="iptables-libs"/>
    </packages>
</image>

## OS and Software information
+ KIWI version: 9.19.15
+ Operating system: 
+ OBS version:

**Comment by schaefi** [comment]
Hmm, I can't remember why we have the run link in the base links

```python
base_system_links = (
            ('/proc/self/fd', '%s/dev/fd'),
            ('fd/2', '%s/dev/stderr'),
            ('fd/0', '%s/dev/stdin'),
            ('fd/1', '%s/dev/stdout'),
            ('/run', '%s/var/run')
        )
```

@davidcassany @Conan-Kudo do you remember ?

**Comment by Conan-Kudo** [comment]
I don't remember. We probably _shouldn't_ have that.

**Comment by schaefi** [comment]
will work on this one
