### ISSUE TITLE
Public API Strong Typing

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi#1644]
## Problem description

For using kiwi as API at least the public interface should be strong typed such that users of the API know how to call the methods and that python can verify and insist on the call to be correct. In kiwi we haven't covered much code of the public API
to be annotated with type hints. The following list creates groups of KIWI code which we will start to update to become strong typed in the order of their entries:

- [x]  Config reading/writing, xml,markup, logging
- [x] Preparation of new root, system/prepare/setup/profile,root_bind
- [x] Storage processing, loop/disk/partitions/filesystems/volumes
- [x] Package handling, package_manager/repositories
- [x] Disk builder
- [x] Filesystem builder
- [x] KIS builder
- [x] Install media builder
- [x] Live builder
- [ ] Container builder, containers, archive, root_import
- [ ] Bootloader, grub,isolinux
- [ ] Utils

**Comment by schaefi** [comment]
Startung with 1. covers:

- [ ] logger

**Comment by schaefi** [comment]
working on the first shot

**Comment by schaefi** [comment]
First round done, card moved back to the backlog. We are revisiting this one in January

**Comment by isbm** [comment]
LOL :heart:

**Comment by schaefi** [comment]
Continue with

* Preparation of new root, system/prepare/setup/profile,root_bind

**Comment by schaefi** [comment]
- [ ] system/prepare.py
- [ ] system/profile.py
- [ ] system/setup.py
- [ ] system/root_bind.py
- [ ] system/root_init.py
- [ ] system/identifier.py
- [ ] system/kernel.py
- [ ] system/result.py
- [ ] system/shell.py
- [ ] system/size.py
- [ ] system/uri.py
- [ ] system/users.py

**Comment by schaefi** [comment]
I'll work on the first three now (prepare/profile/setup)

**Comment by jesusbv** [comment]
I will work on `users`, `uri` and `size`

**Comment by jesusbv** [comment]
I will work on `root_bind`, `root_init` and `identifier`

**Comment by jesusbv** [comment]
I will work on `kernel`, `result` and `shell`

**Comment by schaefi** [comment]
Thanks much @jesusbv, well done :+1: For this sprint we are good. Thus I moved the issue back to the backlog. We will agree and continue on the next step in the February sprint meeting.

**Comment by schaefi** [comment]
For the next sprint I think we should cover:

- [ ] storage/device_provider.py
- [ ] storage/disk.py
- [ ] storage/loop_device.py
- [ ] storage/luks_device.py
- [ ] storage/mapped_device.py
- [ ] storage/raid_device.py
- [ ] storage/setup.py
- [ ] storage/subformat/base.py
- [ ] storage/subformat/gce.py
- [ ] storage/subformat/ova.py
- [ ] storage/subformat/qcow2
- [ ] storage/subformat/vagrant_base.py
- [ ] storage/subformat/vagrant_libvirt.py
- [ ] storage/subformat/vagrant_virtualbox.py
- [ ] storage/subformat/vdi.py
- [ ] storage/subformat/vhd.py
- [ ] storage/subformat/vhdfixed.py
- [ ] storage/subformat/vhdx.py
- [ ] storage/subformat/vmdk.py
- [ ] filesystem/base.py
- [ ] filesystem/btrfs.py
- [ ] filesystem/clicfs.py
- [ ] filesystem/ext2.py
- [ ] filesystem/ext3.py
- [ ] filesystem/ext4.py
- [ ] filesystem/fat16.py
- [ ] filesystem/fat32.py
- [ ] filesystem/isofs.py
- [ ] filesystem/setup.py
- [ ] filesystem/squashfs.py
- [ ] filesystem/swap.py
- [ ] filesystem/xfs.py

**Comment by jesusbv** [comment]
will start with

storage/device_provider
storage/disk
storage/loop_device
storage/luks_device
storage/mapped_device

**Comment by jesusbv** [comment]
will continue with

storage/raid_device
storage/setup
storage/subformat/base
storage/subformat/gce
storage/subformat/ova
storage/subformat/qcow2

**Comment by davidcassany** [comment]
@jesusbv if you don't mind I am willing to take the ones under the filesystem folder. Basically the ones under

filesystem/*

There are many, but I think they are all pretty simple and straight forward

**Comment by schaefi** [comment]
I will take over:

￼ storage/subformat/vagrant_base.py
￼ storage/subformat/vagrant_libvirt.py
￼ storage/subformat/vagrant_virtualbox.py
￼ storage/subformat/vdi.py
￼ storage/subformat/vhd.py
￼ storage/subformat/vhdfixed.py
￼ storage/subformat/vhdx.py
￼ storage/subformat/vmdk.py
￼

**Comment by schaefi** [comment]
Done with what we wanted to get done in this sprint. Thanks to everybody.

Back to the backlog.

We are getting closer with this, soon all public methods will be covered by type information. Really nice

**Comment by schaefi** [comment]
Next steps

- [ ] package_manager/base.py
- [ ] package_manager/pacman.py
- [ ] package_manager/microdnf.py
- [ ] package_manager/apt.py
- [ ] package_manager/dnf.py
- [ ] package_manager/zypper.py
- [ ] repository/base.py
- [ ] repository/pacman.py
- [ ] repository/apt.py
- [ ] repository/dnf.py
- [ ] repository/template/apt.py
- [ ] repository/zypper.py
- [ ] builder/container.py
- [ ] builder/kis.py
- [ ] builder/filesystem.py
- [ ] builder/disk.py
- [ ] builder/live.py
- [ ] builder/install.py
- [ ] builder/archive.py

**Comment by schaefi** [comment]
@KeithMnemonic Thanks much you did all of this :+1:
