### ISSUE TITLE
creat debian10 arm64 demo fail

### ISSUE THREAD

**Issue by piqao** [OSInside/kiwi#1675]
## Problem description
Host debian9 arm64
Compile the source code successfully wiki version 9.23.3
'kiwi-ng --profile=Disk --debug --type oem system build     --description kiwi-descriptions/debian/arm64/debian-buster     --target-dir ./debian10'
Print as follows ...
[ DEBUG   ]: 16:24:27 | bootstrap: I: Extracting libuuid1...
[ DEBUG   ]: 16:24:27 | bootstrap: I: Extracting libzstd1...
[ DEBUG   ]: 16:24:28 | bootstrap: I: Extracting login...
[ DEBUG   ]: 16:24:28 | bootstrap: I: Extracting mawk...
[ DEBUG   ]: 16:24:28 | bootstrap: I: Extracting mount...
[ DEBUG   ]: 16:24:28 | bootstrap: I: Extracting ncurses-base...
[ DEBUG   ]: 16:24:28 | bootstrap: I: Extracting ncurses-bin...
[ DEBUG   ]: 16:24:28 | bootstrap: I: Extracting passwd...
[ DEBUG   ]: 16:24:28 | bootstrap: I: Extracting perl-base...
[ DEBUG   ]: 16:24:28 | bootstrap: I: Extracting sed...
[ DEBUG   ]: 16:24:28 | bootstrap: I: Extracting sysvinit-utils...
[ DEBUG   ]: 16:24:28 | bootstrap: I: Extracting tar...
[ DEBUG   ]: 16:24:28 | bootstrap: I: Extracting tzdata...
[ DEBUG   ]: 16:24:28 | bootstrap: I: Extracting util-linux...
[ DEBUG   ]: 16:24:28 | bootstrap: I: Extracting zlib1g...
[ INFO    ]: Processing: [########################################] 100%
[ DEBUG   ]: 16:24:28 | command get error code 1   //my add print debootstrap commd error code 
[ ERROR   ]: 16:24:28 | KiwiBootStrapPhaseFailed: Bootstrap package installation failed: 
[ INFO    ]: 16:24:28 | Cleaning up SystemPrepare instance
[ DEBUG   ]: 16:24:28 | EXEC: [mountpoint -q /root/debian10/build/image-root/var/cache/kiwi]
[ DEBUG   ]: 16:24:28 | EXEC: [mountpoint -q /root/debian10/build/image-root/var/cache/kiwi]
[ DEBUG   ]: 16:24:28 | EXEC: [umount -l /root/debian10/build/image-root/var/cache/kiwi]
[ DEBUG   ]: 16:24:28 | EXEC: [rmdir --ignore-fail-on-non-empty /root/debian10/build/image-root/var/cache/kiwi]
[ DEBUG   ]: 16:24:28 | EXEC: [rmdir --ignore-fail-on-non-empty /root/debian10/build/image-root/var/cache]
[ DEBUG   ]: 16:24:28 | EXEC: [rmdir --ignore-fail-on-non-empty /root/debian10/build/image-root/var]
[ DEBUG   ]: 16:24:28 | EXEC: [rm -f /root/debian10/build/image-root/etc/resolv.conf]
[ DEBUG   ]: 16:24:28 | EXEC: [rm -f /root/debian10/build/image-root/etc/hosts]

Compare debian10 x86 normal installation log 
The place of failure should be 'Installing core packages...'

I tried before
1. Run alone
debootstrap --no-check-gpg --variant=minbase --include=grub-theme-starfield,usrmerge --components=main,contrib,non-free buster /root/debian10/build/image-root http://ftp.cn.debian.org/debian 
--Base system installed successfully.

2. Install related packages
$ pip3 install --upgrade pip
$ pip3 install numpy --upgrade --ignore-installed
$ pip install scipy --upgrade --ignore-installed
$ pip install scikit-learn --upgrade --ignore-installed

3. Change file attributes
$ chown root:root ./debian10

None of the above works...

## Expected behaviour
'kiwi-ng --profile=Disk --debug --type oem system build     --description kiwi-descriptions/debian/arm64/debian-buster     --target-dir ./debian10' 
No error code 1 occurs when kiwi-ng  calling external commands  debootstrap ..

**Comment by schaefi** [comment]
> Host debian9 arm64

ok

> [ DEBUG ]: 16:24:28 | command get error code 1 //my add print debootstrap commd error code

Looks like the debootstrap call issued by kiwi failed. Unfortunately there is not much information why.
Maybe this is related to #1593

Have you tried to use ```<repository ... use_for_bootstrap="true" .../>``` in your image description. If this repo will be the same as you used in your manual call it should be the same call kiwi performs.

Thoughts ?

**Comment by piqao** [comment]
> > 主机debian9 arm64
> 
> 好
> 
> > [调试]：16:24:28 | 命令获取错误代码1 //我添加打印debootstrap commd错误代码
> 
> 看起来猕猴桃发出的debootstrap调用失败。不幸的是，为什么没有太多信息。
> 也许这与[＃1593有关](https://github.com/OSInside/kiwi/issues/1593)
> 
> 您是否尝试过`<repository ... use_for_bootstrap="true" .../>`在图像描述中使用。如果此回购与您手动调用中使用的回购相同，则它应与猕猴桃执行的调用相同。
> 
> 有什么想法吗？

View debootstrap.log

[root@linx debootstrap]#pwd
/root/debian10/build/image-root/debootstrap
[root@linx debootstrap]#cat debootstrap.log 
mkdir: cannot create directory ‘/root/debian10/build/image-root/dev/pts/’: File exists

So it looks like the file already exists
When debootstrap extracting the installation package

[root@linx dev]#pwd
/root/debian10/build/image-root/dev
[root@linx dev]#rm -rf *
[root@linx dev]#ls
[root@linx dev]#

Solve the problem
But i don't know why

**Comment by schaefi** [comment]
Thanks for debugging this. Yes kiwi mounts devtmpfs inside of the new root tree. Looks like this conflicts in this case. I wonder why this is not a generic issue. We are building integration tests on x86_64 using the ubuntu distro. I think on the level of debootstrap there should not be much difference... maybe a wrong assumption.

we will check this. Thanks

**Comment by schaefi** [comment]
@piqao Hi as you have seen we have a pending PR to solve the issue. However there is still some discussion needed and I have no arm hardware available for testing at the moment. Could you assist us and maybe test the patch from the open PR. That would be great, thanks much

**Comment by schaefi** [comment]
@piqao could you share your image description for debian arm64 ? I'd like to test if the open PR fixes the issue

Thanks
