### ISSUE TITLE
kiwi ng installation - missing dependency

### ISSUE THREAD

**Issue by t-ru** [OSInside/kiwi#1677]
## Problem description
mkfs.btrfs is missing

## Expected behaviour
kiwi ng installation should install btrfsprogs if not installed
kiwi ng installation should install xfsprogs if not installed

## Steps to reproduce the behaviour
1. Install openSUSE Leap 15.2. with any filesystem but not btrfs or xfs.
2. Create an image with brtfs filesystem
... error...  mkfs.btrfs ist missing
2. Create an image with xfs filesystem
... error...  mkfs.xfs ist missing

## OS and Software information
+ KIWI version: KIWI (next generation) version 9.22.1
+ Operating system: openSUSE Leap 15.2 
+ OBS version: ---

**Comment by schaefi** [comment]
See #1503 for details

Install:

```bash
$ sudo ${package_manager} in kiwi-systemdeps-filesystems
```

**Comment by t-ru** [comment]
`os-appliance-builder:~ # zypper install -y kiwi-systemdeps-filesystems`
`Loading repository data...`
`Reading installed packages...`
`No provider of 'kiwi-systemdeps-filesystems' found.`

There is no package kiwi-systemdeps-filesystem available at Tumbleweed

???

**Comment by schaefi** [comment]
yes, we haven't submitted it yet. This change needs to be done carefully. Currently we are testing it. The package that should go out to TW is in staging here:

    https://build.opensuse.org/project/show/Virtualization:Appliances:Staging

Just give us a bit of time until we do the submission to TW

Thanks
