### ISSUE TITLE
kiwi ng installation - Installation on Tumbleweed fails

### ISSUE THREAD

**Issue by t-ru** [OSInside/kiwi#1680]
## Problem description

rpm --import https://build.opensuse.org/projects/Virtualization:Appliances:Builder/public_key

fails on Tumbleweed with error "import read failed(2)"

## Solution for Tumbleweed

zypper install wget

zypper addrepo http://download.opensuse.org/repositories/Virtualization:/Appliances:/Builder/openSUSE_Tumbleweed appliance-builder

wget https://build.opensuse.org/projects/Virtualization:Appliances:Builder/public_key
rpm --import public_key
rm public_key

zypper install -y python3-kiwi

Please update the wiki.

## OS and Software information
+ KIWI version: latest
+ Operating system: openSUSE Tumbleweed
+ OBS version:

**Comment by schaefi** [comment]
Hmm, not sure why you think this is a kiwi problem ?

The project pub-key is created and provided by obs not kiwi
The rpm import just imports a key to the rpm keyring, if this does not work something is wrong with the key or the keyring
but how is this related to the kiwi image builder ?

Your solution also confuses me. Using zypper to add a repo adds the repokey on "zypper refresh", why is an extra rpm import of
some key needed

Sorry all this is confusing and I think not related to kiwi 

Can you please clarify ?

Thanks

**Comment by t-ru** [comment]
There is no problem with the key. The problem is that the installation was not tested on a minimal base system.
On a minimal Tumbleweed "rpm --import https..." is not working.

**Comment by schaefi** [comment]
and why ?

> error "import read failed(2)"

this doesn't tell me much and I still don't understand how it's related to kiwi. On that system you might have key import problems with other keys as well

Bear with me I still don't get it

**Comment by t-ru** [comment]
I use the official documentation from https://osinside.github.io/kiwi/installation.html for installation. The described procedure
is not working on a minimal Tumbleweed. This is the relation to kiwi.

The command "rpm --import https:... " triggers internally curl to download. But curl is not installed on a minimal Tumbleweed.
This is the reason for the error.

The correct installation steps are:

1. zypper install curl
2. zypper addrepo...
3. rpm --import https://...
4. zypper in python3-kiwi

I think it's useful to add the step "zypper install curl" to wiki

**Comment by schaefi** [comment]
Ah, ok. Thanks now I understand
