### ISSUE TITLE
kiwi ng installation - missing dependencies

### ISSUE THREAD

**Issue by t-ru** [OSInside/kiwi#1681]
## Problem description

missing dependencies at build time

https://github.com/OSInside/kiwi/issues/1677 was closed but the solution "sudo ${package_manager} install kiwi-systemdeps-filesystems" is wrong.

## Solution

1. show all kiwi packages: zypper search kiwi
2. install all buildservice host requirements: zypper install zypper install kiwi-*-requires

Please update the wiki.
 
## OS and Software information
+ KIWI version: 
+ Operating system: 
+ OBS version:

**Comment by schaefi** [comment]
> #1677 was closed but the solution "sudo ${package_manager} install kiwi-systemdeps-filesystems" is wrong.

Sorry but this is not an information we can work with. @Conan-Kudo implemented the systemd-deps solution and it works well on all our integration tests. If you see an issue please provide more details

> install all buildservice host requirements: zypper install zypper install kiwi-*-requires

As the name says, they are for buildservice hosts. The kiwi-requires packages are obs internal packages, never published and only used in combination with obs workers. All of those packages have a PublishFilter set such that they are not available to customers, intentionally. What you do here with installing them on your host is not actually not supported.

The new kiwi-systemdeps packages are part of the upstream project source and package definition and also taken by the other distribution vendors. The kiwi-requires barely worked for suse builds and failed for any other distro. The kiwi-requires are also pretty much unmaintained as they are used obs internal and basically nobody really cares or even knows about them :)

Please let us focus on the agreements done in the conversations in #1677 and let's fix issues there

Thanks

**Comment by schaefi** [comment]
JFI: kiwi-systemdeps packages not yet in TW, we are testing all of it right now

**Comment by schaefi** [comment]
The packages are available now. We plan to close this one together with the implementation of #1686

**Comment by schaefi** [comment]
If there are further concerns from your side it would be great if you can give us feedback here. Thanks much

**Comment by schaefi** [comment]
for reference

```
$ osc api 'build/openSUSE:Factory/_result?view=binarylist&repository=standard&arch=x86_64' | grep kiwi-systemdeps

      <binary filename="kiwi-systemdeps-9.23.12-1.1.x86_64.rpm" size="605861" mtime="1612469088"/>
      <binary filename="kiwi-systemdeps-bootloaders-9.23.12-1.1.x86_64.rpm" size="605781" mtime="1612469088"/>
      <binary filename="kiwi-systemdeps-containers-9.23.12-1.1.x86_64.rpm" size="605929" mtime="1612469088"/>
      <binary filename="kiwi-systemdeps-core-9.23.12-1.1.x86_64.rpm" size="605989" mtime="1612469088"/>
      <binary filename="kiwi-systemdeps-disk-images-9.23.12-1.1.x86_64.rpm" size="605957" mtime="1612469088"/>
      <binary filename="kiwi-systemdeps-filesystems-9.23.12-1.1.x86_64.rpm" size="606181" mtime="1612469088"/>
      <binary filename="kiwi-systemdeps-image-validation-9.23.12-1.1.x86_64.rpm" size="605845" mtime="1612469088"/>
      <binary filename="kiwi-systemdeps-iso-media-9.23.12-1.1.x86_64.rpm" size="605965" mtime="1612469088"/>
```

**Comment by schaefi** [comment]
So this is working for us, feel free to approach us if something does not work for you. Thanks
