### ISSUE TITLE
Use only required dracut modules for the installation initrd

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi#1683]
## Problem description

The installation initrd for kiwi is expected to only run with the ```dracut-kiwi-oem-dump``` provided code. The dracut call to create this initrd runs inside of the root system and would include other dracut modules that are present or for which a config is provided. This however can lead to bad side effects. There is for example the MicroOS image which installs additional dracut modules that does something in an initrd. We don't want them to be part of the kiwi initrd that should only call the dumping
code.

We already omit other kiwi modules to be installed in the kiwi initrd but we have no handle for other "unknown" dracut modules that are just imported but unwanted.

I don't know if a good solution can be found to this problem

**Comment by davidcassany** [comment]
Just for the records this is related to #1676 .

According to dracut man page this can be achieved by using `dracutmodules+=" <dracutmoduleslist> "`:

```
dracutmodules+=" <dracut modules> "
           Specify a space-separated list of dracut modules to call when
           building the initramfs. Modules are located in
           /usr/lib/dracut/modules.d. This option forces dracut to only
           include the specified dracut modules. In most cases the
           "add_dracutmodules" option is what you want to use.
```

or by the equivalent command line flag `--modules`:

```
-m, --modules [LIST]  Specify a space-separated list of dracut modules to
                         call when building the initramfs. Modules are located
                         in /usr/lib/dracut/modules.d.
```

I guess should investigate which the list we require and make us of this `--modules` flag in KIWI when creating the installation initrd and, as a plus, check if there is any chance for further customizing dracut when this is being used, for instance check if `--add` is still functional.
