### ISSUE TITLE
XFS build fails - grub2-i386-pc

### ISSUE THREAD

**Issue by t-ru** [OSInside/kiwi#1691]
## Problem description

I try to build SLES 15 SP 2 with root filesystem on xfs. Building with ext4 works fine. Building with xfs fails.

```
INFO: 08:25:20 | Installing grub2 on disk /dev/loop0
DEBUG: 08:25:20 | EXEC: [mountpoint -q /tmp/kiwi_mount_manager.r4j126ag]
DEBUG: 08:25:20 | EXEC: [mount /dev/mapper/loop0p3 /tmp/kiwi_mount_manager.r4j126ag]
DEBUG: 08:25:20 | EXEC: [mountpoint -q /tmp/kiwi_mount_manager.r4j126ag/boot/efi]
DEBUG: 08:25:20 | EXEC: [mount /dev/mapper/loop0p2 /tmp/kiwi_mount_manager.r4j126ag/boot/efi]
DEBUG: 08:25:20 | EXEC: [mountpoint -q /tmp/kiwi_mount_manager.r4j126ag/dev]
DEBUG: 08:25:20 | EXEC: [mount -n --bind /dev /tmp/kiwi_mount_manager.r4j126ag/dev]
DEBUG: 08:25:20 | EXEC: [mountpoint -q /tmp/kiwi_mount_manager.r4j126ag/proc]
DEBUG: 08:25:20 | EXEC: [mount -n --bind /proc /tmp/kiwi_mount_manager.r4j126ag/proc]
DEBUG: 08:25:20 | EXEC: [mountpoint -q /tmp/kiwi_mount_manager.r4j126ag/sys]
DEBUG: 08:25:20 | EXEC: [mount -n --bind /sys /tmp/kiwi_mount_manager.r4j126ag/sys]
DEBUG: 08:25:20 | EXEC: [chroot /tmp/kiwi_mount_manager.r4j126ag grub2-install --skip-fs-probe --directory /usr/lib/grub2/i386-pc --boot-directory /boot --target i386-pc --modules ext2 iso9660 linux echo configfile search_label search_fs_file search search_fs_uuid ls normal gzio png fat gettext font minicmd gfxterm gfxmenu all_video xfs btrfs lvm luks gcry_rijndael gcry_sha256 gcry_sha512 crypto cryptodisk test true loadenv multiboot part_gpt part_msdos biosdisk vga vbe chain boot /dev/loop0]
DEBUG: 08:25:21 | EXEC: Failed with stderr: Installing for i386-pc platform.
grub2-install: error: unknown filesystem.
, stdout: (no output on stdout)
ERROR: 08:25:21 | KiwiCommandError: chroot: stderr: Installing for i386-pc platform.
grub2-install: error: unknown filesystem.
, stdout: (no output on stdout)
INFO: 08:25:21 | Cleaning up BootLoaderInstallGrub2 instance
```

## Expected behaviour

Successfully building SLES 15 SP 2.

## Steps to reproduce the behaviour

1. Schema = 7.2 (older schemas also failing)

`<image schemaversion="7.2" name="test-xfs-sles-15">`

2. Type / Disk

```
<type 
            image="oem" 
            filesystem="xfs" 
            format="vmdk" 
            firmware="uefi" 
            bootpartition="false" 
            devicepersistency="by-uuid">
            <bootloader name="grub2" timeout="10" />
            <size unit="G">75</size>
            <oemconfig>
                <oem-resize>false</oem-resize>
            </oemconfig>      
</type>
```

3. Packages 
```
<packages type="image" patternType="plusRecommended">
	...
	<!-- XFS -->
        <package name="xfsprogs"/>
	...
</packages >
```

## OS and Software information
+ KIWI version: KIWI (next generation) version 9.23.5
+ Operating system: openSUSE Tumbleweed
+ OBS version: -

**Comment by schaefi** [comment]
```
DEBUG: 08:25:21 | EXEC: Failed with stderr: Installing for i386-pc platform.
grub2-install: error: unknown filesystem.
```

looks to me like something that needs to be fixed in grub ? There is code in grub that detects the filesystem and it doesn't seem to work on ix86. We are building for xfs on x86_64 very often and don't see issues.  Would you mind to take a look at the build log from here:

* https://build.opensuse.org/package/live_build_log/Virtualization:Appliances:Images:Testing_x86:suse/test-image-azure/images/x86_64

and check if you have all grub components for 32bit in your case available compared to the 64bit build that succeeds.

Thanks

**Comment by schaefi** [comment]
Your system needs to install:

```
grub2-i386-efi  (if EFI)
grub2-i386-pc
```

Can you confirm ?

**Comment by t-ru** [comment]
SLES 15 SP2 has xfsprogs 4.15
Tumbleweed has xfsprogs 5.9

Differences of XFS metadata created on SLES 15 SP 2 to Tumbleweed.
```
SLES 15 SP 2: sparse=0, reflink=0
Tumbleweed: sparse=1, reflink=1
```

reflink=1 is not a problem. sparse=1 is the reason for this error. Grub on SLES 15.x is not compatible with sparse=1 

see https://patchwork.kernel.org/project/xfs/patch/ce584ae1-ee62-2dcb-9366-eb0a6df6e98e@sandeen.net/

Solution:
`fscreateoptions="-i sparse=0"`

**Comment by schaefi** [comment]
Oh I see. Thanks a ton for the valuable feedback

**Comment by schaefi** [comment]
Q: For the sprint planning. Should we "somehow" check the incompatibilities between xfsprogs ?

**Comment by schaefi** [comment]
we are going to add a documentation hint for this sort of trouble. Other than pointing you to the kiwi boxbuild method which allows to control the environment there is little we can do. Thanks

**Comment by schaefi** [comment]
working on this one now

**Comment by t-ru** [comment]
New trouble section in documentation is a good idea. I think you can close it case
