### ISSUE TITLE
Prevent creating of EFI CSM(legacy bios) partition

### ISSUE THREAD

**Issue by t-ru** [OSInside/kiwi#1709]
## Problem description

By default kiwi creates a EFI CSM(legacy bios) partition. I found no param to prevent the creation. Is it possible to prevent the creation?

## OS and Software information
+ KIWI version: KIWI (next generation) version 9.23.5
+ Operating system: Tumbleweed
+ OBS version:

**Comment by schaefi** [comment]
you are right EFI images are all built in a way that they are CSM compatible. This is done on the x86 architecture only and should not cause any issue. Can you explain why this should be configurable and allowed to be switched off ?

Thanks

**Comment by schaefi** [comment]
Closing on no further feedback.
