### ISSUE TITLE
default fsck options in fstab are not optimal

### ISSUE THREAD

**Issue by seife** [OSInside/kiwi#1728]
## Problem description
fsck is not running at all for anything at boot

## Expected behaviour
fsck is running by default for all file systems in fstab

## Steps to reproduce the behaviour
   * Boot a kiwi image that has an additional filesystem than / (the rootfs is always checked by systemd-fsck-root.service).
   * Check the mount unit of the additional file system, e.g. with `systemctl cat tmp.mount`
   * note that there is no "Requires=systemd-fsck@..." lin in the tmp.mount file.
   * change the "0 0" options of /tmp in fstab to "0 1" and reboot
   * check tmp.mount again
   * note that there now is a "Requires=systemd-fsck@..." line.

This is important to make e.g. "fsck.repair=yes" work.

## OS and Software information
+ KIWI version: 9.23.5
+ Operating system: SLES15-SP2
+ OBS version: 2.10

My guess is, that the defaults in kiwi/builder/disk.py functions _add_simple_fstab_entry() and _add_generic_fstab_entry() should be changed from "0 0" to "0 2"
rootfs already has "11"

**Comment by t-ru** [comment]
kiwi creates:

- root 0 0
- swap 0 0
- other 0 0

best practices is:

- root 1 1
- swap  0 0
- other  1 2

I've integraded a /etc/fstab.script in my kiwi builds. this patches the /etc/fstab. 
This is a solution but this is not good.

Please fix it.

**Comment by t-ru** [comment]
Quick and dirty and customizable

[project-root-dir]/root/etc/fstab.script
```
#!/bin/bash

#==============================================================================
# Setup fsck options to /etc/fstab
#==============================================================================

_fstab="/etc/fstab"
_tmp1="/tmp/fstab.tmp1"
_tmp2="/tmp/fstab.tmp2"

# delete tmp files if exists
[ -f ${_tmp1} ] && rm ${_tmp1}
[ -f ${_tmp2} ] && rm ${_tmp2}

# create tmp files 
touch ${_tmp1}
touch ${_tmp2}

# copy fstab to tmp1
cat ${_fstab} > ${_tmp1}

# all = 1 2
awk '(NF==6){ print $1,$2,$3,$4,1,2; next } 1' ${_tmp1} > ${_tmp2}
cat ${_tmp2} > ${_tmp1}

# root = 1 1
awk '(NF==6)&&($2=="/"){ print $1,$2,$3,$4,1,1; next } 1' ${_tmp1} > ${_tmp2}
cat ${_tmp2} > ${_tmp1}

# set swap = 0 0
awk '(NF==6)&&($2=="swap"){ print $1,$2,$3,$4,0,0; next } 1' ${_tmp1} > ${_tmp2}
cat ${_tmp2} > ${_tmp1}

# /boot/efi = 0 0
awk '(NF==6)&&($2=="/boot/efi"){ print $1,$2,$3,$4,0,0; next } 1' ${_tmp1} > ${_tmp2}
cat ${_tmp2} > ${_tmp1}

# reformat
column -t  ${_tmp1} > ${_tmp2}
cat  ${_tmp2} > ${_tmp1}

# copy fstab to tmp1
cat ${_tmp1} > ${_fstab}

# delete tmp files if exists
[ -f ${_tmp1} ] && rm ${_tmp1}
[ -f ${_tmp2} ] && rm ${_tmp2}
```
fstab.script requires executable permissions. 2 options:

1. chmod 744 [project-root-dir]/root/etc/fstab.script OR
2. config.sh

config.sh
```
#==============================================================================
# Make misc scripts executable 
#==============================================================================
echo "---- Make misc scripts executable ----"
if [ -f /etc/fstab.script ] ; then
    chmod 744 /etc/fstab.script
    echo "/etc/fstab.script .....................: done"
else
    echo "/etc/fstab.script .....................: file not found"
fi
...
...
```

for details see https://osinside.github.io/kiwi/working_with_images/custom_fstab_extension.html

@schaefi : 
Please add it to https://osinside.github.io/kiwi/troubleshooting.html 
I think no patch is required. a custom script is customizable by user. a patch is static.

**Comment by seife** [comment]
> Kiwi creates all fstab entries with "0 0". Also root. Changing the default (overall) from "0 0" to "0 2" is a bad idea. 👎

Why?

> @schaefi :
> Please add it to https://osinside.github.io/kiwi/troubleshooting.html
> I think no patch is required. a custom script is customizable by user. a patch is static.

I disagree.
The defaults of a kiwi-built image should be as close to a manual installation as reasonably possible, (the "principle of least surprise").

Just to verify this, I installed  a default Leap 15.2, only changed rootfs from btrfs to ext4, and it has this fstab:

```
UUID=6ec9eca5-387e-44dd-a8d9-6968abd595e6  /     ext4  defaults  0  1
UUID=293fcbac-2bdc-4d05-9714-ef437137feee  swap  swap  defaults  0  0
```

A kiwi-installed system should be similar.

**Comment by t-ru** [comment]
You don't understanding "what is Kiwi". Kiwi is a framework to create images for various.

NOT ONLY LEAP! 

I'm creating kiwi images for many distributions:

- SLES
- RHEL
- OpenSUSE
- CentOS
- Debian

If you install Leap you get a other result as you install an other distribution.

If you install a distribution by DVD the result for fsck options depends on:

- installed distribution
- settings you made in the installer

There are many special cases for setting the fsck options. Changing the default from "0 0" is not so easy.

**Comment by seife** [comment]
> You don't understanding "what is Kiwi". Kiwi is a framework to create images for various distributions.

Are you trying to troll me?

> I'm creating kiwi images for many distributions:

Me too. And guess what? None of them has "0 0" as default for file systems that have a working fsck.

> If you install Leap you get an other result as you install an other distribution.
> 
> If you install a distribution by DVD the result for fsck options depends on:
> 
>     * installed distribution
> 
>     * settings you made in the installer
> 
> 
> There are many special cases for setting the fsck options. Changing the default from "0 0" is not so easy.

Which distribution has "0 0" as default?
And why would "0 0" be a better default than "0 1" (or "0 2" for everything non-root)?

> A Kiwi build result will never be the same as a DVD installer result

But it should be similar, at least by default. Again, the principle of least surprise.

> With fstab.script you've the freedom to set any as you need.

And even you can use it to set the (mostly useless, IMVHO) "0 0" parameters if you desire so.

> Take a look at my script. In the first step it sets new defaults. Then it sets the options for special cases.
> If you have other requirements you can modify it. I you've more special cases you can copy two lines and adapt it.

I have a simple fstab.script right now that only consists of one line:
```
sed -i -e 's/\(^.*ext4.*\)0[[:space:]]\+0$/\10 2/' /etc/fstab
```
But this should not be necessary.

**Comment by t-ru** [comment]
openSUSE Tumbleweed installed by DVD with btrfs
```
UUID=1219606d-cdc2-4c81-a382-607b07659b9a  /                       btrfs  defaults                         0  0
UUID=1219606d-cdc2-4c81-a382-607b07659b9a  /.snapshots             btrfs  subvol=/@/.snapshots             0  0
UUID=9a6e3ccd-4663-46d8-8ec6-aa7e3b709cdf  swap                    swap   defaults                         0  0
UUID=1219606d-cdc2-4c81-a382-607b07659b9a  /var                    btrfs  subvol=/@/var                    0  0
UUID=1219606d-cdc2-4c81-a382-607b07659b9a  /usr/local              btrfs  subvol=/@/usr/local              0  0
UUID=1219606d-cdc2-4c81-a382-607b07659b9a  /srv                    btrfs  subvol=/@/srv                    0  0
UUID=1219606d-cdc2-4c81-a382-607b07659b9a  /root                   btrfs  subvol=/@/root                   0  0
UUID=1219606d-cdc2-4c81-a382-607b07659b9a  /opt                    btrfs  subvol=/@/opt                    0  0
UUID=1219606d-cdc2-4c81-a382-607b07659b9a  /home                   btrfs  subvol=/@/home                   0  0
UUID=1219606d-cdc2-4c81-a382-607b07659b9a  /boot/grub2/x86_64-efi  btrfs  subvol=/@/boot/grub2/x86_64-efi  0  0
UUID=1219606d-cdc2-4c81-a382-607b07659b9a  /boot/grub2/i386-pc     btrfs  subvol=/@/boot/grub2/i386-pc     0  0
UUID=5EBC-49EE                             /boot/efi               vfat   utf8                             0  2

```
... all set to "0 0"

**Comment by t-ru** [comment]
> 
> I have a simple fstab.script right now that only consists of one line:
> 
> ```
> sed -i -e 's/\(^.*ext4.*\)0[[:space:]]\+0$/\10 2/' /etc/fstab
> ```
> 
And only works for ext4. What is with btrfs, xfs, ext3,... ? Your script is not working.

**Comment by seife** [comment]
My image uses ext4 only, this is why I used ext4. omit the 4. 

https://github.com/yast/yast-storage-ng/commit/65be16e505d3ee91d19652228c0f6894833ad6e7 and
https://github.com/yast/yast-storage-ng/commit/09094b00ad7399c83c54522b7725a41fb8b79ea4, or just plain
https://github.com/yast/yast-storage-ng/blob/master/src/lib/y2storage/mount_point.rb

seem to imply that at least ext[234] and jfs benefit from fsck.

Anyway, as the fsck actually do nothing if the file system was unmounted cleanly, and basically just replay the journal (same as mount) if the file system is mountable, I'm wondering why you are advocating against a sensible default here.

fs_passno=0 makes it for example impossible to use the fsck.repair= options and this is, at least for ext[234] users, a surprising result.

For XFS, the passno does not matter, as there basically is no fsck that could run unattended. The fsck.xfs program is basically a elaborate way to spell "/bin/true". So setting passno != 0 on xfs file systems will not do anything good, but it will also cause no harm. BTRFS seems similar, at least after reading the manpage of fsck.btrfs.

So I have a very real scenario with passno=0 causing harm, but cannot really imagine harm done by passno != 0.

**Comment by seife** [comment]
JFTR: fedora uses "1 1" (root) and "1 2" (others) for ext4 file systems.

**Comment by t-ru** [comment]
Is "0 0" a bug? No.

SUSE is setting "abc". Red Hat is setting "def". Debian is setting "...". There is no single standard.

Why to change? I see no reason. "0 0" is just not your preferred setting. You have the possibility to set it as you like.

**Comment by seife** [comment]
Is "0 1" a bug? No.
Nobody is setting "0 0" for extX, because it is stupid. There is no single standard.

Why change? "0 1"/"0 2" is just much more useful for everyone. You have the possibility to revoer to "0 0" as you like.

**Comment by t-ru** [comment]
> "0 1"/"0 2" is just much more useful for everyone.

No, if I want to use dump.
No, if I want to use btrfs.

It is possible to make useful default settings for all cases. But the effort for it is huge. There are many special cases.
Your use case (ext4) is not the holy grail.

**Comment by schaefi** [comment]
Hi guys. I was reading all of the information provided here and would like to summarize and add my thoughts on this. There are strong opinions and good arguments in both directions so let's come to an agreement and a solution which we can all agree with.

First I'd like to share why kiwi sets fs_passno=0 to all filesystems except root. At the time this was done the reason was because we know when the image got built all filesystems are clean and a check setting seems not required to me for the initial deployment of the image. Root forms an exception as a deployment process can touch (resize) this part.

If another setting is needed we leave it up to the user so far to adapt the fstab as needed. If I understand it correctly this concept is in line with how @t-ru thinks it should be. Changing the setting however is not really user friendly. If I look at the script from @t-ru it shows that some lines of code are needed for a relatively simple change.

@seife has a different use case and I also think your motivation is to follow a standard. At this point I agree it would be great to have some standard but with regards to the fs_passno there is really none just a recommendation. Reading the fstab documentation it is said:

```
The root filesystem should be specified with a fs_passno of  1. 
Other  filesystems   should  have  a fs_passno of 2.
```

So this is probably just a recommendation and I'm relatively convinced that distributors just set whatever they see the best fit in their individual situation. Even kiwi did not respect it ;)

Another aspect is that the handling of fstab has been moved to systemd and the generator code there works with the
settings in a dynamic way. This lead to features like ```fsck.repair=yes``` which will be not respected at all by the way kiwi
creates the fstab. Furthermore sophisticated filesystems like btrfs/xfs also ignores the original meaning of fs_passno and
applies their own idea of when the filesystem needs to be checked.

Taking all that into account I think we could do the following:

* keep ```0 0``` as the default as it's the most harmless setting and also considered a "standard" by kiwi. If we change this users might be confused about an unexpected behavior change as well as users like @t-ru with custom scripts will not be amused.
* add a new attribute to the ```<systemdisk>``` section which allows for ```<volume name="foo" check="true|false"/>```. This would add a possibility to allow activating the check "0 2" on an individual volume base.
* The rootfs as well as the boot and efi partitions will not be covered by the new attribute. Would this be an issue ? I don't think so 

How about this suggestion ?

Thanks

**Comment by seife** [comment]
Hi Marcus,

the suggestion looks fine to me. A side effect of this way of implementation is, that it is actually documented ;-) so probably less surprises on why it deviates from the "normal" installer-generated fstab entries.

Root will always be checked, no matter what is in fs_passno, because root is not checked by the fstab-generator generated dependencies, but always before even mounting and then starting the fstab-generator. Additionally it is already set to be checked.

The actual value of fs_passno again seems to no longer really mean anything because the dependencies of the file systems are determined by systemd anyway. Old fs_passno was basically a way to specify "you first need to do root before you do anything else", nowadays with real, dynamic dependencies this is no longer needed.

Thanks!

Stefan
