### ISSUE TITLE
OEM image fails with "dracut: FATAL: no partition id setup found"

### ISSUE THREAD

**Issue by doccaz** [OSInside/kiwi#1734]
## Problem description
After building a OEM image and booting it into KVM with SLED 15 SP1, it fails with the message: "dracut: FATAL: no partition id setup found".

The same XML, when built with the Live profile, works perfectly. The Virtual/VMX profile also fails with "Failed to mount install ISO device".

## Expected behaviour
The installer should find the included OS image.

## Steps to reproduce the behaviour
1. create the install ISO
                sudo kiwi \
                        --debug \
                        --profile=Disk \
                        --type oem \
                        --shared-cache-dir=out/cache system build \
                        --description kiwi-descriptions/suse/x86_64/suse-sled-15.1-tcc \
                        --target-dir=out/oem

2. Attach the image to an existing VM (4GB of RAM, 60GB SATA disk, SATA CDROM)
3. hit "e" at the grub2 menu
4. remove the "splash" parameter, change loglevel to 15
5. crash!

I also booted it with rd.debug=1, and collected the dracut logs:
[rdsosreport.txt](https://github.com/OSInside/kiwi/files/6016546/rdsosreport.txt)

## OS and Software information
+ KIWI version: KIWI (next generation) version 9.21.23
+ Operating system: openSUSE Leap 15.2
+ OBS version: n/a

**Comment by schaefi** [comment]
This is very very strange. The message "No partition id setup found" appears if the initrd build by kiwi does not have included the file /config.partids. The inclusion of this file is part of the kiwi build process and therefore should always exist.

I will verify this and come back with further details

**Comment by schaefi** [comment]
Any chance we can see your kiwi-descriptions/suse/x86_64/suse-sled-15.1-tcc/... data ?

**Comment by schaefi** [comment]
I've done a test with our integration test from here:

* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:leap/test-image-disk

my install test was as follows:

```
qemu-img create mydisk 20g
qemu-kvm -cdrom kiwi-test-image-disk.x86_64-1.42.1-Build2.3.install.iso -serial stdio -hda mydisk
```

and that worked as expected. Also the config.partids are present in the image. So I cannot reproduce the error
as you saw it. Let's further investigate that:

* your image description would be helpful for us, possible ?
* do you have any scripts/other code that performs changes to the initrd ?
* can you apply my qemu based testing to your install.iso ? Do you see still the same issue ?

Thanks

**Comment by davidcassany** [comment]
Just for the records I also tried to reproduce this issue using the `python3-kiwi-9.21.23` from Leap update repo without success. I could not reproduce it.

**Comment by doccaz** [comment]
> Any chance we can see your kiwi-descriptions/suse/x86_64/suse-sled-15.1-tcc/... data ?

Sure. Here you go.
[suse-sled-15.1-tcc.tar.gz](https://github.com/OSInside/kiwi/files/6022141/suse-sled-15.1-tcc.tar.gz)

**Comment by doccaz** [comment]
> This is very very strange. The message "No partition id setup found" appears if the initrd build by kiwi does not have included the file /config.partids. The inclusion of this file is part of the kiwi build process and therefore should always exist.
> 
> I will verify this and come back with further details

The file is in the image-root directory:
`
kiwi_BiosGrub="1"
kiwi_BootPart="4"
kiwi_EfiPart="2"
kiwi_RootPart="4"
kiwi_SwapPart="3"
`

**Comment by doccaz** [comment]
> * your image description would be helpful for us, possible ?
Sure, I attached to the other comment above.

> * do you have any scripts/other code that performs changes to the initrd ?
Included in the tar.gz.

> * can you apply my qemu based testing to your install.iso ? Do you see still the same issue ?
Log attached. Had to add "-m 4096" to the qemu-kvm line or else it'd crash with no memory. Also added a "console=ttyS0,115200"  to the GRUB command line.
[console.txt](https://github.com/OSInside/kiwi/files/6022244/console.txt)

Thanks for the help!

**Comment by schaefi** [comment]
Thanks for the details.

> Log attached. Had to add "-m 4096"

yep sorry, I miss to provide this info... I use an alias that sets some qemu options ;)
ok the same error in that log. At least some consistency

I'm currently trying to reproduce the issue... no luck so far

One last question. Can you attach your build log file ? I saw you use --debug. Could you instead run the build with --logfile /some/logfile and attach this log here ?

Thanks

**Comment by doccaz** [comment]
> One last question. Can you attach your build log file ? I saw you use --debug. Could you instead run the build with --logfile /some/logfile and attach this log here ?
> 

Sure, here it is: [oem-build.log](https://github.com/OSInside/kiwi/files/6024276/oem-build.log)

**Comment by schaefi** [comment]
I've rebuild your image description and tested it with:

```
kvm -cdrom SLES-15.1_TCC.x86_64-1.15.2.install.iso -hda mydisk
```

That also worked for me... Hmm

I had to change the repo setup of course because you used local DVD. I haven't done any other change. Still investigating

**Comment by schaefi** [comment]
Oh I think I found the problem. In your log I see:

```
INFO: 15:18:56 | Creating install image boot image
DEBUG: 15:18:56 | EXEC: [cp /home/erico/Projetos/kiwi/out/oem/build/image-root/boot/vmlinuz-4.12.14-195-default /home/erico/Projetos/kiwi/out/oem/kiwi_install_media.qomtqgbx/boot/x86_64/loader//linux]
WARNING: 15:18:56 | dracut module "kiwi-dump-reboot" not found in the root tree
WARNING: 15:18:56 | module "kiwi-dump-reboot" not included in initrd
```

The kiwi-dump-reboot module is provided with the package ```dracut-kiwi-oem-dump``` but the in your build the used package is an older version which doesn't have it. Your build installs:

```
DEBUG: 15:13:04 | system: Retrieving package dracut-kiwi-oem-dump-9.17.15-1.6.x86_64 (453/491), 323.6 KiB ( 16.8 KiB unpacked)
```

but it should be

```
DEBUG: 17:05:20 | system: Retrieving package dracut-kiwi-oem-dump-9.21.23-3.36.3.x86_64 (441/470), 349.9 KiB ( 19.5 KiB unpacked)
```

like in my build.

This is also the reason why my changed repos fixed it.

So if you build with kiwi 9.21.23 you should make sure the dracut-kiwi-* modules are also from 9.21.23. The 9.21.23 kiwi version in SLES correctly provides all this packages. Why your repo setup selected the old package is something I don't know. Probably it took the version from your DVD. So on your build host (Leap 15.2) there is kiwi 9.21.23 (from SLE15 as I see this with kiwi_revision='80a3546a57a5249179881da4fd9a666f2b7f7624') but the repo setup of your image description uses dracut-kiwi
modules from an older version which in this case causes an issue

So if you change your repo setup in a way that it uses kiwi-dracut-oemdump from >= 9.21.23 you should be fine

Can you confirm ?

**Comment by schaefi** [comment]
@davidcassany maybe it would be a good idea to make this WARNING an error and stop the build. It's pretty hard to debug the consequences. Thoughts ?

**Comment by davidcassany** [comment]
@schaefi not so sure to be honest. It is coded this way to allow building images without being forced to use KIWI specific modules. If we want to make it an error for such case it should be done at runtime check level. IMHO this particular case does not require a new check or a change in runtime checks as the root error is not caused by the dracut modules configuration by itself. The problem is misaligned dracut modules vs KIWI.

I am wondering if wouldn't make sense to make a runtime check for that, we could do it at the begining of the create step. We do not have have checks for the create step. Probably this is a good example of a check that could be done there. It could consist of checking the package database for dracut modules and check its version against of the version of the current KIWI process.

To me feels like a complex check, but I see no other way to better instruct users regarding the potential issues derived from using not aligned KIWI vs dracut modules.

There could be another radically different approach which is KIWI itself installs those modules from its own sources, so the end user does not have to list them into the description. This is a breaking change and I dislike having this sort of hidden procedures, but this would completely solve the nature of this problem by design.

**Comment by schaefi** [comment]
> not so sure to be honest. It is coded this way to allow building images without being forced to use KIWI specific modules.

I think this wasn't my point. In kiwi when we build the install image we have in the code

```python
self.boot_image_task.include_module(
    'kiwi-dump', install_media=True
)
self.boot_image_task.include_module(
    'kiwi-dump-reboot', install_media=True
)
```

This ends up in dracut as 

```
EXEC: [chroot ... dracut ... --add  kiwi-dump kiwi-dump-reboot
```

So we explicitly request this modules. Users can provide their own setup on top which we support with ```<installmedia>```
In the end there is a list of modules to omit and to add. All those that stays to be added should be now found. If they are not found I would say this should be showstopper. Like in this case

```
WARNING: 15:18:56 | dracut module "kiwi-dump-reboot" not found in the root tree
WARNING: 15:18:56 | module "kiwi-dump-reboot" not included in initrd
```

So we know about modules not found 

```
def _module_available(self, module):
        warn_msg = 'dracut module "{0}" not found in the root tree'
        if module in self.available_modules:
            return True
        log.warning(warn_msg.format(module))
        return False
```

Is there any particular reason why we not fail in this situation ?

**Comment by davidcassany** [comment]
> Is there any particular reason why we not fail in this situation ?

Yes there is. This was a result of fc4a1616bc2d319342f6243446639bab7233e545 to solve #1300. This was coded under the assumption that runtime checks already validated dracut modules were requested. In this reported issue the runtime check is useless because the dracut modules version does not match KIWI version hence the check turns to be not precise.

While I can understand that probably we should find a better strategy for #1300 that is not leading to the `_module_available` implementation you saw. I believe this would not actually solve the issue have here (it might, but just for this very particular case).

So IMHO we issue is how to let user know dracut modules being used in the target image are not aligned with KIWI. This sort of mismatches can produce many different failures and not adding the expected dracut modules is just one of those. So I'd be pretty satisfied if we find a way to tell the user that there is this sort of misalignment so they have some hints about how to solve the issue.

**Comment by davidcassany** [comment]
I agree that for this particular case of the `kiwi-dump` module custom configuration could be achieved by deactivating the runtime checks and using the `<installmedia>` section. So probably it is time to rethink #1300 as the we gained more flexibility since then, we have `<installmedia>` and we also have `<oem-resize>false</oem-resize>` to avoid `kiwi-oem-repart`.

However I still believe this is just another related issue of the problem that was reported here.

**Comment by schaefi** [comment]
> Yes there is. This was a result of fc4a161 to solve #1300. This was coded under the assumption that runtime checks already  validated dracut modules were requested. 

Ah yes I remember. And we have check_dracut_module_for_oem_install_in_package_list() which returns success because the requirement is satisfied.

The problem here is that for a particular version of kiwi a version constraint for the dracut module exists because at some point in the past dracut-kiwi-oem-dump was splitted into two dracut modules kiwi-dump and kiwi-dump-reboot

> So IMHO the issue is how to let user know dracut modules being used in the target image are not aligned with KIWI. This sort of mismatches can produce many different failures and not adding the expected dracut modules is just one of those. So I'd be pretty satisfied if we find a way to tell the user that there is this sort of misalignment so they have some hints about how to solve the issue.

yes. not so easy

**Comment by schaefi** [comment]
I'll try to come up with a suggestion and we can discuss from there

**Comment by davidcassany** [comment]
Probably this is a quite stupid solution, but what about making a runtime check for that. So at the beginning of the creation step we could run make use of the package manager to query the version of the dracut modules and check it against the running KIWI. If there is a mismatch we could throw a big warning. 

The big problem of this is that it doesn't happen early on the build process and that it not straight forward to instruct from a message how to proceed in case it fails (not always will fail using misaligned versions). So I don't see a clear way to make it non confusing.

**Comment by doccaz** [comment]
> So if you build with kiwi 9.21.23 you should make sure the dracut-kiwi-* modules are also from 9.21.23. The 9.21.23 kiwi version in SLES correctly provides all this packages. Why your repo setup selected the old package is something I don't know. Probably it took the version from your DVD. So on your build host (Leap 15.2) there is kiwi 9.21.23 (from SLE15 as I see this with kiwi_revision='80a3546a57a5249179881da4fd9a666f2b7f7624') but the repo setup of your image description uses dracut-kiwi
> modules from an older version which in this case causes an issue
> 
> So if you change your repo setup in a way that it uses kiwi-dracut-oemdump from >= 9.21.23 you should be fine
> 
> Can you confirm ?

Yes, I can confirm that. The SLE15SP1 ISO contains version 9.17.15, and my Leap 15.2 system is using version 9.21.23. 

But shouldn't kiwi be using the dracut files from the *host system*  (in this case Leap 15.2) instead of the ones from the *repository*? Using the ones from the repo, you'll never be able to build older OSes reliable unless you have the corresponding updated packages built for that OS version *and* available in a repo. 

I created an appliance at OBS with the same files: https://build.opensuse.org/package/show/home:emendonca:kiwi-tcc/TCC
(just commented out the repositories and set it to "obsrepositories://" like in the test appliances). It fails with the same problem, even though I can see that the Virtualization:Appliances:Builder/SLE_15_SP1  path contains a newer kiwi package. If I followed the logic correctly, the error would go away if I added an Updates repo that contained the same version of kiwi as the one present in this repository.

So, wouldn't it be wiser to use the dracut modules from the host system? The modules are shell scripts, no binary code AFAIK.

**Comment by schaefi** [comment]
@davidcassany I'm thinking in a similar direction but wanted to give the dracut modules a version which is managed by bumpversion such that we can create a runtime(create stage) check that can check the kiwi version with the dracut module versions. I don't want to instruct the package manager with this task because there are more and more images which deletes the package manager or use them outside of the real root tree

**Comment by schaefi** [comment]
> But shouldn't kiwi be using the dracut files from the host system (in this case Leap 15.2) 

nope that would be a wrong approach for the purpose of creating an initrd for the target system. Remember if you rebuild your initrd e.g a kernel update arrived on your deployed machine you will recall dracut and at that time there is no build host anymore

**Comment by schaefi** [comment]
I agree this is not a problem for the install media, but that's just a corner case

**Comment by schaefi** [comment]
> The big problem of this is that it doesn't happen early on the build process

well this can't be avoided from my understanding. You have to wait until the dracut packages got installed before you can check the integrity of the system. There is no other way

**Comment by doccaz** [comment]
> > But shouldn't kiwi be using the dracut files from the host system (in this case Leap 15.2)
> 
> nope that would be a wrong approach for the purpose of creating an initrd for the target system. Remember if you rebuild your initrd e.g a kernel update arrived on your deployed machine you will recall dracut and at that time there is no build host anymore

I mean, not using the complete dracut files and binaries from the host, but copying the kiwi-specific dracut modules from the host to the target system. Is there anything else from kiwi that is needed on the target system?

**Comment by schaefi** [comment]
>I mean, not using the complete dracut files and binaries from the host, but copying the kiwi-specific dracut modules from the host to the target system. Is there anything else from kiwi that is needed on the target system?

you could do this as a workaround approach to fix your issue. But as a general solution this is not applicable. There are dracut-kiwi-* packages which we deliver with the builder and having them installed in a clean way keeps the consistency of the system. A custom over-copy of data will introduce more unmanaged data to your rootfs which we usually try to avoid

**Comment by doccaz** [comment]
FYI: my build worked on OBS after adding a path for SUSE:SLE-15-SP1:Update/standard to the repositories. All three profiles were build and tested ok (Disk, Virtual, Live). I cannot build it locally without a RMT server with the mirrored updates, though. 

Perhaps there should be a note on the documentation about the required updates for SLE?

**Comment by schaefi** [comment]
@doccaz we have added a runtime check to check for the dracut mod vs. kiwi compatibility and fail the build when we know this is not going to end well. This will help to identify and clarify the issue better. For details see #1741 

> Perhaps there should be a note on the documentation about the required updates for SLE?

There should be a general topic about how to build for repos that are not publicly available. SLE in this case. The doc team at SUSE is currently writing a best practice chapter and this will be available in the next weeks at documentation.suse.com. Once I can find it there I'll create a reference in the kiwi docs under the new Troubleshooting chapter

Really sorry about the inconvenience you had but I think with the check in kiwi and the docs in the future we can
improve the situation with SLES and repos a bit.

Thanks
