### ISSUE TITLE
Built images have content in /run

### ISSUE THREAD

**Issue by Vogtinator** [OSInside/kiwi#1744]
`/run` is for runtime content and is generally in a ramdisk. However, images built with kiwi currently have this fully populated, like a running system. This can be seen by either mounting the image manually or if it uses btrfs snapshots, by `ls /.snapshots/1/snapshot/run`.

**Comment by davidcassany** [comment]
In fact I just verified that `/run` gets populated at prepare step while creating the root-tree and then it gets synchronized to the persistent device. I believe we should exclude any `/run` content in any sync operation. Gonna provide a PR for that.

For reference this is how FHS defines `/run`: [Run-time variable data](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s15.html)
