### ISSUE TITLE
devicepersistency="by-label" not working in grub configuration

### ISSUE THREAD

**Issue by Nonfilin78** [OSInside/kiwi#1757]
## Problem description
devicepersistency="by-label" is set.
As expected, all entries of /etc/fstab are set correctly.
But the settings for Grub in /boot/grub2/grub.cfg still refer to a device via UUID in the kernel command line.

excerpt from fstab: /etc/fstab:
```
LABEL=ROOT / btrfs defaults 0 0
LABEL=EFI /boot/efi vfat defaults 0 0
```
and so on...

exverpt from /boot/grub2/grub.cfg:
```
linux /boot/vmlinuz-5.3.18-22-defaut root=UUID=fd49f3.....
```

## Expected behaviour
excerpt from /boot/grub2/grub.cfg:
```
linux /boot/vmlinuz-5.3.18-22-defaut root=LABEL=ROOT.
```

## Steps to reproduce the behaviour
excerpt from kiwi descriptionfile:
```
  <preferences profiles="VMware">
    <version>15.2</version>
    <packagemanager>zypper</packagemanager>
    <bootsplash-theme>SLE</bootsplash-theme>
    <bootloader-theme>SLE</bootloader-theme>
    <rpm-excludedocs>false</rpm-excludedocs>
    <keytable>de</keytable>
    <locale>en_US</locale>
    <timezone>Europe/Berlin</timezone>
    <type
      image="vmx"
      filesystem="btrfs"
      format="vmdk"
      bootloader="grub2"
      firmware="uefi"
      efipartsize="33"
      kernelcmdline="plymouth.enable=0 console=ttyS0,115200 console=tty0 consoleblank=0"
      bootpartition="false"
      bootkernel="custom"
      devicepersistency="by-label"
      rootfs_label="ROOT"
      btrfs_quota_groups="true"
      btrfs_root_is_snapshot="true"
    >
      <systemdisk>
        <volume name="home"/>
        <volume name="root"/>
        <volume name="tmp"/>
        <volume name="opt"/>
        <volume name="srv"/>
        <volume name="boot/grub2/i386-pc"/>
        <volume name="boot/grub2/x86_64-efi" mountpoint="boot/grub2/x86_64-efi"/>
        <volume name="usr/local"/>
        <volume name="var" copy_on_write="false"/>
      </systemdisk>
      <size unit="G" unpartitioned="2">60</size>
    </type>
  </preferences>
```

## OS and Software information
+ KIWI version: 9.20.5-3.18.1
+ Operating system: obs-worker (opensuse leap 15.1)
+ OBS version: 2.10.8-lp151.56.2

**Comment by schaefi** [comment]
Hmm there seems to be a generic issue with the persistency type selection, there is also #1747

we will look into it

**Comment by Nonfilin78** [comment]
## Steps to reproduce the behaviour
I was also able to reproduce the error on build.opensuse.org, to eliminate errors in the local OBS installation.
1. Branch [SUSE:Templates:Images:SLE-15-SP2/kiwi-templates-JeOS](https://build.opensuse.org/package/show/SUSE:Templates:Images:SLE-15-SP2/kiwi-templates-JeOS)
2. change devicepersistency to "by-label" in JeOS.kiwi

the resulting image has the same problem.
