### ISSUE TITLE
Unable to build debian image, no multi mirror or apt pinning support

### ISSUE THREAD

**Issue by MartinVerges** [OSInside/kiwi#1763]
## Problem description
I need to install some packages from `buster` release, some from `buster-backports` and some other from `inofficial-mirror`.
Unfortunately `config.sh` is called after the package installation, so I can't modify the apt config inside the image, after bootstrap.

## Expected behaviour
Being able to install packages from a specified mirror like:
`<package name="mypackage" repo="aliasname">`

Having a way of configuring the image before the package installation starts, like `config.sh` but `after-bootstrap.sh`.

## Steps to reproduce the behaviour
Try to install a package from a specific release or mirror.

## OS and Software information
+ KIWI version: 9.23.16
+ Operating system: openSUSE Leap 15.2

**Comment by schaefi** [comment]
Hi @MartinVerges, could you share the needed config bits on the apt configuration level to allow the operation as you need it ?

Thanks

**Comment by MartinVerges** [comment]
Hello,

in Debian, you can configure pinning to select which package you would like to get from what mirror.

For example, I like to build a Debian Image with a recent Ceph Version. On the official buster mirrors, Ceph is in 12.2 (super old) as you find it on https://packages.debian.org/buster/ceph. If you need a newer version, you have to use the provided debian buster-backports mirror https://packages.debian.org/buster-backports/ceph to receive a new Version (14.2).

With the ugly limitation of debootstrap to only support a single mirror, you can only install the base components using debootstrap like that:
```
    <repository type="apt-deb" alias="buster" use_for_bootstrap="true" distribution="buster" components="main contrib non-free" repository_gpgcheck="false" imageinclude="false" priority="50">
        <source path="http://ftp.de.debian.org/debian/"/>
    </repository>
    <packages type="bootstrap">
        <package......>
    </packages>
```
In the next stage `kiwi-ng` chroots into the image and installs the packages 
```
    <packages type="image" patternType="onlyRequired">
        <package......>
    </packages>
```

As there is no script to add changes, and no way to set apt priorities or mirror sources for the second stage, it's not possible to select the ceph version from the backports mirror instead of the main mirror.
It gets even uglier if you have packages from unstable/testing mirrors or third party that you would like to add.

So you end up by just installing the super low basis and then do the rest in a shell script without the benefits of kiwi-ng.

Thanks for looking into it, if I can help you with anything let me know.

**Comment by schaefi** [comment]
ok, yes we also stumbled over the "one-repo-for-debootstrap" problem too. There was an issue which I think is related to your problem. See #1593 

We added the opportunity to specify which repo should be used for the basic bootstrap. So I think you should be able to add
any repositories you need in a collection of ```<repository>``` sections (maybe plus prios) and one of those repos you mark with

```xml
<repository ... use_for_bootstrap="true"/>
```

If your bootstrap list does not contain ceph it will be installed in the second stage by apt taking the repo setup into account and choosing the latest version per configured prios

Would that work in your case ?

**Comment by MartinVerges** [comment]
Having to create my own debian mirror with the packages required and maintaining dependencies is quite hard, just to make use of kiwi-ng. I would then just stick with plain old bash script after the vanilla image was created. However thanks for the suggestion.

Using `package=version`, is also a lot of work unfortunately and will break apart often when the packages change.  Unfortunately apt does not support a syntax like `>=1.2.3` on command line.

In the Debian world, you usually configure your apt as I did in my root folder:

```
kiwi-builder:~/os-image-builder/debian-10 # cat root/etc/apt/preferences

# will be installed, even if it is not from the target release, unless the installed version is more recent
# Pin-Priority <1000 >=990
Package: *
Pin: release o=Debian,a=buster-updates
Pin-Priority: 990

# will be installed, except if a version is available that belongs to the target release or the installed version is newer
# Pin-Priority <990 >=500
Package: *
Pin: release a=stable
Pin-Priority: 700

Package: *
Pin: release a=buster-backports
Pin-Priority: 650

Package: *
Pin: release a=testing
Pin-Priority: 400

Package: *
Pin: release a=unstable
Pin-Priority: 300

# will be installed, unless a version belonging to another distribution is available or the installed version is newer
# Pin-Priority <500 >=100

# causes a version to be installed only if there is no installed version of the package
# Pin-Priority <100 >=0

kiwi-builder:~/os-image-builder/debian-10 # cat root/etc/apt/preferences.d/pin-
pin-apparmor-packages  pin-kernel-packages    pin-mirror-croit-io    pin-nfs-packages       pin-samba-packages     
kiwi-builder:~/os-image-builder/debian-10 # cat root/etc/apt/preferences.d/pin-samba-packages 
Package: samba* ctdb smbclient winbind python-samba libnss-winbind libpam-winbind libwbclient* libsmbclient* registry-tools libparse-pidl-perl
Pin: release a=stable
Pin-Priority: 800
kiwi-builder:~/os-image-builder/debian-10 # cat root/etc/apt/preferences.d/pin-mirror-croit-io 
Package: *
Pin: origin mirror.croit.io
Pin-Priority: 700
``` 

That way you can select what and when to install in a fine granular way. The only small requirement to kiwi would be, to have a way of injecting this config after the bootstrap and before the apt package installation. Or as proposed to select the mirror to use for a package using the xml file syntax. But with the current implementation, kiwi-ng is unfortunately quite limited in the debian and ubuntu world in my opinion.

**Comment by MartinVerges** [comment]
btw. just to give some general Feedback. For the Suse OS, kiwi-ng is awesome software. Thanks for it!

**Comment by schaefi** [comment]
Thanks Martin for your feedback

> In the Debian world, you usually configure your apt as I did in my root folder:

That was the information I was looking for. So if this is the common practice we should support/allow some way to do this.
With the provided data we will come up with a solution and appreciate your feedback once there is a pull request to address this.

> btw. just to give some general Feedback. For the Suse OS, kiwi-ng is awesome software. Thanks for it!

Thanks much. The overall idea from the beginning on was to provide a useful appliance builder for all modern linux distributions. 
This is also the reason why our integration tests provides test builds for Ubuntu, Debian, Fedora, CentOS, SUSE ... and hopefully more. So kiwi is really not a suse only thing and we take your issue report serious.

Thanks

**Comment by schaefi** [comment]
>That way you can select what and when to install in a fine granular way. The only small requirement to kiwi would be, to have a way of injecting this config after the bootstrap and before the apt package installation. Or as proposed to select the mirror to use for a package using the xml file syntax. But with the current implementation, kiwi-ng is unfortunately quite limited in the debian and ubuntu world in my opinion.

Agreed. So my current idea is to provide an attribute to point to a post_bootstrap script like this

```xml
<packages type="bootstrap" post_bootstrap="/path/to/script"/>
    ...
</packages>
```

* The post_bootstrap attribute is only allowed for the "bootstrap" packages type. We will make that sure by a schematron rule
* The given script will run directly after the bootstrap is done
* The given script is not dedicated to a specific package manager, it can be used as a general hook after bootstrap
* The documentation for the available script hooks will be updated pointing the debian package priority setup as one example use case

What do you think ?

@davidcassany Your feedback on the proposed change would be much appreciated

Thanks

**Comment by davidcassany** [comment]
@schaefi I like the idea of having a hook right after the bootstrap phase, since, IMHO, it is the earliest chance we have to call a chrooted script and a good chance to customize stuff right before most packages are installed. I am not sure if I prefer an explicit reference to the script via an XML attribute or just call it if `post_bootstrap.sh` file exists in the project folder. Probably I'd vote for the later so it has the same behavior as it does for `disk.sh`, `images.sh` or `config.sh`, only the stage on which they are applied changes.

What I am wondering though, is if there is an easier way to customize the package manager (also having in mind #1782). Note that using this script for the package manager configuration is not obvious from user point of view as we are not using regular configuration locations at build time and we are mostly not using it for the final image, thus making a package manager config customization that has to be used at build time but also persist to the resulting image would be certainly possible but not that obvious. It is hard to come up with generic concept to allow config customization on package manager that is not package manager specific, probably setting a drop in configuration folder? where the user can drop in additional configuration files. Not sure if all package managers support such a concept.

I was also wondering about the idea of allowing users to apply the root overlay tree in other phases (via some type attribute) of the process (before bootstrap, after bootstrap, after packages install or after system setup as it is now). However it has the same issues about customizing the package manager and it is not as flexible as a script. So, while I think it would be an interesting feature I don't think it is really usable to solve this package manager configuration issues.

All in all, I think the script you suggest is the most straight forward option regarding the implementation and regarding the flexibility it provides.

**Comment by rominf** [comment]
I like the idea about `post_bootstrap.sh`. I think it will perfectly solve my issue in #1782.

**Comment by schaefi** [comment]
Thanks for the feedback, so ```post_bootstrap.sh``` it will be :)

@davidcassany; I was also thinking about a generic concept to allow package manager customization but every package manager has their own concept and very big differences from a feature perspective. I simply did not see how we could come up with a generic interface to serve them all. If we go with a subset that all of them provides we surely will not cover important features users want to make use of. In the end users will still need scripts. Therefore I think we should allow ```post_bootstrap.sh``` and leave the responsibility to know about the package manager features on the user level as a first
opportunity.

I'll provide a PR to address this
