### ISSUE TITLE
Building minimal CentOS 7 images is broken when "yum" package manager is used

### ISSUE THREAD

**Issue by Conan-Kudo** [OSInside/kiwi#1768]
## Problem description
Some time ago, we aliased `yum` to `dnf` in the code. However, I found out that when requesting `yum` for CentOS image descriptions, it attempts to install `yum` when going into the "image" phase. This is fine on CentOS 8, but broken on CentOS 7 (and openSUSE Leap 15.x), where legacy `yum` still exists. Consequently, it breaks because then `dnf` is not installed.

## Expected behavior
DNF gets installed and consistently used, even when `yum` is set in the XML.

## Steps to reproduce the behavior
Try to build a CentOS 7 image using [the example description](https://github.com/OSInside/kiwi-descriptions/blob/master/centos/x86_64/centos-07.0/config.xml) _without_ `nextgen-yum4` installed in the bootstrap phase.

## OS and Software information
+ KIWI version: 9.23.20
+ Operating system: Fedora 33
+ OBS version: N/A

**Comment by schaefi** [comment]
will fix this
