### ISSUE TITLE
Using container registries to import KIWI prepare step

### ISSUE THREAD

**Issue by davidcassany** [OSInside/kiwi#1771]
This issue is originated from #38. In KIWI we could enable the possibility to store the root-tree (result of prepare step) in to a container registry (or similar OCI artifact) so that it could be used later on for fast image rebuild with or without root-tree changes.

The point is that by storing the result of the prepare step we include the KIWI metadata including all the image details and image description. This could help to build some very basic consistency checks so that not any container stored out there can be pulled.

This can eventually be helpful to provide a truly reproducible images mechanism and also a easy way to provide fine tuning or derived images of any kind given an image base root-tree.

The idea is to provide a mechanism to store a root-tree in a registry (local or remote) and also provide a mechanism to pull any previously stored tree and make use of it to build an image.

**Comment by schaefi** [comment]
really exciting hackweek project :smiley:

**Comment by schaefi** [comment]
Implementing as plugin. For details see: https://github.com/OSInside/kiwi-stackbuild-plugin

**Comment by schaefi** [comment]
Closing on behalf of #1907

Thanks
