### ISSUE TITLE
Fedora 33 boxbuild (profile=Virtual) fails because of D-Bus failure

### ISSUE THREAD

**Issue by rominf** [OSInside/kiwi#1773]
## Problem description
I'm trying to build Fedora 33 VM image using the boxbuld. Build fails because the network doesn't work.

I'm getting this in the middle of the output:
```
[FAILED] Failed to listen on D-Bus System Message Bus Socket.                                                                                                                                  
See 'systemctl status dbus.socket' for details.                                                                                                                                                
[DEPEND] Dependency failed for Network Manager.                                                                                                                                                
[DEPEND] Dependency failed for Network Manager Wait Online.                                                                                                                                    
[DEPEND] Dependency failed for Home Area Manager.
```

## Expected behaviour
The build is successful.

## Steps to reproduce the behaviour

1. Install Fedora 33 workstation.
2. Install `kiwi-cli`, `kiwi-boxed-plugin`.
3. Clone the kiwi-descriptions repo.
4. Build the image using the command: `kiwi-ng --profile=Virtual system boxbuild --box fedora -- --description ~/kiwi-descriptions/fedora-33/ --target-dir ~/kiwi-fedora`.

## OS and Software information
+ KIWI version: 9.23.20
+ Operating system: Fedora 33
+ OBS version: N/A

**Comment by rominf** [comment]
Build without `boxbuild` fails as in #1772.

**Comment by rominf** [comment]
The question is: is it possible to build Fedora 33 VM image at all?

**Comment by schaefi** [comment]
Hmm, the network issue is new to me. I'll give it a try. We use the virtio-net module for networking. So this might also be a kvm problem with virtio on your host. I'll check here if I run into the same problem

**Comment by schaefi** [comment]
I can reproduce this, dbus seems to be not running. I remember I had that issue in the past. I'm looking into it

**Comment by schaefi** [comment]
I found the issue. The fedora box is missing ```<package name="dbus-daemon"/>```.

**Comment by Conan-Kudo** [comment]
You want `dbus-broker` instead.

**Comment by schaefi** [comment]
ok

**Comment by schaefi** [comment]
The updated box will build here:

* https://build.opensuse.org/project/show/Virtualization:Appliances:SelfContained:fedora

Currently in blocked state... waiting for obs to start the build

**Comment by schaefi** [comment]
@rominf for the time being simply switch to the universal box. This is also a Fedora system but with more tools installed such that you can also build for other distros there.

```
kiwi-ng --profile=Virtual system boxbuild --box universal -- --description ~/kiwi-descriptions/fedora-33/ --target-dir ~/kiwi-fedora
```

This currently builds fine here

**Comment by schaefi** [comment]
@rominf @Conan-Kudo ok my build for Fedora33 completed successfully with the universal box (Fedora32). You can use this box for building

I have swiched the repos to the latest stable Fedora release (Fedora33) for the fedora box. Once the build is done I think this can be used to reproduce the permission issue from #1772. I hope we can check and find the reason for the issue. When using the option '--box-debug' there is a way to debug the virtual environment. I'll try to reproduce the issue and most probably will come back with some questions.

So I think the issue reported here has a workaround with the universal box. Please close if you agree with me.

Regarding #1772 we will follow up in that issue thread.

Thanks

**Comment by rominf** [comment]
Thanks! Universal box works for me!
