### ISSUE TITLE
Debian Stretch fails to build on universal box build.

### ISSUE THREAD

**Issue by mottsen** [OSInside/kiwi#1775]
## Problem description

Using the debian-stretch image from [here](https://github.com/OSInside/kiwi-descriptions/tree/master/debian/x86_64/debian-stretch) fails to build when using a the universal boxbuild.  It is able to build using the ubuntu boxbuild image.

Here is the error thrown when attempting to use the universal box:
```
[ ERROR   ]: 19:03:28 | KiwiInstallPhaseFailed: System package installation failed: debconf: delaying package configuration, since apt-utils is not installed
E: Can not write log (Is /dev/pts mounted?) - posix_openpt (19: No such device)
dpkg: warning: 'sh' not found in PATH or not executable
dpkg: warning: 'rm' not found in PATH or not executable
dpkg: warning: 'tar' not found in PATH or not executable
dpkg: warning: 'ldconfig' not found in PATH or not executable
dpkg: warning: 'start-stop-daemon' not found in PATH or not executable
dpkg: error: 5 expected programs not found in PATH or not executable
Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin
E: Sub-process /usr/bin/dpkg returned an error code (2)
```

## Expected behaviour

Universal boxbuild to build image successfully.

## Steps to reproduce the behaviour

1. Download the debian stretch image from [here](https://github.com/OSInside/kiwi-descriptions/tree/master/debian/x86_64/debian-stretch)
2. Remove the OBS repository section
3. Attempt to build the Virtual Profile using a boxbuild with the universal image.

## OS and Software information
+ KIWI version: 9.23.20 and boxed-plugin 0.2.6
+ Operating system: Ubuntu 18.04
+ OBS version: N/A

**Comment by schaefi** [comment]
Hmm, it says apt-utils is not installed. My first guess is that the debootstrap call did not install the required component.
Does it help if you add the package ```<package name="apt-utils"/>``` to the ```<packages type="bootstrap"/>``` section in the kiwi configuration file. This should make debootstrap to install this component and make the later chroot based apt-get call happy ?

I haven't tested it though

**Comment by mottsen** [comment]
Adding apt-utils to the bootstap section gets a bit further, but still doesn't give a happy build:
```
[ INFO    ]: Processing: [########################################] 100%
Extracting templates from packages: 100%Failed: System package installation failed: 
E: Can not write log (Is /dev/pts mounted?) - posix_openpt (19: No such device)
dpkg: warning: 'sh' not found in PATH or not executable
dpkg: warning: 'rm' not found in PATH or not executable
dpkg: warning: 'tar' not found in PATH or not executable
dpkg: warning: 'ldconfig' not found in PATH or not executable
dpkg: warning: 'start-stop-daemon' not found in PATH or not executable
dpkg: error: 5 expected programs not found in PATH or not executable
Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin
E: Sub-process /usr/bin/dpkg returned an error code (2)

```

**Comment by schaefi** [comment]
Hi, I debugged this for hours and I have no clue why it fails with this error message. If you use "--box ubuntu" the same description builds just fine. If you use "--box universal" apt fails with the message you posted. I can only think of some inconsistency of the apt/debootstrap toolchain build for Fedora compared to the toolchain present on ubuntu. The universal box is using Fedora32 as the base system and has the apt/debootstrap tooling installed. There is most probably an issue in this area but I could not find the reason.

**Comment by schaefi** [comment]
I could successfully build buster

```
kiwi-ng system boxbuild --box universal -- --description ~ms/Project/kiwi-descriptions/debian/x86_64/debian-buster/ --target-dir /tmp/mytest/
```

but it fails for stretch with the reported error

```
kiwi-ng system boxbuild --box universal -- --description ~ms/Project/kiwi-descriptions/debian/x86_64/debian-stretch/ --target-dir /tmp/mytest/
```

I think this a debootstrap issue with the version available on Fedora. I moved the box to build against Fedora33 but this did not change the behavior.

I'm sorry for this one we need help from the Fedora side. Using a box based on Debian like ```--box ubuntu``` solves this issue as a workaround.

**Comment by schaefi** [comment]
I have updated the universal box to Fedora34 but still the same issue when trying to run debootstrap for "stretch" it still fails. Building the same using ```--box ubuntu``` works.

I'm closing this one now, since there is imho an acceptable workaround and my ask for help did not get peoples attention ;)

**Comment by schaefi** [comment]
closed
