### ISSUE TITLE
Options specialty when using the boxbuild command

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi#1779]
## Problem description

When using the box plugin and the boxbuild command there is a special option handling to distinguish options for the boxbuild command and the actual build command inside of the box. The separator between the two is a double ```--``` as in

```
kiwi-ng --type iso system boxbuild --box leap -- \
      --description kiwi-descriptions/suse/x86_64/suse-leap-15.1 \
      --target-dir /tmp/myimage
```

Even though the current docs at https://osinside.github.io/kiwi/self_contained.html would allow to cut and paste from the example there are people who stumble over the problem that exists if you forget the ```--```

## Expected behaviour

It should be obvious to people how the command works. I therefore suggest to add a warning/hint box that explains why the
separation is important and that users gets pointed to this information in the documentation

**Comment by frgomes** [comment]
The documentation is fine and clear enough about the separator ``--``. The example is fine too.

IMHO, the real "problem" is that ``--`` does not appear anywhere when I do:

    $ kiwi-ng system boxbuild --help

**Comment by schaefi** [comment]
going to work on this one
