### ISSUE TITLE
WSL appx image in OBS required author contact as email results in invalid appx schema

### ISSUE THREAD

**Issue by jfkw** [OSInside/kiwi#1780]
## Problem description

kiwi image definition fields `author` and `contact` overwrite prepared wsl-appx metadata for `AppxManifest.xml` `Identity` `Name`. `Properties` elements `DisplayName` and `PublisherDisplayName` are also overwritten by static string `system-container`,

I am working on direct kiwi WSL appx image generation in OBS. Package `wsl-appx` provides a complete `AppxManifest.xml` and associated metadata. When kiwi image builder `kiwi-images-wsl` creates the `.appx` image, required fields `author` and `contact`:

``` xml
 <?xml version="1.0" encoding="utf-8"?>
 <image schemaversion="6.1" name="opensuse-wsl">
   <description type="system">
     <author>SUSE WSL Team</author>
     <contact>wsl@suse.com</contact>
     <specification>openSUSE WSL Image</specification>
   </description>
   <preferences>
```
overwrite the prepared `Identity` attribute `Name` with an email address:

``` diff
--- wsl-appx-input-AppxManifest.xml
+++ kiwi-wsl-images-output-AppxManifest.xml
-  <Identity Name="REDACTED.openSUSELeap15.3Beta"      Version="15.3.2645.0" Publisher="E=home:(...), CN=home:(...)" ProcessorArchitecture="x64"/>
+  <Identity Name="SUSE WSL Team &lt;wsl@suse.com&gt;" Version="15.3.2645.0" Publisher="E=home:(...), CN=home:(...)" ProcessorArchitecture="x64"/>

   <Properties>
-    <DisplayName>openSUSE Leap 15.3 Beta</DisplayName>
-    <PublisherDisplayName>SUSE</PublisherDisplayName>
+    <DisplayName>system-container</DisplayName>
+    <PublisherDisplayName>system-container</PublisherDisplayName>
```

This results in invalid character schema validation (angle brackets, spaces) when attempting to run the `.appx` image in Windows, as well as loss of the image name data prepared in package `wsl-appx` using information from file `os-release` and other informaiton. This information is necessary to publish in the Windows Store:

```
PS C:\Users\User> Add-AppxPackage .\opensuse-wsl.x86_64-1.0.0-Build29.1.appx
Add-AppxPackage : Deployment failed with HRESULT: 0x80080204, The Appx package's manifest is invalid.
error 0xC00CE169: App manifest validation error: The app manifest must be valid as per schema: Line 3, Column 15,
Reason: 'SUSE WSL Team <wsl@suse.com>' violates pattern constraint of '[-.A-Za-z0-9]+'.
The attribute 'Name' with value 'SUSE WSL Team <wsl@suse.com>' failed to parse.
```

A related unwanted substitution of data also occurs with the `Properties` elements `DisplayName` and `PublisherDisplayName` by `system-container`, as shown in the above diff. These should also be preserved verbatim for proper publishing in the Windows Store.

## Expected behaviour

- kiwi image generation for image type `appx` should not overwrite `AppxManifest.xml` element `Identity` attribute `Name`.
- The `AppxManifest.xml` schema regex for element `Identity` attribute `Name`.  `[-.A-Za-z0-9]+` which cannot use an email address.
- In this case, the overloaded term `Name` refers to a fully qualified published image identity in the Windows Store, not author identity, so these fields are not quite the correct semantic information.
- The above diff in output `AppxManifest.xml` should be eliminated for publishing the the Windows store to work.

## Steps to reproduce the behaviour

Build `kiwi-images-wsl` appx images in OBS using `AppxManifest.xml` prepared by `wsl-appx`. The OBS project configuration to implement this currently lives in ephemeral package project branches. which I can point to in comments if requested.

## OS and Software information
+ KIWI version: `python3-kiwi-9.21.23` according to `osc buildinfo -d`
+ Operating system: openSUSE Leap 15.3 Beta image target, but OBS is the build environment
+ OBS version: deployed version at build.opensuse.org as of 2021-03-19, I don't know how to check that deployment.

**Comment by Vogtinator** [comment]
Some of that might be a side effect of https://github.com/OSInside/kiwi/pull/1560.

You could try setting an empty name (`<containerinfo name=""/>`) and author (`<history author=""/>`) as hacky workarounds.

**Comment by jfkw** [comment]
I have tried the following kiwi image specification:
```xml
<image schemaversion="6.1" name="opensuse-wsl">
  <description type="system">
    <author />
    <contact />
    <specification>openSUSE WSL Image</specification>
  </description>
  <preferences>
    <type image="appx" metadata_path="/usr/share/wsl-appx">
      <containerconfig name="">
        <history author=""/>
      </containerconfig>
    </type>
    <version>1.0.0</version>
    <packagemanager>zypper</packagemanager>
```
However with the exception of incomplete email address, the occurrences of unintended `AppxManifest.xml` metadata overwriting are unchanged. Am I using the empty elements and attributes correctly for the suggested workaround?
```diff
--- wsl-appx-input-AppxManifest.xml
+++ kiwi-wsl-images-output-AppxManifest.xml
-  <Identity Name="REDACTED.openSUSELeap15.3Beta"      Version="15.3.2645.0" Publisher="E=home:(...), CN=home:(...)" ProcessorArchitecture="x64"/>
+  <Identity Name=" &lt;&gt;"                          Version="15.3.2645.0" Publisher="E=home:(...), CN=home:(...)" ProcessorArchitecture="x64"/>

   <Properties>
-    <DisplayName>openSUSE Leap 15.3 Beta</DisplayName>
-    <PublisherDisplayName>SUSE</PublisherDisplayName>
+    <DisplayName>system-container</DisplayName>
+    <PublisherDisplayName>system-container</PublisherDisplayName>
```

**Comment by Vogtinator** [comment]
Indeed, in `xml_state.py` it ignores empty values already, so those never reach `appx.py` and it uses the defaults...

So this needs some changes in kiwi to avoid overwriting those values.

**Comment by schaefi** [comment]
yep agreed. We will look into it for the next sprint. Thanks much for the detailed report :+1:
