### ISSUE TITLE
Add a possibility to pass custom config values to the repository configuration before the image build

### ISSUE THREAD

**Issue by rominf** [OSInside/kiwi#1782]
## Problem description
I'm using Kiwi to build Fedora 33. I use private repositories and I want to speed things up by increasing `max_parallel_downloads` in the repo description.

## Expected behaviour
There is a possibility to pass custom config values (such as `max_parallel_downloads`) to the repository configuration. This configuration should be applied before the image build.

## Steps to reproduce the behaviour
Not applicable.

## OS and Software information
+ KIWI version: 9.23.20
+ Operating system: Fedora 33
+ OBS version: Not applicable

**Comment by schaefi** [comment]
Hi, there is a conversation ongoing in #1763 which will lead to a feature that I think can be used to solve the reported issue here as well. Would you mind to take a look at the last comments from #1763 and share your thoughts with regards to the issue you reported ?

Thanks
