### ISSUE TITLE
WSL Kiwi examples

### ISSUE THREAD

**Issue by t-ru** [OSInside/kiwi#1785]
## Problem description
Hello,
I plan to create custom WSL images for Tumbleweed. In repo "kiwi-descriptions" I found no samples.
Is there a sample description available?

+ KIWI version: 
+ Operating system: 
+ OBS version:

**Comment by t-ru** [comment]
I followed this description.

https://osinside.github.io/kiwi/building_images/build_wsl_container.html

```
zypper addrepo https://download.opensuse.org/repositories/Virtualization:/WSL/openSUSE_Tumbleweed/ WSL
zypper refresh

```
... Error. Reason: There is no repo description.

I removed the repo and installed latest fb-util-for-appx from Tubleweed. The I downloaded the wsl-appx from https://download.opensuse.org/repositories/Virtualization:/WSL/openSUSE_Tumbleweed/ and installed it with rpm.

But no AppxManifest.xml and no Distrolauncher-exe was installed. Where can I find it?

**Comment by schaefi** [comment]
Hi, there is an example build here:

* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:tumbleweed/test-image-wsl
* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:tumbleweed/wsl-appx

We packaged our own version of wsl-appx for this integration test. It will probably not fit your use case but should give you the needed information

**Comment by schaefi** [comment]
I'm closing this one as there is no further feedback. I assume the provided information was helpful
