### ISSUE TITLE
Use DownloadInAdvance mode for zypper

### ISSUE THREAD

**Issue by davidcassany** [OSInside/kiwi#1789]
## Problem description

In relation to https://build.opensuse.org/request/show/883228 and other upcoming zypper changes (to make use of librpm on single transaction operations) there is the possibility that file triggers start being used. In order to ensure zypper behaves consistently even when the underlying rpm is not including the mentioned patch `DownloadInAdvance` mode should be used, this way the transaction happens as a whole and with the upcoming zypper changes zypper will still be capable to handle the file triggers.

Due to an old Yast related hack zypper defaults to `DownloadAsNeeded` when `--root` flag is provided, which in turn it also disables file checks. We have been suggested to be explicit and always use `--download-in-advance` (or `commit.downloadmode` options in `zypp.conf`) mode in KIWI. 

## Expected behaviour

We run the installation of bootstrap packages in a single transaction, so first all packages are downloaded and then installed.

**Comment by schaefi** [comment]
sounds perfect to me :+1: I assume we have to create that change with respect to older versions of zypper which do not have the ```--download-in-advance``` feature. So just as a heads up, the implementation will most probably need to differentiate this with the help of ```CommandCapabilities.has_option_in_help(...)```

**Comment by davidcassany** [comment]
As far as I understand the `--download-in-advance` and the `commit.downloadmode` option in `zypp.conf` are available zypper options since quite a while. So at most we could check that if leap 15.0 already includes it. By the way, the zypper change will also land in SLE 15, however they do like we do (or we try to at least), there is a single zypper version for the whole SLE 15 stack no differences across SPs.

I just saw that there is no `--download-in-advance` option in `zypper install --help`, however there is 

```
--download <MODE>       Set the download-install mode. Available modes: only, in-advance,
                        in-heaps, as-needed Default: DownloadDefault
```

Probably the `--download-in-advance` is some sort of interpolation of it (like `--download-only` option) or probably it was just a misspell on rocket chat where they told me to use it.

**Comment by schaefi** [comment]
> I just saw that there is no --download-in-advance option in zypper install --help, however there is ```--download MODE```

ok that explains it. I was aware of the different download modes and you are right they exist for a very long time. The advise to NOT use in-advance was given my Michael Andres at the time of the implementation years ago. So probably something has changed.

In general I like the ```in-advance``` mode more because that is more transaction based, will have a speed increase, is less error faulty and allows for better error checking if there are any

**Comment by davidcassany** [comment]
> The advise to NOT use in-advance was given by Michael Andres at the time of the implementation years ago, it was never touched

Yes, Michael Andres told me today that zypper when using `--root` flag turns to `as-needed` mode. This is an old hack due to some Yast issue, he told me they might fix that too and suggested me to always use the in-advance mode for KIWI.

Anyway, all this is is just to be prepared in case packagers start using post transaction file triggers (all these rpm and zypper changes are to allow them), given they were not working up to now, there are none in SUSE's land nowadays. So we would be affected by these changes only for non suse based hosts using zypper to build suse image which include packages making use of file triggers... so this has pretty low impact, but since it is a low hanging fruit that might solve some hard to debug issues in future I think we should do it.

**Comment by schaefi** [comment]
Going to work on this one
