### ISSUE TITLE
Allow to specify target for archive element

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi#1794]
## Problem description

The current ```<archive>``` element does not allow to specify a target directory to unpack the archive
It would be a nice feature if this would be possible

```xml
<archive name="foo.tar.gz" target_dir="etc"/>
```

**Comment by davidcassany** [comment]
I think this also raised in on matrix chat with @rominf while trying to figure out strategies to build images with preloaded container templates that were previously created by another build.

I guess here the relevant loginc is to ensure the `target_dir` won't scape outside the target root

**Comment by Vogtinator** [comment]
There's also a use for the inverse: Specifying the prefix (or files) from the archive to extract. This is useful when you have tarballs which contain just a single directory, e.g. created by `mkdir -p directory/foo; tar -caf archive.tar.xz directory`. Currently those always extract as `/directory/foo`, with no way to strip the `/directory` prefix. Most automatically created tarballs like from GitHub releases or `obs_scm` are like that.

Maybe an option to override the uid/gid of extracted files would be useful as well.
