### ISSUE TITLE
Installation documentation has an old key

### ISSUE THREAD

**Issue by ellcs** [OSInside/kiwi#1799]
## Problem description

The installation documentation contains an expired key:

```
rpm -qi gpg-pubkey-74cbe823-* | gpg2
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   dsa1024 2009-05-04 [SC] [expires: 2020-10-09]
      F7E82012C74FD0B85F5334DC994B195474CBE823
```

Copied from: https://osinside.github.io/kiwi/installation.html#installation-from-obs

## Expected behaviour

Installation steps, including validation, work without errors. 

Thank you! :)

**Comment by dcermak** [comment]
I'm not sure if it's really worth investing in automating something that will break every other year. An automated warning would certainly be nice though, but I don't really know a simple way how this could be checked.

**Comment by schaefi** [comment]
We discussed this in the planning meeting and would like to change the docs in a way that we document the install
of kiwi as follows

```
$ sudo zypper--gpg-auto-import-keys install python3-kiwi
```

documenting the manual import of keys will go away

Thoughts ?

**Comment by schaefi** [comment]
working on it

**Comment by ellcs** [comment]
:tada: :tada:
