### ISSUE TITLE
Feature request: run debootstrap with --verbose

### ISSUE THREAD

**Issue by Finkregh** [OSInside/kiwi#1800]
## Problem description
i'd like to have deboostrap started with "--verbose"

## Expected behaviour
use kiwi with i.e. `--debug`, `deboostrap` is run with `--verbose`

## Steps to reproduce the behaviour
build any image

## OS and Software information
+ KIWI version: 9.23.16
+ Operating system: Ubuntu 18.04.5 LTS
+ OBS version: not involved

**Comment by schaefi** [comment]
good idea :+1:

**Comment by schaefi** [comment]
According to @davidcassany and his extensive testing on debootstrap, the --verbose option provides not much helpful information. The man page says it provides more information on download. This is good but does not help to prevent hiding of other errors.

So in addition to the verbose option we should check the caller code if we can identify if there is something preventing the full debootstrap output to be part of the log

**Comment by schaefi** [comment]
This looks resolved
