### ISSUE TITLE
RHEL/Fedora UEFI (signed EFI) is not set up correctly

### ISSUE THREAD

**Issue by Conan-Kudo** [OSInside/kiwi#1806]
## Problem description

KIWI does not detect and install signed EFI binaries for Shim and GRUB2 on Fedora when the legacy `shim.efi` binary path is missing. Some time ago, the EFI binaries changed to be `shim<efiarch>.efi` in `/boot/efi/EFI/<vendor>` in order to support multiarch setup for UEFI. In particular, that change was done for [supporting booting from 32-bit UEFI on x86_64](https://fedoraproject.org/wiki/Changes/32BitUefiSupport).

## OS and Software information
+ KIWI version: 9.23.22
+ Operating system: Fedora 34
+ OBS version: N/A

**Comment by schaefi** [comment]
I'll start to work on this one. First trying to build the integration test for v34 which should show us the issue

**Comment by schaefi** [comment]
@Conan-Kudo the fallback setup seems to still work on Fedora 34. I got the following:

```
[  188s] [ WARNING ]: 09:54:27 | --> Running fallback setup for shim secure boot efi image
[  188s] [ DEBUG   ]: 09:54:27 | EXEC: [cp /usr/src/packages/KIWI-oem/build/image-root/boot/efi/EFI/fedora/shim.efi /usr/src/packages/KIWI-oem/build/image-root/boot/efi/EFI/BOOT/bootx64.efi]
[  188s] [ DEBUG   ]: 09:54:27 | EXEC: [cp /usr/src/packages/KIWI-oem/build/image-root/boot/efi/EFI/fedora/grubx64.efi /usr/src/packages/KIWI-oem/build/image-root/boot/efi/EFI/BOOT/grubx64.efi]
```

So ```/boot/efi/EFI/fedora/shim.efi``` is still provided

What needs to be done to reproduce the new situation ?

Thanks

**Comment by schaefi** [comment]
For details see the build in:

* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:fedora/test-image-live-disk

I switched to Fedora 34 to reproduce the change

**Comment by schaefi** [comment]
shim is taken from here

```
[   66s] [ DEBUG   ]: 09:52:25 | bootstrap:  shim-x64                    x86_64 15.4-4                      Fedora_34 466 k
```

**Comment by Conan-Kudo** [comment]
Hmm, I was under the impression from @martinezjavier that the fallback path was gone, because he told me to stop using it in livecd-tools in https://github.com/livecd-tools/livecd-tools/pull/182.

**Comment by schaefi** [comment]
maybe @martinezjavier can clarify that part ? Thanks

**Comment by martinezjavier** [comment]
> Hmm, I was under the impression from @martinezjavier that the fallback path was gone, because he told me to stop using it in livecd-tools in [livecd-tools/livecd-tools#182](https://github.com/livecd-tools/livecd-tools/pull/182).

The fallback is still shipped by the `shim-x64` package as a backward compatibility since users may had installed a Fedora release before the `x64` / `ia32` split. But still I think is better to use `shimx64.efi` to avoid having issues if `shim.efi` is deprecated at some point of if you want to add in the future support for machines that ship a 32-bit EFI firmware.

**Comment by schaefi** [comment]
Ah ok, that makes sense. So in the kiwi integration test we still say

```xml
<package name="shim"/>
```

which causes the installation of the mentioned ```shim-x64```.

@martinezjavier could you instruct me about the package setup that avoids the installation of the package for backward compatibility but provides the shimx64.efi ?

Thanks

**Comment by martinezjavier** [comment]
@schaefi the same `shim-x64` package ships both `/boot/efi/EFI/fedora/shim.efi` and `/boot/efi/EFI/fedora/shimx64.efi`. The `shim-x64` package also `Provides: shim` and that's why your integration test is working, this was also done for backward compatibility.

**Comment by schaefi** [comment]
ok, got it, thanks
