### ISSUE TITLE
Trigger the CI in PRs from forked repositories.

### ISSUE THREAD

**Issue by davidcassany** [OSInside/kiwi#1808]
## Problem description

Looks like the CI is not triggered when there is a PR from a forked repository. See #1805 no tests were triggered and missing changes on unit tests were not discovered since a new PR from a branch was done (#1807)

## Expected behaviour

PRs from a forked repository should trigger the CI so we do not need to manually run the tests to verify they pass.

**Comment by schaefi** [comment]
I'm not sure if this is possible. The CI we are using with kiwi is gitlab and I currently don't think that it knows anything about forks. We would need to switch to github actions which would be not so much work but also on actions there are restrictions for forked repos for good reasons like exposing secrets

**Comment by davidcassany** [comment]
right, checking out a PR to a `custom_branch` can be done with `git fetch origin pull/<pr_ID>/head:custom_branch` regardless if the PR is from a fork or not.

**Comment by dcermak** [comment]
> I'm not sure if this is possible. The CI we are using with kiwi is gitlab and I currently don't think that it knows anything about forks. We would need to switch to github actions which would be not so much work but also on actions there are restrictions for forked repos for good reasons like exposing secrets

This is a long existing limitation of GitLab CI: https://gitlab.com/gitlab-org/gitlab/-/issues/5667


> right, checking out a PR to a `custom_branch` can be done with `git fetch origin pull/<pr_ID>/head:custom_branch` regardless if the PR is from a fork or not.

You could setup a github action that will checkout the PR and push it as a new branch into the kiwi repo. You'll probably not get the nice report in github's UI, but at least you'll get a run on gitlab.

**Comment by schaefi** [comment]
I have started to move CI tasks to github actions. Together with the "Fork pull request workflows from outside collaborators" setup this fixes the issue described here. Related to this report:

* #1913
