### ISSUE TITLE
Enable custom Application IDs in ISOs

### ISSUE THREAD

**Issue by davidcassany** [OSInside/kiwi#1810]
## Problem description

Currently in live images KIWI allows to customize `Volume ID` and `Publisher` fields of a generated ISO, however ISO supports a wider range of metadata fields. The problem seen in [bsc#1184581](https://bugzilla.suse.com/show_bug.cgi?id=1184581) is that the Volume ID is not sufficient to express all the data the developer wanted, mostly because it is restricted to 32 characters only.

As an alternative other fields that are not that constrained could be used, in particular Application ID (restricted to 128 characters) seams to be a good match for the purpose. I believe it would be good that KIWI allows to set a custom Application ID.

Currently KIWI include the MBR ID into the Application ID, I could not really figure out why, probably for debugging purposes back at the time all this part was coded?

I did the quick hack of adding random string as the Application ID to the xorriso call and all worked fine, EFI or BIOS booting as CROM or as a disk. I did not test with cdrtools but the implementation seams to be absolutely parallel to the xorriso implementation regarding this metadata attribute.

## Expected behaviour

There is a way to set a custom Application ID in KIWI ISOs

**Comment by schaefi** [comment]
> Currently KIWI include the MBR ID into the Application ID

This is an artifact from times when the custom initrd identified the device it belongs to by reading the Application ID. It would still be in use for images created using oemboot.

If we allow custom settings for the App ID in iso's this allows breaking the old oemboot/isoboot/pxeboot concept

I'm fine if we go forward here but we should at least document that the Application ID is used for the old custom initrds. I would also like to keep the existing concept if no App ID is specified by the user, such that we can stay backward compatible

**Comment by Conan-Kudo** [comment]
This would also be useful for Fedora since we'd want to set this. Not only should it be configurable from the XML, but also from the CLI, similar to the ask in #2588.
