### ISSUE TITLE
Prepare integration tests without interaction

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi#1811]
## Problem description

Some integration tests needs a selection at boot time in the grub menu or a selection of the install device if multiple are present

## Expected behaviour

We should go over all integration tests and make sure that no interaction is needed to let them run.

This is important for the function testing concept we want to implement based on openQA. When running through openQA such manual selections are painful and can be easily avoided

**Comment by davidcassany** [comment]
See some interactive tests listed here https://github.com/OSInside/kiwi/pull/1745#issuecomment-834237774

**Comment by schaefi** [comment]
working on it
