### ISSUE TITLE
[Documentation] Building in the Open Build Service: dead link

### ISSUE THREAD

**Issue by FroggyFlox** [OSInside/kiwi#1812]
## Problem description
While looking at the the documentation on _Building in the Open Build Service_ , @phillxnet and I noticed that the link to the SUSE Testing image on x86 on OBS--used as an example-- is unfortunately dead:
https://github.com/OSInside/kiwi/blob/master/doc/source/working_with_images/build_in_buildservice.rst#L20

## Expected behaviour
I personally directed myself to the _leap_ Testing image instead so the link could indeed point to:
https://build.opensuse.org/project/show/Virtualization:Appliances:Images:Testing_x86:leap

If this is a good example, I can take care of submitting a very simple PR pointing to the `Testing_x86:leap` package instead, or anything more appropriate.

Thanks!

**Comment by schaefi** [comment]
Thanks for catching this one. While looking at the broken link I also found some other inconsistencies in the documentation and started to fix them

**Comment by schaefi** [comment]
@FroggyFlox it would be great if you can build the docs from the pull request branch in #1817 and see if that fixes your issue and maybe if you see further changes or inconsistencies. To build the docs just checkout the kiwi git and call

```
tox -e doc
==> point your browser to doc/build/html/index.html
```

Thanks much

**Comment by FroggyFlox** [comment]
@schaefi, 
Thanks a lot for all these fixes; I certainly didn't think it would be leading to so many changes! I'm sorry I didn't have the time to get to testing your PR on time.

Thanks again to you and all other contributors here for creating such a great tool and being so responsive, informative, and helpful!
