### ISSUE TITLE
kiwi does not cleanup temporary kiwi_boot_root_copy.* directory

### ISSUE THREAD

**Issue by tong-da-wei** [OSInside/kiwi#1837]
## Problem description
After kiwi is cut out, a temporary directory is generated in the tmp directory. In versions earlier than kiwi-9-20-19, the temporary directory is cleared after kiwi is cut out. However, the temporary directory is not cleared after kiwi-9.20.20. As a result, a large amount of memory is consumed.
## Expected behaviour
No directory named kiwi_boot_root_copy.xxx exists in the /tmp directory of the root directory.
## Actual behavior
A directory named kiwi_boot_root_copy.xxx exists in the tmp directory, which occupies a large amount of memory.
## Steps to reproduce the behaviour
Execute the kiwi cropping function until the production is complete and view the files or directories in the tmp directory in the root directory.
## OS and Software information
+ KIWI version: 9.21.7
+ Operating system: linux

**Comment by tong-da-wei** [comment]
It seems that this submission was introduced:https://github.com/OSInside/kiwi/commit/c9b9025e435687e7817232706a51aee0449d19b8

**Comment by schaefi** [comment]
Thanks, can you confirm you are using a custom initrd based setup with a setting similar to ```<type ... boot="..." />``` in your XML description ? I'm asking to create a reproducer for this issue.

Thanks

**Comment by tong-da-wei** [comment]
Thanks，After the .iso file is created, view the tmp directory.
Thanks

**Comment by tong-da-wei** [comment]
We're using  <type image="pxe" filesystem="ext4" boot="pxeboot/linuximage"/>

**Comment by tong-da-wei** [comment]
It has been determined that the problem is caused by this commit, what is the impact if I roll back this commit?
https://github.com/OSInside/kiwi/commit/c7ed1cfc290a89a414b0109fafd3e4e39f30195b
Thanks

**Comment by snowliuping** [comment]
kiwi/builder/kis.py called prepare(), but it did not call cleanup().

**Comment by schaefi** [comment]
> It has been determined that the problem is caused by this commit, what is the impact if I roll back this commit?
> [c7ed1cf](https://github.com/OSInside/kiwi/commit/c7ed1cfc290a89a414b0109fafd3e4e39f30195b)
> Thanks

The commit you referenced was done to make sure the destructors (which among others cleans up data) are called by python at the right time. If all references to a class are gone python calls the destructor. In the kiwi code there were places where the destructor was called too early or never and that commit fixes this part. If you revert it you are getting back other issues like left over tmpdirs and umounts on still busy devices depending on the image type and configuration. So in short reverting this commit maybe solves a part of your issue but will bring back others

I'm currently busy with some other tasks but will come back to this one next. I think your estimation that the kis builder is missing the explicit cleanup call could be the right track

**Comment by tong-da-wei** [comment]
> > It has been determined that the problem is caused by this commit, what is the impact if I roll back this commit?
> > [c7ed1cf](https://github.com/OSInside/kiwi/commit/c7ed1cfc290a89a414b0109fafd3e4e39f30195b)
> > Thanks
> 
> The commit you referenced was done to make sure the destructors (which among others cleans up data) are called by python at the right time. If all references to a class are gone python calls the destructor. In the kiwi code there were places where the destructor was called too early or never and that commit fixes this part. If you revert it you are getting back other issues like left over tmpdirs and umounts on still busy devices depending on the image type and configuration. So in short reverting this commit maybe solves a part of your issue but will bring back others
> 
> I'm currently busy with some other tasks but will come back to this one next. I think your estimation that the kis builder is missing the explicit cleanup call could be the right track

Thank you. When can you fix the problem?

**Comment by tong-da-wei** [comment]
Adding the _del_ destructors function to the BootImageKiwi class solves the problem. Does this cause other problems?

**Comment by schaefi** [comment]
I'll come up with a pull request to fix this today

**Comment by tong-da-wei** [comment]
@schaefi 
So far, the problem has really been solved.
Thank ,very much for this restoration.
