### ISSUE TITLE
Regression: Unwanted GRUB_DISABLE_LINUX_UUID=true added to /etc/default/grub

### ISSUE THREAD

**Issue by geckolinux** [OSInside/kiwi#1842]
Hi there, I'm using the latest Kiwi 9.23.31 from OBS Virtualization:/Appliances:/Builder on an openSUSE Leap 15.3 VM to generate [ISOs that are also based on Leap 15.3](https://sourceforge.net/projects/geckolinux/files/Static/153.210606/). At some point since February of this year there has been a regression that is causing Kiwi to add the `GRUB_DISABLE_LINUX_UUID=true` parameter to `/etc/default/grub` on the live ISO. This is a problem for installing my custom spins with the Calamares installer, as described [here](https://github.com/calamares/calamares/issues/1719). Basically, it often leads to an unbootable system after installation, because it is using the wrong `/dev/sdX` device for the `root=` parameter in GRUB2. This appears to be a regression, as I've never had this problem before, and my most recent set of [published ISOs based on Leap 15.2](https://sourceforge.net/projects/geckolinux/files/Static/152.210223/) from February of this year don't have this issue. But I'm not sure if it's a change in Kiwi or something about Leap 15.3 compared to 15.2. I have compared the `/etc/grub.d/` directives between 15.2 and 15.3 and they are exactly the same, so it's not coming from there.

I'm able to work around this issue by adding `devicepersistency="by-uuid"` to my `config.xml`, for example:

` <type image="iso" primary="true" flags="overlay" hybrid="true" firmware="uefi" kernelcmdline="quiet splash" hybridpersistent_filesystem="ext4" hybridpersistent="true" devicepersistency="by-uuid" volid="GeckoLinux_STATIC_BareBones" mediacheck="true"/>`

So I'm not sure if this is actually a regression or a feature change or a documentation issue. Here's what I can find about the `GRUB_DISABLE_LINUX_UUID` variable:
- https://documentation.suse.com/kiwi/9/single-html/kiwi/index.html
> **devicepersistency=”by-uuid|by-label”:**
> 
> Specifies which method to use for persistent device names. This will affect all files written by kiwi that includes device references for example etc/fstab or the root= parameter in the kernel commandline. By default `by-uuid` is used
- https://github.com/OSInside/kiwi/blob/master/kiwi/bootloader/config/grub2.py
```
        if self.persistency_type != 'by-uuid':
            grub_default_entries['GRUB_DISABLE_LINUX_UUID'] = 'true'
```
So it appears that using UUID should be the default behavior and the `devicepersistency="by-uuid"` option shouldn't be needed. But maybe I'm wrong.

Here's the relevant snippet from the Kiwi build process: [build.txt](https://github.com/OSInside/kiwi/files/6613075/build.txt)
And here's the full Kiwi recipe [here](https://github.com/geckolinux/geckolinux-project/blob/geckolinux-release/GeckoLinux_STATIC_Plasma.tar.gz).

Thanks for looking into this!

**Comment by schaefi** [comment]
Sorry for the long delay.

You are so right. This seems to be a bug. The default device persistence setting is UUID, but this is not explicitly expressed. Therefore the comparison for ```if self.persistency_type != 'by-uuid':``` will apply in the default case which is wrong. 

I'm going to fix this such that only in case the other persistency type "by-label" is explicitly selected we disable UUID

Thanks for finding this, there will be a PR in a minute

**Comment by geckolinux** [comment]
Fantastic, thanks very much @schaefi !
