### ISSUE TITLE
baseCleanMount  deprecation kills built of Sles12sp4 pxe images on on Slep15sp1 build servers

### ISSUE THREAD

**Issue by ralhei** [OSInside/kiwi#1844]
## Problem description
The fact that the noop `baseCleanMount` bash function in `config/functions.sh` has been changed from a deprecation warning to an actual script exit prohibits the built of  pxe images on Slep15sp1. This is the case since version 9.23.35 and above. The last working version is 9.23.34.

Unfortunately we cannot upgrade OSes in order to keep other installed packages running reliably in a cluster of multiple-hundreds of hosts.

## Steps to reproduce the behaviour
We have a complex `config.xml` configuration, would need to spend time to strip it to the most simple version that can reproduce this. 

## OS and Software information
+ KIWI version: 9.23.35+
+ Operating system:  Sles15sp1
+ OBS version:  ??

**Comment by schaefi** [comment]
Could you give me further details on the scripts you are using which includes baseCleanMount ? Is this from pxe builds using custom kiwi initrd descriptions referenced via the ```<type ... boot="..." />``` in your kiwi XML description ?

I did not quite understand why the image descriptions you are using could not be adapted to no longer use obsolete(now deprecated) function calls ?

Thanks

**Comment by schaefi** [comment]
Any news on this one ? Thanks

**Comment by ralhei** [comment]
Sorry for the delay, I'll try to provide more details in the next two days.

**Comment by ralhei** [comment]
More details about what is happening:
The config.xml file contains the following 'type' definition for the pxe image:
```
  <preferences profiles="pxe">
    <type image="pxe" filesystem="xfs" boot="netboot/suse-SLES12" bootkernel="custom"/>
  </preferences>
```
In the kiwi log file I can find the following line:
```
DEBUG: 15:21:29 | EXEC: [cp /usr/share/kiwi/custom_boot/netboot/suse-SLES12/config.sh /home/ralph1/projects/sles12-sp4-agent/_build/kiwi_boot_root.ok4sn0d6/image/config.sh]
```
This `config.sh` file is the actual culprit (see the bottom, where it calls `baseCleanMount`) -- and it is really old, here are its contents:
```
#!/bin/bash
#================
# FILE          : config.sh
#----------------
# PROJECT       : openSUSE KIWI Image System
# COPYRIGHT     : (c) 2006 SUSE LINUX Products GmbH. All rights reserved
#               :
# AUTHOR        : Marcus Schaefer <ms@suse.de>
#               :
# BELONGS TO    : Operating System images
#               :
# DESCRIPTION   : configuration script for SUSE based
#               : operating systems
#               :
#               :
# STATUS        : BETA
#----------------
#======================================
# Functions...
#--------------------------------------
test -f /.kconfig && . /.kconfig
test -f /.profile && . /.profile

#======================================
# Greeting...
#--------------------------------------
echo "Configure image: [$kiwi_iname]..."

#======================================
#======================================
# Keep UTF-8 locale
#--------------------------------------
baseStripLocales \
    $(for i in $(echo $kiwi_language | tr "," " ");do echo -n "$i.utf8 ";done)
baseStripTranslations kiwi.mo

#======================================
# Umount kernel filesystems
#--------------------------------------
baseCleanMount

exit 0
```

I'm actually still starting to learn about kiwi, and took over this code from some colleague, so I'm not sure how to approach this. Should I modify my `type` declaration in `config.xml` ? Any help is really appreciated.

**Comment by schaefi** [comment]
Simply delete the line that says ```baseCleanMount```. This method is a noop for a long time and got deprecated now. It did nothing before so just deleting it from your config.sh script is a safe change that will not cause you any harm

**Comment by ralhei** [comment]
Since I don't know in advance on which of our many hosts the images will be built and I have little control of the installations on those machines I'm looking at possibilities to patch the `config.sh` (i.e. remove the call to `baseCleanMount` as you suggested) after the
```
DEBUG: 15:21:29 | EXEC: [cp /usr/share/kiwi/custom_boot/netboot/suse-SLES12/config.sh /home/ralph1/projects/sles12-sp4-agent/_build/kiwi_boot_root.ok4sn0d6/image/config.sh]
```
step has happened, i.e. to run e.g. `sed` on `/_build/kiwi_boot_root.ok4sn0d6/image/config.sh`.

Is there a way to intercept the build process at this stage? This seems to happen far later than the custom `config.sh` of my build configuration is executed, so I was wondering if there is a second chance to customize this step.

**Comment by ralhei** [comment]
We have decided to build kiwi image within docker containers where we can easily patch `/usr/share/kiwi/custom_boot/netboot/suse-SLES12/config.sh`. These containers are completely under our control so this makes it easier to handle this issue and avoids applying changes on centrally managed server.
Thanks for your help anyway.
