### ISSUE TITLE
Unable to build SLES12 images on kiwi running SLES15SP2 / rpm --initdb process hangs

### ISSUE THREAD

**Issue by PeterBarczi** [OSInside/kiwi#1846]
## Problem description
 - it is unable to build SLES12 images on kiwi running SLES15SP2
 - build hangs during bootstrap phase:
`[ INFO    ]: 14:06:36 | --> collection type: onlyRequired`
`[ INFO    ]: 14:06:36 | --> package: filesystem`
`[ INFO    ]: 14:06:36 | --> package: glibc-locale`
`[ INFO    ]: 14:06:36 | --> package: module-init-tools`
`[ INFO    ]: 14:06:36 | --> package: udev`
`[ INFO    ]: 14:06:36 | --> package: zypper`
`[ INFO    ]: Processing: [################                        ] 40%`

- rpmdb --initdb process is hanging
- after some investigation it seems that is caused by different rpm db location path, which differs between SLES12 & SLES15
- is there any workaroud for that? Thank you!

## Expected behaviour
Build SLES12 images via kiwi running on SLES15SP2.

## Steps to reproduce the behaviour
- Install latest SLES15SP2
- Install kiwi - python3-kiwi via OS repositories

## OS and Software information
+ KIWI version:  9.23.20
+ Operating system: SLES15SP2
+ OBS version:

**Comment by davidcassany** [comment]
@PeterBarczi yes the rpmdb path and changed between SLE15 and SLE12. Note that between SLE15 and SLE12 there is a huge gap and many pieces might not be backward compatible.

The best approach to build SLE12 images using KIWI is actually using a SLE12 host. So use a SLE12 host for SLE12 images to avoid incompatibilities. We make an effort to keep KIWI stable across service packs, but between major SLE versions is beyond our scope. It tends to become unmanageable building images cross major SLE versions, the differences between OSes is just too huge and core utilities such as rpm or zypper might present incompatibilities.

**Comment by PeterBarczi** [comment]
@davidcassany Thanks for clarification, we do it the way you described, just wanted to simplify the process and perform the building of images only via one host running SLES15..
