### ISSUE TITLE
kiwi creates vmdk with wrong ddb.adapterType for VMware guests

### ISSUE THREAD

**Issue by philptk** [OSInside/kiwi#1847]
## Problem description
We are creating VMware images with kiwi and the following config.xml:
`...`
`          <machine memory="2048" guestOS="sles12-64" HWversion="15">`
`              <vmdisk id="0" controller="pvscsi"/>`
`              <vmnic driver="vmxnet3" interface="0" mode="bridged"/>`
`              <vmdvd id="1" controller="ide"/>`
`          </machine>`
`...`

If the image is created now, the vmx correctly says pvscsi. This is important to get the intended driver pvscsi:
`...`
`scsi0.virtualDev` = "pvscsi"
`...`
But the vmdk also contains pvscsi. Basically this is working. According to vmware, however, it must always be lsilogic to allow disc extension.
`...`
`ddb.adapterType` = "pvscsi"

as a workaround we're creating our images with lsilogic in the config.xml
`...`
`          <machine memory="2048" guestOS="sles12-64" HWversion="15">`
`              <vmdisk id="0" controller="lsilogic"/>`
`              <vmnic driver="vmxnet3" interface="0" mode="bridged"/>`
`              <vmdvd id="1" controller="ide"/>`
`          </machine>`
`...`

after that we change the virtualDev in the vmx File.

`e.g.`
`sed -i "s/lsilogic/pvscsi/g" ${VMX_FILE_NAME_FULL}`

I guess all VMware customers are affected. 
Is there any other way to get pvscsi configured correctly without this workaround?

## OS and Software information
+ KIWI version:  9.21.23-3.30.2
+ Operating system: SLES15
+ OBS version: SLES 15-SP2

**Comment by schaefi** [comment]
So this weird behavior in kiwi about pvscsi is the result of https://github.com/OSInside/kiwi/pull/783

I'm not aware of any other procedure to munge this in and I agree with you that it's totally confusing. From my perspective the right place for a fix would be qemu.

I did not quite get why you need your workaround, because if you set pvscsi in kiwi it actually does what you do in your workaround. It builds with lsilogic and changes the adapter type to pvscsi in the metadata afterwards. Or did I miss the point ?

Thanks

**Comment by philptk** [comment]
Hi,

from my point of view no change in qemu is needed as the adapterType in the vmdk should **not** be set to pvscsi.
That's what VMware support told me.
But the value is set by kiwi manually after image creation.

The only difference between lsilogic and pvscsi should be the definition of the virtualDev in the vmx.
The vmdk should be similar.

Regards Philipp

**Comment by schaefi** [comment]
Ok, then let's do that. I'll come up with a PR next and would like to ask you to review/test it. I don't have access to VMware components and can only test through qemu. Thanks much

**Comment by schaefi** [comment]
@philptk did you had a chance to look at the pull request ? What do you think ? Thanks

**Comment by schaefi** [comment]
@philptk I'm afraid without feedback from your side I will not merge the change, since this is an environment I don't perform tests, your feedback is crucial for a change.

I'm going to close this issue and the associated pull request if there will be no further conversation.

Thanks

**Comment by philptk** [comment]
@schaefi Sorry, seems I've overlooked the last notification. 
Change seems to be valid from my point of view. 
But please be aware, that I've only very limited python knowledge. :-)

**Comment by schaefi** [comment]
Thanks, that's fine. It's great to get the feedback from a logic perspective. If that makes sense to you we can go ahead and merge the change. Thanks
