### ISSUE TITLE
Please add arch="xxx" to repository

### ISSUE THREAD

**Issue by MartinVerges** [OSInside/kiwi#1868]
## Problem description

I need a repository only for an architecture like x86. I can't add `arch="x86_64"` to the repository of my xml definition.

## Expected behaviour

Allow me to filter repository's based on the architecture to build for.

## Steps to reproduce the behaviour

Add a repository that can only be used for arch=xxx and build from a different arch.

```xml
        <repository type="rpm-md" alias="OSS_Leap_15_2" imageinclude="true" arch="x86_64">
                <source path="http://download.opensuse.org/distribution/leap/15.2/repo/oss/"/>
        </repository>
        <repository type="rpm-md" alias="OSS_Leap_15_2" imageinclude="true" arch="aarch64">
                <source path="https://download.opensuse.org/ports/aarch64/distribution/leap/15.2/repo/oss/"/>
        </repository>
```

## OS and Software information
+ KIWI version: KIWI (next generation) version 9.23.31
+ Operating system: opensuse leap 13.2

**Comment by Conan-Kudo** [comment]
You could just _add_ all of them, just give them unique aliases. It's not particularly harmful to do so.

**Comment by schaefi** [comment]
right, the repo definition just gives kiwi (to be more precise the package manager) a source of information. Depending on the host architecture and the dependency solver result from the package manager the respective packages are fetched from the repos. As @Conan-Kudo said you can add all repos for all archs you want to build images for and it will not harm your build for a particular architecture
