### ISSUE TITLE
Avoid default use of `NamedTemporaryFile()` for big files

### ISSUE THREAD

**Issue by davidcassany** [OSInside/kiwi#1870]
## Problem description

`NamedTemporaryFile()` is likely to place files in `/tmp` and this temporary directory is curretly mounted on tmpfs in some distros,  including Fedora, openSUSE, etc. Using `/tmp` for huge temporary files (e.g. filesystem images) is likely to consume all the available space.

## Expected behaviour

In KIWI there should be a criteria about how to make use of `NamedTemporaryFiles` so that we can control big files are not placed over tmpfs filesystems. #1869 fixes it for live images, however temporary files are used in places, the same error is likely to appear for other use cases.

Related to #1866

**Comment by schaefi** [comment]
Hmm, this won't be easy to find across the entire code which NamedTemporaryFiles are "small" and which can grow "big"
So we need to go over the code and fix this one by one

**Comment by davidcassany** [comment]
Yes I agree this is not simple to fix. One option would be to tweak the default via environment variables, from [python docs](https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp):

> If dir is not None, the file will be created in that directory; otherwise, a default directory is used. The default directory is chosen from a platform-dependent list, but the user of the application can control the directory location by setting the TMPDIR, TEMP or TMP environment variables.

So we could eventually set an environment variable on KIWI run so all temporary files (that are depending on `mkstemp`, which is the case for `TemporaryFile`) are placed to `/var/tmp` (or any other folder of our choice). So that we could revert #1869 and control it in a single place. I am not a fan of using environment variables for this sort of things, since I find it pretty obscure, but it is the only idea that came to my mind that does not force us to go over the code and argue which should be modify and which not.

**Comment by Conan-Kudo** [comment]
We could also just always use `/var/tmp` for everything. There's no technical reason to use `/tmp` for anything if we want it to be in `/var/tmp` for big stuff. Little stuff can go there too.

**Comment by schaefi** [comment]
> We could also just always use /var/tmp for everything

I like this idea

**Comment by schaefi** [comment]
From the discussion on the community meeting:

* Create a new namespace to handle temporary files e.g KiwiNamedTemporaryFile
* In that namespace set /var/tmp to be the default location, eventually also set a default prefix if possible.
  Details: https://docs.python.org/3/library/tempfile.html#tempfile.tempdir
* Allow to overwrite the default location by a command line option

**Comment by schaefi** [comment]
I will work on this now
