### ISSUE TITLE
KIWI creates weird folder in /boot/efi

### ISSUE THREAD

**Issue by Vogtinator** [OSInside/kiwi#1874]
I didn't actually run the built image, but I noticed this output during build of an image for Rock64:

```
[ 1199s] [ DEBUG   ]: 08:26:44 | EXEC: [bash -c strings /usr/src/packages/KIWI-oem/build/image-root/usr/share/efi/aarch64/grub.efi | grep EFI\/]
[ 1199s] [ DEBUG   ]: 08:26:45 | EXEC: [mkdir -p /tmp/kiwi_mount_manager.395u6ibu/boot/efi/(no output on stdout)]
[ 1200s] [ INFO    ]: 08:26:45 | Copying /usr/src/packages/KIWI-oem/build/image-root/boot/efi/EFI/BOOT/grub.cfg -> /tmp/kiwi_mount_manager.395u6ibu/boot/efi/(no output on stdout)/grub.cfg to be found by EFI
```

The `(no output on stdout)` part looks wrong...

**Comment by davidcassany** [comment]
This should have been already fixed in https://github.com/OSInside/kiwi/pull/1825 few weeks ago, could you point me in which build did you saw that? Since v9.23.32 this should have been fixed. I am afraid we might miss looked it for 15.3 series.

**Comment by Vogtinator** [comment]
> I guess you saw that on Factory (where we have v9.23.31 at the moment). Next update in Factory will fix it.

Indeed. There doesn't seem to be any active submission to TW currently, the version in the devel prj is a month old.

**Comment by schaefi** [comment]
I have done a submission to Virt:App:Builder last Thursday and am just waiting for the auto submit to Factory.
There is also an open PR which I think needs clarification first (#1877) which is the reason why I did not create a manual SR to factory right now

**Comment by Vogtinator** [comment]
> I have done a submission to Virt:App:Builder last Thursday and am just waiting for the auto submit to Factory.

Why wait for that? All it does is wait for seven days and then create a request, so it's just an unneccessary delay.

**Comment by Vogtinator** [comment]
> > I have done a submission to Virt:App:Builder last Thursday and am just waiting for the auto submit to Factory.
> 
> Why wait for that? All it does is wait for seven days and then create a request, so it's just an unneccessary delay.

And this delay accumulates, which meant that kiwi in TW was about two months out of date: https://build.opensuse.org/request/show/905081
