### ISSUE TITLE
kernel commandline is truncated when it contains 'root='

### ISSUE THREAD

**Issue by rjschwei** [OSInside/kiwi#1875]
## Problem description
When the `kernelcmdline` attribute contains `root=` to set the root device kiwi will truncat the command line written to /etc/default/grub and any command line arguments given after root= will be omitted from `GRUB_CMDLINE_LINUX_DEFAULT`

## Expected behaviour
No truncation. All specified kernel command line arguments form the XML should be added to `GRUB_CMDLINE_LINUX_DEFAULT`

## Steps to reproduce the behaviour
Build an image with `root=` and some argument after in the `kernelcmdline` attribute. The resulting image will hav ethe settings after `root=` missing in `/etc/default/grub`

## OS and Software information
+ KIWI version: 
+ Operating system: SLES 15 SP3
+ OBS version:

**Comment by schaefi** [comment]
@rjschwei I've created a PR to fix this and also tested it on the Oracle image cmdline setting. For me it looks good. Would you mind to double check ? Thanks
