### ISSUE TITLE
guestOS type is "Other OS" by default and not configurable

### ISSUE THREAD

**Issue by koteswara-kelam** [OSInside/kiwi#1888]
## Problem description
I generated centos ova using kiwi-ng and when I deploy ova, the guestOS type is "Other OS". How to configure it to "CentOS" in config.xml? which tag I should use?

## OS and Software information
+ KIWI version: 
+ Operating system: 
+ OBS version:

**Comment by schaefi** [comment]
It should be configurable. See here for an example in the docs:

*  https://osinside.github.io/kiwi/building_images/build_simple_disk.html?highlight=guestos

Does this work ?

**Comment by koteswara-kelam** [comment]
I tried <machine guestOS="centos8_64Guest"></machine> but it was not reflected in "Edit setting" of VM in vcenter,
It comes as Guest OS=Linux, Guest OS Version=Other Linux(64-bit)

**Comment by schaefi** [comment]
You can get that info from here

* https://vmware.github.io/vsphere-automation-sdk-java/vsphere/6.5.0/vsphereautomation-client-sdk/com/vmware/vcenter/vm/GuestOS.html

For centos you can set

```
guestOS="CentOS 7 (64-bit)"
```

If this does not work as you expect please get in contact with the VMware folks

Hope that helps
