### ISSUE TITLE
Derived images

### ISSUE THREAD

**Issue by t-ru** [OSInside/kiwi#1895]
## Problem description
Hello,

I want to build images for 

- multiple plattforms (e.g. vmware, azure, gce) and 
- with multiple usage type (different packages)

I want to reduce copy&paste code.

My idea is:

- Step 1: create a base image description an run kiwi-ng system prepare
- Step 2: create a plattform image description (e.g. vmware, azure, ...) and run kiwi-ng system prepare on result from Step 1
- Step 3: create a usage type description (e.g. nginx, mariadb) and  and run kiwi-ng system prepare on result from Step 2

Is this possible?

Is there a better approach?

## OS and Software information
+ KIWI version: 
+ Operating system: 
+ OBS version:

**Comment by schaefi** [comment]
I'll follow up on this one soon, stay tuned ...

**Comment by schaefi** [comment]
Reading your use case I think you have two options:

1. Make use of profiles and architecture specifications
2. Make use of the new stackbuild plugin

With the 1. approach you would write image descriptions such that you can differentiate by profile. In The public cloud team we have a similar use case were we create images for different CSPs (cloud service providers) and architectures. Let me explain by an example:

```xml
<image ...>
    ...
    <profiles>
        <profile name="Azure" description="Azure Guest Image"/>
        <profile name="EC2-HVM" description="EC2 HVM Guest Image"/>
        <profile name="GCE" description="GCE Guest Image"/>
        <profile name="OCI" description="OCI Guest Image"/>
    </profiles>
    <preferences>
        basic settings that applies to all targets
    </preferences>
    <preferences profiles="Azure">
        settings only for Azure
    </preferences>
    <packages type="image" profiles="Azure">
        <archive name="azure-root.tar.gz"/>
        <package name="azure-cli"/>
    </packages>
    ...and so on
    <packages ...>
        <package name="grub2-x86_64-efi" arch="x86_64"/>
        <package name="grub2-arm64-efi" arch="aarch64"/>
    </packages>
</image>
```

The above hopefully helps to explain what I meant. Regarding different architectures the assumption is made that the target in your case e.g VMware should behave the same no matter if it's x86_64 or aarch64. In this case you should be able to differentiate packages by architecture but keep the behavior. If the behavior is also different my advise would be an arch profile

From a building perspective you would call

```
$ sudo kiwi-ng --profile Azure system build ...
```

**Comment by schaefi** [comment]
If the 1. approach is not suitable you could think of using the stackbuild plugin.

Please note this is new stuff. So there is a new plugin for kiwi

```
https://pypi.org/project/kiwi-stackbuild-plugin
```

if you install this from pip you get two new commands in kiwi

```
kiwi-ng system stash
kiwi-ng system stackbuild
```

The stackbuild plugin allows to store and reuse KIWI built root-trees as OCI containers.

That way you can preserve stateful information of your root trees and can stack them as you see fit

From a processing perspective this would look like this. Bear with me the below is from a presentation I'm currently
preparing, it's not complete

```
sudo kiwi-ng system build \
        --description kiwi/build-tests/x86/tumbleweed/test-image-MicroOS/ \
        --set-repo http://download.opensuse.org/tumbleweed/repo/oss \
        --target-dir /tmp/myimage

    sudo kiwi-ng system stash \
        --root /tmp/myimage/build/image-root \
        --container-name tw-appliance

    sudo podman images
  
    sudo podman login
    sudo podman push tw-appliance \
        docker://docker.io/schaefi/tw-appliance:latest

    https://hub.docker.com/repositories
```

So the above process allows you to stash a state of an image root tree and store it in a container registry.
You can now re-use this data in stackbuild

```
sudo kiwi-ng system stackbuild \
        --stash tw-appliance \
        --from-registry docker.io/schaefi \
        --description /some/description/on/top/of/a/stash \
        --target-dir /tmp/myimage
```

That way you can stack together whatever you want. But be careful kiwi does not check if the stacked components really play well together

**Comment by schaefi** [comment]
I hope this information is helpful. I kept it relatively rough and high-level. Let me know if you have questions.

Thanks

**Comment by t-ru** [comment]
Hello schaefi,

**approach 1**

This approach I used in former times.  I need to build:

os: sles and sles4sap
plattforms: vmware and azure
usage types:
- sap-as (sap application server)
- sap-db-hdb (sap hana db server)
- sap-db (sap maxdb server)
- sap-db-ase (sap ase db server)
- sap-db-ora (sap oracle db server)

2 (os) x 2 (plattform) x 5 (usage types) = 20 possible combinations
20 combinations are 20 kiwi profiles.

20 profiles in 1 description and with 1 config.sh... unmaintainable... the hell... 

Is reusing in config.sh of code possible? no
Is reusing of config in kiwi.xml possible? no
Are include files in config.xml possible? no

This approach is copy&paste. If a new SP will be released... copy & paste.
I now the images of suse cloud team. Especially I check the different azure images of sles4sap.
It is clear to see that they are copy&paste. Configured things in one image, are missing in an other images.


**Approach 2**

As the result I need a vmware or azure image. is this possible with stackbuild-plugin? or is the result every a oci container.
```
zypper install python38-pip
pip install  kiwi-stackbuild-plugin
kiwi-ng system stash --list

[ ERROR   ]: 16:12:58 | Unexpected error:
Traceback (most recent call last):
  File "/bin/kiwi-ng", line 33, in <module>
    sys.exit(load_entry_point('kiwi==9.23.49', 'console_scripts', 'kiwi-ng')())
  File "/usr/lib/python3.8/site-packages/kiwi/kiwi.py", line 68, in main
    App()
  File "/usr/lib/python3.8/site-packages/kiwi/app.py", line 35, in __init__
    task_class().process()
  File "/usr/local/lib/python3.8/site-packages/kiwi_stackbuild_plugin/tasks/system_stash.py", line 78, in process
    os.listdir(StackBuildDefaults.get_stash_home())
FileNotFoundError: [Errno 2] No such file or directory: '/root/.config/kiwi_stash'

```

**Comment by schaefi** [comment]
ok, I see your problem of maintaining. In this case the following project might be helpful:

* https://github.com/SUSE-Enceladus/keg

Also see the docs:

* https://documentation.suse.com/keg/1/single-html/keg/index.html

**Comment by schaefi** [comment]
>mkdir /root/.config/kiwi_stash
>... solves the problem

God, yeah it's new stuff... will fix

**Comment by schaefi** [comment]
> As the result I need a vmware or azure image. is this possible with stackbuild-plugin? or is the result every a oci container?

The container stores the root tree, basically the result of the "kiwi-ng system prepare --root /the/new/root-tree" You can build any target from this tree

But I think the keg concept fits better to your maintenance problem

**Comment by schaefi** [comment]
> > mkdir /root/.config/kiwi_stash
> > ... solves the problem
> 
> God, yeah it's new stuff... will fix, thanks :)

done in 1.0.4, available in a few seconds

**Comment by schaefi** [comment]
So the idea with the stackbuild process is to preserve root-tree's as containers and you can re-use and stack them. However this only makes sense to retain a certain state of an OS root tree in a registry. You case is the typical maintenance problem of how to deal with my XXX image descriptions. A lot of data is the same but there is this little change needed for vmware, and this little change for something else but 80% are still the same. For this reason we implemented keg which allows to store the description in a way that you can prevent the repetition and maintenance becomes much easier. It's work in the beginning but it pays of later.

We are also currently moving our descriptions into keg-recipes

**Comment by t-ru** [comment]
> > As the result I need a vmware or azure image. is this possible with stackbuild-plugin? or is the result every a oci container?
> 
> The container stores the root tree, basically the result of the "kiwi-ng system prepare --root /the/new/root-tree" You can build any target from this tree
> 
> But I think the keg concept fits better to your maintenance problem

I don't think. If I use keg I need to start from beginning. I need to define all from scratch.

**Comment by schaefi** [comment]
yes it's some work, we also suffer from it. I'm sorry I have not more ideas available right now

**Comment by t-ru** [comment]
With stash/stackbuild it's only possible to reuse a image one time.

My idea:

- sles-15-3: description contains only the bootstrap files
- sles-15-3.plattform: description contains only kernel, plattform specific files
- sles-15-3.plattform.minimal:  description contains minimal packages
- sles-15-3.plattform.usage-type: description contains packages, disk definition, config.sh, ...
-
build 1:
kiwi-ng --profile=default system prepare --description=sles-15-3 --root=/tmp/myimage

build 2:
kiwi-ng --profile=default system prepare --description=sles-15-3.plattform --root=/tmp/myimage --allow-existing-root

build 3:
kiwi-ng --profile=default system prepare --description=sles-15-3.minimal --root=/tmp/myimage --allow-existing-root

build 4:
kiwi-ng --profile=default system prepare --description=sles-15-3.usage-type --root=/tmp/myimage --allow-existing-root
kiwi-ng --profile=default system create....

Is this possible?

**Comment by schaefi** [comment]
I think this approach will work if you do it as an atomic operation. Meaning the build of ```sle-15-3.vmware``` consists out of four steps:

1. kiwi-ng --profile=default
2. kiwi-ng --profile=sles
3. kiwi-ng --profile=vmware
4. kiwi-ng --profile=sles-vmware

If you do it that way I don't see a problem.

If you plan to keep the contents of ```--root=/kiwi-build/stack/root``` and build other images (not sle-15-3.vmware) using this root tree then I would expect problems sooner or later because you can't be sure if the root-tree is suitable. There is also potential for unknown side effects due to data in the root-tree you don't expect or was added "somehow"

> With stash/stackbuild it's only possible to reuse a image one time.

Not with the version 1.0.5 that I pushed out recently. If you like to do the above
with stash/stackbuild it would look like the following

```
kiwi-ng --profile=default ... --root=/kiwi-build/stack/sle-15-3-bootstrap
kiwi-ng system stash --root /kiwi-build/stack/sle-15-3-bootstrap --container-name sle153-bootstrap

kiwi-ng --profile=sles ... --root=/kiwi-build/stack/sle-15-3-product
kiwi-ng system stash --root /kiwi-build/stack/sle-15-3-product --container-name sle153-product

kiwi-ng --profile=vmware ... --root=/kiwi-build/stack/sle-15-3-platform
kiwi-ng system stash --root /kiwi-build/stack/sle-15-3-platform --container-name sle153-platform
```

In your local container registry you will now find the stashes registered

```
podman images
```

You can now decide to work with them as local registered containers or push them to the registry.
I personally would push them and fetch/maintain them as needed. Once they are pushed you
also free yourself from keeping the local stashes around and can delete them if you like

```
sudo podman login
sudo podman push  sle153-bootstrap docker://docker.io/.../sle153-bootstrap:latest
```

On top of the data you could now stackbuild your image

```
kiwi-ng --profile=sles-vmware system stackbuild \
    --stash sle153-bootstrap \
    --stash sle153-product \
    --stash sle153-platform \
    --from-registry docker.io/... \
    --description=...sle-15-3.vmware \
    --target-dir /tmp/my_vmware_image
```

The stackbuild command will fetch the given stashes either from the given registry or from your local registry if not registry was specified. It will then mount the stash rootfs and create a root tree from it. The root tree is created using rsync from the mounted stashes. The result tree is the combined end result of three rsync operations in the order of the given --stash options. This ends in the same you did with the prepare calls. On top of the tree the actual image build starts.

You can repeat that as often as you like and you don't have to care for your local root tree because stackbuild creates one for each build process. Building it that way always ensures the same end result and is deterministic. I think managing the stashes using a registry is also more comfortable than keeping the root-tree around.

Let me know what you think

**Comment by t-ru** [comment]
I tried this:

```
kiwi-ng --profile=default ... --root=/kiwi-build/stack/sle-15-3-bootstrap
kiwi-ng system stash --root /kiwi-build/stack/sle-15-3-bootstrap --container-name sle153-bootstrap

kiwi-ng --profile=sles ... --root=/kiwi-build/stack/sle-15-3-product
kiwi-ng system stash --root /kiwi-build/stack/sle-15-3-product --container-name sle153-product

kiwi-ng --profile=vmware ... --root=/kiwi-build/stack/sle-15-3-platform
kiwi-ng system stash --root /kiwi-build/stack/sle-15-3-platform --container-name sle153-platform
```

I tried it out. With this procedure stacking is partially possible. Requirement is:

- image descriptions contains a bootstrap section (packages filesystem, glib-locale, zypper) AND
- the product description (SLES, SLES4SAP)

**Comment by schaefi** [comment]
ok, so you would consider the stash/stackbuild an option to solve your issue ?

**Comment by schaefi** [comment]
@t-ru maybe also interesting in this regard is the new include feature:

* https://osinside.github.io/kiwi/image_description/elements.html#include

With that information I'm closing the issue and hope this is ok for you ? There are several opportunities which we have discussed and I assume you have decided for one or the other or something completely different :) If there is more that needs attention please open a new issue.

Thanks much
