### ISSUE TITLE
Support for LUKS2

### ISSUE THREAD

**Issue by Vogtinator** [OSInside/kiwi#1898]
Some time ago, cryptsetup introduced the new LUKS2 format which is very similar to LUKS1. It's the upstream default, but some distros (like openSUSE) use LUKS1 as default. For Tumbleweed this is about to change.

GRUB 2.06 supports booting from LUKS2 (though there are a few bugs, I'm working on fixes currently), but the `luks2` module needs to be included. FWICT, this isn't listed in `get_grub_basic_modules` yet.

It would be nice if kiwi also allows specifying whether to use LUKS1 or LUKS2.

**Comment by schaefi** [comment]
Hi, thanks for the info

Can luks and luks2 co-exist in a grub image ?

The list you mentioned is only taken into account if kiwi can't find a pre-build grub module by the distro and decide to build its own. That's why I'm asking

Thanks

**Comment by schaefi** [comment]
Do we need to differentiate on the cryptsetup level between the two formats or is this something decided when building the cryptsetup package ?

**Comment by Vogtinator** [comment]
> Can luks and luks2 co-exist in a grub image ?

Yep

> The list you mentioned is only taken into account if kiwi can't find a pre-build grub module by the distro and decide to build its own. That's why I'm asking

There are three different paths:
1. EFI + Secure boot: Use pre-built grub.efi. That will include `luks2` in the future
2. EFI without secure boot: Kiwi calls `grub2-mkimage` and needs to make sure that `luks2` is included as well
3. BIOS boot: Kiwi calls `grub2-mkimage` and needs to make sure that `luks2` is included as well

> Do we need to differentiate on the cryptsetup level between the two formats or is this hard wired when building the cryptsetup package ?

The package only sets the default LUKS version, which is used when `--type` isn't given to `cryptsetup luksFormat`.

**Comment by schaefi** [comment]
Thanks

**Comment by rasentry** [comment]
Is there any chance choosing luks version feature will be implemented?

**Comment by schaefi** [comment]
I would say we have to offer this as there will be distributions with luks and luks2 co-existing. Looking at this is on my list, but I'm afraid my time is limited at the moment so I can't make any promises on the timeline.

Implementation should be relatively straight forward. As I need encryption to work on Debian for the job in the near future I will definitely look at it.

Is there any urgency for this on your side, deadlines, etc ?

Thanks

**Comment by rasentry** [comment]
Nothing critical, can live with that a couple months.
Thank you for your time and your work!

**Comment by schaefi** [comment]
@rasentry JFI this topic was also brought on the agenda here at work. Thus I definitely will work on support for luks2 within the next three months. My employer also wants to use "--integrity" which is supported with luks2 (dm_integrity) only afaik

@Vogtinator if you have further topics, requirements for luks2, let's summarize them here

Thanks much
