### ISSUE TITLE
The initrd generated by kiwi tailoring does not generate the dependency of the modules.dep driver. As a result, the product root cut cannot be executed.

### ISSUE THREAD

**Issue by AnHeBridgeNorth** [OSInside/kiwi#1904]
## Problem description
kiwi cuts out unnecessary drivers and dependent drivers. When the kernel driver is cut out, the depmod command is invoked to generate a module.dep file.
When the customized driver is copied to the extra directory of the kernel, depmod is not called and the modules.dep file is not updated. As a result, the dependency of the customized driver in the initrd module.dep is generated.

## Expected behaviour
Driver dependencies are re-recorded in the modules.dep file.

## Actual behavior
Driver dependencies are not recorded in the modules.dep file.

## Steps to reproduce the behaviour
During KIWI production, customize the dependency between drivers. After the production is complete, view the modules.dep file.

## OS and Software information
+ KIWI version: 9.21.7
+ Operating system: linux

**Comment by schaefi** [comment]
any concerns, questions, feedback ?

**Comment by tong-da-wei** [comment]
I'm sorry. I was busy with other business a while ago and forgot to reply.
I think you should have misunderstood me. What I want to say is that kiwi generates a modules.dep file in the /usr/lib/modules/ directory structure during the tailoring process. This file records the dependencies between kernel drivers. If I change the system's default inter-kernel dependencies, or add my own kernel driver dependencies, the modules.dep file does not correctly record the kernel driver dependencies. If you also have the modules.dep file, I think you should have the same confusion, and if you don't have the modules.dep file, turn it off.

**Comment by schaefi** [comment]
> I'm sorry. I was busy with other business a while ago and forgot to reply.

No problem we are all in the same boat with this :)

> I think you should have misunderstood me. What I want to say is that kiwi generates a modules.dep file in the 
/usr/lib/modules/

Hmm, I don't see where kiwi would do that ? To my understanding modules.dep belongs to the kernel and is
provided by the respective kernel package: e.g /lib/modules/5.3.18-lp152.78-default/modules.dep on kernel-default in leap

>This file records the dependencies between kernel drivers. If I change the system's default inter-kernel dependencies, or add >my own kernel driver dependencies, the modules.dep file does not correctly record the kernel driver dependencies.

yep you are completely right. However, I don't see where kiwi would touch this file. imho it would be a mistake if kiwi messes with the modules.dep

Can you point to the place were kiwi modifies the module dependencies ?

Thanks

**Comment by AnHeBridgeNorth** [comment]
I found nothing in the kiwi source code related to kernel module dependencies. My understanding is that the modules.dep file needs to be updated by calling the depmod command. My idea was if I could add this call command after kiwi has finished cropping to do this. I don't know if that's possible.

**Comment by schaefi** [comment]
ok, so it looks to me your goal is to bring in your own kernel module into the image build with the problem that modules.dep was not properly updated. I think there are the following solutions:

1. Package your kernel module as kmod package. Installation of the package when done in the way your target distribution wants it will call depmod to add the dependencies. I would consider this the most clean solution

2. Your module is build in a custom way like some of the proprietary stuff. In this case you can always add a ```depmod -a``` call as part of the kiwi ```config.sh``` file.

option 2) follows mostly the idea you raised
