### ISSUE TITLE
Building for CentOS Stream 9

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi#1920]
## Description

CentOS Stream 9 is approaching. @Conan-Kudo would like to share his thoughts about the repository situation and maybe work areas for kiwi how to consume the repos and build for this target.

**Comment by schaefi** [comment]
Takeaways from the meeting:

* Create a CentOS9 example description in the kiwi-descriptions repo

@Conan-Kudo which repos should we use to setup the image until it appears on the mirrors ?

**Comment by Conan-Kudo** [comment]
The ones I use in the example description I wrote for my talk at oSVC21 should work for now: https://github.com/datto/osvc21-kiwi-demo-descriptions/blob/fc01fde4a701aa74748d7f74573be5cefd8ed825/txz-build/config.xml#L24-L32

**Comment by Conan-Kudo** [comment]
Looks like mirrors are going to be set up tomorrow, if @adrianreber is to be believed: https://pagure.io/fedora-infra/ansible/pull-request/775

**Comment by Conan-Kudo** [comment]
The official mirror URLs are now available:

```xml
    <repository type="rpm-md" alias="CentOS9-CRB" sourcetype="metalink">
        <source path="metalink=https://mirrors.centos.org/metalink?repo=centos-crb-9-stream&amp;arch=x86_64"/>
    </repository>
    <repository type="rpm-md" alias="CentOS9-AppStream" sourcetype="metalink">
        <source path="https://mirrors.centos.org/metalink?repo=centos-appstream-9-stream&amp;arch=x86_64"/>
    </repository>
    <repository type="rpm-md" alias="CentOS9-BaseOS" sourcetype="metalink">
        <source path="metalink=https://mirrors.centos.org/metalink?repo=centos-baseos-9-stream&amp;arch=x86_64"/>
    </repository>
```

**Comment by Conan-Kudo** [comment]
The official mirror URLs are now available:

```xml
    <repository type="rpm-md" alias="CentOS9-CRB" sourcetype="metalink">
        <source path="https://mirrors.centos.org/metalink?repo=centos-crb-9-stream&amp;arch=x86_64"/>
    </repository>
    <repository type="rpm-md" alias="CentOS9-AppStream" sourcetype="metalink">
        <source path="https://mirrors.centos.org/metalink?repo=centos-appstream-9-stream&amp;arch=x86_64"/>
    </repository>
    <repository type="rpm-md" alias="CentOS9-BaseOS" sourcetype="metalink">
        <source path="https://mirrors.centos.org/metalink?repo=centos-baseos-9-stream&amp;arch=x86_64"/>
    </repository>
```

**Comment by schaefi** [comment]
Great thanks for the update, going to create and build

**Comment by schaefi** [comment]
@Conan-Kudo please find the centos 9 example description pushed out here:

* https://github.com/OSInside/kiwi-descriptions/tree/master/centos/x86_64/centos-09.0

The image supports Live and Virtual disk image types in bios mode

There are the following outstanding issues:

* No dracut-kiwi-* packages available in centos 9
  This will self heal as soon as obs adds centos 9 repos such that we can build the kiwi packages for it

* No grub2 x86_64 efi module package available
   It exists on Koji but was not published to the repos so far. I have a lot of other things to do and it would be nice to get some help in this regard. It probably just needs somebody pushing the publish button


Let me know what you think, thanks much

**Comment by Conan-Kudo** [comment]
> @Conan-Kudo please find the centos 9 example description pushed out here:
> 
> * https://github.com/OSInside/kiwi-descriptions/tree/master/centos/x86_64/centos-09.0
> 
> The image supports Live and Virtual disk image types in bios mode
> 
> There are the following outstanding issues:
> 
> * No dracut-kiwi-* packages available in centos 9
>   This will self heal as soon as obs adds centos 9 repos such that we can build the kiwi packages for it

Can you try to poke the OBS team to add CentOS Stream 9 to the build system?

> * No grub2 x86_64 efi module package available
>   It exists on Koji but was not published to the repos so far. I have a lot of other things to do and it would be nice to get some help in this regard. It probably just needs somebody pushing the publish button
> 

Bug filed: https://bugzilla.redhat.com/show_bug.cgi?id=2005037

**Comment by Conan-Kudo** [comment]
Fix incoming: https://gitlab.com/redhat/centos-stream/release-engineering/pungi-centos/-/merge_requests/169

**Comment by schaefi** [comment]
I have updated the public example from here

* https://github.com/OSInside/kiwi-descriptions/tree/master/centos/x86_64/centos-09.0

And added all the EFI/UEFI support back since the packages are now present. I build the appliance via

```
kiwi-ng --profile Virtual system boxbuild --box universal -- --description kiwi-descriptions/centos/x86_64/centos-09.0/ --target-dir /tmp/mytest-centos
```

And the result worked well for me

Thanks everybody
