### ISSUE TITLE
Unable to create pxe image

### ISSUE THREAD

**Issue by mmontecchi** [OSInside/kiwi#1923]
## Problem description
Hi,
following documentation I have an error running:
kiwi-ng --type pxe system build     --description kiwi/build-tests/x86/tumbleweed/test-image-pxe     --set-repo http://download.opensuse.org/tumbleweed/repo/oss     --target-dir /tmp/mypxe-result
The error is :
kiwing:~ # kiwi-ng --type pxe system build     --description kiwi/build-tests/x86/tumbleweed/test-image-pxe     --set-repo http://download.opensuse.org/tumbleweed/repo/oss     --target-dir /tmp/mypxe-result
[ INFO    ]: 21:59:53 | Reading runtime config file: '/etc/kiwi.yml'
[ INFO    ]: 21:59:53 | Loading XML description
[ INFO    ]: 21:59:53 | Support for XML markup available
[ ERROR   ]: 21:59:53 | KiwiTypeNotFound: build type pxe not found in [<kiwi.xml_parse.description object at 0x7f3598257b70>]

## OS and Software information
+ KIWI version: 
KIWI (next generation) version 9.23.20
+ Operating system: 
openSUSE 15.3
+ OBS version:

**Comment by schaefi** [comment]
Hi, yes I see the docs needs to be fixed. If you look at the appliance description you see that it uses profiles

```
<profiles>
    <profile name="Flat" description="Standard uncompressed pxe filesystem image"/>
    <profile name="Compressed" description="Compressed pxe filesystem image"/>
 </profiles>
```

None of the profiles are pre-selected so you need to select one in the kiwi-ng call. If you don't select one it ends with no 
type being specified and the respective error message. So to build this call

```
kiwi-ng --profile Flat system build \
    --description kiwi/build-tests/x86/tumbleweed/test-image-pxe \
    --set-repo http://download.opensuse.org/tumbleweed/repo/oss --target-dir /tmp/mypxe-result
```

or

```
kiwi-ng --profile Compressed system build \
    --description kiwi/build-tests/x86/tumbleweed/test-image-pxe \
    --set-repo http://download.opensuse.org/tumbleweed/repo/oss --target-dir /tmp/mypxe-result
```

I will fixup the docs and also the error message which includes a python reference object

Thanks
