### ISSUE TITLE
Add `$releasever` support

### ISSUE THREAD

**Issue by Conan-Kudo** [OSInside/kiwi#1927]
Currently, we set `--releasever 0` for DNF and Micro DNF in order to enable bootstrapping. However, in order to support leveraging the same description across different Fedora releases with templated repository URLs, we need to be able to pass a real value in from the command-line or the XML description to set this value. If not set, we should continue to set it to zero when the package manager supports `--releasever`.

**Comment by schaefi** [comment]
Looking into this one next

**Comment by schaefi** [comment]
I was thinking about the implementation and came across some questions.

The ```--releasever``` information is passed at the time the package manager should actually install something. This means at the time of the install the information about the release is relevant not before ? Is this correct ? Do you think it will be handled that way when other package managers will need it ? ```zypper --releasever=15.3 dup``` also does it at the time of the install

If you agree I would place the relesever information as part of the ```<preferences>``` section e.g

```xml
<preferences>
    <release_version>15.3</release_version>
    ...
</preferences>
```

@Conan-Kudo @davidcassany Thoughts ?

Thanks

**Comment by schaefi** [comment]
You can manage several ```<preferences>``` sections in kiwi and you can handle this also via ```<include>```. When kiwi works with the final set of ```<preferences>``` data it will dict merge the information. Thus in the end there can only be one information for ```release_version``` and the last one providing it will win. The way how the author of the image description structure the profiles, includes, number and content of preferences decides how this information will be used.

Thus from my perspective enough flexibility and the correct section.

But would be curios about your feedback. I'm not going to start coding before ;)

**Comment by Conan-Kudo** [comment]
@schaefi Control from preferences would be useful for Koji, I think, since @tkopecek will be able to (re)write the field in Koji. But I'd also like it to be controllable via the CLI to make it easy for it to be set without mangling the XML (especially for testing builds).

**Comment by tkopecek** [comment]
Yep, it seems possible to me that we can add our own `preferences` section to the end of the main config file. I'm a bit uneasy about confusion it could create. Multiple preferences sections in included files which could be overriden by something what will appear later (in completely different file). It is not a problem with the original design but now (with inclusion) it is a bit more error prone. Not sure what should be the right solution here as I'm not daily kiw user, so take my suggestions at a distance:
1) limit "preferences" (or all basic) node(s) children to only one apperance - e.g. multiple `preferences` but `release_version` can appear only once. Reject such input.
2) use some "protected" keyword on things which should be never overriden via following stanzas. Just warn about this behaviour.
3) keep the current behaviour and rely on release engineers to handle it on some process level. This looks to me like most fragile solution as it can't be automated and depends on some external knowledge.

**Comment by Conan-Kudo** [comment]
Preferences has an inheritance model, there's only one preferences per profile and a global preference. The profile preference "wins" over the global one. So if we're passing a profile, and the profile has a preferences section, just set it there. If there's no profile, we can set it at the global preference level.
