### ISSUE TITLE
Add support for setting GPG public key file paths for repositories

### ISSUE THREAD

**Issue by Conan-Kudo** [OSInside/kiwi#1928]
Currently, KIWI does not provide a way in the XML description to specify paths to GPG public key files so that the content can be verified for integrity before using it. This is dangerous for people building in less trusted environments (such as outside of the build system). At least for Debian and RPM package managers, there are ways to handle importing the GPG keys before processing repository content, and we should do so if the description has them configured.

This would likely involve downloading/copying the GPG key to temporary space that's mounted in the chroot so the in-chroot package manager can access them (either to trigger manual import for APT or to have them specified in the repo definition for DNF/MicroDNF/Zypper).

**Comment by schaefi** [comment]
This duplicates #1883
