### ISSUE TITLE
Ubuntu PXE images causing loop on dracut

### ISSUE THREAD

**Issue by ulkuderner** [OSInside/kiwi#1936]
## Problem description
When you would like to create ubuntu-focal based image an set installpxe="true" on config.xml images builds successfuly. But on the boot site dracut enters a loop then drops on emergency shell.

On kiwi debug boot:
dracut-initqueu: /bin/dracut/finished/wait.network.sh@(source): exit 1
dracut-initqueu: /lib/dracut-lib.sh@447(check_finished): return 1
..
dracut-initqueu: /bin/dracut-initqueue@30(): '[' -f /lib/dracut/hooks/initqueue/work ']'
dracut-initqueu: /bin/dracut-initqueue@34(): for job in $hookdir/initqueue/settled/*.sh
dracut-initqueu: /bin/dracut-initqueue@35(): '[' -e /lib/nethooks/hooks/initqueue/*.sh ']'
dracut-initqueu: /bin/dracut-initqueue@35(): break
dracut-initqueu: /bin/dracut-initqueue@40(): udevadm settle--timeout=0
dracut-initqueu: /bin/dracut-initqueue@42(): for job in $hookdir/initqueue/settled/*.sh
dracut-initqueu: /bin/dracut-initqueue@43(): '[' -e /lib/nethooks/hooks/initqueue/*.sh ']'
dracut-initqueu: /bin/dracut-initqueue@43(): break
dracut-initqueu: /bin/dracut-initqueue@48(): udevadm settle--timeout=0
dracut-initqueu: /bin/dracut-initqueue@51(): sleep 0.5
..
..
..

## Expected behaviour
After installing the kernel system needs to go install tui and download the image.

## Steps to reproduce the behaviour
create ubuntu-focal image with setting installpxe="ture"

## OS and Software information
+ KIWI version: KIWI (next generation) version 9.23.56
+ Operating system:  Debian 10.10
+ OBS version: -

**Comment by schaefi** [comment]
Looks like it loops on getting a network interface. With the provided information there is not much I can come up with to help. Kiwi uses the upstream dracut code for all of the network settings. I suggest you try the boot with:

```
rd.debug rd.shell rd.break=initqueue
```

This should drop you into a shell inside of the initrd and you maybe can dig into what's missing to get a network interface and an ip assigned

**Comment by schaefi** [comment]
Don't think there is much we can do on this end so far
