### ISSUE TITLE
Support grub2 with TPM support

### ISSUE THREAD

**Issue by msmeissn** [OSInside/kiwi#1947]
## Problem description

The recently release grub2 now contains TPM support. There are SUSE specific options to select between non-TPM and TPM based grub2 for creating an image.

## Expected behaviour

UEFI secureboot + TPM:

shim-install --suse-enable-tpm

non-secureboot EFI + tpm:

grub2-install --suse-enable-tpm

## OS and Software information
+ KIWI version: 
+ Operating system:  SLES 15 SP2 + SP3
+ OBS version:

**Comment by msmeissn** [comment]
The problem is that you cant easy detect  this if you build images for general purpose.

So an additional TPM option might be needed in the kiwi configuration.

(You also need to have it before you start the image, as it needs to have the right bootloader.)

Currently it is also directly in the grub2-x86_64-efi package besides the regular grub.efi, so you can decide based on that either.

We COULD split it out of the regular grub2 package, but this needs review from grub2 maintainer.

**Comment by schaefi** [comment]
Thanks for the details. I'll take a look how this can be included in a generic and open way such that we will have an opportunity to support the TPM support process the other distros might come up with. Since only suse has shim-install this will end up in a per distro support

@Conan-Kudo Do you have any insight about the TPM support in the RHEL/Fedora family ?

Thanks

**Comment by schaefi** [comment]
@msmeissn I have created a PR and would like to ask you to review that. I have several questions on the change which we need to clarify to avoid any breaking change. Thanks much

**Comment by msmeissn** [comment]
I think Red Hat enables TPM support by default in their grub2 packages. I checked CentOS 8 and it looks like that.

**Comment by schaefi** [comment]
ok, thanks for the feedback. In this case I think the issue self heals
