### ISSUE TITLE
Allow to copy files to containers from image description without archive  

### ISSUE THREAD

**Issue by fcrozat** [OSInside/kiwi#1953]
## Problem description
It is currently difficult to do the equivalent from Dockerfile
`COPY this_file / `
directly in kiwi image description.

This requires usage of "archive" or config.sh
## Expected behaviour
Allowing to specific directly files in the kiwi description to be copied to a specific location on the image.

**Comment by schaefi** [comment]
Hmm, why can't this be done with overlayfiles ?

The following is an example from some arbitrary image description

```
tree
.
├── appliance.kiwi
├── config.sh
├── disk.sh
└── root
    ├── etc
    │   ├── sysconfig
    │   │   └── network
    │   │       └── ifcfg-lan0
    │   └── udev
    │       └── rules.d
    │           └── 70-persistent-net.rules
    └── usr
        └── lib
            └── systemd
                └── system
                    ├── dracut_hostonly.service
                    └── grub_config.service
```
The files below root/ are copied (rsync) as they are into the image root tree

Any reason why you can't use this ?

**Comment by schaefi** [comment]
adding this now

**Comment by schaefi** [comment]
It took a long time, sorry for the delay but now there is a PR open to address this
