### ISSUE TITLE
Fedora test images have weird entries in /etc/os-release

### ISSUE THREAD

**Issue by dcermak** [OSInside/kiwi#1957]
## Problem description

`/etc/os-release` of the Fedora test images in https://build.opensuse.org/project/show/Virtualization:Appliances:Images:Testing_x86:fedora contains some weird values. For instance `ID` is set to `generic`, `HOME_URL` points to zombo.com and the privacy policy is linked to nsa.gov…

![image](https://user-images.githubusercontent.com/45594031/138712095-996f159f-2068-4271-9665-d5a770c90f2f.png)

## Expected behavior

`/etc/os-release` should match upstream:
```ShellSession
❯ cat /etc/os-release
NAME=Fedora
VERSION="34 (Thirty Four)"
ID=fedora
VERSION_ID=34
VERSION_CODENAME=""
PLATFORM_ID="platform:f34"
PRETTY_NAME="Fedora 34 (Thirty Four)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:34"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f34/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=34
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=34
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"

```

## Steps to reproduce the behavior

1. Boot https://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/Testing_x86:/fedora/images/kiwi-test-image-live-disk.x86_64-2.0.0-Disk-Build23.25.raw.xz
2. login as root
3. `. /etc/os-release && [[ "${ID}" = "fedora" ]]` yields `1`

## OS and Software information
+ KIWI version: 
+ Operating system: 
+ OBS version:

**Comment by dcermak** [comment]
We forgot to add this change to the Rawhide images.

**Comment by schaefi** [comment]
This is fixed and rolled out on Virtualization:Appliances:Images:Testing_x86:rawhide
