### ISSUE TITLE
Support for "this://" for repository paths

### ISSUE THREAD

**Issue by zohourih** [OSInside/kiwi#1964]
In original Kiwi (https://doc.opensuse.org/projects/kiwi/doc/, section 4.1.7), a "this://" keyword was provided that allowed settings repository paths based on relative path rather than full path (the latter being done using "dir://"). However, this functionality does not seem to have been ported over to Kiwi NG. Is there a way to achieve the same functionality with Kiwi NG, or are there any plans to add support for this functionality?

**Comment by schaefi** [comment]
You are right, this "this" uri type was not ported.

Just to put me right, the this:// path was basically a pointer to the directory which holds your image description. In the past people could use it in the repository section to point to a repo which they host as part of their image description.

This is what you would like to achieve correct ?

Thanks

**Comment by zohourih** [comment]
@schaefi Yes; specifically, this keyword provides us with the possibility of pointing to a local repository that gets pulled to a random location using a script, by using the path of the repository folder relative to the image description, and not having to keep track of the full path of the random location.

**Comment by Conan-Kudo** [comment]
We also going to be dropping `dir://` handler too, per #1926.

**Comment by zohourih** [comment]
Ah, well, that is not very good news. Will there be any alternative to achieve the same behavior?

**Comment by schaefi** [comment]
> Ah, well, that is not very good news. Will there be any alternative to achieve the same behavior?

Let's add something that brings a smile on your face :) First I have added the this:// type such that you can reference the repo living in your image description. We might consider to allow this uri type for other source locators in the future as well but so far it can only be used in a repo definition like in the following example

```xml
<repository>
    <source path="this://my_repo"/>
</repository>
```

**Comment by schaefi** [comment]
Regarding the information from @Conan-Kudo about the removal of ```rpm-dir``` in the future, this is correct and not a limitation of kiwi but something package managers will not support. Actually this is a good change because metadata for a repo should not be calculated by the package manager.

For you this means you need to create repo metadata but this is not a big issue imho. Assuming you have the directory

```
my_repo/package_a.rpm
my_repo/package_b.rpm
```

you can go in that dir and call

```
createrepo .
```

which will create you repo metadata. Once there is repo metadata you don't need to specify the repo type in the kiwi XML description anymore because package managers will now find out temselves.

Respectively if you have other types of packages, e.g .debs you need to create repo metadata using the tools that exists for this case.

I hope this makes sense to you and helps you to move forward.

Thanks

**Comment by zohourih** [comment]
@schaefi Thank you for adding this feature, I really appreciate the effort.

I just had a question regarding use of createrepo that you mentioned. Let's say I have a folder called "rpms" with .rpm files inside it. I do a `cd rpms; creatrepo .` to create the repository metadata as you suggested. At this point, what should I put in the config.xml to point kiwi to this "local" repository?

**Comment by Conan-Kudo** [comment]
Just put the path to the folder for the local repository. It'll "Just Work(tm)"

**Comment by zohourih** [comment]
@Conan-Kudo In the following snippet, I have tried `rpms/`, `/work/rpms` and `dir://rpms` as \*path\*, but only the latter seems to work which is the same as what I had before, with the exception of the repository type changing from `rpm-dir` to `rpm-md`. Is this the correct way to do it?

```
<repository type="rpm-md" alias="local-rpms">
    <source path="*path*"/>
</repository>
```

**Comment by Conan-Kudo** [comment]
You cannot use `dir://`. You need to use either `file://` (absolute path) or `this://` (relative path)

**Comment by zohourih** [comment]
Oh, I see. For some reason I thought `file://` was going to be added in kiwi 10. Indeed `file://` works as well. Thank you.
