### ISSUE TITLE
The --temp-dir option does not work for `system build` command.

### ISSUE THREAD

**Issue by kshtsk** [OSInside/kiwi#1966]
## Problem description
The --temp-dir option does not work for `system build` command.

The the TEMP_DIR from defaults module is changed several times the kiwi-ng still creates
temporary directories in `/var/tmp`.

## Expected behaviour

The temporary dir should be overridden by --temp-dir.

## Steps to reproduce the behaviour

Just use --temp-dir and --debug and observe where tmp directory is created.

**Comment by kshtsk** [comment]
Corresponding fix in #1965

**Comment by schaefi** [comment]
Thanks a ton, what a stupid mistake from my side :man_facepalming:

**Comment by schaefi** [comment]
Fixed with #1965, thanks much
