### ISSUE TITLE
Unittests failed due to missing 'factor'.

### ISSUE THREAD

**Issue by kshtsk** [OSInside/kiwi#1968]
## Problem description
When developing the library on system where 'factor' dependency is missing it is not possible to pass unittests.

## Expected behaviour
Unittests should be crossplatform without extra dependencies.

## Steps to reproduce the behaviour
Run it any OS where are no 'factor' tool installed, for example, mac os, or bsd.
tox -e 'unit_py3_8' "-n 5"

**Comment by kshtsk** [comment]
Found this code:
```
    def _block_list(self, file_size):
        """
        Calculates the number of blocks and the block size for a given file
        size in bytes.

        :param int file_size: files size in bytes.

        :return: int:blocksize, int:blocks

        :rtype: tuple
        """
        blocksize = 1
        for factor in self._prime_factors(file_size):
            if blocksize * factor > 8192:
                break
            blocksize *= factor
        blocks = int(file_size / blocksize)
        block_list = namedtuple(
            'block_list', ['blocksize', 'blocks']
        )
        return block_list(
            blocksize=blocksize,
            blocks=blocks
        )

    def _prime_factors(self, number):
        """
        Get prime factors for the given number

        :param int number: number to factorize

        :return: prime factors

        :rtype: int generator
        """
        factor_call = Command.run(['factor', format(number)])
        for factor in factor_call.output.split(':')[1].lstrip().split(' '):
            yield int(factor)
```
That looks pretty like strange to have such a dependency, if someone give me an idea what would be better description for the _block_list method, because it does not describe why block size for the file should be divide the file size without a residue, I could probably rewrite the method to drop the dependency. From other side from the code I see that the block size should not be greater than square root of 8192.

**Comment by kshtsk** [comment]
So... instead of calling the `factor` there can be used python `primefac` module for example, and probably in stead of compute all prime factors for the file size, it is easier to compute prime factors less than maximal block size (8192 in our case). In other words go through the list of primes till 8192 and check the residue of modulo `%` operation?

**Comment by kshtsk** [comment]
```
def _prime_factors(self, number, _max=8192):
  n = number
  for i in primegen(_max):
    while n % i == 0:
      n = n // i
      yield i
```
blocksize can be evaluated as:
```
        block_size = 1
        max_block_size = 8192
        for factor in self._prime_factors(file_size, max_block_size):
            if block_size * factor > max_block_size:
                break
            blocksize *= factor

```
or it can be combined in one function
```
def _block_size(self, number, _max=8192):
  n = number
  bs = 1
  for i in primefac.primegen(_max):
    while n % i == 0:
      _bs = bs * i
      if _bs > _max:
        return bs
      bs = _bs
      n = n // i
      if n == 1:
        return bs
  return bs
```

**Comment by Conan-Kudo** [comment]
I'm not sure this is actually a bug. KIWI is for building Linux appliances, and we _expect_ it to run on a Linux environment.
