### ISSUE TITLE
Feature request: add support for custom bootloader template classes

### ISSUE THREAD

**Issue by iammattcoleman** [OSInside/kiwi#1970]
## Problem description
I'm building a live ISO and would like to fully customize the grub menu's behavior, changing the full script body (including all menu entries).

## Expected behaviour
The user is able to write a custom Python class that receives [parameters](https://github.com/OSInside/kiwi/blob/master/kiwi/bootloader/config/grub2.py#L353-L374) as input. A way of specifying the class name/path should be added to `config.xml`.

**Comment by schaefi** [comment]
From the community meeting we decided to go forward with this as follows:

* Adding @iammattcoleman to the team, yay :)
* @schaefi will create a branch to start and add the code to show how a new attribute to the schema gets added, maybe something like 
   ```xml
   <type ... grub_iso_template="/path/to/template_file" .../>
   ```
* support Matt with the rest of the implementation in case there are questions/issues

**Comment by schaefi** [comment]
@iammattcoleman I have added you to the team, happy to have you here :+1:

**Comment by schaefi** [comment]
To get you started with this I think the following steps are needed:

- [ ] Create a new attribute in the XML description to handle the custom template file
- [ ] Update the bootloader code to make use of the custom template if available
- [ ] Document the parameters which are passed to the template engine

**Comment by schaefi** [comment]
I have created a new branch named

* support_custom_bootloader_template

Please feel free to take over this branch and implement the missing bits and pieces. As discussed I have created the needed change in kiwi to add a new attribute. To get familiar with this process let me explain a few things:

1. In kiwi the schema is developed as RelaxNG schema in the compact form. This is the file kiwi/schema/kiwi.rnc
    When working with the schema this is the only file that gets changed by humans
2. From the compact file all other schema variants which are needed from code are autogenerated
3. Also the entire python API is created from the schema automatically
4. All the automated data is created with
    ```
    make kiwi/schema/kiwi.rng
    ```
5. The files generated namely 
    * a/kiwi/schema/kiwi.rng
    * a/kiwi/xml_parse.py
    Are no subject in a review

In the one commit in the branch I did exactly that. So for you the interesting part is mostly the change in the kiwi.rnc file. If you are familiar with RelaxNG schemas and schematron rules this will look familiar

**Comment by schaefi** [comment]
@iammattcoleman I think also important is the information here:

* https://osinside.github.io/kiwi/contributing.html

I usually work from within a python virtual environment because it contains all python modules needed for the kiwi development. Because of this we encoded the setup of the development environment almost completely into ```tox```
It makes your life much easier :)

**Comment by schaefi** [comment]
Last but not least in the commit here I added a new attribute called ```grub_template``` as part of the ```<bootloader>``` section . User will be able to specify it like in the following example

```xml
<type ...>
    <bootloader ... grub_template="/path/to/template"/>
</type>
```
I think that matches the idea which we have in mind with this ?

**Comment by schaefi** [comment]
@iammattcoleman all right, the stage is yours now. Let me know if there are questions, concerns or any sort of blocking issues. We will solve them. Also feel free to contact @davidcassany and/or @Conan-Kudo for help, since I'm not always around and all this is better shared on multiple shoulders.

Thanks much

**Comment by iammattcoleman** [comment]
I've added a couple commits, currently prefixed with `(WIP)`, to the branch you created for me, which implement...
* loading the custom template
* providing the description path to BootLoaderConfigGrub2

https://github.com/iammattcoleman/kiwi/commits/support_custom_bootloader_template

Does this approach look good? Or, should I use a `this://` URL like the `<import>` element's `from` attribute? Different parts of the codebase seem to handle accessing files from the description directory in different ways, so it's unclear to me how I should do that.

Here's an image description that uses the new feature:
https://github.com/iammattcoleman/overlay-test/commits/test-grub-template-support
* The initial commit does not use the new template feature.
* The second commit changes it to use the new template feature.
* The most recent commit ("use Kiwi's kernel parameters") was kept separate to illustrate that we may want to rethink how the kernel command line options are stored in the `parameters` dict in order to make templating more flexible.

**Comment by schaefi** [comment]
@iammattcoleman Thanks for working on this, really great :+1: 

JFI: you are on the team list here, so you could have added the commits directly into the existing branch instead of your forked repo. I think working with branches makes it a bit easier compared to working with forks. For example if you would create a PR from your fork I have to explicitly approve running the workflows on it... which I tend to forget :)

I will comment on the code you created, overall this looks all great. Thanks

**Comment by schaefi** [comment]
I commented. Feel free to push all your commits to the branch ;)

**Comment by Conan-Kudo** [comment]
> I have to explicitly approve running the workflows on it... which I tend to forget :)

This is only until he has his first PR merged. And don't worry, I don't forget. 😉

**Comment by iammattcoleman** [comment]
I just pushed a new version (squashed to a single commit, now) to the branch that addresses all the comments you put on my fork @schaefi and also adds documentation for the new functionality.

**Comment by iammattcoleman** [comment]
I need to update the unit test, so I've added the Work In Progress label again and closed the pull request.

**Comment by iammattcoleman** [comment]
I've added unit tests in #2034. Please let me know if there's anything I can improve. This is the first time I've used pytest, so there's a good chance that there's a better or more idiomatic way I could've written them.
