### ISSUE TITLE
Update build tests source services automatically on git change

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi#1980]
## Description

The kiwi integration build test sources are organized in this git below the ```build-tests``` directory.

We use the open buildservice to let us build this integration tests. The open build service projects
are setup using source services. The source services fetches the individual build-test
information from git and obs builds the package.

The projects to build the integration tests in the open buildservice are organized as a collection
of sub projects below the ```Virtualization:Appliances:Images``` project. The following list shows
all sub project paths:

* Virtualization:Appliances:Images:Testing_x86:tumbleweed 
*  Virtualization:Appliances:Images:Testing_x86:rawhide 
*  Virtualization:Appliances:Images:Testing_x86:leap 
*  Virtualization:Appliances:Images:Testing_x86:centos 
*  Virtualization:Appliances:Images:Testing_x86:fedora 
*  Virtualization:Appliances:Images:Testing_x86:ubuntu 
*  Virtualization:Appliances:Images:Testing_x86:debian 
*  Virtualization:Appliances:Images:Testing_s390:tumbleweed 
*  Virtualization:Appliances:Images:Testing_s390:sle15
*  Virtualization:Appliances:Images:Testing_arm:tumbleweed 
*  Virtualization:Appliances:Images:Testing_arm:fedora 
*  Virtualization:Appliances:Images:Testing_ppc:tumbleweed 
*  Virtualization:Appliances:Images:Testing_ppc:sle15 
*  Virtualization:Appliances:Images:Testing_ppc:fedora 
*  Virtualization:Appliances:Images:Testing_x86:archlinux

## Issue

If there is a change in the git sources of the build-tests there is no mechanism that triggers the
source service for the open buildservice such that the image will be automatically rebuild with the
changed test.

The open buildservice provides integration opportunities based on a token and webhooks
as explained here:

Tokens in OBS

* https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.authorization.token.html#id-1.5.10.17.4

Use on github
 
* https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.source_service.html#sec.obs.sserv.token_usage

## Expected Behavior

A change of the build-tests data in git triggers the respective source service in obs

**Comment by schaefi** [comment]
As a summary to the conversation we had on Matrix I think this would be the task list for this issue

- [ ] Create a token with the project scope set to Virtualization:Appliances:Images. Still not clear if that would allow access to any sub-projects
- [ ] Register the token as a secret variable
- [ ] Create github action to include a trigger event for each build-test, eventually using ```uses: distributhor/workflow-webhook@v2``` as suggested by @davidcassany 

Feel free to correct, adapt change this

**Comment by dcermak** [comment]
I am not certain how tokens are exactly scoped on OBS, so I cannot give a definitive answer here.
If you want to use a token with an API call to obs' APi, then you have to add the `Authorization:` header with the value: `Token ${Token.secret}`. And there's also a catch with OBS' API: triggering a service run will give you a success if triggering succeeded, however, that doesn't mean that the service run succeeded… Just something to be aware of.

**Comment by davidcassany** [comment]
> As a summary to the conversation we had on Matrix I think this would be the task list for this issue

Looks good to me, and I agree this should be our first attempt. My only concern is adding a token for `Virtualization:Appliances:Images` seams wrong to me, as this project holds quite few images beyond what we have in `build-tests`. Probably none of the non test images under `Virtualization:Appliances:Images` is using services, but still that can turn to be problem at certain point. The problem is that we do not have a parent project holding all the tests and **only** tests.

Anyway, I'd say this is for a second round setup. First I'd validate what happens with subprojects having a project level token and triggering it.

@schaefi @dcermak I can try to set that up and do a test to see what happens subprojects

**Comment by dcermak** [comment]
sounds good to me @davidcassany !

**Comment by schaefi** [comment]
>Looks good to me, and I agree this should be our first attempt. My only concern is adding a token for Virtualization:Appliances:Images seams wrong to me

I suggested that because of the sub-projects. If we assume the token is valid for the sub-projects this is the top level entry point. If you don't like that and go deeper you would probably need a token for each Virtualization:Appliances:Images:Testing_XX project which I don't like because there will be more of these sub projects in the future and the token mess begins

> The problem is that we do not have a parent project holding all the tests and only tests.

exactly

> @davidcassany I can try to set that up and do a test to see what happens with subprojects

Sounds great to me, thanks much

**Comment by davidcassany** [comment]
All right, my tests up to now are a bit frustrating. I can't manage to run services at project level... Gonna investigate a bit further, but I am afraid we will be have to deal with a generic runservice token (meaning the token is devoted to a user, without project&package constraints) and make use of it on per project & package basis...

Up to now I managed to succeed with:

```
curl -H "Authorization: Token <genericToken>" -X POST "https://api.opensuse.org/trigger/runservice?project=<project>&package=<package>"
```

It should be relatively simple to script a curl call per package. Not what I expected but still possible.

These are failed attempts:

```
# Using only project paramter over a genericToken
$ curl -H "Authorization: Token <genericToken>" -X POST "https://api.opensuse.org/trigger/runservice?project=<project>"
<status code="unknown_package">
  <summary>Package not found: Virtualization:Appliances:Images:Testing_x86:archlinux/</summary>
</status>

# Creating a token with only a project as a paramter
$ osc api -X POST /person/dcassany/token?project=Virtualization:Appliances:Images:Testing_x86:archlinux
Server returned an error: HTTP Error 404: Not Found
Package not found: Virtualization:Appliances:Images:Testing_x86:archlinux/

# Using osc token subcommand succeeds, but the result is a generic token
$ osc token -c Virtualization:Appliances:Images:Testing_x86:archlinux
<status code="ok">
  <summary>Ok</summary>
  <data name="token">TOKEN</data>
  <data name="id">5702</data>
</status>

$ osc api -X GET /person/dcassany/token
<directory count="5">
  ...
  <entry id="5702" string="TOKEN" kind="runservice" name="" triggered_at=""/>
</directory>
```

So it is not possible to create tokens at project level neither trigger services at project level. Choices so far are:

* Create token per package (not viable given the amount of images we have)
* Create a generic token and call it under the scope of some specific package having some little script in place to loop around all modified images.

**Comment by schaefi** [comment]
> So it is not possible to create tokens at project level

That's what I thought too but @dcermak said the OBS API would support it...

**Comment by dcermak** [comment]
> That's what I thought too but @dcermak said the OBS API would support it...

I said I *thought*/*assumed*. Looks like my assumption was wrong.

**Comment by schaefi** [comment]
@davidcassany  @dcermak  I experimented with this concept in another project to get familiar with it. So far this worked well. What I did was this:

* created a token for home:marcus.schaefer (my home project)
* added the token as a secret to https://github.com/OSInside/cloud-builder-packages (a reference git I use for some site project)
* created the following github workflow: https://github.com/OSInside/cloud-builder-packages/blob/master/.github/workflows/ci-update-xsnow.yml

That's it and worked fast and reliable

Applied here this would mean I would create one github workflow per integration test.

Do you think this makes sense or is too cumbersome ?

Thanks much

**Comment by dcermak** [comment]
> Applied here this would mean I would create one github workflow per integration test.

Why? What would stop you from calling the following in a loop:
```bash
curl -H "Authorization: Token ${{ secrets.OBS_TOKEN }}" -X POST "https://api.opensuse.org/trigger/runservice?project=home:marcus.schaefer&package=xsnow"
```

**Comment by schaefi** [comment]
@dcermak I'm sorry I can't follow you. My goal was to update the source service if the respective integration test changes on the git side. If we take ```build-tests/x86/leap/test-image-disk``` as an example I was thinking on a github action that runs on changes of any file in that directory and it will trigger a POST request for this particular test which would be ```...?project=Virtualization:Appliances:Images:Testing_x86:leap&package=test-image-disk```

In this concept we would need one github action per integration test.

I do not understand what you mean by calling in a loop ?

Thanks

**Comment by dcermak** [comment]
Marcus Schäfer ***@***.***> writes:

> @dcermak I'm sorry I can't follow you. My goal was to update the source service if the respective integration test changes on the git side. If we take ```build-tests/x86/leap/test-image-disk``` as an example I was thinking on a github action that runs on changes of any file in that directory and it will trigger a POST request for this particular test which would be ```...?project=Virtualization:Appliances:Images:Testing_x86:leap&package=test-image-disk```
>
> In this concept we would need one github action per integration test.
>
> I do not understand what you mean by calling in a loop ?

something like `for proj in (virt:app:img:testing:leap virt:app:img:testing:tw); do curl $URL; done`

**Comment by schaefi** [comment]
@dcermak as discussed let's do it the way you suggested. I'm going to look at this, thanks
