### ISSUE TITLE
Systemd .path units cannot be enabled

### ISSUE THREAD

**Issue by ozboss** [OSInside/kiwi#1984]
## Problem description

I would like to enable a .path systemd-unit inside config.sh.
Kiwi only handles .service and .mount units.

Please enable handling of other unit types aswell.

## Expected behaviour

`baseInsertService unit.path ` inside config.sh enables 'unit.path'

## Steps to reproduce the behaviour

Inside config.sh:

``` 
baseInsertService unit.path
```

## OS and Software information
+ KIWI version: 9.24.6
+ Operating system: Debian 10
+ OBS version: -

**Comment by Conan-Kudo** [comment]
You can use `systemctl enable` instead.

**Comment by Conan-Kudo** [comment]
We might want to consider dropping the `baseInsertService` and `suseInsertService` functions entirely, since they're not really needed in our current support matrix.

**Comment by ozboss** [comment]
> You can use `systemctl enable` instead.

Thanks @Conan-Kudo, yes this is correct and honestly just as good.
For me it didn't work in the config.sh because I was installing systemd at a later point in time with tasksel and it took me a while to figure that out.
Closing this issue.
