### ISSUE TITLE
Missing support for managing DNF modules

### ISSUE THREAD

**Issue by Conan-Kudo** [OSInside/kiwi#1999]
## Problem description

In CentOS Stream 8 and Red Hat Enterprise Linux 8, there are [Application Streams](https://access.redhat.com/support/policy/updates/rhel8-app-streams-life-cycle) that are offered in the form of modules (using [Fedora Modularity](https://docs.fedoraproject.org/en-US/modularity/) technology). To build images that use this content, I need support in KIWI enable various modules.

[DNF supports the `dnf module switch-to` command](https://dnf.readthedocs.io/en/latest/command_ref.html#module-command), which lets you declare modules to enable and it'll do every action required to change the state to match what you expect. Micro DNF doesn't support this, though, and only supports `module reset`, `module disable`, and `module enable` subcommands.

If you wanted to use the same pattern for both DNF and Micro DNF, the way to do it would be as follows:
* For each module request, run `dnf|microdnf reset <module>`, then `dnf|microdnf enable <module>`

The `dnf module switch-to` command will also switch installed package content in one go, but we can avoid needing this if we run the module switching stage after bootstrap and before running the image package installation phase.

## OS and Software information
+ KIWI version: 9.24.13
+ Operating system: CentOS Stream 8
+ OBS version: N/A

**Comment by schaefi** [comment]
@Conan-Kudo @davidcassany I have started to work on this but would like to get your feedback and also start with small steps. The first important agreement we need to find is how to describe this in a way that it doesn't feel distribution specific, generic enough and also clear to understand. My idea is as follows:

The concept of modules independent of the individual implementation implies to enable/disable additional software components or in general application streams. Therefore I think the following feels generic and easy to understand:

```xml
<packages type="image">
    ...
    <appStream name="module-name" enable="true|false"/>
    <appStream name="another-module-name" enable="true|false"/>
</packages>
```

Thoughts ?

**Comment by Conan-Kudo** [comment]
Call them `module` and I think we're fine here. I don't think it'd be a good idea to leak the AppStream brand name into here.

**Comment by schaefi** [comment]
> The dnf module switch-to command will also switch installed package content in one go, but we can avoid needing this if we run the module switching stage after bootstrap and before running the image package installation phase.

I did not understand this. As we are starting from an empty stage, why is any switching needed ?

Also are you saying we cannot use modules during the bootstrap phase ? This is the phase were dnf is called from the host with options to target into the new root

**Comment by Conan-Kudo** [comment]
> > The dnf module switch-to command will also switch installed package content in one go, but we can avoid needing this if we run the module switching stage after bootstrap and before running the image package installation phase.
> 
> I did not understand this. As we are starting from an empty stage, why is any switching needed ?
> 
> Also are you saying we cannot use modules during the bootstrap phase ? This is the phase were dnf is called from the host with options to target into the new root

We can if we configure repos and immediately configure modules after. Then we don't need switching.

**Comment by schaefi** [comment]
>We can if we configure repos and immediately configure modules after before package installation. Then we don't need switching.

This sounds good to me, so the entire module setup is something that belongs more into the repository area of the implementation

**Comment by Conan-Kudo** [comment]
> > We can if we configure repos and immediately configure modules after before package installation. Then we don't need switching.
> 
> This sounds good to me, so the entire module setup is something that belongs more into the repository area of the implementation

It's globally scoped across all configured repos.

**Comment by schaefi** [comment]
If I call ```dnf reset``` and ```dnf enable foo``` what happens behind the scene ? Is this information places into the repo files or is it done in an extra config file or something completely differently ?

**Comment by schaefi** [comment]
If the setting of the module configuration is global and we want this from the zero stage I suggest to allow setting up the modules only in the bootstrap section. Taking your name suggestion into account this would mean something like

```xml
<packages type="bootstrap">
    ...
    <module name="module-name" enable="true|false"/>
    <module name="another-module-name" enable="true|false"/>
</packages>
```

I'm not so happy with just ```module``` it doesn't tell users much and it can be anything. Maybe we want to express this with a bit more context ? e.g ```appModule``` or ```applicationModule```

**Comment by schaefi** [comment]
@Conan-Kudo ok I have started a branch with the basic description which is as of today as follows:

```xml
<packages type="bootstrap">
        <collectionModule name="module-name" enable="true|false"/> 
</packages>
```

* collectionModule can only be used in the bootstrap section
* We want the setting for modules to be done once in a global scope at the bootstrap phase, to avoid the need for switching
* We want the implementation to be done for dnf and microdnf in the same way

Since kiwi does the repo setup once and inherits this information into the chroot I still need to understand what happens behind the scene on a ```dnf module enable|disable```. That's not yet clear to me. Also do we need a ```dnf module reset``` when we do all this from a zero stage ?

Thanks

**Comment by Conan-Kudo** [comment]
> 
> Since kiwi does the repo setup once and inherits this information into the chroot I still need to understand what happens behind the scene on a `dnf module enable|disable`. That's not yet clear to me.

When `dnf module disable|enable` happens, DNF generates some state data to mark the module as inactive or active and configures filter rules for what packages are available. When a module is enabled, its packages overshadow the "non-modular" equivalents if they exist.

> Also do we need a `dnf module reset` when we do all this from a zero stage ?
> 

@dmach would be able to clarify this for certain, but I believe we _do_ need the `dnf module reset` so that default streams are unset.

**Comment by Conan-Kudo** [comment]
> `<collectionModule name="module-name" enable="true|false"/> `

I think this should actually be   `<collectionModule name="module-name" stream="module-stream" enable="true|false"/>`

The reason for this is simple: I don't think we want to pass the stream to `dnf module reset`. I'm not sure if that handles unsetting all streams properly if you do it that way, so we'd want:

1. `dnf module reset module-name`
2. `dnf module enable|disable module-name:module-stream`

Though I think @dmach or @j-mracek would be able to clarify here.

**Comment by j-mracek** [comment]
``dnf module reset module-name`` is only required for enable operation when ``module-name:other-stream`` is enabled. The reset step prevents from dnf to error out - not allowed stream switching.


1.    ``dnf module reset module-name``
2.    ``dnf module enable module-name:module-stream``

With module disable you do not need to use reset command and you should not use stream, because you disable whole module.
1. ``dnf module disable module-name:``

**Comment by schaefi** [comment]
@j-mracek Thanks for the details. I understand enabling a module for stream A requires a reset before if that module was enabled for stream B. If the module was not enabled for any stream, the reset does not hurt, does it ?

Another question with regards to the disable operation. You said stream should not be used for disabling. This means a module can only be enabled for one stream, correct ?

If my assumptions are correct we would allow:

```xml
<packages type="bootstrap">
        <collectionModule name="module-name" stream="stream-name" enable="true"/>
        <collectionModule name="module-name" enable="false"/>
</packages>
```

* disabling a module with a stream name associated will lead to an error
* enabling a module will be done by:
   ```
   dnf module reset module-name
   dnf module enable module-name:stream-name
   ```
* disabling a module will be done by:
   ```
   dnf module disable module-name:
   ```
   The colon at the end of this call is relevant correct ?

Thanks much

**Comment by Conan-Kudo** [comment]
I don't think `module-name:` is a valid module spec, [based on the documentation](https://dnf.readthedocs.io/en/latest/command_ref.html#specifying-modules).

**Comment by Conan-Kudo** [comment]
According to [the `dnf module` subcommand documentation](https://dnf.readthedocs.io/en/latest/command_ref.html#module-command), only `dnf module disable module-name` is valid. You cannot pass NSVCAs in partial or complete form to that subcommand, only module names.

**Comment by schaefi** [comment]
I have adapted the schema definition. The following settings are allowed:

```xml
<packages type="bootstrap">
    <collectionModule name="foo" enable="false"/>
</packages>
```

```xml
<packages type="bootstrap">
    <collectionModule name="foo" enable="true"/>
</packages>
```

```xml
<packages type="bootstrap">
    <collectionModule name="foo" stream="bar" enable="true"/>
</packages>
```

The following settings are invalid and will case a schema validation error

```xml
<packages type="image">
    <collectionModule name="foo" enable="true"/>
</packages>
```

* reason: collectionModule only allowed in bootstrap section, because we want this setup to happen once and as early as possible

```xml
<packages type="bootstrap">
    <collectionModule name="foo" stream="bar" enable="false"/>
</packages>
```

* reason: disabling module does not allow to specify a stream

```xml
<packages type="bootstrap">
    <collectionModule name="foo"/>
</packages>
```

* reason: the specification to enable or disable a module is mandatory and we want this explicitly set

```xml
<packages type="bootstrap">
    <collectionModule name="foo:xxx" enable="true"/>
</packages>
```

* reason: The given package name is not rpm name compliant. Please note the regular expression applied to ```name``` and ```stream``` attributes are set to

```
safe-posix-name = xsd:token {pattern = "[a-zA-Z0-9_\-\.]+"}
```

I had a hard time finding a real convention for package names of rpm and the above is currently the safest one I could come up with. We also don't have full reqular expression support (e.g negative character classes are not supported) in the scope of the RelaxNG schema.

Please take a look and let me know if there are concerns, improvements, things I missed, etc...

Thanks much

**Comment by Conan-Kudo** [comment]
This looks great for initial support! You should also probably allow the `~` and `^` characters, but beyond that, I think you've got it.

**Comment by j-mracek** [comment]
Yes, `module reset` does not 

> @j-mracek Thanks for the details. I understand enabling a module for stream A requires a reset before if that module was enabled for stream B. If the module was not enabled for any stream, the reset does not hurt, does it ?
> 

The `reset` step does not hurt.

> Can a module be enabled without any stream name, e.g
> 
> ```
> dnf module enable module-name:
> ```
> 

Yes, but only when default stream is describe in METADATA.

> ?
> 
> Another question with regards to the disable operation. You said stream should not be used for disabling. This means a module can only be enabled for one stream, correct ?

Yes, only one stream per module can be enabled. Try `dnf module enable nodejs:12 nodejs:14`

> 
> Based on current assumptions we would allow:
> 
> ```
> <packages type="bootstrap">
>         <collectionModule name="module-name" stream="stream-name" enable="true"/>
>         <collectionModule name="module-name" enable="false"/>
> </packages>
> ```
> 
>     * disabling a module with a stream name associated will lead to an error
> 
>     * enabling a module will be done by:
>       ```
>       dnf module reset module-name
>       dnf module enable module-name:stream-name(or empty)
>       ```
> 
>     * disabling a module will be done by:
>       ```
>       dnf module disable module-name:
>       ```
>  

Please replace eplace `module-name:` by `module-name`
     
>       
>           
>             
>           
>       
>             
>           
>       
>           
>         
>       The colon at the end of this call is relevant correct ?
> 
> 
> Thanks much
