### ISSUE TITLE
lib/firmware cleanup fails in 15.4 with kernel modules zstd compressed

### ISSUE THREAD

**Issue by bugfinder** [OSInside/kiwi#2002]
## Problem description
when looking for unreferenced firmware files, the code only looks for .ko and .ko.xz files to find kernel modules

## Expected behaviour
support also files and modules in gz or zst format

## Steps to reproduce the behaviour
build image on 15.4

## OS and Software information
+ KIWI version: 
+ Operating system: 
+ OBS version:

**Comment by schaefi** [comment]
Fixed with #2003
