### ISSUE TITLE
Trouble booting the Archlinux images

### ISSUE THREAD

**Issue by dcermak** [OSInside/kiwi#2005]
## Problem description

I have started adding openQA tests for kiwi in https://github.com/OSInside/kiwi-functional-tests/pull/14 and noticed a bunch of booting issues:

- [ ] The `install.iso` from the [`test-image-live-disk-kis:Disk`](https://build.opensuse.org/package/binaries/Virtualization:Appliances:Images:Testing_x86:archlinux/test-image-live-disk-kis:Disk/images) package does not boot in either EFI or BIOS.
  in BIOS mode, it appears to hang, but it actually displays the following output to the serial console:
```
[  OK  ] Finished dracut pre-mount hook.
         Mounting /sysroot...
[FAILED] Failed to mount /sysroot.
See 'systemctl status sysroot.mount' for details.
[DEPEND] Dependency failed for Initrd Root File System.
[DEPEND] Dependency failed for Relo…figuration from the Real Root.
[  OK  ] Stopped Dispatch Password …ts to Console Directory Watch.
[  OK  ] Stopped target Basic System.
[  OK  ] Reached target Initrd File Systems.
[  OK  ] Stopped target System Initialization.
[  OK  ] Stopped dracut pre-mount hook.
[  OK  ] Stopped dracut initqueue hook.
[  OK  ] Stopped dracut pre-trigger hook.
[  OK  ] Stopped dracut pre-udev hook.
[  OK  ] Stopped dracut cmdline hook.
[  OK  ] Stopped dracut ask for additional cmdline parameters.
[  OK  ] Started Emergency Shell.
[  OK  ] Reached target Emergency Mode.

Generating "/run/initramfs/rdsosreport.txt"


Entering emergency mode. Exit the shell to continue.
Type "journalctl" to view system logs.
You might want to save "/run/initramfs/rdsosreport.txt" to a USB stick or /boot
after mounting them and attach it to a bug report.


Press Enter for maintenance
(or press Control-D to continue): 
```
  in EFI mode, we get this failure instead:
![image](https://user-images.githubusercontent.com/45594031/146509752-b7ea4b37-a0df-46bf-bdf0-7f4edac74640.png)

- [ ] `kiwi-test-image-live-disk-kis.x86_64-1.0.0-Live-Build24.52.iso` from [`test-image-live-disk-kis:Live`](https://build.opensuse.org/package/binaries/Virtualization:Appliances:Images:Testing_x86:archlinux/test-image-live-disk-kis:Live/images) does only boot in BIOS mode, but not in EFI. With EFI, the firmware does not recognize the iso as a bootable device.

## Expected behavior

The images should be bootable in EFI & BIOS mode

## Steps to reproduce the behavior

1. Download the respective ISO images
2. Create a new virtual machine with virt-manager, optionally enable EFI in the chipset menu
3. Try to launch the VM

**Comment by davidcassany** [comment]
Ouch, I guess I will have to keep an eye to that. It's been a while since I last checked the ArchLinux images... At some point it is likely there will be a break if ArchLinux fully adopts dracut. I am wondering if this is related to that... gonna investigate it.

**Comment by schaefi** [comment]
Thanks David for looking into this, much appeciated

**Comment by davidcassany** [comment]
I am wondering if the new custom grub templates @iammattcoleman  coded could provide a work around for the media installation on EFI. @schaefi @iammattcoleman, are the templates applicable for the installation media or only live media? In Arch Linux the installation media grub configuration should be slightly modified, at a time I did not increase the grub config burden up to another level to support a rolling release none of us is following closely 😅
