### ISSUE TITLE
Include specific set of xattrs for OCI images

### ISSUE THREAD

**Issue by ignatenkobrain** [OSInside/kiwi#2009]
## Problem description

```xml
<?xml version="1.0" encoding="utf-8"?>

<image schemaversion="7.4" name="c9s">
    <description type="system">
        <author>Igor Raits</author>
        <contact>igor.raits@gmail.com</contact>
        <specification>CentOS Stream 9</specification>
    </description>
    <preferences>
        <version>1.0.0</version>
        <!-- <release-version>9</release-version> -->
        <packagemanager>dnf</packagemanager>
        <locale>en_US</locale>
        <keytable>us</keytable>
        <timezone>Europe/Prague</timezone>
        <type image="docker">
            <containerconfig name="c9s-base"/>
        </type>
        <rpm-excludedocs>true</rpm-excludedocs>
        <rpm-check-signatures>true</rpm-check-signatures>
    </preferences>
    <repository type="rpm-md" alias="baseos">
        <source path="http://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/"/>
    </repository>
    <repository type="rpm-md" alias="appstream">
        <source path="http://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/"/>
    </repository>
    <packages type="image" patternType="onlyRequired">
        <package name="bash"/>
    </packages>
    <packages type="bootstrap">
        <package name="centos-stream-release"/>
    </packages>
</image>

```

Building such image fails on:

```
[ DEBUG   ]: 00:05:06 | EXEC: [rsync -a -H -X -A --one-file-system --inplace --delete --exclude /image --exclude /.profile --exclude /.kconfig --exclude /run/* --exclude /tmp/* --exclude /.buildenv --exclude /var/cache/kiwi --exclude /dev/* --exclude /sys/* --exclude /proc/* /home/brain/tmp/tmp/out/build/image-root/ /var/lib/containers/storage/overlay/83aacfbaf9fc572a5850a7513c9619076514c7d15f931146b0e92eb7235c8ff4/merged]
[ DEBUG   ]: 00:05:06 | EXEC: Failed with stderr: rsync: [receiver] rsync_xal_set: lsetxattr("/var/lib/containers/storage/overlay/83aacfbaf9fc572a5850a7513c9619076514c7d15f931146b0e92eb7235c8ff4/merged/.","security.selinux") failed: Operation not supported (95)
… (bunch more messages about selinux)
```

## Expected behaviour

Most likely rsync needs to skip extended attributes as those are not useful in the containers .

## Steps to reproduce the behaviour

Get simple config.xml and try to build an image.

## OS and Software information
+ KIWI version: 9.24.13 (+ `buildah-1.23.1-1.fc36.x86_64` + `skopeo-1.5.2-1.fc36.x86_64`)
+ Operating system: Fedora 36 (host), CentOS Stream 9 (target)
+ OBS version: N/A

**Comment by schaefi** [comment]
Before we try to find a smart solution to this issue can you confirm that the problem disappears if you follow the information from here:

* https://osinside.github.io/kiwi/troubleshooting/security.html

If yes I can tell you that I ran into some other issues with enabled selinux policies regarding image building. This is also the reason why I stopped trying to find workarounds for active policy settings because at some point I always ended with "I need this permission to build" ... then I tried to update the policy to fit my use case ... and the next system with enabled security policy killed it again ... so I stopped it and took the risk

For those who cannot afford weaker security policies there is also the option to build via the kiwi boxplugin:

* https://osinside.github.io/kiwi/plugins/self_contained.html

This allows the host to keep the security (KVM needs to be allowed in that policy) and still builds images with all features working.

I would be very interested to hear your feedback regarding the security policies and their impact and how to handle this gracefully in an image builder. I think there should be no extra code in kiwi to mess with the policies.

Thanks much

**Comment by ignatenkobrain** [comment]
I have SELinux in permissive mode, otherwise kiwi does not work at all. Disabling it completely probably could help with the issue but I think just improving rsync call would be slightly better.

**Comment by schaefi** [comment]
I agree to that, but there is already code checking this condition:

```python
if not self.target_supports_extended_attributes():
            warn_me = False
            if '-X' in rsync_options:
                rsync_options.remove('-X')
```

The problem is the environment seems to support extended attributes (tested via xattr) and thus kiwi keeps -X for syncing. Why this should not make sense when building in a container is not clear to me. The rootfs of your image can contain files with extended attributes no matter if it was created inside of a container or elsewhere.

If there would be an opportunity to check in the active selinux policy if extended attributes are allowed on file transfer or not we could add a code point for it in kiwi

**Comment by ignatenkobrain** [comment]
Yeah, but I suppose the devil there is in the mismatch or host and target system.. as the roots was created inside the chrome  using selinux labels from target system.. those are not understood by the host system as it has different set of labels, etc.

**Comment by schaefi** [comment]
Yes I can imagine that. Out of curiosity and if it is possible for you to access the system, could you try to simply patch the kiwi code here: ```/usr/lib/python*/site-packages/kiwi/defaults.py``` and change:

```
@staticmethod
    def get_sync_options():
        ...AS YOU SEE FIT
```

Does this change fix the build or do you run into other problems related to security policy settings ?
I think if the container shares the selinux policy (and I think privileged containers does this) you can run into other
issues in addition to the way rsync is called.

All this can be relatively confusing and I think if we do changes in kiwi related to selinux it should be somehow
made very clear in the code such that we are not confused when reading it sometime later :)

**Comment by ignatenkobrain** [comment]
@schaefi dropping `-X` from that method does the trick for me.

root-less container looks like this:

```
bash-5.1# ls -lZ
total 16
dr-xr-xr-x.   1 root   root   system_u:object_r:container_file_t:s0:c610,c734   0 Aug  9 22:40 afs
lrwxrwxrwx.   1 root   root   system_u:object_r:container_file_t:s0:c610,c734   7 Aug  9 22:40 bin -> usr/bin
dr-xr-xr-x.   1 root   root   system_u:object_r:container_file_t:s0:c610,c734   0 Aug  9 22:40 boot
drwxr-xr-x.   5 root   root   system_u:object_r:container_file_t:s0:c610,c734 360 Jan  4 01:14 dev
drwxr-xr-x.   1   1000   1000 system_u:object_r:container_file_t:s0:c610,c734  46 Jan  4 01:14 etc
drwxr-xr-x.   1 root   root   system_u:object_r:container_file_t:s0:c610,c734   0 Aug  9 22:40 home
lrwxrwxrwx.   1 root   root   system_u:object_r:container_file_t:s0:c610,c734   7 Aug  9 22:40 lib -> usr/lib
lrwxrwxrwx.   1 root   root   system_u:object_r:container_file_t:s0:c610,c734   9 Aug  9 22:40 lib64 -> usr/lib64
drwxr-xr-x.   1 root   root   system_u:object_r:container_file_t:s0:c610,c734   0 Aug  9 22:40 media
drwxr-xr-x.   1 root   root   system_u:object_r:container_file_t:s0:c610,c734   0 Aug  9 22:40 mnt
drwxr-xr-x.   1 root   root   system_u:object_r:container_file_t:s0:c610,c734   0 Aug  9 22:40 opt
dr-xr-xr-x. 674 nobody nobody system_u:object_r:proc_t:s0                       0 Jan  4 01:14 proc
drwxr-xr-x.   1 root   root   system_u:object_r:container_file_t:s0:c610,c734   8 Dec 31 08:54 root
drwxr-xr-x.   1 root   root   system_u:object_r:container_file_t:s0:c610,c734  40 Jan  4 01:14 run
lrwxrwxrwx.   1 root   root   system_u:object_r:container_file_t:s0:c610,c734   8 Aug  9 22:40 sbin -> usr/sbin
drwxr-xr-x.   1 root   root   system_u:object_r:container_file_t:s0:c610,c734   0 Aug  9 22:40 srv
dr-xr-xr-x.  13 nobody nobody system_u:object_r:sysfs_t:s0                      0 Jan  2 12:14 sys
drwxrwxrwt.   1 root   root   system_u:object_r:container_file_t:s0:c610,c734   0 Jan  4 01:14 tmp
drwxr-xr-x.   1 root   root   system_u:object_r:container_file_t:s0:c610,c734 100 Dec 31 00:13 usr
drwxr-xr-x.   1 root   root   system_u:object_r:container_file_t:s0:c610,c734 154 Jan  4 01:14 var
```

According to what I found on the internet, tar should be created without selinux labels as those are not really used within a container. I've also tried to dump fedora/centos images and seems those images do not have any extended attributes.

That said, I think it is correct to exclude xattr preserving for container builds completely (I suppose `tar` should be called also with `--no-xattrs` to be fully sure).

**Comment by davidcassany** [comment]
Just for the records, a while ago we got a bug report at SUSE claiming KIWI was not preserving files capabilities (bsc#1028842), my point is that we can't expect to always drop extended attributes, there is people out there relaying on those. We need some control over it or distinguish use cases. Probably, as discussed within the community meeting, we can assume extended attributes are not needed in OCI images.

**Comment by schaefi** [comment]
Thanks David.

> we can assume extended attributes are not needed in OCI images.

yep, let's do that, it will also fix the issue for @ignatenkobrain

**Comment by ignatenkobrain** [comment]
FTR https://github.com/osbuild/osbuild/pull/623 is how osbuild solves this problem (and they keep some of the xattrs), so I suppose we could do the same for OCI.

**Comment by darix** [comment]
This breaks fscaps, which are stored in in xattr.

**Comment by darix** [comment]
PR for the revert in https://github.com/OSInside/kiwi/pull/2643
