### ISSUE TITLE
Running customization scripts is not possible from within mock (koji)

### ISSUE THREAD

**Issue by ignatenkobrain** [OSInside/kiwi#2010]
## Problem description

I'm trying to run some post_bootstrap.sh script when building image with kiwi from koji but sadly that does not really work. Screen does not run.

```
DEBUG util.py:446:  [ DEBUG   ]: 17:03:41 | EXEC: [screen -t -X chroot /builddir/result/image/build/image-root image/post_bootstrap.sh]
DEBUG util.py:446:  [ INFO    ]: 17:03:41 | Calling post_bootstrap.sh script
DEBUG util.py:446:  [ DEBUG   ]: 17:03:41 | --------------out start-------------
DEBUG util.py:446:  [ DEBUG   ]: 17:03:41 | Must be connected to a terminal.
DEBUG util.py:446:  [ DEBUG   ]: 17:03:41 | --------------out stop--------------
DEBUG util.py:444:  [ ERROR   ]: 17:03:41 | KiwiScriptFailed: post_bootstrap.sh failed: 
```

## Expected behaviour

Somehow it does not fail.

## Steps to reproduce the behaviour

Build image in koji using kiwi (#1918) with post_bootstrap.sh script referenced.

## OS and Software information
+ KIWI version: `9.24.15-1.el9`
+ Operating system: `CentOS Stream 9`
+ OBS version: N/A

**Comment by Conan-Kudo** [comment]
cc: @tkopecek @schaefi

**Comment by Conan-Kudo** [comment]
This is also probably the reason why the script fails when running an image build in GitLab CI too...

**Comment by Conan-Kudo** [comment]
@schaefi Why don't we just use subprocess here?

**Comment by ignatenkobrain** [comment]
I suppose because of possibility to debug scripts

**Comment by schaefi** [comment]
Igor is correct here, when kiwi is called with "--debug" it runs scripts through screen. There was a conversation on matrix about this issue and we came across that people who use "--debug" sometimes don't do it because they want to debug but because they want the full info on stdout. Because of that reason a patch in kiwi was made:

```
commit 7e0927e8d5d0162e86fbb6c98e815cf82eaf8fbc (origin/allow_stdout_logging)
Author: Marcus Schäfer <ms@suse.de>
Date:   Tue Oct 5 17:25:25 2021 +0200

    Allow logfile option to log on stdout
    
    The option setting '--logfile stdout' is now a special form
    and logs the messages usually written to a file to stdout
    instead. This is handy if all messages of the build are
    requested but the --debug switch is not because it does more
    than that, e.g calling scripts through debug'able screen
    sessions

```

Thus if you are also using --debug for non debugging reasons, please switch to ```--logfile stdout```

Does this help ?

Thanks

**Comment by Conan-Kudo** [comment]
Not really. I want to capture the logs as files still, but I also want the debug mode to work in CI (GitLab has interactive terminals for debugging jobs).

**Comment by schaefi** [comment]
@Conan-Kudo I haven't used the interactive terminal feature of gitlab. If they open a terminal session to the container support for pseudo terminals seems required to me. If the container supports this you should also have not issue with the kiwi --debug flag.

Is there anything we need to do in kiwi to help you at this point ?

**Comment by ignatenkobrain** [comment]
Koji actually does not use `--debug` by default, it was just me trying to debug stuff around… So I guess I'm good at this moment but not sure if @Conan-Kudo has some use-case for it.

**Comment by Conan-Kudo** [comment]
It'd be nice to have a `--verbose` equivalent that didn't use screen and preserved all the other behaviors (including logging to files) while still printing out everything to stdout/stderr. This isn't strictly needed for Koji since it can poll log files, but GitLab CI would benefit from it.

**Comment by schaefi** [comment]
Ok, let's do that. I'm going to add an additional ```--debug-scripts-in-screen``` or similar such that users can combine as they see fit
