### ISSUE TITLE
kiwi-dump-image writes compressed disk image during PXE installation

### ISSUE THREAD

**Issue by qby-wenzel** [OSInside/kiwi#2015]
## Problem description
When installing images using the PXE method, everything works as expected until the image itself (_foobar.x86_64-20220106.xz_) is dumped to disk. Due to changes in the [kiwi-net-lib.sh](https://github.com/OSInside/kiwi/commit/282529de8f612dee32d54ee868c2365dcd829220#diff-737d484eaf4d87a23c3e04b3b3aeece6b7bf3d71f79b9589c3f1a66457a2b344), the `_is_compressed` function can't return the correct state of any external file.

[`fetch_file`](https://github.com/OSInside/kiwi/blob/282529de8f612dee32d54ee868c2365dcd829220/dracut/modules.d/99kiwi-lib/kiwi-net-lib.sh#L30) tries to detect the file type / compression but fails, because the file is not stored locally:
```bash
# xz -l http://example.com/foobar.x86_64-20220106.xz; echo $?
xz: http://example.com/foobar.x86_64-20220106.xz: No such file or directory
1
```

As we did not alter our PXE installation process and this issue came up after updating kiwi, I'm curious why this worked out in the first place:

> Just for the records I successfully pxe deployed an OEM image (using `installpxe`). 👍🏽
_Originally posted by @davidcassany in https://github.com/OSInside/kiwi/issues/1987#issuecomment-977749776_

## Expected behaviour
Image stream is decompressed first before dumped to disk.

## Steps to reproduce the behaviour
- create PXE image using the `installpxe="true"` and `<oem-unattended>true</oem-unattended>` option
- try to install the PXE image using the kernel parameter for kiwi: `rd.kiwi.install.pxe rd.kiwi.install.image=http://example.com/foobar.x86_64-20220106.xz`

## OS and Software information
+ KIWI version: 9.24.14-1.1
+ Operating system: Leap 15.2
+ OBS version: 2.10.11-lp152.78.1

**Comment by schaefi** [comment]
> fetch_file tries to detect the file type / compression but fails, because the file is not stored locally

Uhm, yes this sounds like a bad bug :( iirc you are pointing to

```
xz -l "${source_url}" &>/dev/null
```

which was formerly done by the checking the extension of the file name.

You are right this can only work if the file would be locally accessibly

Thanks much for reporting

**Comment by schaefi** [comment]
@qby-wenzel I've created a PR to address this issue. Would be great if you can take a short look, thanks much

**Comment by qby-wenzel** [comment]
@schaefi Thank you and @davidcassany for such a quick (re)action! I appreciate that very much :) I answered in the PR, too.

**Comment by davidcassany** [comment]
@qby-wenzel @schaefi my bad on testing this code. I remember I did quite few runs from ISO and PXE, I bet I did not reboot the installed machine as long as it looked like successful installation. Really sorry for that, I did not properly test it.
