### ISSUE TITLE
additionaltags for container should allow different container name

### ISSUE THREAD

**Issue by fcrozat** [OSInside/kiwi#2045]
Currently, when building container, we can only add different tag with the same containername, which prevent easy double publishing of a container.

For instance:
```xml
<preferences>
    <type image="docker">
      <containerconfig
        name="foo"
        tag="V1"
        additionaltags="V2"
```
will returns in the additional tags added to the container to be:
`foo:V2`

but if we want to ship foo container as "bar" container, we can't attach all the tags specified in the additionaltags.

We are relying on `<!-- OBS-AddTag: -->` but it isn't enough as it only propagate all additionaltags to it.

**Comment by schaefi** [comment]
I'm sure @davidcassany likes to comment on this one :)

**Comment by davidcassany** [comment]
> I'm sure @davidcassany likes to comment on this one :)

Yes :)

I just verified `skopeo` supports additional full names (aka `repo:tag`), hence it should be possible from a KIWI perspective to code it. Do you have any suggestion on how to express it?

```xml
<preferences>
    <type image="docker">
      <containerconfig
        name="foo"
        tag="V1"
        additionaltags="bar:V2,whatever:V3"/>
    </type>
</preferences>
```

Resulting to something like that after loading it to the containers storage:
```
foo:V1
bar:V2
whatever:V3
```

Also something like 
```xml
<preferences>
    <type image="docker">
      <containerconfig
        name="foo"
        tag="V1"
        additionaltags="V2,whatever:V3"/>
    </type>
</preferences>
```

should be possible to maintain backward compatibility. It would be translated to:
```
foo:V1
foo:V2
whatever:V3
```

So if `repo` section is absent in one of the additional tags, then it is assumed that it refers to `name` attribute from `containerconfig`.

Later this week I'll try to give it a close look to the code, speaking from memory, but this should be pretty straight forward to code. No schema change and just small adjustment of the `skopeo` call.

**Comment by Vogtinator** [comment]
> > I'm sure @davidcassany likes to comment on this one :)
> 
> Yes :)
> 
> I just verified `skopeo` supports additional full names (aka `repo:tag`), hence it should be possible from a KIWI perspective to code it.

Great! Question is whether that's also read correctly by OBS. If not, that might need a fix as well.

> Do you have any suggestion on how to express it?
>
> ```
> <preferences>
>     <type image="docker">
>       <containerconfig
>         name="foo"
>         tag="V1"
>         additionaltags="bar:V2,whatever:V3"/>
>     </type>
> </preferences>
> ```
> 
> Resulting to something like that after loading it to the containers storage:
> 
> ```
> foo:V1
> bar:V2
> whatever:V3
> ```
> 
> Also something like
> 
> ```
> <preferences>
>     <type image="docker">
>       <containerconfig
>         name="foo"
>         tag="V1"
>         additionaltags="V2,whatever:V3"/>
>     </type>
> </preferences>
> ```
> 
> should be possible to maintain backward compatibility. It would be translated to:
> 
> ```
> foo:V1
> foo:V2
> whatever:V3
> ```

There is a possible ambiguity there. It could also be interpreted as:

```
foo:V1
V2:latest
whatever:V3
```

> So if `repo` section is absent in one of the additional tags, then it is assumed that it refers to `name` attribute from `containerconfig`.
> 
> Later this week I'll try to give it a close look to the code, speaking from memory, but this should be pretty straight forward to code. No schema change and just small adjustment of the `skopeo` call.

**Comment by davidcassany** [comment]
> > Also something like
> > ```
> > <preferences>
> >     <type image="docker">
> >       <containerconfig
> >         name="foo"
> >         tag="V1"
> >         additionaltags="V2,whatever:V3"/>
> >     </type>
> > </preferences>
> > ```
> > 
> > should be possible to maintain backward compatibility. It would be translated to:
> > ```
> > foo:V1
> > foo:V2
> > whatever:V3
> > ```
> 
> There is a possible ambiguity there. It could also be interpreted as:
> 
> ```
> foo:V1
> V2:latest
> whatever:V3
> ```
> 

Note this would not be backward compatible. In `addtitionaltags` attribute has been only supporting tags, so adding repos to the syntax is fine, but should be clear that only setting an additional repo is not possible, it will be interpreted as a tag. Id say this is the counter part of change, probably not that obvious at a glance, but we should make it explicit in the schema docs.

**Comment by davidcassany** [comment]
> should we introduce a new attribute for the repo/tags, to preven the ambiguity ?

I don't think so, since they are tight together (`repo` and `tag`), at least not a new attribute. At most we could consider a child section, something like:

```xml
<containerconfig ...>
  <additionalnames>
     <name repo="myrepo" tag="mytag"/>
     <name repo="other" tag="othertag"/>
     ...
   </additionalnames>
</containerconfig>
```

If any of the `repo` or `tag` in `<name>` is omited we could use some sort of defaults (inherit form parent  `containerconfig` and/or just `latest` for tags).

Do you think something like that would be worth? I am no so sure, but probably makes sense.

**Comment by fcrozat** [comment]
additionalnames allows more flexibility. But I'd like to have more opinions.

**Comment by Vogtinator** [comment]
IMO something like `additionalnames`, which accepts whole names instead, makes the change in behaviour more obvious (and opt-in). IMO the `<name repo="myrepo" tag="mytag"/>` approach is too XML-y for my taste, especially as it has to be valid syntax for namespace/repo:tag anyway, which is rather tightly constrained already.

It could also accept something like `name="foo" additionalnames=":latest,:notquitelatest"` to fully supersede `additionaltags`, though that wouldn't be necessary.
