### ISSUE TITLE
buildah: tag is not really a tag but name

### ISSUE THREAD

**Issue by ignatenkobrain** [OSInside/kiwi#2050]
## Problem description

```xml
<type image="oci">
  <containerconfig name="gdc-c9s-base" tag="latest"/>
</type>
```

^ with buildah results into a container that has name `latest` which suggests that the `name` attribute is not used at all.

## Expected behaviour

`gdc-c9s-base:latest`

## Steps to reproduce the behaviour

1. Build image with above settings
2. `podman load -i …`
3. `podman images`

## OS and Software information
+ KIWI version: 9.24.19
+ Operating system: Fedora 35
+ OBS version: N/A

**Comment by Vogtinator** [comment]
Probably a difference between `oci` and `docker` image types

**Comment by davidcassany** [comment]
Having a look, KIWI only knows about OCI images so I believe this is likely to be a miss use of buildah or skopeo.

**Comment by davidcassany** [comment]
@ignatenkobrain which version of buildah are you using? I just gave a quick test on my openSUSE Leap host and it just worked as expected. I am using `buildah` v1.17. Gonna give a  test on TW which will be closer to upstream, but so far it all looks sane on my end.

**Comment by ignatenkobrain** [comment]
```
buildah-1.23.1-1.fc35.x86_64
skopeo-1.5.2-1.fc35.x86_64
```

**Comment by davidcassany** [comment]
@ignatenkobrain Sorry I over saw the image type was set to OCI. Yes, KIWI is not setting the repo for OCI images, it just sets the tag. I do not remember the details why it was coded this way, I assume skopeo and probably buildah too where not supporting it. In fact, when native containers support was coded in KIWI the `oci-archive` type was not yet supported in `skopeo`, so probably this is a legacy leftover from that time. Anyway, this should fixed, gonna provide a PR for that.

Thanks for reporting it.
