### ISSUE TITLE
Setting GID at Group Creation

### ISSUE THREAD

**Issue by dlawle** [OSInside/kiwi#2064]
## Problem description
It doesn't appear to be possible to set a GID for a group, while also setting a user/UID with a different value. If this is possible, it is poorly documented, and I've not seen how to accomplish this. 

Here's an example of my current user creation step, without any reference to GID:
```
<users>
    <user name="test" id="1001" groups="testgrp" home="/home/test" password="test" pwdformat="plain" realname="test" shell="/bin/bash"/>
    <user name="root"  groups="root" pwdformat="encrypted" password="$1$xyz$YCCZsvYCmSe.qXSOYUWkJ/" home="/root" />
</users>
```

## Expected behaviour
What I'm trying to accomplish is setting a GID for "testgrp". I'm in the process of upgrading from an old version of kiwi (7.x) to the current version. In the past (ver 7.x) we were able to accomplish this like the following example:
```
  <users group="testgrp" id="2001">
      <user home="/home/test" id="1001" name="pos" password="test" realname="test" shell="/bin/bash"/>
  </users>
```
(obviously this does not work anymore) 

In system_setup.py there does appear to be some mention of group id creation in setup_groups:
https://github.com/OSInside/kiwi/blob/2267023dbddf92bfc46a00b041f637affdca1591/kiwi/system_setup.py#L208-L223

as well as directly below in setup_users:
https://github.com/OSInside/kiwi/blob/2267023dbddf92bfc46a00b041f637affdca1591/kiwi/system_setup.py#L225-L288

Did this get stripped out from the old to new version? 

## Steps to reproduce the behaviour

I've tried a few different combinations in our XML, but nothing seems to stick. 

## OS and Software information
+ KIWI version: 9.23.20
+ Operating system: SLES 15 SP3

**Comment by schaefi** [comment]
There was a strong veto by Thorsten Kukuk back in time that kiwi should not allow setting the group ID. Unfortunately I can't remember the details, it's years ago. Maybe you can get in touch and double check. Unless the reasons are still valid I have no objections to add this.

Thanks

**Comment by dlawle** [comment]
Thanks so much @schaefi! I looked through @thkukuk's original commit 2267023dbddf92bfc46a00b041f637affdca1591 but do not see too many notes about the topic. I appreciate the quick response though!

**Comment by schaefi** [comment]
I'm going to bring this up at the community meeting

**Comment by schaefi** [comment]
we discussed this in the community meeting and decided to add support for setting the gid.

Please keep in mind that distributors provides their own way of handling groups, e.g on suse groups are provided by individual packages and it is expected that any new group is provided by such a package. From that perspective image descriptions which sets arbitrary group id's are probably not welcome. However, it's a good feature from an appliance building perspective so we are going to add it

**Comment by schaefi** [comment]
@dlawle sorry for the long delay. PR to handle this now open
