### ISSUE TITLE
FileNotFoundError at the end of the image build

### ISSUE THREAD

**Issue by prpmuc** [OSInside/kiwi#2091]
## Problem description
At the end of an oem image build I get
> FileNotFoundError: [Errno 2] No such file or directory: '.../output-iso/kiwi_boot_root.br2l25f2'

I think the reason is that in kiwi/boot/image/builtin_kiwi.py lines 80-82 should have been removed when changing the handling of temporary files in commit fc2446dfeaeb4084b2e72edaef0e08a259b58ed4

## OS and Software information
+ KIWI version: 9.24.16
+ Operating system: openSUSE Leap 15.3

**Comment by schaefi** [comment]
Can you provide your image configuration (at least the ```<type>``` setup) such that we can reproduce it locally ?

Thanks

**Comment by prpmuc** [comment]
From my config.xml:

`<type image="oem" filesystem="ext4" boot="/home/prp/kiwi-project/bootimages/oemboot/suse-leap15.0" firmware="efi" bootloader="grub2" boottimeout="30" bootkernel="custom" initrd_system="kiwi" installiso="true">`

**Comment by schaefi** [comment]
Ah I see you are using custom kiwi initrd. Out of curiosity, you do this intentionally right ? If you have no strong reasons for using a custom initrd built by kiwi I suggest to move to dracut (initrd_system="dracut" or delete the attribute as dracut is the
standard for some time)

back to the issue

There is an integration test, testing the custom kiwi initrd feature here:

* https://github.com/OSInside/kiwi/blob/master/build-tests/x86/tumbleweed/test-image-disk-legacy/appliance.kiwi
* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:tumbleweed/test-image-disk-legacy

The test is only in parts comparable to what you did but I think in case of a generic issue is should have also failed, but that test worked.

So for digging deeper into this would you mind to try a rebuild of your image using the latest version of kiwi ?
You can find it built for Leap here:

* http://download.opensuse.org/repositories/Virtualization:/Appliances:/Builder/openSUSE_Leap_15.3/

If that also shows the error we need your custom initrd description which you use from your home

```
... boot="/home/prp/kiwi-project/bootimages/oemboot/suse-leap15.0"
```

maybe you can tar it up

This information together with the type setup you already provided should allow a local reproducer

Thanks

**Comment by prpmuc** [comment]
Thank you for your feedback. I use kiwi since some years to build a custom installation medium. But I rarely have to change something in my setup and never needed a deep understanding of kiwi. So my current config has grown over the years and gets fixed when it breaks ...

I will try to reproduce the problem with the latest version of kiwi, but this might take some time.

But I think the problem is simple: In `kiwi/boot/image/builtin_kiwi.py` there is

    def prepare(self) -> None:
        """
        Prepare new root system suitable to create a kiwi initrd from it
        """
        if self.boot_xml_state:
            self.boot_root_directory_temporary = Temporary(
                prefix='kiwi_boot_root.', path=self.target_dir
            ).new_dir()
            self.boot_root_directory = self.boot_root_directory_temporary.name
            self.temp_directories.append(
                self.boot_root_directory
            )

You can see that the temporary kiwi_boot_root file gets created with `Temporary` which will also take care of removal. But the file is also added to `self.temp_directories` which leads to removal by

    def cleanup(self) -> None:
        for directory in self.temp_directories:
            if directory and os.path.exists(directory):
                Path.wipe(directory)

(also from `kiwi/boot/image/builtin_kiwi.py`) The FileNotFoundError is probably triggered when `Temporary` wants to remove the file which has already  been removed by this `cleanup`.

**Comment by schaefi** [comment]
I'm afraid I will not have time to take a deeper look into this issue and as you stated it as a "cosmetic" issue as well I hope it's ok when we close this one. Please drop me a note if there is an urgency to re-open this one. Thanks for your understanding
