### ISSUE TITLE
Unable to set filesystem type for boot partition

### ISSUE THREAD

**Issue by Conan-Kudo** [OSInside/kiwi#2092]
## Problem description
I'm trying to create cloud images that use `/boot` with ext4 or xfs and have the rest of it use Btrfs, but there's no way to set that when `bootpartition="true"`, since there's no `bootpartfstype` or similar parameter. This leads to a weird situation that's not great for interoperability purposes across RHEL and Fedora.

## OS and Software information
+ KIWI version: 9.24.24
+ Operating system: Fedora Linux 35
+ OBS version: N/A

**Comment by schaefi** [comment]
There is

```
k.type.bootfilesystem.attribute =
        ## if an extra boot partition is required this attribute
        ## specify which filesystem should be used for it. The
        ## type of the bootloader might overwrite this setting
        ## e.g for the syslinux loader fat is required
        attribute bootfilesystem {
            "ext2" | "ext3" | "ext4" | "fat32" | "fat16"
        }
```

**Comment by Conan-Kudo** [comment]
how in the world did I miss this? Also interestingly it doesn't support btrfs or xfs, but kiwi will happily do that by default...
