### ISSUE TITLE
Excluding /run from images breaks Ceph deployment in Rook-based k8s environments

### ISSUE THREAD

**Issue by tserong** [OSInside/kiwi#2093]
## Problem description

Prior to #1759 being merged, `/run` and `/tmp` were sync'd from the build root to the image. This notably meant that `/run/*` _subdirectories_ created by RPM packages as part of their postinstall scripts were also included in the built image. This is important for Ceph when deployed via Rook in Kubernetes environments (https://github.com/rook/rook/blob/master/design/ceph/ceph-config-updates.md#minimal-command-line-options points out that "...it is [...] desirable to use the /var/run/ceph path in containers"). TL;DR: without `/run/ceph` existing inside Ceph container images, those container images are unusable in a k8s/rook environment.

I do understand that we don't want weird build-time artifacts landing in container images, but given that removing everything under `/run` _also_ removes directories that might be required by software installed in the container, can this blanket exclusion be reverted? Or can we somehow add an override for directories we know we want to keep?

## Expected behaviour

Subdirectories of `/run` that were created as a result of `systemd-tmpfiles --create` when packages were installed are present in container images built with kiwi.

## Steps to reproduce the behaviour

Pull a ceph container image built with kiwi >= v9.23.21 and observe that the `/run` directory is practically empty:

```
> podman pull registry.opensuse.org/filesystems/ceph/images/opensuse/ceph/ceph
> podman run -it registry.opensuse.org/filesystems/ceph/images/opensuse/ceph/ceph /bin/bash
# ls /run
.containerenv
```

Prior to the exclusion of `/run`, you'd see something more like this:
```
# ls /run
.containerenv ceph cryptsetup faillock lock log lsm lvm motd.d nfs regenerate-initrd systemd user zabbix zypp.pid
```

Obviously having `zypp.pid` and `regenerate-initrd` in there aren't great, and I'm not sure where `nfs` came from, but all the rest (`ceph`, `cryptsetup`, `faillock`, `lock`, `log`, `lsm`, `lvm`, `motd.d`, `systemd`, `user`, and `zabbix`) are put there as a result of packages being installed in the image, so presumably should remain.

## OS and Software information
+ KIWI version: 9.24.16
+ Operating system: SLE 15 SP2
+ OBS version: Whatever is currently running on build.suse.de.

**Comment by Vogtinator** [comment]
Packages shouldn't put any content into `/run` or `/tmp` themselves, it wouldn't be visible in booting systems anyway.

Relying on specific content in `/run` or `/tmp` on bootup is a bug. Is it not possible to have rook create the directory?

**Comment by tserong** [comment]
> Packages shouldn't put any content into `/run` or `/tmp` themselves, it wouldn't be visible in booting systems anyway.

It's not packages putting content there directly, rather it's packages installing config in `/usr/lib/tmpfiles.d/`, then systemd takes care of creating directories in `/run` based on those files both at boot time (for normal systems) and also at package installation time (via rpm postisntall scripts which call `systemd-tmpfiles --create`). The problem in the container case is that there _isn't_ a boot process.

I don't know if it's possible to have rook create the directory - all I know is what's in https://github.com/rook/rook/blob/master/design/ceph/ceph-config-updates.md#minimal-command-line-options, which indicates that rook relies on the `/run/ceph` directory being present in the container:

> `--run-dir` exists for all daemons, but it is likewise more desirable to use the `/var/run/ceph` path in containers. Additionally, this directory stores only unix domain sockets, and it does not need to be persisted to the host. **We propose to simply use the `/var/run/ceph` location in containers for runtime storage of the data.** (emphasis added)

**Comment by Vogtinator** [comment]
Hm, so arguably every component by itself is behaving correctly here. Ideally the container's entrypoint would run `systemd-tmpfiles --create` or just `mkdir -p`, but I assume the entrypoint isn't actually used?

**Comment by davidcassany** [comment]
Well KIWI stopped to sync `/run`, `/tmp` and similar paths to follow FHS, as @Vogtinator already pointed. In fact the [spec](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s15.html) is pretty clear on that regard. 

> `--run-dir` exists for all daemons, but it is likewise more desirable to use the `/var/run/ceph` path in containers. Additionally, this directory stores only unix domain sockets, and it does not need to be persisted to the host. **We propose to simply use the `/var/run/ceph` location in containers for runtime storage of the data.** (emphasis added)

This is intereseting, I believe we are including `/var/*` in containers, hence this should be there if created. If `/var/run/ceph` is created in `config.sh`, then the resulting container will include it. Note that for this to happen the distro provided `/var/run` symlink to `/run` should be deleted and then create a `/var/run/cepth` directory. I doubt this is a good solution, but just to let you know there are options to include data in `/var/run` on containers.

Including an entrypoint in your container to create required temporary directories as @Vogtinator  suggested sounds like a much better approach to me and you won't have to hack around distro's default directory hierarchy.

**Comment by tserong** [comment]
> AFAICS our ceph-containers do not use the entrypoint.
> @tserong Is this an option we could use?

I'm not sure, but I doubt it. For some background for anyone unfamiliar with Ceph, it's a distributed storage system consisting of several different daemons, which you run many instances of, across many hosts in a cluster. The way Ceph uses containers, is there's one container which contains (ha!) all the Ceph binaries, and has no entrypoint defined. If you want to spin up a Ceph MON daemon, you start the Ceph container running /usr/bin/ceph-mon. If you want to start a Ceph OSD, you start the Ceph container running /usr/bin/ceph-osd, and so on for the other daemon types.

Just thinking aloud, maybe we could do an entrypoint shim which in turn ran `systemd-tmpfiles --create`, then went and ran the binary you wanted... But, that'd need to be proposed and accepted into upstream Ceph first, and also would _still_ require a change to rook, to invoke that new entrypoint rather than the various daemon binaries directly. This doesn't fix the problem we have now, which is that existing Rook users can no longer use Ceph containers built with kiwi  >= v9.23.21.

> Well KIWI stopped to sync `/run`, `/tmp` and similar paths to follow FHS, as @Vogtinator already pointed. In fact the [spec](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s15.html) is pretty clear on that regard.

I absolutely agree for regular system images (which actually have boot processes as mentioned in the FHS spec), but I think [containers](https://www.reddit.com/r/ProgrammerHumor/comments/cw58z7/it_works_on_my_machine/) are a little different, in that they're meant to have everything included inside them, that the binaries they contain _need_ in order to run. If a binary expects to write to /run/foo/bar and the /run/foo directory isn't there, then the container doesn't include everything it needs to run, i.e. the container is broken. On a normal system or virtual machine, /run/foo would have been created automatically by systemd at boot time _or_ by systemd-tmpfiles at package installation time. In a container, there's no boot process to create that structure, and the package installation magic actually happens at container _build_ time, not at container runtime, so, like I said, I think things are a little different in this specific context, which is why I'm arguing for keeping those directories around.

> This is intereseting, I believe we are including `/var/*` in containers, hence this should be there if created. If `/var/run/ceph` is created in `config.sh`, then the resulting container will include it. Note that for this to happen the distro provided `/var/run` symlink to `/run` should be deleted and then create a `/var/run/cepth` directory. I doubt this is a good solution, but just to let you know there are options to include data in `/var/run` on containers.

Oooh, that's nasty :-) I will actually try that as an immediate band-aid solution. We may be lucky in that Ceph defaults to /var/run/ceph rather than /run/ceph

**Comment by Vogtinator** [comment]
> > AFAICS our ceph-containers do not use the entrypoint.
> > @tserong Is this an option we could use?
> 
> I'm not sure, but I doubt it. For some background for anyone unfamiliar with Ceph, it's a distributed storage system consisting of several different daemons, which you run many instances of, across many hosts in a cluster. The way Ceph uses containers, is there's one container which contains (ha!) all the Ceph binaries, and has no entrypoint defined. If you want to spin up a Ceph MON daemon, you start the Ceph container running /usr/bin/ceph-mon. If you want to start a Ceph OSD, you start the Ceph container running /usr/bin/ceph-osd, and so on for the other daemon types.

Unless rook explicitly overrides the entrypoint instead of just specying a command, that will still work. e.g. if you have an image which specifies `/entrypoint.sh` as entrypoint and do `podman run image /usr/bin/ceph-mon`, it will execute `/entrypoint.sh /usr/bin/ceph-mon`. So you can have an entrypoint like this:

```
#!/bin/sh
mkdir -p /run/ceph
exec "$@"
```

**Comment by tserong** [comment]
Thanks @Vogtinator, I did not know that. I'll give it a try!

**Comment by ml8mr** [comment]
Thanks for the comments and ideas.

> Well KIWI stopped to sync `/run`, `/tmp` and similar paths to follow FHS, as @Vogtinator already pointed. In fact the [spec](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s15.html) is pretty clear on that regard.

As I read the spec, _files_ in `/run` are cleared at boot, but _directories_ are allowed. Shouldn't these directories (and their associated permissions) be preserved in the container build? The actual problem we're running into is a "permission denied" error due to the daemon being unable to create the `/run/ceph` subdirectory. (Well, the `/var/run/ceph` subdirectory, but the symlink drops `/var`.) If the directory structure was preserved in the container build, this process would work.

**Comment by tserong** [comment]
> This is intereseting, I believe we are including `/var/*` in containers, hence this should be there if created. If `/var/run/ceph` is created in `config.sh`, then the resulting container will include it. Note that for this to happen the distro provided `/var/run` symlink to `/run` should be deleted and then create a `/var/run/cepth` directory. I doubt this is a good solution, but just to let you know there are options to include data in `/var/run` on containers.

This doesn't solve the problem in the rook/k8s case. It _does_ give a `/var/run/ceph`, which ceph itself uses, but it turns out rook also looks for `/run/ceph` (and that's not configurable), so we need to keep the `/var/run` symlink to `/run`, _and_ preserve the general directory structure.

> Unless rook explicitly overrides the entrypoint instead of just specying a command, that will still work.

Unfortunately rook/k8s _does_ explicitly override the entrypoint, so that doesn't work either.

**Comment by tserong** [comment]
I've just opened #2095 which adds some rsync filtering to include the directory structure under `/run` in container builds, and only in container builds. No files will be included, only directories. No other build types are affected. As @ml8mr mentioned, the FHS spec says that it's fine to have subdirectories inside `/run`, so IMO this still adheres to the FHS. What does everyone think?
