### ISSUE TITLE
Add documentation about GRUB authorization

### ISSUE THREAD

**Issue by tbazant** [OSInside/kiwi#2115]
## Problem description
I have already described the topic in the SUSE Administration Guide (see https://github.com/SUSE/doc-sle/pull/1164/files#diff-f47b6d53eaf93443eb5f106c1b5a83389597f6f4d3fcd961bfd827f97473a1f7R726) and now would like to update upstream KIWI documentation to include it as well.

**Comment by tbazant** [comment]
@schaefi is this https://github.com/OSInside/kiwi/blob/master/doc/source/concept_and_workflow/customize_the_boot_process.rst the right to place the GRUB authorization section?

**Comment by schaefi** [comment]
Hi, thanks for making our docs better, much appreciated :+1: 

The chapter "Customizing the Boot Process" has been written to explain how a user could influence the image on the level of the initrd. I think extending it with a specific topic about bootloader authorization would not be the best place. I also think your topic deserves its own namespace.

Thus how about creating a "Working with images" topic. You can see the list of more use case specific topics here:

* https://osinside.github.io/kiwi/working_with_images.html

I would add your topic as an extra chapter to this list

What do you think ?

**Comment by tbazant** [comment]
That sounds great. Although i'm totally newbie at RST, i think i can try to create the new chapter myself, alongside its content.

**Comment by tbazant** [comment]
@schaefi BTW should i work via fork of `master` ? or  better branch (i have no rights to create it)?

**Comment by schaefi** [comment]
I have sent you an invitation, given your approval you should be able to work from a branch. Thanks much

**Comment by tbazant** [comment]
@schaefi Added a PR, please review https://github.com/OSInside/kiwi/pull/2119

**Comment by schaefi** [comment]
We moved the proposed documentation into a gist for review by the grub dev team as we believe this should be documented in grub first. On a next step we need a followup PR describing the process how to make use of this grub feature when building an image with kiwi:

* https://gist.github.com/schaefi/5ade26d4d4f6007fc6cf17b3bea01e67

**Comment by schaefi** [comment]
Closing on behalf of the gist data
