### ISSUE TITLE
RPMs from repository type 'rpm-dir' not found after zypper libzypp update

### ISSUE THREAD

**Issue by kable-wilmoth** [OSInside/kiwi#2118]
## Problem description
After applying the latest OS updates I was not able to build my appliance anymore.
I realize that this isn't necessarily a 'kiwi' issue.  Just wasn't sure where to bring this up.

The error output:
[ ERROR   ]: 15:16:56 | KiwiInstallPhaseFailed: System package installation failed: No provider of 'hacloud' found.
[ INFO    ]: 15:16:56 | Cleaning up SystemPrepare instance

The 'hacloud' RPM package is built locally and stored in a directory that is then specified as a repository.
<repository type='rpm-dir'>
   <source path='dir://{{APPLIANCE_PROJECT_ROOT}}/target/kiwi/repo/'/>
</repository>

## Expected behaviour
The RPM is found and installed as normal.

## Steps to reproduce the behaviour
On your OS have older versions of these installed, for example:
- zypper - 1.14.51-27.1
- libzypp - 17.29.4-31.1
- libsolv-tools - 0.7.20-9.2

Specify a RPM package that resided in a local repository of type='rpm-dir'
Confirm your appliance builds and the specified RPM was installed

Update the OS so that the libraries bump to their latest versions:
- libzypp=17.30.0-150200.36.1
- libsolv-tools=0.7.22-150200.12.1

Attempt to rebuild your appliance and notice your local RPM will not be found.
Rollback these libraries and your appliance will build again.

## OS and Software information
+ KIWI version: KIWI (next generation) version 9.23.20
+ Operating system: openSUSE Leap 15.3
+ OBS version: N/A

**Comment by schaefi** [comment]
seems like it's time to delete rpm-dir as a valid repo type. Actually the support for plain dir with rpms only barely worked in zypper. I guess the developers have dropped the support for this type of repo source in zypp and the solver.

Thus there is little we can do in kiwi to make it work again

My recommendation is that you create repo metadata in your plain rpm dir. It should be relatively easy. Just go to the directory containing your rpms and call

```
createrepo .
```

You have now real metadata for the packages you want to use. In the kiwi XML description you can now use this local repo with the repotype ```rpm-md``` and this will solve the dependency issues if your packages fits together with all other repos that you are using

Thoughts ?

**Comment by schaefi** [comment]
Also see #1926

**Comment by kable-wilmoth** [comment]
Agree this can be closed in favor of [#1926](https://github.com/OSInside/kiwi/issues/1926)
