### ISSUE TITLE
grub2-install mocking of /bin/true is copying host machine binary

### ISSUE THREAD

**Issue by gmoro** [OSInside/kiwi#2124]
Copy command is not run inside the chroot, and /bin/true is a symlink so you end copying the host machine file.
Noticed the problem because my /bin/true binary is linked against a newer version of glibc, what caused the binary to not being able to run.

Will provide a PR soon to run the command inside the chroot instead to guarantee we copy the right file

**Comment by schaefi** [comment]
Uh, good catch. Thanks. 

> Will provide a PR soon to run the command inside the chroot instead to guarantee we copy the right file

great :+1:

**Comment by schaefi** [comment]
@gmoro Hi, do you still plan to fix this ?
