### ISSUE TITLE
How to collect source RPMs to build an SBOM?

### ISSUE THREAD

**Issue by gk4** [OSInside/kiwi#2157]
## Problem description
As a developer I need to build an SPDIX formatted SBOM defined by the U.S. DoD.    To use the Linux Foundation's scancode tool to build an SBOM, then I need the installed source RPMs so that I can scan to collect the licenses and attributions.   I see that kiwi saves RPMs in  the /var/cache/kiwi/packages/ directory.   Is there a way to get it to also collect the source RPMs?

## OS and Software information
+ KIWI version:  9.24.23
+ Operating system:  SLES 15 SP3
+ OBS version:

**Comment by schaefi** [comment]
Hi, I think kiwi is not the right tool for your use case. As an image builder kiwi installs binary packages and operates on them to build binary images. However, kiwi has no need to operate on the source packages and thus has no code for it.

In past projects people use kiwi to create the ISO image which contains "data", data in this context could be anything also a certain structure with source rpm files as an example. So you could still use kiwi as the tool to produce you an ISO or something else but you need to write the code to download/organize the source RPMs structure yourself

At SUSE there is a project called "product builder" which implements the code to create SUSE install media. Maybe you can take a look there and see if this helps you

**Comment by schaefi** [comment]
Closing per last comment, please re-open if you have further questions, thanks
