### ISSUE TITLE
Kiwi fails to switch rpmdb backends during CentOS 8 builds

### ISSUE THREAD

**Issue by tomrund** [OSInside/kiwi#2165]
## Problem description
- Kiwi fails to run `rpm --rebuilddb` between the bootstrap and install phases
- During the image build attempt this leads to an issue with rpmdb switching between the `bdb` and `sqlite` backends
- Using the same kiwi description I'm able to successfully build CentOS 8 on Fedora 36
- This ultimately results in the image build failure below while attempting to build CentOS 8:
 
 ```
[ ERROR   ]: 21:21:21 | KiwiInstallPhaseFailed: System package installation failed: warning: Found SQLITE rpmdb.sqlite database while attempting bdb backend: using sqlite backend.
warning: Found SQLITE rpmdb.sqlite database while attempting bdb backend: using sqlite backend.
RPM: warning: Found SQLITE rpmdb.sqlite database while attempting bdb backend: using sqlite backend.
RPM: error: unable to open sqlite database /var/lib/rpm/rpmdb.sqlite for writing, sqlite support is read-only
RPM: error: cannot open Packages index using sqlite - No such file or directory (2)
RPM: error: cannot open Packages database in /var/lib/rpm
Error: Could not run transaction.

[ INFO    ]: 21:21:21 | Cleaning up SystemPrepare instance
``` 

## Expected behaviour
- Kiwi should run `rpm --rebuilddb` between the bootstrap and install phases which will allow `rpmdb` to transition between the `bdb` and `sqlite` backends which will lead to successfully installing image packages and ultimately a successful image build for CentOS 8

## Steps to reproduce the behaviour
- Use a fully patched and up to date CentOS 9 system to perform the image build attempt
- Install `epel-release` to enable the EPEL repo
- Install `kiwi-cli` and dependencies
- Attempt to build an `oem` type CentOS 8 image with kiwi as an admin user
- To use the exact template and image build commands I've used, [clone this git repo](https://github.com/tomrund/centos8-kiwi-description)
  - Clone git repo `git clone https://github.com/tomrund/centos8-kiwi-description`
  - `cd centos8-kiwi-description`
  - `dnf install -y make`
  - `make build-centos8-template-bios`
  - Optionally, run `make clean` in-between build attempts

## OS and Software information
+ KIWI version: KIWI (next generation) version 9.24.43
+ Operating system: CentOS Stream release 9
+ OBS version: N/A

**Comment by Conan-Kudo** [comment]
I'm able to reproduce the issue using kiwi from EPEL for CentOS/RHEL 9.

The issue here seems to be that on CentOS 9, we have SQLite rpmdb with read-only BDB rpmdb support, but on CentOS 8, we have the inverse: bdb rpmdb with read-only SQLite rpmdb support.

This is tripping up things because the auto-switching of backends doesn't happen in this case. We _do_ regenerate the rpmdb if we know that the dbpath differs between host and the guest, I think? We probably need to just do this unconditionally.
