### ISSUE TITLE
AlmaLinux/CentOS UEFI Live images not booting in qemu/VirtualBox/(most) pyhsical PCs

### ISSUE THREAD

**Issue by TheMasterFX** [OSInside/kiwi#2172]
## Problem description
I build a Live ISO with this kiwi config: https://github.com/OSInside/kiwi/tree/master/build-tests/x86/centos/test-image-live-disk-v8
When I try to boot the ISO in qemu in uefi mode (virt-manager => mount ISO) it doesn't  boot properly (no boot device found). I found the same problem on many physical PCs.
If I manually add a boot entry which points to /EFI/almalinux/shimx64.efi or /EFI/centos/shimx64.efi it works properly. 
Also on many physical PCs I get a message to repair the boot entrys (seems to be part of the uefi firmware)
In my opionion there is something wrong in the bootfiles structure as mentioned here: [Issue #2008](https://github.com/OSInside/kiwi/issues/2008), so maybe my issue is kind of a duplicate.
As mentioned by _ignatenkobrain_ in his issue the structure of a "official ISO" seems to be different.
I tried to modify the boot structure by using the editbootinstall script, but this only works on OEM images, not (Live)ISO, even this don't might have worked since the efi-partition for the ISO is build in a different loop-device/folder as the appliance itself. 
I even have the problem with CentOS 7.

This is what Kiwi generates in the EFI folder
```
$ sudo tree -s /mnt/EFI/
/mnt/EFI/
├── [       2048]  almalinux
│   ├── [        122]  BOOTX64.CSV
│   ├── [       2048]  fonts
│   │   └── [    2560080]  unicode.pf2
│   ├── [        141]  grub.cfg
│   ├── [    2219032]  grubx64.efi
│   ├── [     850232]  mmx64.efi
│   ├── [     922832]  shimx64-almalinux.efi
│   └── [     925424]  shimx64.efi
└── [       2048]  BOOT
    ├── [     922832]  bootx64.efi
    ├── [     925424]  BOOTX64.EFI
    ├── [      90296]  fbx64.efi
    ├── [        141]  grub.cfg
    ├── [    2219032]  grubx64.efi
    └── [     850232]  mmx64.efi

3 directories, 13 files
```
This is what we found on the official AlmaLinux Install ISO
```
$ sudo tree -s /mnt/EFI/
/mnt/EFI/
└── [       2048]  BOOT
    ├── [       1351]  BOOT.conf
    ├── [     737696]  BOOTIA32.EFI
    ├── [     925424]  BOOTX64.EFI
    ├── [       2048]  fonts
    │   ├── [        223]  TRANS.TBL
    │   └── [    2560080]  unicode.pf2
    ├── [       1351]  grub.cfg
    ├── [    1486872]  grubia32.efi
    ├── [    2300440]  grubx64.efi
    ├── [     676120]  mmia32.efi
    ├── [     850232]  mmx64.efi
    └── [       1995]  TRANS.TBL

2 directories, 11 files
```
So I think  BOOTX64.EFI is in reality the shimx64.efi, but Kiwi has two files upper and lowercase BOOTX64.EFI while the lowercase is smaller in size like the shimx64-almalinux.efi. So maybe this is the issue. Also Live ISO should not create a bootentry (I think this is done via BOOTX64.CSV !? So maybe the best way to fix it is to keep the structure as flat as the original ISOs!?
## Expected behaviour
ISO is booted properly on UEFI devices
## Steps to reproduce the behaviour
Build image with [this config](https://github.com/OSInside/kiwi/tree/master/build-tests/x86/centos/test-image-live-disk-v8) and boot with qemu in uefi mode or try to boot on physical device (some might work, HP Notebooks doesn't in 80% of the cases)
## OS and Software information

* KIWI version: 9.24.45-1
* Operating system host version: AlmaLinux 8.6 / CentOS 7.9
* Operating system target version: AlmaLinux 8.6 / CentOS 7.9
* Open Build Service version (N/A if not using OBS): N/A
* Koji version (N/A if not using Koji): N/A

**Comment by schaefi** [comment]
most probably because we don't yet support the almalinux vendor directory:

* https://github.com/OSInside/kiwi/blob/master/kiwi/defaults.py#L994

**Comment by TheMasterFX** [comment]
With CentOS 8.5 it looks almost the same to mee.
Normally the EFI Partition is FAT32, so there shouldn't (couldn't) be two files with the same name only differ in upper/lowercasse
```

├── [       2048]  BOOT
│   ├── [    1238416]  bootx64.efi
│   ├── [    1244496]  BOOTX64.EFI
│   ├── [     362264]  fbx64.efi
│   ├── [        141]  grub.cfg
│   ├── [    2285848]  grubx64.efi
│   └── [    1162400]  mmx64.efi
└── [       2048]  centos
    ├── [        134]  BOOTX64.CSV
    ├── [       2048]  fonts
    │   └── [    2560080]  unicode.pf2
    ├── [        141]  grub.cfg
    ├── [    2285848]  grubx64.efi
    ├── [    1162400]  mmx64.efi
    ├── [    1238416]  shimx64-centos.efi
    └── [    1244496]  shimx64.efi

```

**Comment by TheMasterFX** [comment]
This is what CentOS 7 Live ISO looks like (which also makes problems)
```
$ sudo tree -s /media/EFI/
/media/EFI/
├── [       2048]  BOOT
│   ├── [    1243864]  bootx64.efi
│   ├── [    1243864]  BOOTX64.EFI
│   ├── [     362232]  fallback.efi
│   ├── [     362232]  fbx64.efi
│   ├── [        141]  grub.cfg
│   ├── [    1122120]  grubx64.efi
│   └── [    1154640]  mmx64.efi
└── [       2048]  centos
    ├── [        134]  BOOT.CSV
    ├── [        134]  BOOTX64.CSV
    ├── [       2048]  fonts
    │   └── [    2560080]  unicode.pf2
    ├── [       2048]  fw
    ├── [      70640]  fwupia32.efi
    ├── [      80072]  fwupx64.efi
    ├── [        141]  grub.cfg
    ├── [    1122120]  grubx64.efi
    ├── [    1154640]  mmx64.efi
    ├── [    1154640]  MokManager.efi
    ├── [    1243864]  shim.efi
    ├── [    1237824]  shimx64-centos.efi
    └── [    1243864]  shimx64.efi

4 directories, 19 files
```

**Comment by TheMasterFX** [comment]
According to the [Shim Documentation](https://github.com/rhboot/shim/blob/main/README.fallback) Live Images and removable media (which are also install ISOs) should not use a boot.csv. Structure should look like:
```
The FS layouts are like this:

for removable media:
\EFI\BOOT\BOOTX64.EFI <-- shim
\EFI\BOOT\MokManager.efi
\EFI\BOOT\grubx64.efi
\EFI\BOOT\grub.cfg

for an installed system:
\EFI\BOOT\BOOTX64.EFI    <-- shim
\EFI\BOOT\MokManager.efi
\EFI\BOOT\fallback.efi
\EFI\fedora\BOOT.CSV
\EFI\fedora\shim.efi
\EFI\fedora\MokManager.efi
\EFI\fedora\grubx64.efi
\EFI\fedora\grub.cfg
```
So they should look like an original Install/Boot ISO. Seems to be generated wrong from Kiwi on CentOS (7+8), Almalinux, Fedora at least.

**Comment by schaefi** [comment]
Sorry for the long delay. I was looking into this issue and tried to reproduce it with the CentOS stream test images that we built. I used the Stream 9 test from here as the base for my testing:

* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:centos/test-image-live-disk-v9

I used the Live image that we built there and booted it in several modes:

```
# Secure Boot mode with ISO as ISO
kvm -bios /usr/share/qemu/ovmf-x86_64-ms.bin -cdrom kiwi-test-image-live-disk-v9.x86_64-1.3.0-Live-Build41.2.iso

# Secure Boot mode with ISO as disk
kvm -bios /usr/share/qemu/ovmf-x86_64-ms.bin -drive file=kiwi-test-image-live-disk-v9.x86_64-1.3.0-Live-Build41.2.iso,if=virtio

# BIOS mode with ISO as ISO
kvm -cdrom kiwi-test-image-live-disk-v9.x86_64-1.3.0-Live-Build41.2.iso

# BIOS mode with ISO as disk
kvm -hda kiwi-test-image-live-disk-v9.x86_64-1.3.0-Live-Build41.2.iso
```

In all of this cases the system boots up. So I was not able to see the issues you saw. The contents of /boot are as follows

```
CentOS Stream 9
Kernel 5.14.0-283.el9.x86_64 on an x86_64

localhost login: root
Password: 
[root@localhost ~]# find /boot
/boot
/boot/config-5.14.0-283.el9.x86_64
/boot/System.map-5.14.0-283.el9.x86_64
/boot/grub2
/boot/grub2/earlyboot.cfg
/boot/grub2/grubenv
/boot/grub2/fonts
/boot/grub2/fonts/unicode.pf2
/boot/symvers-5.14.0-283.el9.x86_64.gz
/boot/vmlinuz-5.14.0-283.el9.x86_64
/boot/.vmlinuz-5.14.0-283.el9.x86_64.hmac
/boot/loader
/boot/loader/entries
/boot/loader/entries/1c53ff79b638430d838228f998df14f0-5.14.0-283.el9.x86_64.conf
/boot/efi
/boot/efi/EFI
/boot/efi/EFI/BOOT
/boot/efi/EFI/BOOT/fbx64.efi
/boot/efi/EFI/BOOT/BOOTX64.EFI
/boot/efi/EFI/centos
/boot/efi/EFI/centos/BOOTX64.CSV
/boot/efi/EFI/centos/grubx64.efi
/boot/efi/EFI/centos/shimx64-centos.efi
/boot/efi/EFI/centos/shimx64.efi
/boot/efi/EFI/centos/mmx64.efi
/boot/initramfs-5.14.0-283.el9.x86_64.img
```

Given that I don't see an issue with booting here I don't know what needs to be changed.

I repeated the same test with the CentOS8 test image from here:

* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:centos/test-image-live-disk-v8

Also this images was able to bootup in the modes listed above

The CentOS 7 code base is EOL for kiwi, thus I did not had a closer look regarding this code stream

Do you have an image build available which allows us to reproduce the issue ?

Thanks
