### ISSUE TITLE
[docs]Where can I find the document on strip files/libs/tools features

### ISSUE THREAD

**Issue by TommyLike** [OSInside/kiwi#2173]
## Problem description
Kiwi support strip files, libs and tools, where can I find the document on this? 
official documentation [here](https://osinside.github.io/)
## OS and Software information

* KIWI version: 
* Operating system host version: 
* Operating system target version: 
* Open Build Service version (N/A if not using OBS): 
* Koji version (N/A if not using Koji):

**Comment by TheMasterFX** [comment]
You this [THIS](https://osinside.github.io/kiwi/concept_and_workflow/shell_scripts.html?highlight=config+sh#functions)?

**Comment by TommyLike** [comment]
> You mean this [THIS](https://osinside.github.io/kiwi/concept_and_workflow/shell_scripts.html?highlight=config+sh#functions)?

ok, thanks!
