### ISSUE TITLE
Overlay archives overwrites symlinks (rootfs overlay) which leads potential to KiwiKernelLookupError 

### ISSUE THREAD

**Issue by TheMasterFX** [OSInside/kiwi#2176]
## Problem description
When using a Root FS Overlay,  either as folder or root.tar.gz or as archive, the contents overwrite symlinks which might lead to an error at build `KiwiKernelLookupError: No kernel found in /home/kiwi_build/alma/build/image-root/boot, searched for`
Since [#2032](https://github.com/OSInside/kiwi/commit/26f18b7a2a31001de9bdbce569c6fdb1ffa7b839) the "/lib/modules" directory is checked which leads in case of CentOS/AlmaLinux with a overlay which has a "/lib" folder to a not available modules folder since they are symlinks to /usr/lib"
Without that check it builds fine, but of cause the /lib-symlink is still overwritten.
Strictly speaking this isn't really a bug in kiwi, but a fault from the user by putting the overlay wrong together. 
## Expected behaviour
Symlinks in /lib or /lib64 are not overwritten by overlay files but copied in the linked folder (at least system symlinks at "/" if already definded)
Or maybe at least put a warning in the log that a symlink was overwritten by the overlay, so the user can check if it is wanted or not.
## Steps to reproduce the behaviour
Create a root or root.tar.gz or include archive package via xml with "lib-folder" included 
## OS and Software information

* KIWI version: 9.24.45-1
* Operating system host version: AlmaLinux 8.6 / CentOS 7.9
* Operating system target version: AlmaLinux 8.6 / CentOS 7.9
* Open Build Service version (N/A if not using OBS): N/A
* Koji version (N/A if not using Koji): N/A

**Comment by schaefi** [comment]
Hmm, I'm not sure if we should add any smart intelligence here. Actually the overlay tree is copied as it is using a sync mechanism. It imho should be clear to people that you can shoot yourself in the foot with this. I think if we add any restrictions or smart checks it will strike back at some point in the future.
