### ISSUE TITLE
Passing config options for vmware

### ISSUE THREAD

**Issue by sundowner69** [OSInside/kiwi#2177]
Hi,
I am building ova templates for SLES15SP3 that should be imported by vsphere. Though I set firmware to "efi", the VM always comes up booting from BIOS instead of EFI. 

I would like to insert config options for the vm into the ovf file like:
<vmw:Config ovf:required="false" vmw:key="firmware" vmw:value="efi"/>

Is that possible with kiwi or do I have to tear apart the ova and edit the ovf manually?

Thanks for your kind feedback!

* KIWI version: 9.24.17
* Operating system host version: SLES15 SP4
* Operating system target version: SLES15 SP3

**Comment by TheMasterFX** [comment]
Shouldn't this be possible via
<vmconfig-entry>firmware= "efi"</vmconfig-entry>

**Comment by sundowner69** [comment]
Thought that I read the whole document alt least twice but did not see it. Worked like a charm. 
Thank you very much!
