### ISSUE TITLE
"Failed to kexec boot system" when using PXE with AlmaLinux 8.6

### ISSUE THREAD

**Issue by TheMasterFX** [OSInside/kiwi#2178]
## Problem description
I'm building a PXE image with AlmaLinux 8.6. When I install the image, it does install the .xz image and verifies it. After that I get the message "Failed to kexec boot system". I tried to debug with "rd.debug rd.shell rd.kiwi.debug" bit I did't get any useful information what exactly happens.
When I reboot the just installed system it just boots up fine.

What I realized in the build log, that the dracut-install failed due to non existent btrfs and btrfsck, but I don't know if that is a problem:
```
dracut-install: ERROR: installing 'btrfs'
dracut-install: ERROR: installing 'btrfsck'
dracut: FAILED: /usr/lib/dracut/dracut-install -D /var/tmp/dracut.CfWdtq/initramfs -a blkid blockdev dd mkdir rmdir grep cut tail head tr bc true false mountpoint basename partprobe sfdisk sgdisk mkswap readlink lsblk btrfs xfs_growfs resize2fs e2fsck btrfsck xfs_repair vgs vgchange lvextend lvcreate lvresize pvresize mdadm cryptsetup dialog pv curl xz dmsetup
```
## Expected behaviour
Appliance is installed without any error.

## Steps to reproduce the behaviour
Use this [Receipe](https://github.com/OSInside/kiwi/tree/master/build-tests/x86/centos/test-image-live-disk-v8), add PXE profile:
```
...
<profiles>
    ...
    <profile name="PXE" description="PXE image"/>
</profiles>
....
<preferences profiles="PXE">
         <type image="oem" initrd_system="dracut" filesystem="ext3" installpxe="true" firmware="bios" kernelcmdline="console=ttyS0" bootloader="grub2">
            <oemconfig>
                <oem-systemsize>2048</oem-systemsize>
                <oem-swap>true</oem-swap>
                <oem-swapsize>200</oem-swapsize>
                <oem-multipath-scan>false</oem-multipath-scan>
            </oemconfig>
        </type>
    </preferences>

... 
    <packages type="image" profiles="PXE">
        <package name="dracut-kiwi-oem-repart"/>
        <package name="dracut-kiwi-oem-dump"/>
    </packages>
```
Build the image and boot with the following pxelinux.cfg/default
```
DEFAULT KIWI-Boot

LABEL KIWI-Boot
    kernel boot/pxeboot.kernel
	append initrd=boot/pxeboot.initrd rd.shell rd.debug rd.kiwi.debug rd.kiwi.install.pxe rd.kiwi.install.image=http://192.168.140.1/image/AlmaLinux-8_appliance.x86_64-1.2.0.xz
	IPAPPEND 2
```

## OS and Software information

* KIWI version: 9.24.45-1
* Operating system host version: AlmaLinux 8.6
* Operating system target version: AlmaLinux 8.6
* Open Build Service version (N/A if not using OBS): N/A
* Koji version (N/A if not using Koji): N/A

**Comment by schaefi** [comment]
Can this be related to #2155

**Comment by schaefi** [comment]
You can double check how kexec is called by unpacking your initrd and looking at the code there

```
lsinitrd --unpack ...
```

**Comment by TheMasterFX** [comment]
Hi,
thanks for the reply. Where do I have to look exactly?
Not too much kexec-stuff in initrd
```
$ grep -rn kexec
shutdown:25:# if "kexec" was installed after creating the initramfs, we try to copy it from the real root
shutdown:27:if [ "$ACTION" = "kexec" ] && ! command -v kexec >/dev/null 2>&1; then
shutdown:29:        cp -a /oldroot/${p}/kexec $p >/dev/null 2>&1 && break
shutdown:31:    hash kexec
shutdown:118:    kexec)
shutdown:119:        kexec -e
Binary file usr/bin/systemctl matches
Binary file usr/lib/systemd/libsystemd-shared-239.so matches
usr/lib/systemd/system/kexec.target:11:Description=Reboot via kexec
usr/lib/systemd/system/kexec.target:14:Requires=systemd-kexec.service
usr/lib/systemd/system/kexec.target:15:After=systemd-kexec.service
usr/lib/systemd/system/plymouth-kexec.service:2:Description=Show Plymouth Reboot with kexec Screen
usr/lib/systemd/system/plymouth-kexec.service:4:Before=systemd-kexec.service
usr/lib/systemd/system/systemd-kexec.service:11:Description=Reboot via kexec
usr/lib/systemd/system/systemd-kexec.service:19:ExecStart=/usr/bin/systemctl --force kexec
```

**Comment by phillxnet** [comment]
I don't know if this will help, but I've just linked to our own issue with a recent kiwi-ng (details in issue) which looks very similar to this one. Apologies if this is just noise and for not really adding much info as yet. I had to first remove some kipple from our kiwi-ng config before I could reasonably report the kexec issue here. @TheMasterFX beat me to the report. Our base OS and build host is openSUSE Leap 15.3 which may help to rule some stuff out.

**Comment by TheMasterFX** [comment]
I just build the same image with CentOS 8.5 and it is the same behavior.

**Comment by TheMasterFX** [comment]
Just tried same appliance xml with CentOS 8.5 with Kiwi 9.24.45, Kiwi 9.24.38 and Kiwi 9.24.36. All the same behavior. I would like to help but I need to know what to look for.

**Comment by phillxnet** [comment]
@TheMasterFX 

> Kiwi 9.24.36

Does look to be before @schaefi suspected change referenced above in comment: https://github.com/OSInside/kiwi/issues/2178#issuecomment-1199245734

> * Mon Jun 13 2022 Marcus Schäfer <marcus.schaefer@gmail.com>
> - Prefer file based syscall in kexec when possible
>   Use file based syscall in kexec if available. This is needed to
>   support boot on an secure boot enabled system and is in general
>   more reliable to boot into the system on real hardware platforms
> 
> * Mon Jun 13 2022 Marcus Schäfer <marcus.schaefer@gmail.com>
> - Bump version: 9.24.41 → 9.24.42
> 
> * Thu Jun 09 2022 Marcus Schäfer <marcus.schaefer@gmail.com>
> - Bump version: 9.24.40 → 9.24.41
> 

At least in my Virtualization_Appliances_Builder package changelog.

There are some earlier changes potentially in this area regarding oem type, and I think pxe images also but don't know, regarding honouring oem specific settings that I referenced in my linked issue, repeated here for ease:

"Fixed handling of oem reboot settings"

https://github.com/OSInside/kiwi/pull/2055

Not sure if these newly re-enabled settings are even relevant to your pxe type re:

> I personally don't need the direct boot of the installed Linux via kexec. A reboot would be okay for me.

See: https://documentation.suse.com/kiwi/9/single-html/kiwi/index.html#oem-customize

but I think I remember some combining of pxe and oem types or something along those lines. Sorry bit foggy on that front.

Changelog I have for reference on this oem change is here (not entirely sure which version Bump is relevant I'm afraid):

> * Mon Feb 07 2022 Marcus Schäfer <marcus.schaefer@gmail.com>
> - Bump version: 9.24.21 → 9.24.22
> 
> * Mon Feb 07 2022 Marcus Schäfer <marcus.schaefer@gmail.com>
> - Revert "Revert "Fixed MicroOS build test""
>   This reverts commit 8c4464b8ff2af2642439ce92e1e2be497f2b0f4d.
>   snapper default config has moved from /etc to /usr/share
>   now hopefully for the last time
> 
> * Mon Feb 07 2022 Marcus Schäfer <marcus.schaefer@gmail.com>
> - Fixed unit tests
>   The pytest interface setup() method call has changed
>   in a way that an additional parameter is passed to
>   the method which leads to a python error at invocation
>   time if the setup method does not define it.
> 
> * Mon Feb 07 2022 Neal Gompa <ngompa@centosproject.org>
> - build-tests: Update CentOS 8 test appliance to CentOS Stream 8
>   CentOS Linux 8 is now EOL, so switch over to CentOS Stream 8.
> 
> * Fri Feb 04 2022 Marcus Schäfer <marcus.schaefer@gmail.com>
> - Fixed handling of oem reboot settings
>   There are oem settings called oem-reboot, oem-reboot-interactive
>   as well as oem-shutdown and oem-shutdown-interactive. When used
>   the information is passed along to the profile but not evaluated
>   by any initrd code. I don't know where on the way we lost the
>   code that actually works with these settings but this commit
>   makes them effective. This Fixes #2056
> 
> * Thu Feb 03 2022 Dirk Müller <dirk@dmllr.de>
> - treat armv8l as armv7hl
>   openSUSE switched from armv7hl buildworkers to aarch64 in 32bit mode
>   which identifies itself as "armv8l" in uname -m.
> 
> * Tue Feb 01 2022 Marcus Schäfer <marcus.schaefer@gmail.com>
> - Bump version: 9.24.20 → 9.24.21

But testing a python3-kiwi version of say 9.24.20 or before may be worth a try to help narrow this down.

The last installer build I did that worked as it used to, i.e. kexec would successfully pass control to the installed image from an oem iso installer (for our image/kiwi-ng anyway) was I think before this Feburary update. I think, on initial guess and log zypper logs, I may have at the time used 9.21.7-lp152.5.7.1 and have since done a 15.2 to 15.3 dup on that machine.

I'll try downgrading here and see if I can narrow this down a tad.
@TheMasterFX It would be good if you could try older versions of kiwi-ng than you already have done, if you have the ability.
It will hopefully help in narrowing down this issue. Or it may just be we are now expected to declare this behaviour, or the old kexec hand-off to installed image is no longer supported. I really don't know as I am not a kiwi-ng developer but I, like you, would like to help out where I can, if I can.

All above is currently guess work I'm afraid. I'll update here if I find anything more promising.

**Comment by FroggyFlox** [comment]
Thanks @phillxnet, ... there may also be an earlier report of a similar behavior: https://github.com/OSInside/kiwi/issues/2013. This one was using 9.24.15-1, but couldn't be reproduced.

**Comment by phillxnet** [comment]
Just tested our own affected profile with at least python3-kiwi downgraded to be before the oem config changes I commented on before:
```
zypper se -s | grep "^i....python3-kiwi\|^i....kiwi-tools"
i  | kiwi-tools                                                    | package    | 9.24.45-lp153.1.1                                                 | x86_64 | Virtualization_Appliances_Builder
i+ | python3-kiwi                                                  | package    | 9.24.17-150100.3.50.1                                             | x86_64 | repo-sle-update
```
and still see the kexec issue.

**Comment by schaefi** [comment]
> Hi, thanks for the reply. Where do I have to look exactly? Not too much kexec-stuff in initrd

thanks for the offer. Here is a procedure that should lead you the code in question. According to your PXE setup I
see the following setting

```
... append initrd=boot/pxeboot.initrd ...
```

I assume your PXE server serves this from /srv/tftpboot/boot/pxeboot.initrd

Take this initrd file and copy it to some sub-directory. From there call the following

```
lsinitrd --unpack pxeboot.initrd
```

The code in question is now found here

```
./lib/dracut/hooks/pre-mount/40-kiwi-dump-reboot-system.sh:
```

If you are there you can add some debug code if you like or you can see that it's older compared to what you find in:
https://github.com/OSInside/kiwi/blob/master/dracut/modules.d/99kiwi-dump-reboot/kiwi-dump-reboot-system.sh

Hope this helps to get you started

Would be good if we can sort that one out

Thanks much

**Comment by TheMasterFX** [comment]
In both cases (Alma 8.6 and CentOSS 8.5) there is no lib/dracut/hooks/pre-mount/40-kiwi-dump-reboot-system.sh

**Comment by schaefi** [comment]
Hmm, something is weird. The way I deploy a disk image via PXE is documented here:

* https://osinside.github.io/kiwi/building_images/build_expandable_disk.html#network-deployment

I was under the impression that you used this concept in some way shape or form. In this case there must be an initrd which drives the deployment based on kiwi code. If this is not the case we are probably talking about different things ?

Please clarify, thanks

**Comment by TheMasterFX** [comment]
Oh sorry, I extraced the wrong initrd, my fault.
Of cause there is a 40-kiwi-dump-reboot-system.sh now. 
And yes I use the pxe environment as described, so pxelinux*.kernel and pxelinux*.initrd are copied in the tftproot, otherwise it it doesn't even try to install the image.

I added some debug prints kxec_options, boot_options and added "--debug" to kexec. Here is what I got:
```
DEBUG: kexec boot-options: console=ttyS0 root=UUID=9da1c9fe-67d3-4612-a378-23fe6baaf6b9 rd.kiwi.debug
DEBUG: keyec options:  --kexec-syscall-auto
# This is the output of
# kexec "${kexec_options}" \
#        --debug \
#        --load /run/install/boot/*/loader/linux \
#        --initrd /run/install/initrd.system_image \
#        --command-line "${boot_options}" &>> /tmp/kexec.debug
Try gzip decompression.
Cannot open ` --kexec-syscall-auto': (null)
Try LZMA decompression.
Cannot open ` --kexec-syscall-auto'
Cannot open ` --kexec-syscall-auto': No such file or directory
```
So it seems like kexec tries to load linux or the initrd from /run/install, trues to open it with gzip and lzma and then fails. Maybe the kernel or initrd is compressed in a different way like in the past?

**Comment by FroggyFlox** [comment]
Thanks a lot for all the debug, @TheMasterFX !

I'll see if I can follow your approach and reproduce your observations when installing from an ISO image but in the meantime I noticed something most likely stupid, but I felt I needed to ask in case it's relevant.
The definition of `${kexec_options}` include a space...
https://github.com/OSInside/kiwi/blob/29b1fe0c53d9ca60afd3a871b9eab15f129fd6a2/dracut/modules.d/99kiwi-dump-reboot/kiwi-dump-reboot-system.sh#L60

... and from your debug output, it seems it creates an extra space (double space) after the `kexec` call:
```
Cannot open ` --kexec-syscall-auto': No such file or directory
(or)
Cannot open ` --kexec-syscall': No such file or directory
```
Could this extra space be the culprit here?
My apologies if I'm just wasting everybody's time here as I'm not familiar at all with `kexec`, but I thought it would be worth asking nonetheless...

**Comment by TheMasterFX** [comment]
> The definition of `${kexec_options}` include a space...
> 
> https://github.com/OSInside/kiwi/blob/29b1fe0c53d9ca60afd3a871b9eab15f129fd6a2/dracut/modules.d/99kiwi-dump-reboot/kiwi-dump-reboot-system.sh#L60
> 
> ... and from your debug output, it seems it creates an extra space (double space) after the `kexec` call:

Dude... you nailed it. I removed the space and now it works, I even tried --kexec-syscall instead and --kexec-syscall-auto and both work! (kind of strange)

**Comment by phillxnet** [comment]
@TheMasterFX Re:

> Dude... you nailed it. I removed the space and now it works, I even tried --kexec-syscall and --kexec-syscall-auto and both work! (kind of strange)
> Good catch @phillxnet

Thanks but the 'space' catch was not me but the venerable @FroggyFlox ;).
Nice catch @FroggyFlox 
I'm still behind the times on this one I'm afraid.

**Comment by TheMasterFX** [comment]
Mmh, kexec has kind of a strange behavior here with a empty variable
If I do
```
# kexec_options=""
# kexec "${kexec_options}" --load /run/install/boot/*/loader/linux --initrd /run/install/initrd.system_image --command-line "${boot_options}"
Cannot open `': No such file or directory
```
=> doesn't work

If I do
```
# kexec_options=""
# kexec "${kexec_options}"--load /run/install/boot/*/loader/linux --initrd /run/install/initrd.system_image --command-line "${boot_options}"
```
=> works
If I do
```
# kexec_options=" "
# kexec "${kexec_options}"--load /run/install/boot/*/loader/linux --initrd /run/install/initrd.system_image --command-line "${boot_options}"
Cannot open ` ': No such file or directory
```
=> doesn't work

If I remove the kexec_options
```
# kexec --load /run/install/boot/*/loader/linux --initrd /run/install/initrd.system_image --command-line "${boot_options}"
Cannot open ` ': No such file or directory
```
=> works
If I add some blanks
```
# kexec      --load /run/install/boot/*/loader/linux --initrd /run/install/initrd.system_image --command-line "${boot_options}"
```
=> works

**Comment by schaefi** [comment]
> > The definition of `${kexec_options}` include a space...
> > https://github.com/OSInside/kiwi/blob/29b1fe0c53d9ca60afd3a871b9eab15f129fd6a2/dracut/modules.d/99kiwi-dump-reboot/kiwi-dump-reboot-system.sh#L60
> > 
> > ... and from your debug output, it seems it creates an extra space (double space) after the `kexec` call:
> 
> Dude... you nailed it. I removed the space and now it works, I even tried --kexec-syscall and --kexec-syscall-auto and both work! (kind of strange) Good catch @phillxnet
> 
> @schaefi How could a fix look like? Just trim whiltespace _kexec_options_?

Oh God, what a stupid mistake from my side. Thanks for hunting this down. From a fixing perspective I would change the option construction such that it looks like this

```bash
if [ -n "${kexec_options}" ];then
    kexec_options="${kexec_options} --kexec-syscall-auto"
else
    kexec_options="--kexec-syscall-auto"
fi
```

This should prevent adding spaces

Alternatively we could also consider to simply overwrite kexec_options without care for its current value. That's because currently kexec_options always starts empty and only checks for one option. It's likely that there will be more options in the future to pass along according to conditions but we could add the more complex solution when it's actually needed. At the moment a simple

```bash
if kexec --help | grep -q kexec-syscall-auto;then
    kexec_options="--kexec-syscall-auto"
fi
```

would also fix it

**Comment by schaefi** [comment]
I'm currently on vacation :) so looking into this when I'm back. Feel free to create a PR as you see fit, contributions are very much appreciated. Thanks much

**Comment by schaefi** [comment]
going to create PR to fix it...
