### ISSUE TITLE
ISO Built with EFI Firmware Won't Boot in UEFI-only Mode

### ISSUE THREAD

**Issue by zohourih** [OSInside/kiwi#2181]
## Problem description
We are building SLES 15.3 ISOs with "firmware" set to "efi", but the resulting ISOs are not detectable as bootable on UEFI-only systems. The following is the relevant part of the description:

```
	<preferences profiles="Disk">
		<type image="oem" filesystem="ext4" initrd_system="dracut" installiso="true" kernelcmdline="splash" firmware="efi">
			<bootloader name="grub2" console="gfxterm" timeout="30"/>
		</type>
	</preferences>
```

If we switch boot mode to DUAL or Legacy in BIOS, the ISO can boot and after the OS is installed, then we can switch back to UEFI-only mode in which case the OS will still boot up just fine.

Note that we are mounting the ISO file via IPMI, so this is not a DVD burning issue or something similar. The standard SLES 15.3 ISO is detected and boots up just fine on the same system with BIOS boot mode set to UEFI-only.

Is there some specific step we need to take to make the ISO bootable in UEFI-only mode?

## Expected behaviour
ISOs built with "efi" firmware should boot in UEFI-only environment.

## Steps to reproduce the behaviour
1. Build an SLES 15.3 ISO with the description posted above
2. Mount the ISO file in a VM or burn it on a DVD
3. Set boot mode in BIOS to UEFI
4. The ISO/DVD will not be detected as bootable

## OS and Software information

* KIWI version: 9.24.31
* Operating system host version: SLES 15.3
* Operating system target version: SLES 15.3
* Open Build Service version (N/A if not using OBS): N/A
* Koji version (N/A if not using Koji): N/A

**Comment by zohourih** [comment]
Any help or pointers on resolving this issue would be appreciated.

**Comment by schaefi** [comment]
> Is there some specific step we need to take to make the ISO bootable in UEFI-only mode?

yes you need to use shim and the signed loader. Change the attribute ```firmware="efi"``` to ```firmware="uefi"``` that should make it work for the secure boot case and any other
