### ISSUE TITLE
Dracut Re-Part/fsck Race Conditions Still Exist

### ISSUE THREAD

**Issue by TheMisanthropicHumanist** [OSInside/kiwi#2185]
## Problem description
Some hardware simply takes an unusual amount of time to detach/re-attach disks during execution of this area of the code on post-deployment reboots. Even with the prior fix implemented, we still see situations where the Root Device isn't available in the expected location when the `fsck` SystemD Service starts.

## Expected behaviour
Root Device is reachable before `fsck` Service starts after repartitioning

## Steps to reproduce the behaviour
Deploy a PXE Bootable OEM Expandable Disk Image of SLES 12 SP5 (Or probably anything, really.) on certain older hardware and wait until the post-deployment reboot (Not counting the reboot triggered at the end of the deployment.)

## OS and Software information
SLES 12 SP5 +-
Older Hardware

* KIWI version: 9.24 +-
* Operating system host version: SLES 15 SP2
* Operating system target version: SLES 12 SP5
* Open Build Service version (N/A if not using OBS): N/A
* Koji version (N/A if not using Koji): N/A

**Comment by TheMisanthropicHumanist** [comment]
So it appears the surprise Race Condition in this case may also/instead be related to having 2 SATA Drives that have to be detached/reattached. This could be happening synchronously under the hood, or otherwise it may just take longer than expected to detach/re-attach 2 SATA Drives.

**Comment by schaefi** [comment]
Hmm, can you try if setting ```DEVICE_TIMEOUT=seconds``` helps to change the behavior ? Our default is set to 60 seconds

The storage wait in the kiwi initrd code uses  ```udevadm settle --timeout=DEVICE_TIMEOUT``` followd by a check for ```blockdev --getsize64``` to return a value > 0. I thought this should be a relatively safe wait period for block devices of any kind, but obviously I'm wrong

I'm sorry at the moment I don't know how to get this race free. We need to understand the exact reason I guess

**Comment by schaefi** [comment]
closing due to no further details provided
