### ISSUE TITLE
[Enhancement] openSUSE - currently only persistent grub options available

### ISSUE THREAD

**Issue by Mexit** [OSInside/kiwi#2188]
## Problem description
Current grub menu (openSUSE-Leap-15.4-Rescue-CD-x86_64-Build7.23-Media.iso):
```
openSUSE Leap 15.4 Rescue CD
Failsafe -- openSUSE Leap 15.4 Rescue CD
Mediacheck
Boot from Hard Disk
```
All of the startup options read the previously saved settings (`rd.live.overlay.persistent rd.live.overlay.cowfs=ext4`).
If I want to run my personalized system on, for example, another computer it automatically reads the saved settings.
There is no menu in the grub that would run the system without these saved settings (fresh ISO).

## Expected behaviour

Proposal to add menu options without loading saved data. Example:
```
openSUSE Leap 15.4 Rescue CD
openSUSE Leap 15.4 Rescue CD (Persistent)
Failsafe -- openSUSE Leap 15.4 Rescue CD
Failsafe -- openSUSE Leap 15.4 Rescue CD (Persistent)
Mediacheck
Boot from Hard Disk
```

**Comment by Mexit** [comment]
I propose a change for all versions: Gnome, KDE, XFCE, Rescue (Leap/Tumbleweed). From the ISO image information, it appears that they are all generated by Kiwi:
`Data preparer id: KIWI - HTTPS://GITHUB.COM/OSINSIDE/KIWI`

Probably the entire menu configuration is in the file:
`https://github.com/OSInside/kiwi/blob/master/kiwi/bootloader/template/grub2.py`

ISO image configurations:
`https://build.opensuse.org/package/show/openSUSE:Factory/livecd-openSUSE`

At the moment: if I had the ISO image running in persistent mode and I want to boot without the saved changes, I have to manually edit the grub configuration menu or rename the file with the saved changes.

**Comment by schaefi** [comment]
Ah you are referring to the live CDs, yes those seemed to be created with kiwi. My suggestion to implement the menu proposal is to use a custom template. For details see:

* https://osinside.github.io/kiwi/image_description/elements.html

search for grub_template.

With this information reach out to the openSUSE:Factory/livecd-openSUSE creators and maybe discuss this option.

If you see issues with this approach feel free to open a new issue describing the details.

Thanks
