### ISSUE TITLE
RFE: add support for btrfs transparent compression

### ISSUE THREAD

**Issue by davide125** [OSInside/kiwi#2202]
[btrfs transparent compression](https://fedoraproject.org/wiki/Changes/BtrfsTransparentCompression) is enabled by default in Fedora these days. It entails setting `compress=zstd:1` on the mount (or setting the corresponding btrfs filesystem property). Ideally this is set since the beginning, so that all of the generated filesystem data is already compressed from the start. Alternatively, one can run `btrfs filesystem defragment` after the fact to force compression, but that is less ideal.

Right now I'm working around this by adding `compress=zstd:1` in `fsmountoptions`, but that only affects fstab in the target system, leaving the existing data uncompressed.

**Comment by schaefi** [comment]
Thanks for the details. the kiwi XML description currently allows for ```fsmountoptions``` as you know and yes that information applies only to the later in system mount of the filesystem (fstab. There is also a ```fscreateoptions``` attribute which allows to pass options to the mkfs call, in this case to ```mkfs.btrfs```. I haven't played with transparent compression but I guess you cannot activate it at the level of mkfs and have to provide this information at mount time, correct ?

**Comment by davide125** [comment]
That's correct, this needs to be activated as a mount option or a filesystem property, there isn't a mkfs option for it.

**Comment by schaefi** [comment]
Hi I was looking into that issue and created an image of the following type:

```xml
<type image="vmx" filesystem="btrfs" bootloader="grub2" firmware="efi" fsmountoptions="compress=zstd:1">
```

After the image build I checked the log to see where in the process the compression got lost. The relevant lines from the log are

```
[ DEBUG   ]: 15:07:00 | EXEC: [mkfs.btrfs -L ROOT /dev/loop0p3]
[ DEBUG   ]: 15:07:01 | EXEC: [mountpoint -q /var/tmp/kiwi_volumes.3jy4332_]
[ DEBUG   ]: 15:07:01 | EXEC: [mount -o compress=zstd:1 /dev/loop0p3 /var/tmp/kiwi_volumes.3jy4332_]
[ DEBUG   ]: 15:07:01 | EXEC: [btrfs subvolume create /var/tmp/kiwi_volumes.3jy4332_/@]
...
[ DEBUG   ]: 15:07:01 | EXEC: [btrfs subvolume set-default 256 /var/tmp/kiwi_volumes.3jy4332_]
...
[ INFO    ]: 15:07:18 | --> Syncing root filesystem data
[ DEBUG   ]: 15:07:18 | EXEC: [rsync --archive --hard-links --xattrs --acls --one-file-system --inplace --exclude /image --exclude /.profile --exclude /.kconfig --exclude /run/* --exclude /tmp/* --exclude /.buildenv --exclude /var/cache/kiwi --exclude /boot/efi/* --exclude /boot/efi/.* /tmp/mytest/build/image-root/ /var/tmp/kiwi_volumes.3jy4332_/@]
```

In this chain of commands I do not see an error and would expect the sync operation to transparently compress the data as it flows into the mounted btrfs. When I try to boot the system I also get a grub error saying ```grub-core/fs/btrfs.c:1669:compression type 0x3 not supported``` This is expected because ```zstd``` support is not part of suse's grub in 15.3 ;) On the other hand it tells me, it's compressed :)

Can you point me where I'm mistaken ?

Thanks

**Comment by davide125** [comment]
You're absolutely right. I've just validated with the compsize tool and the data is compressed correctly as expected. I think we're good here.
