### ISSUE TITLE
Switch from using kpartx (DM-based) to partx (simple loop based)

### ISSUE THREAD

**Issue by Conan-Kudo** [OSInside/kiwi#2208]
## Problem description
KIWI currently uses device-mapper backed loop devices for creating disks:

https://github.com/OSInside/kiwi/blob/7fdf127e89ac97b45e140b99112b059b9df5bb84/kiwi/storage/disk.py#L394-L409

https://github.com/OSInside/kiwi/blob/7fdf127e89ac97b45e140b99112b059b9df5bb84/kiwi/storage/disk.py#L479-L499

https://github.com/OSInside/kiwi/blob/7fdf127e89ac97b45e140b99112b059b9df5bb84/kiwi/storage/disk.py#L501-L514

This causes all kinds of problems when trying to use it in various build environments.

From what I can tell, there doesn't seem to be a reason for us to use this over the plain `partx` provided by util-linux. The only real restriction is that if you're trying to create disk images with LVM in them, you'll hit the same problems we have now, but that drastically reduces the scope of issues that we have now when trying to run kiwi in build environments or container environments.

The basic flow for using plain `partx` is like follows (snipped from some other shell code):

```shell
# Create a 120GB disk image file in the temp directory
disk_size_in_gb=120

fallocate -l "${disk_size_in_gb}G" "${work_dir}/${image_name}.img"

# Instantiate a loop device backed by the image file
loopdev=$(losetup --show -f "${work_dir}/${image_name}.img")

# [...]

# Remove loop partition devices
partx -d "${loopdev}"

# Remove loop device
losetup -d "${loopdev}"

```

## OS and Software information

* KIWI version: 9.24.48
* Operating system host version: CentOS Stream 9
* Operating system target version: CentOS Stream 9
* Open Build Service version (N/A if not using OBS): N/A
* Koji version (N/A if not using Koji): 1.30.1

**Comment by davidcassany** [comment]
I have no strong opinion in one tool versus the other, but the fact that `partx` comes as part of `util-linux` sounds cool, less dependencies and if it also helps on KIWI integration with some build envs thats a valuable gain. At a glance it doesn't look like it would have big impact in dracut modules, which is the hardest part to refactor, as I see it only being used once in `kiwi-dump-reboot` (looks like a narrow use case).

Still this sort of changes are tricky and require quite some testing, the fact that it mostly applies on the python code makes me believe this should be doable. I would not discard unexpected issues/regressions are found while coding/testing it, though.
