### ISSUE TITLE
https://osinside.github.io/kiwi/ - 404 error

### ISSUE THREAD

**Issue by taroth21** [OSInside/kiwi#2221]
## Problem description
When I click on https://osinside.github.io/kiwi I get a 404 error.

## Expected behaviour
Usually, one could access the generated upstream docs from this URL above.  Not sure if it's a temporary issue only or if the link to the generated docs needs to be fixed in the 'About' section of the repo.

**Comment by schaefi** [comment]
OMG what happened ? I will look at it. Thanks

**Comment by schaefi** [comment]
I don't get it ? What's the problem with the deployment:

https://github.com/OSInside/kiwi/actions/runs/3726290631

@Conan-Kudo @davidcassany Any idea ?

Thanks

**Comment by schaefi** [comment]
found and fixed

**Comment by taroth21** [comment]
@schaefi Thank you, Marcus!
