### ISSUE TITLE
tpm disk unlock

### ISSUE THREAD

**Issue by rjschwei** [OSInside/kiwi#2224]
## Problem description

There is a set of upstream patches that enables grub to decrypt a disc based on secrets obtained from tpm. Since the patches have not been merged into upstream grub SUSE has merged the patches into the SUSE grub package and created a module to facilitate the functionality. Therefore this is at present SUSE specific. The code is activated by

`grub2-install --suse-enable-tpm`

or

`shim-install --suse-enable-tpm`

in addition 

`TRUSTED_BOOT="yes"`

needs to be set in `/etc/sysconfig/bootloader`

## Expected behaviour

The desire is to trigger kiwi to add the additional argument to `grub2-install` and set the variable in the config.

## Proposal

Introduce `suse-tpm-unlock` attribute to the `bootloader` element as a bool `true|false` and let this configuration in the XML trigger the process of adding the additional argument to grub2-install.

I realize this is very SUSE specific and it would be much nicer to have a non distribution specific implementation. Given the path chosen for grub I am not certain this is possible.

@schaefi thoughts?

When we agree on a direction I can deliver the implementation.

Thanks,
Robert

**Comment by schaefi** [comment]
Hi Robert, the lovely --suse-xx options that makes the live of everybody harder as it should be are back ;) I remember we had to deal with this sort of options in the past and I was so happy when they were gone.

On the path forward it would be nice if SUSE would stop doing this and contribute to grub like others do. As I know it's not going to happen here is what I think we can do:

1. We could create a new attribute in the ```<bootloader>``` element as suggested but not distro specific. Maybe just ```trusted_boot="true|false"```
2. Restrict ```trusted_boot``` in the schema to the ```grub``` bootloader only. Remember we support some other loaders including systemd-boot and all that will only work for grub as I think ?
3. Add documentation to the new attribute and mention under which condition an effective implementation exists. There will be more distros in the future that supports a TPM concept, so the code and the docs can follow
4. Implement ```TRUSTED_BOOT="yes"``` in the code of bootloader/grub that writes ```/etc/sysconfig/bootloader``` depending on the value of the attribute in the image description.
5. Implement the required changes to the ```shim-install``` and ```grub-install``` calls and use the method:
   ```python
   if CommandCapabilities.has_option_in_help('shim-install', '--suse-enable-tpm', root=self.root_dir, raise_on_error=False):
       ...
   ```

If there is no way in shim-install and grub-install to uniquely identify suse options through the help or similar output, we will not accept custom caller options, so it's a must have that we can call the tool to check for its capabilities in some way shape or form

That way it is sort of maintainable but still it would be really better if there are no --suse-something options in core tools

Hope this makes sense and helps a bit

**Comment by rjschwei** [comment]
Thanks, yes this makes sense.

Well the code for not making it SUSE specific is pending upstream, the problem is that getting things into grub upstream appears to be happening at the same speed as tectonic plate movement. The code was contributed by Microsoft and has been pending for a long time. It is needed to support confidential VMs and since it was not merged upstream it was decided that the out of tree code would be enabled with a SUSE specific option.

**Comment by schaefi** [comment]
I assume it will land in SLES which means even if it gets upstream we might end up in the situation to support both, an upstream version and the --suse-xx SLES extension, right ?

One question: I understand the need for ```shim-install --suse-enable-tpm```. However, I do not understand the need for ```grub2-install --suse-enable-tpm``` if there is also ```TRUSTED_BOOT="yes"``` which could serve as the trigger for performing on the grub2-install level or am I mistaken. To be honest the change on the ```grub2-install``` side hurts the most becuase ```shim-install``` is used in the SUSE ecosystem only anyway

**Comment by rjschwei** [comment]
The option is already in SLES and openSUSE it was merged in October, I'm just finally getting around to pick it up.

Well `TRUSTED_BOOT="yes"` is for perlbootloader and will trigger the addition of `--suse-enable-tpm`. Therefore this covers the use case where grub and or the shim gets updated. During image build we use `grub2-install` directly and as such the `TRUSTED_BOOT` variable has no effect.

Alternatively we could pursue a more generic direction. The `bootloader` element could get

`bootloader_install_args`
`shim_install_args`
`bootloader_cfg_opts`

attributes. Then what is passed is controlled from the image configuration. We would then set

`<bootloader name="grub2" timeout="1" bootloader_install_args="suse-enable-tpm" shim_install_args="suse-enable-tpm" bootloader_cfg_opts="TRUSTED_BOOT='yes'"/>`

All new attributes could be a comma separated string and it would be a completely generic solution. If/when there is an upstream solution in how TPM unlock is treated we could still add `trusted_boot=true|false` if desired.

Of course it could very well be that the upstream solution is completely generic, i.e.

- check if the filesystem is encrypted
- if yes check if there is a TPM 
- if yes try to retrieve the secrets
- if no secret ask the user

The disadvantage of the generic approach is that it adds 3 attributes instead of one, but it is not restricted to grub and can be used/misused as people that build images see fit.

**Comment by schaefi** [comment]
I like the idea to allow caller arguments on the level of the image description :+1:

**Comment by rjschwei** [comment]
@schaefi stuck at generating xml_parse.py. The file has a header that gives a command line, which is useful but I have not found any information on how to generate kiwi_for_generateDS.xsd

**Comment by schaefi** [comment]
ok you never touch xml_parse.py, this is auto generated code. If you plan to change the schema *only* work on the file
```kiwi/schema/kiwi.rnc``` This is the reduced RelaxNG schema definition from which everything else originates, api, api docs, xsd, schematron rulese, etc etc.. Once you have finished the changes in kiwi.rnc you can run the generation of all auto generated data as follows:

I assume you have created the tox devel env as documented: https://osinside.github.io/kiwi/contributing.html

```
source .tox/3/bin/activate
make kiwi/schema/kiwi.rng
```

That's it

**Comment by schaefi** [comment]
If you like we can also work together on this. I can create a branch with an idea about the schema change and you just take over. Thoughts ?

**Comment by rjschwei** [comment]
I pushed the `bootLoadOpts` branch

Yes I created the venv but kiwi_for_generateDS.xsd is not there

**Comment by rjschwei** [comment]
And I generated kiwi.rng using trang instead of the make command so that's where I veered of the path.

**Comment by schaefi** [comment]
ok, so the .rnc changes are not complete:

```
/home/ms/Project/kiwi/kiwi/schema/kiwi_modified_for_generateDS.rnc:2715:9: error: reference to undefined pattern "k.bootloader.bootloader_install_args"
/home/ms/Project/kiwi/kiwi/schema/kiwi_modified_for_generateDS.rnc:2716:9: error: reference to undefined pattern "k.bootloader.shim_install_args"
/home/ms/Project/kiwi/kiwi/schema/kiwi_modified_for_generateDS.rnc:2717:9: error: reference to undefined pattern "k.bootloader.bootloader_cfg_opts"
make: *** [Makefile:69: kiwi/schema/kiwi.rng] Error 1

```

**Comment by schaefi** [comment]
I'm going to fix it ok ? and push a commit

**Comment by schaefi** [comment]
I pushed a commit also with an idea how I would handle these additional arguments. I think a comma as space separator and an implicit add of ```--``` makes it more complicated than it should be when parsing this information. Also it will not be very flexible with regards to the various ways how developers pass arguments to their programs :)

Let me know what you think. Here is how I would do it

```xml
<bootloader name="grub2">
    <bootloadersettings>
        <shimoption name="--foo" value="bar"/>
        <shimoption name="--suse-we-adapt-you-succeed"/>
        <installoption name="--A" value="123"/>
        <installoption name="B"/>
        <configoption name="--joe"/>
        <configoption name="-x"/>
    </bootloadersettings>
</bootloader>
```

Thoughts ?

**Comment by rjschwei** [comment]
Yes that makes sense

**Comment by schaefi** [comment]
> Yes that makes sense

perfect, feel free to change element/attribute names as you see fit. Self explaining names are so hard to find ;)

**Comment by rjschwei** [comment]
@schaefi turns out that I am not going to get to this anytime soon, any chance you can push this through in your spare time?

**Comment by schaefi** [comment]
@rjschwei I can take a look and create a pull request from the branch we already have. I can't make any promises when I get to it though. I would also need you as a reviewer if it actually works because testing all the TPM stuff from grub for real is more work.

**Comment by rjschwei** [comment]
@schaefi thanks, review and test should be reasonably straight forward.

**Comment by schaefi** [comment]
@rjschwei short before a PR, I was so free to force push into the existing branch which I guess is ok... late here will finsih this tomorrow
