### ISSUE TITLE
Failed to mount install ISO device

### ISSUE THREAD

**Issue by LesserBabka** [OSInside/kiwi#2228]
## Problem description
OEM installer displays "Failed to mount install ISO device" and then aborts. Happens when zfs has been included in package list. 

If excluding the zfs dracut module from the installer, the problem is not encountered.
 ```
 <installmedia>
      <initrd action="omit">
          <dracut module="zfs"/>
      </initrd>
  </installmedia>
```

From `/run/initramfs/log/boot.kiwi`
```
...
... mount -n CDLABEL=INSTALL /run/install
mount: /run/install: special device CDLABEL=INSTALL does not exist,
...
```

Executing `blkid` in the emergency shell
```
...
/dev/sr0: BLOCK_SIZE="2048" UUID="2023-01-12-06-53-42-00" LABEL="INSTALL" TYPE="iso9660" PTTYPE="dos"
...
```

Replacing `root=install:CDLABEL=INSTALL` with `root=install:/dev/sr0` in the installer kernel command line does not work, but I'm not familiar with this mechanism.

## Steps to reproduce the behaviour

1. Build appliance installer including zfs in package list.
2. Boot the installer.
3. (If there are multiple disks, select a target disk)

## OS and Software information
The kiwi configuration is very close to example in kiwi repo build-tests/x86/leap/test-image-disk, with zfs added to package list. If there is problem to reproduce I can describe other discrepancies, but I would be very surprised if it would make a difference.
zfs packages installed:
zfs-kmp-default-2.1.7_k5.14.21_150400.24.38-lp154.2.2.x86_64
zfs-2.1.7-lp154.2.2.x86_64

* KIWI version: python3-kiwi-9.24.43-150100.3.56.3.x86_64
* Operating system host version: openSUSE Leap 15.4
* Operating system target version:  openSUSE Leap 15.4
* Open Build Service version (N/A if not using OBS): How to check this?

**Comment by schaefi** [comment]
Thanks for the report. Indeed this sounds very strange. Can you repeat the procedure with zfs in the initrd and kernel cmdline option ```rd.debug``` enabled. This will produce a lot more information on the console and might give a hint how zfs influences the process

Thanks

**Comment by schaefi** [comment]
closing as there are no further details provided
