### ISSUE TITLE
kiwi-test-image-live-disk-v7.x86_64-1.3.0-Disk-Build47.1.install.iso fails to boot with UEFI

### ISSUE THREAD

**Issue by dcermak** [OSInside/kiwi#2229]
## Problem description

The CentOS 7 live disk install iso fails to install in openQA: the image boots and tries to install, but during installation, you see the following issue pop up in the serial console:
```
┌──────────────────────────────────────────────────────────────────────────────┐
│ Failed to kexec boot system                                                  │
├──────────────────────────────────────────────────────────────────────────────┤
│                                   <  OK  >                                   │
└──────────────────────────────────────────────────────────────────────────────┘
```

The VM then reboots but it appears to get caught in a reboot loop and tries to reinstall again.

The only useful output that I found in the serial console are the following warnings/errors:
```
         Starting dracut pre-mount hook...

[    2.223408] dracut-pre-mount[420]: mount: /dev/sr0 is write-protected, mounting read-only
```
and:
```
[   45.615170] dracut-pre-mount[420]: Cannot open `': No such file or directory
[   45.620168] dracut-pre-mount[420]: Nothing has been loaded!
```

## OS and Software information

* KIWI version: latest on OBS
* Operating system host version: 
* Operating system target version: 
* Open Build Service version (N/A if not using OBS): 
* Koji version (N/A if not using Koji):

**Comment by schaefi** [comment]
CentOS7 has been dropped from the list of distros we create integration tests for. Regarding CentOS we focus on CentOS stream v8/v9

Thus closing this one
