### ISSUE TITLE
kiwi-test-image-disk-ramdisk does not find a suitable device for installation

### ISSUE THREAD

**Issue by dcermak** [OSInside/kiwi#2230]
## Problem description

The [RAM-disk install iso image](https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:tumbleweed/test-image-disk-ramdisk) does no longer install successfully, when you boot it in openQA or virt-manager it launches and then displays the following error on the serial console:
```
┌──────────────────────────────────────────────────────────────────────────────┐
│ No device(s) for installation found                                          │
├──────────────────────────────────────────────────────────────────────────────┤
│                                   <  OK  >                                   │
└──────────────────────────────────────────────────────────────────────────────┘
```

Then the VM reboots and repeats or fails to boot (depending on your boot priority).

## Expected behavior

It should boot as it used to

## Steps to reproduce the behavior

- download https://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/Testing_x86:/tumbleweed/images/iso/kiwi-test-image-disk-ramdisk.x86_64-1.42.1-Build41.9.install.iso
- boot it in virt-manager
- switch to the serial console

## OS and Software information

* KIWI version: latest on OBS
* Operating system host version: 
* Operating system target version: 
* Open Build Service version (N/A if not using OBS): 
* Koji version (N/A if not using Koji):

**Comment by schaefi** [comment]
Interesting this means there is no /dev/ramX device available. Usually because the ramdisk module from the kernel was not loaded. kiwi forces loading of brd if ```rd.kiwi.ramdisk``` is set. I can see the setting in the test image description. Thus my assumption is that the generated initrd did not include the brd.ko driver

**Comment by schaefi** [comment]
sh-5.2# modprobe brd
modprobe: FATAL: Module brd not found in directory /lib/modules/6.1.4-1-default

**Comment by schaefi** [comment]
That's the reason. I prepare a patch
