### ISSUE TITLE
Archlinux kiwi-test-image-live-disk-kis Live Build iso fails to boot

### ISSUE THREAD

**Issue by dcermak** [OSInside/kiwi#2233]
## Problem description

The [kiwi-test-image-live-disk-kis.x86_64-1.0.0-Live-Build54.11.iso](https://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/Testing_x86:/archlinux/images/iso/kiwi-test-image-live-disk-kis.x86_64-1.0.0-Live-Build54.11.iso) fails to boot in BIOS and UEFI mode:

![image](https://user-images.githubusercontent.com/45594031/212087018-ca08bef7-8581-4556-91bf-e4531b78a962.png)

## Expected behavior

The Live ISO should just boot.

## Steps to reproduce the behavior

- Download https://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/Testing_x86:/archlinux/images/iso/kiwi-test-image-live-disk-kis.x86_64-1.0.0-Live-Build54.11.iso
- Create a VM and boot it
- watch it fail

## OS and Software information

* KIWI version: 
* Operating system host version: 
* Operating system target version: 
* Open Build Service version (N/A if not using OBS): 
* Koji version (N/A if not using Koji):

**Comment by schaefi** [comment]
@davidcassany can you have a look please ?

**Comment by schaefi** [comment]
going to switch to grub for booting Live images for Arch
