### ISSUE TITLE
Missing kiwi-ng OBS repository for SLES 15 SP4

### ISSUE THREAD

**Issue by kagehisa** [OSInside/kiwi#2240]
## Problem description
There is currently no available OBS repository to install kiwi-ng on an SLES 15 SP4 system. 
The repositories provided at [OBS](https://download.opensuse.org/repositories/Virtualization:/Appliances:/Builder/) end at SLES 15 SP3. This repository works somewhat on SLES 15 SP4 but for example one of the dependencies for the `python3-kiwi_boxed_plugin` is missing because no repository for SLES 15 SP4  provides `python3-progressbar2` 

## Expected behaviour
The Installation method described in the [documentation](https://osinside.github.io/kiwi/installation.html#installation-from-obs) is possible on an SLES15 SP4 system.

## Steps to reproduce the behaviour
Try to add OBS provided repository as is described in [documentation](https://osinside.github.io/kiwi/installation.html#installation-from-obs) on an SLES15 SP4 system.

## OS and Software information

* KIWI version: N/A
* Operating system host version: SLES15 SP4
* Operating system target version: N/A
* Open Build Service version (N/A if not using OBS): N/A
* Koji version (N/A if not using Koji): N/A

**Comment by schaefi** [comment]
I added them:

https://build.opensuse.org/project/repository_state/Virtualization:Appliances:Builder/SLE_15_SP4

Should be filled with data soon.

Thanks
