### ISSUE TITLE
squashfs image type doesn't support squashfscompression attribute

### ISSUE THREAD

**Issue by zzzoom** [OSInside/kiwi#2241]
## Problem description
Trying select a compression algorithm when building a squashfs filesystem image, like  `<type image="squashfs" squashfscompression="zstd"/>` fails with:
```
[ INFO    ]: 06:07:37 | Schematron validation failed:
[ INFO    ]: 06:07:37 | --> squashfscompression attribute is only available for the following image types: oem pxe kis iso
[ ERROR   ]: 06:07:37 | KiwiDescriptionInvalid: Failed to validate schema and/or schematron rules. Use --debug for more details
```

## Expected behaviour
A squashfs filesystem image is built with the selected compression algorithm.

## Software information

* KIWI version: 9.24.55

**Comment by schaefi** [comment]
Oh well, what a bug :) see the open PR that should fix it
