### ISSUE TITLE
Installing ca-certificates in bootstrap ends in failure for SLE12SP4 and SP5

### ISSUE THREAD

**Issue by aaannz** [OSInside/kiwi#2245]
## Problem description

Hi,

I'm trying to use kiwi-ng to build SLE12SP5 image (tried SP4 as well) using kiwi-ng. Because of this is SUMA environment, I need to have custom certificate present in kiwi bootstrap. This certificate is added using `--add-bootstrap-package` command and package with certificate is successfully trying to be installed. However both installation of this package and ca-certificates package ends with an error:

```
...
DEBUG: 11:16:45 | bootstrap: Retrieving package ca-certificates-1_201403302107-15.6.2.noarch (107/139),  21.3 KiB ( 27.3 KiB unpacked)
DEBUG: 11:16:45 | bootstrap: Retrieving: ca-certificates-1_201403302107-15.6.2.noarch.rpm [done]
DEBUG: 11:16:45 | bootstrap: (107/139) Installing: ca-certificates-1_201403302107-15.6.2.noarch [.......done]
DEBUG: 11:16:45 | bootstrap: Additional rpm output:
DEBUG: 11:16:45 | bootstrap: warning: /var/lib/Kiwi/build97/chroot/var/lib/Kiwi/build97/cache/packages/key_repo5/getPackage/NULL/a5475844ac65373b6d756a6fdcf02ed2b3e1fe4672026affbc78e8ddc7488c4d/ca-certificates-1_201403302107-15.6.2.noarch.rpm
: Header V3 RSA/SHA256 Signature, key ID 39db7c82: NOKEY
DEBUG: 11:16:45 | bootstrap: p11-kit: couldn't lookup home directory for user 0: No such file or directory
DEBUG: 11:16:45 | bootstrap: p11-kit: couldn't lookup home directory for user 0: No such file or directory
DEBUG: 11:16:45 | bootstrap: p11-kit: couldn't lookup home directory for user 0: No such file or directory
DEBUG: 11:16:45 | bootstrap: Died at /usr/lib/ca-certificates/update.d/80etc_ssl.run line 87.
DEBUG: 11:16:45 | bootstrap: p11-kit: couldn't lookup home directory for user 0: No such file or directory
DEBUG: 11:16:45 | bootstrap: Retrieving package pam-1.1.8-24.49.1.x86_64 (108/139), 421.9 KiB (  1.5 MiB unpacked)
...
```

Because of this failure certificate is not properly inserted and zypper calls after switching to bootstrap chroot fails on https validation.

Both SLE12SP5 and SLE12SP4 are affected (they are using different p11-kit version)

SLE15 images are not affected.

## Expected behaviour

Installation of ca-certificate package is done without any error.

## Steps to reproduce the behaviour

I am using template from https://github.com/aaannz/manager-build-profiles/blob/kiwing_sles12/OSImage/POS_Image-JeOS6/config.xml
Build is triggered by SUMA integration, that means kiwi config repos are disabled and repositories from SUMA are provided as command line options together with certificate package.

## OS and Software information

* KIWI version: both 9.20.6 and 9.24.43 are affected
* Operating system host version: tested on SLE12 SP5 and SLE15 SP4
* Operating system target version: SLE12SP4 and SLE12SP5
* Open Build Service version (N/A if not using OBS): N/A
* Koji version (N/A if not using Koji): N/A

**Comment by schaefi** [comment]
Hmm, looks like a packaging issue to me. No idea what p11-kit does at install time but obviously it is expecting an environment that is not/not yet suitable at that time of the install. Usually an issue with prereq setting in the spec file of the package.

From a kiwi perspective I don't see how we can help here. If installing the package does not work you should be able to workaround it and bring in the missing data via a ```post_bootstrap.sh``` script

* https://osinside.github.io/kiwi/concept_and_workflow/shell_scripts.html

Hope this helps

**Comment by aaannz** [comment]
Thanks for the feedback. However I am not sure if it is just packaging. When I execute zypper command exactly as is in kiwi build log but to different zypper root, it will pass without issue. Switching to the chroot and trying curl works as well.

e.g. in build log I see:
`
DEBUG: 15:23:50 | EXEC: [zypper --non-interactive --pkg-cache-dir /var/lib/Kiwi/build129/chroot/var/lib/Kiwi/build129/cache/packages --reposd-dir /var/lib/Kiwi/build129/chroot/var/lib/Kiwi/build129/cache/zypper/repos --solv-cache-dir /var/lib/Kiwi/build129/chroot/var/lib/Kiwi/build129/cache/zypper/solv --cache-dir /var/lib/Kiwi/build129/chroot/var/lib/Kiwi/build129/cache/zypper --raw-cache-dir /var/lib/Kiwi/build129/chroot/var/lib/Kiwi/build129/cache/zypper/raw --config /var/lib/Kiwi/build129/chroot/tmp2tmidjnl --root /var/lib/Kiwi/build129/chroot install --auto-agree-with-licenses --no-recommends ca-certificates filesystem findutils fipscheck glibc-locale rhn-org-trusted-ssl-cert-osimage sles-release udev zypper]
`

Which I will use the very same command except changed `--root /tmp/testimage`, removed `--config /var/lib/Kiwi/build129/chroot/tmp2tmidjnl` and all cache dirs I removed `/var/lib/Kiwi/build129/chroot` prefixes as bind mounts are unmounted after failed build. And added curl package for tests.

So I have following command:
`
zypper --pkg-cache-dir /var/lib/Kiwi/build129/cache/packages --reposd-dir /var/lib/Kiwi/build129/cache/zypper/repos --solv-cache-dir /var/lib/Kiwi/build129/cache/zypper/solv --cache-dir /var/lib/Kiwi/build129/cache/zypper --raw-cache-dir /var/lib/Kiwi/build129/cache/zypper/raw --root /tmp/testone/ install --auto-agree-with-licenses --no-recommends ca-certificates filesystem findutils fipscheck glibc-locale rhn-org-trusted-ssl-cert-osimage sles-release udev zypper curl
`

Running it installs everything without issue.

**Comment by aaannz** [comment]
FYI, you were right. Shadow package provides what ca-certificates needs. Making sure shadow is installed sooner then ca-certificates makes things work.
