### ISSUE TITLE
crypt module cause build image not bootable with kernel 5.14

### ISSUE THREAD

**Issue by cheeye** [OSInside/kiwi#2250]
## Problem description
Image with kernel 5.14 is not bootable. Got a lot of below messages and entered emergency dracut shell. 
```
Warning: /lib/dracut/hooks/initqueue/finished/devexists-\x2fdev\x2fdisk\x2fby-uuid\x2feUUID
```
The kernel 5.14 has some changes in /usr/lib/dracut/modules.d/90kernel-modules/module-setup.sh which is different from earlier versions. It seems it enables encryption by default? 

And in the kiwi, I also noticed that crypto module is included during the build.  How to exclude crypto related modules in the kiwi during the build process? 

## OS and Software information

* KIWI version: 9.23.20
* Operating system host version: SLES15SP2
* Operating system target version: SLES15SP4
* Open Build Service version (N/A if not using OBS): 
* Koji version (N/A if not using Koji):

**Comment by schaefi** [comment]
I cannot reproduce this issue but if removing crypto from the dracut generated initrd would be a solution that can be done as follows:

1. Create a dracut config overlay file in your kiwi image description, e.g ```root/etc/dracut.conf.d/disable-crypto.conf
2. Add the following contents

    ```
    omit_dracutmodules+=" crypto "
    ```

**Comment by schaefi** [comment]
I assume the issue has been resolved or is no longer valid due to no further feedback
