### ISSUE TITLE
dracut: kiwi-overlay: Kiwi picks the wrong partition to use as the rootfs when multiple squashfs's are present

### ISSUE THREAD

**Issue by IsaacJT** [OSInside/kiwi#2251]
## Problem description

The dracut module responsible for setting up the overlayfs root filesystem fails to determine the correct partition to use as the root in when multiple partitions containing squashfs are present.

This is most likely caused by the following lines in the module: https://github.com/OSInside/kiwi/blob/master/dracut/modules.d/90kiwi-overlay/kiwi-overlay-root.sh#L41

The module script lists all squashfs partitions found, and then picks the first one. If this first one is not the intended root device, the script will use that one anyway, causing the boot to fail.

This overrides the root device config set in the kernel command line, e.g. `root=overlay:PARTUUID=...`.

## Expected behaviour

The partition containing the root squashfs-based filesystem is mounted to /.

## Steps to reproduce the behaviour

Configure the application.xml with the following parameters:

```
<image ...>
    ...
    <preferences>
        ...
        <type image="oem" filesystem="xfs" firmware="efi" initrd_system="dracut"
            overlayroot="true" overlayroot_write_partition="false"
            overlayroot_readonly_partsize="256"
            kernelcmdline="console=ttyS0 rd.root.overlay.readonly"
            bootpartition="true" bootpartsize="256" bootfilesystem="ext4" format="qcow2"
            devicepersistency="by-partuuid">
            ...
            <partitions>
                ...
                <partition name="oci-preloaded" size="512" mountpoint="/var/lib/containers/loaded"
                    filesystem="squashfs" />
                ...
            </partitions>
        </type>
    </preferences>
</image>
...
``` 

Then try to boot the resulting image. Dracut should report `[FAILED] Failed to start Switch Root.`, and in the emergency shell you will be able to see the contents of the incorrect squashfs partition in `/sysroot`.

## OS and Software information

* KIWI version: 9.24.56 
* Operating system host version: Ubuntu 23.04
* Operating system target version: Ubuntu 23.04
* Open Build Service version (N/A if not using OBS): N/A
* Koji version (N/A if not using Koji): N/A

**Comment by schaefi** [comment]
Hi Isaac, great catch and thanks for reporting. I agree the check to pick the write partition is weak and needs to be fixed

**Comment by Conan-Kudo** [comment]
Note that kiwi-live and kiwi-overlay are obsolete and intended to be replaced with dracut's dmsquash-live and dmsquash-live-autooverlay functionality. Please try that and see if it works first?

**Comment by schaefi** [comment]
@Conan-Kudo right for live ISO images and their persistency we have dracut upstream modules which is great. So this obsoletes ```dracut/modules.d/90kiwi-live```. However, there is also an overlay module to support disk images with an overlay feature which is done in ```dracut/modules.d/90kiwi-overlay``` and I'm not sure if ```dmsquash-live-autooverlay``` can be used for it as a 1:1 drop in. I agree it would be good to also obsolete the disk overlay dracut module with a dracut upstream variant.

Nevertheless it would be good to fix the mentioned defect as long as we still have the code in kiwi

**Comment by IsaacJT** [comment]
@Conan-Kudo do you have any links for examples for `dmsquash-live-autooverlay`? I've been trying to get it to work with persistent read/write overlay partitions but it always fails with cryptic error messages and will only mount a tmpfs. There doesn't seem to be any documentation for it at all.

My current command line:

```
root=live:PARTLABEL=p.lxreadonly rd.live.overlay.overlayfs rd.live.overlay=LABEL=ROOT rd.live.overlay.cowfs=xfs ro console=ttyS0 systemd.verity=1 rd.live.overlay.overlayfs rd.live.overlay=LABEL=ROOT
rd.live.overlay.cowfs=xfs rd.live.debug
```

This fails with:

```
Mar 06 11:09:29 localhost unknown:    Unable to find a persistent overlay; using a temporary one.
                                 All root filesystem changes will be lost on shutdown.
Mar 06 11:09:29 localhost unknown:          Press [Enter] to continue.
...
Mar 06 11:09:35 localhost kernel: overlayfs: failed to resolve '/run/overlayfs': -2
Mar 06 11:09:35 localhost mount[503]: mount: /sysroot: special device LiveOS_rootfs does not exist.
Mar 06 11:09:35 localhost mount[503]:        dmesg(1) may have more information after failed mount system call.
Mar 06 11:09:35 localhost systemd[1]: sysroot.mount: Mount process exited, code=exited, status=32/n/a
Mar 06 11:09:35 localhost systemd[1]: sysroot.mount: Failed with result 'exit-code'.
Mar 06 11:09:35 localhost systemd[1]: Failed to mount /sysroot.
```
