### ISSUE TITLE
Not setting `console=` still sets `GRUB_TERMINAL=` when it is unwanted

### ISSUE THREAD

**Issue by Conan-Kudo** [OSInside/kiwi#2261]
## Problem description

I need to be able to prepare images without _any_ `GRUB_TERMINAL` setting, but currently if I don't set `console=`, it gets set to `gfxterm`. Instead, I want GRUB's own defaults to kick in because using `console` causes garbage rendering, and `gfxterm` doesn't exist on RH/Fedora apparently.

## OS and Software information

* KIWI version: 9.24.52
* Operating system host version: Fedora Linux 37
* Operating system target version: Fedora Linux 38
* Open Build Service version (N/A if not using OBS): N/A 
* Koji version (N/A if not using Koji): N/A

**Comment by leifliddy** [comment]
To be clear, the garbage rendering issue exists on Apple Silicon systems. 
hmmm, what if we just allowed console to contains an empty string ie `console=""`
And then modified the patterns to allow an empty string as a value ie 
```
validate_grub_console_patterns_ = [['^(\s*|console|gfxterm|serial)( (console|gfxterm|serial))*$']]
...
<param name="pattern">(\s*|console|gfxterm|serial)( (console|gfxterm|serial))*</param>
```
The end result would be that `/etc/default/grub` contained `GRUB_TERMINAL=""`
Would that be an acceptable solution. If so, I could sort that out no problem. 
Another option would be to devise a mechanism in which grub directives could be omitted entirely. 
But that would likely take quite a bit of work as we'd probably need to devise a special keyword like 
`console="omit"` and then match and act on that logic.

**Comment by Conan-Kudo** [comment]
> hmmm....what if we just allowed console to contains an empty string ie `console=""`

That is reasonable.
