### ISSUE TITLE
Add support for dnf5

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi#2262]
## Problem description

dnf5 is the new version of dnf which comes with a different interface than dnf4 uses.
Thus it makes sense to create a new package manager class to support this package
manager. Selecting dnf5 needs its own name. My suggestion would be

```xml
<packagemanager>dnf5</packagemanager>
```

**Comment by Conan-Kudo** [comment]
Let's go with this for now.

**Comment by Conan-Kudo** [comment]
I've also packaged `dnf5` for openSUSE now, though it isn't in Factory just yet... https://build.opensuse.org/package/show/home:Pharaoh_Atem:DNF5_SUSE/dnf5
