### ISSUE TITLE
Avoid Removal of Repositories Before config.sh is Executed

### ISSUE THREAD

**Issue by zohourih** [OSInside/kiwi#2264]
## Problem description
We have a use case where we need to dynamically pull a few packages from a specific set of URLs that can change over time, install them with zypper using the `config.sh` script, and let zypper automatically pull and install the dependencies from the repositories that are defined in `config.xml`. However, it seems as the installation of packages defined in `config.xml` is done, the kiwi build process removes all the repositories and hence, the repositories are not available anymore when `config.sh` is executed. Same thing happens if we try installing those packages using the `post_bootstrap.sh` script.

## Expected behaviour
We want to be able to keep the repositories that are added in `config.xml`, until `config.sh` is fully executed.

## Steps to reproduce the behaviour
- Add repositories in `config.xml`
- Use zypper to install a package that has dependency to packages available in the repositories defined in `config.xml`
- The build will fail since the repositories are removed before `config.sh` is run and package dependencies cannot be satisfied

## OS and Software information

* KIWI version: 9.25.36
* Operating system host version: SLES 15 SP3
* Operating system target version: SLES 15 SP3
* Open Build Service version (N/A if not using OBS): N/A
* Koji version (N/A if not using Koji): N/A

**Comment by schaefi** [comment]
Hi,

the repository setup is still present when the ```config.sh``` script is called. So you can use zypper as intended but you need to specify the location of the repositories because kiwi does not use the default location in order to prevent any conflict between build time actions and runtime actions. So in short if you look into a kiwi log file you see calls like

```
zypper --non-interactive --gpg-auto-import-keys --pkg-cache-dir /var/cache/kiwi/packages --reposd-dir /var/cache/kiwi/zypper/repos --solv-cache-dir /var/cache/kiwi/zypper/solv --cache-dir /var/cache/kiwi/zypper --raw-cache-dir /var/cache/kiwi/zypper/raw  install --download in-advance --auto-agree-with-licenses -- ...
```

All repos kiwi setups during build you will find in ```/var/cache/kiwi/...```. Thus it's required to pass this information to the package manager. In the same way you can also call it inside of ```config.sh```

By the way this applies to all package managers for which we have added support. A good way to find out how the package manager is called is by looking into a kiwi log file and grab the command line and adapt it for your specific use case.

Hope this helps

**Comment by zohourih** [comment]
@schaefi Thank you for your response. It indeed brings me one step closer to the solution as now zypper can find the repositories and automatically find the dependencies for the packages that are to be installed in the script. However, the actual installation of the dependencies now fails with the following error:

```
[ DEBUG   ]: 01:59:01 | 28 new packages to install.
[ DEBUG   ]: 01:59:01 | Overall download size: 20.0 MiB. Already cached: 0 B. After the operation, additional 82.8 MiB will be used.
[ DEBUG   ]: 01:59:01 | Continue? [y/n/v/...? shows all options] (y): y
[ DEBUG   ]: 01:59:02 | Retrieving package libhiredis0_13-0.13.3-bp153.2.3.1.x86_64 (1/28),  32.8 KiB ( 63.6 KiB unpacked)
[ DEBUG   ]: 01:59:02 | Retrieving: libhiredis0_13-0.13.3-bp153.2.3.1.x86_64.rpm [done]
[ DEBUG   ]: 01:59:02 | libhiredis0_13-0.13.3-bp153.2.3.1.x86_64.rpm:
[ DEBUG   ]: 01:59:02 |     Header V3 RSA/SHA256 Signature, key ID 65176565: NOKEY
[ DEBUG   ]: 01:59:02 | Looking for gpg key ID 65176565 in cache /var/cache/kiwi/zypper/pubkeys.
[ DEBUG   ]: 01:59:02 | Repository Backports-SLE-15SP3-Pool does not define additional 'gpgkey=' URLs.
[ DEBUG   ]: 01:59:02 | Abort, retry, ignore? [a/r/i] (a): a
```

This happens for any package from any repository, so it seems there is still something missing in the command line. I have set my zypper command line to exactly what you suggested. However, the actual command line that I see in the log has an extra `--config /kiwi_XXXXXXXX` argument. Could this be the reason why the package installation is failing? The kiwi_XXXXXXXX part doesn't seem to be fixed, anyway, so I don't know how I could predict the value and put it in the script even if it is required.

**Comment by schaefi** [comment]
Hi, the remaining issue is that the repo keys for the repos you are using to install are not imported in the current state of the image root. You can solve this in different ways. The most easy one is:

* call zypper with --no-gpg-checks

Probably unwanted. The better solution is to install the signing keys prior calling config.sh

```xml
<repository ...>
  <source path="...">
    <signing key="/path/to/sign_key_a"/>
    <signing key="/path/to/sign_key_b"/>
  </source>
</repository>
```

Also see: https://osinside.github.io/kiwi/image_description/elements.html#repository-source

You are not forced to let kiwi import these keys, you can also do it in a manual or appropriate way according to your use case. In general zypper expects the signing keys for the repos to live in ``` /var/cache/zypp/raw/REPO/repodata/```

Hope this helps

**Comment by udf2457** [comment]
@zohourih Did you ever find a solution ?  I am seeing a problem myself and have been unable to find a solution.

**Comment by zohourih** [comment]
@udf2457 I ended up using `--no-gpg-checks` as [schaefi](https://github.com/schaefi) suggested.

**Comment by udf2457** [comment]
> [@udf2457](https://github.com/udf2457) I ended up using `--no-gpg-checks` as [schaefi](https://github.com/schaefi) suggested.

Actually @zohourih , after bashing my head on this problem all day, and after I sent you the message, I accidentally and randomly found the solution after much more searching, see here....

https://github.com/uyuni-project/uyuni/issues/7717#issuecomment-1772251340


So, you need:

1. `<package name="openSUSE-build-key" />` in the `<packages type="bootstrap">` section
2. `post_bootstrap.sh` as below (or add the line to your existing one if you are already using `post_bootstrap`:

```
#!/usr/bin/env bash
set -uo pipefail
# This is needed because of this : https://github.com/uyuni-project/uyuni/issues/7717#issuecomment-1772251340
rpm --import /usr/lib/rpm/gnupg/keys/gpg-pubkey-29b700a4-62b07e22.asc
```

@schaefi Is there any way `kiwi` can make up for openSUSE's failings ?  e.g. internally calling `rpm --import` on keys a user has explicitly declared under <repository> ?
