### ISSUE TITLE
kiwi doesn't install the correct grub2-efi binary for ISOs for CentOS/Fedora images

### ISSUE THREAD

**Issue by Conan-Kudo** [OSInside/kiwi#2270]
## Problem description
When creating CentOS/Fedora live media, kiwi does not install the right signed grub2 EFI binary.
As a consequence, the resulting image is not bootable.

This is caused by kiwi not being aware of the `gcdx64.efi` (x64), `gcdaa64.efi` (aa64), and `gcdia32.efi` (ia32) binaries to install in place of the normal `grubx64.efi`, `grubaa64.efi`, and `grubia32.efi` binaries for CD/ISO boot.

You can see the install pattern for these in Lorax: https://github.com/weldr/lorax/commit/7ba88931ac38116d1cd0fd9c70b38e5fcc2475a0

## Expected behavior
Built ISO boots in a VM in UEFI mode

## Steps to reproduce the behavior
1. Build a CentOS Hyperscale GNOME or KDE live image
2. Boot it in GNOME Boxes in UEFI mode

Sample KDE build: https://cbs.centos.org/koji/taskinfo?taskID=3303471
Sample GNOME build: https://cbs.centos.org/koji/taskinfo?taskID=3303474

## OS and Software information

* KIWI version: 9.24.52
* Operating system host version: CentOS Stream 9
* Operating system target version: CentOS Stream 9
* Open Build Service version (N/A if not using OBS): N/A
* Koji version (N/A if not using Koji): 1.31

**Comment by schaefi** [comment]
Going to look into it as soon as I find a slot

**Comment by schaefi** [comment]
That we have to differentiate an EFI binary file by the type of the image that we built is new and requires some refactoring. To be honest I question this concept on the Fedora side, what is the benefit of maintaining the many EFI binaries ?

**Comment by Conan-Kudo** [comment]
I don't know, maybe @martinezjavier knows?

**Comment by schaefi** [comment]
@Conan-Kudo is there a difference in the location/names of the EFI binaries for ISO's also in terms of signed and not-signed variants ? In kiwi we have get_signed_grub_loader() and get_unsigned_grub_loader() methods. These needs to change to also receive the image type such that we can differentiate even further

**Comment by Conan-Kudo** [comment]
No. The filenames only differ in the RPM, you have to install it as the single correct name for `shim` to load it.

**Comment by schaefi** [comment]
yes I got that, but are there rpm that differentiate between signed and not-signed, e.g providing ```gcdx64.efi``` and maybe ```gcdx64.signed.efi``` or something ?

**Comment by schaefi** [comment]
The lorax patch does not differentiate them either so I assume not

**Comment by Conan-Kudo** [comment]
They are all signed. Unsigned binaries are not shipped in Fedora for GRUB.
