### ISSUE TITLE
OBS thread usage

### ISSUE THREAD

**Issue by yobson** [OSInside/kiwi#2271]
## Problem description
I’m not sure if this is the place, but when building kiwi images on OBS, the final compression of the image is ‘xz -T=0’ when building in a chroot, this uses all of the cores on the machine instead of the number allocated to the worker

## Expected behaviour
Xz to use the number of allocated cores

## OS and Software information

* KIWI version: 9.24.43
* Operating system host version: openSUSE Leap 15.4
* Operating system target version: openSUSE Leap 15.4
* Open Build Service version (N/A if not using OBS): 2.10
* Koji version (N/A if not using Koji): N/A

**Comment by schaefi** [comment]
Depending on what image you are building there might be several xz (and other) compression calls as part of the process. You are right that kiwi's default options for calling xz is "--threads=0" which takes all available cores into account... usually a wanted setting :)

Can you provide an OBS build log such that we can identify which stage we are talking about and if there is a way to influence the option settings. From a kiwi perspective you can provide an ```/etc/kiwi.yml``` file (for example as a package that you place as support: packagename in your prjconf) with the following content

```yaml
# Setup behaviour of XZ compressor
xz:
  # Specify options used in any xz compression call
  - options: '--threads=0'
```

But as I said there might be other compression calls not issued by kiwi. Thus a log file would be helpful

The part I did not understand is how you would allocate a different CPU set for a chroot ? A chroot just changes the root to another directory but does not impact host capabilities. A chroot or a container still shares the kernel with the host which means the number of available CPUs is the same. Of course quotas and limits for executions can be specified via taskset or other ways to tell the kernel to schedule/behave differently, but changing the number of cores is imho only possible if you run a new machine VM/(or hardware passing nr_cpus=...) which is actually also the information used by xz to parallelize.

I was also a bit confused when you talked about chroot in combination with obs workers. OBS workers to my understanding are either real machines or KVM based virtual machines. In both cases you might have a way to influence the number of cores assigned to the worker but it is not related to a chroot.

So something I probably misunderstood and maybe you can clarify on this part to understand the issue better

Thanks

**Comment by schaefi** [comment]
I guess the question has been answered
