### ISSUE TITLE
No space left on device (28)

### ISSUE THREAD

**Issue by pham-tuan-binh** [OSInside/kiwi#2276]
## Problem description
I'm building an oem image within a docker container. After changing the kernel-default package to a custom kernel package (repo in a local dir), the kiwi command build with error "No space left on device (28)" from rsync on /var/tmp.
## Expected behaviour
Image built successfully
## Steps to reproduce the behaviour
The image built fine with kernel-default but with a custom kernel  rpm pkg built from linux-5.14.21, it showed the error.
## OS and Software information
Docker
Suse LES 15 Sp4

Ker
* KIWI version: 9.24.49
* Operating system host version: 
* Operating system target version: 
* Open Build Service version (N/A if not using OBS): 
* Koji version (N/A if not using Koji):

**Comment by pham-tuan-binh** [comment]
The error was caused because the size of the package is too big (~1.2gb). After reducing the size to 80mb, everything works.

**Comment by schaefi** [comment]
ok, seems like this one can be closed
