### ISSUE TITLE
Cant build image by new version kiwi

### ISSUE THREAD

**Issue by black13ua** [OSInside/kiwi#2277]
## Problem description
After update kiwi 9.24.41 -> 9.24.57 build failed with error:

```
...
[  192s] [ INFO    ]: 15:14:50 | --> EFI partition adding 20 MB
[  192s] [ INFO    ]: 15:14:50 | Using calculated disk size: 2237 MB
[  192s] [ INFO    ]: 15:14:50 | Creating raw disk image /usr/src/packages/KIWI-oem/kiwi-test-image-live-disk-v8.x86_64-1.3.0.raw
[  192s] [ DEBUG   ]: 15:14:50 | EXEC: [qemu-img create /usr/src/packages/KIWI-oem/kiwi-test-image-live-disk-v8.x86_64-1.3.0.raw 2237M]
[  192s] [ DEBUG   ]: 15:14:50 | EXEC: [losetup -f --show /usr/src/packages/KIWI-oem/kiwi-test-image-live-disk-v8.x86_64-1.3.0.raw]
[  192s] [ DEBUG   ]: 15:14:50 | Initialize gpt disk
[  192s] [ DEBUG   ]: 15:14:50 | EXEC: [sgdisk --zap-all /dev/loop0]
[  193s] [ INFO    ]: 15:14:51 | --> creating EFI CSM(legacy bios) partition
[  193s] [ DEBUG   ]: 15:14:51 | EXEC: [sgdisk -n 1:2048:+2M -c 1:p.legacy /dev/loop0]
[  194s] [ DEBUG   ]: 15:14:52 | EXEC: [sgdisk -t 1:EF02 /dev/loop0]
[  196s] [ INFO    ]: 15:14:54 | --> creating EFI partition
[  196s] [ DEBUG   ]: 15:14:54 | EXEC: [sgdisk -n 2:0:+20M -c 2:p.UEFI /dev/loop0]
[  197s] [ DEBUG   ]: 15:14:55 | EXEC: [sgdisk -t 2:EF00 /dev/loop0]
[  198s] [ INFO    ]: 15:14:56 | --> using all_freeMB for the root(rw) partition if present
[  198s] [ INFO    ]: 15:14:56 | --> creating root partition [with 0 clone(s)]
[  198s] [ DEBUG   ]: 15:14:56 | EXEC: [sgdisk -n 3:0:0 -c 3:p.lxroot /dev/loop0]
[  199s] [ DEBUG   ]: 15:14:57 | EXEC: [sgdisk -t 3:8300 /dev/loop0]
[  200s] [ DEBUG   ]: 15:14:58 | EXEC: [partx --add /dev/loop0]
[  200s] [ DEBUG   ]: 15:14:58 | EXEC: Failed with stderr: partx: /dev/loop0: error adding partitions 1-3
[  200s] , stdout: (no output on stdout)
[  200s] [ ERROR   ]: 15:14:58 | KiwiCommandError: partx: stderr: partx: /dev/loop0: error adding partitions 1-3
[  200s] , stdout: (no output on stdout)
[  200s] [ INFO    ]: 15:14:58 | Cleaning up LoopDevice instance
[  200s] [ DEBUG   ]: 15:14:58 | EXEC: [losetup -d /dev/loop0]
[  200s] [ INFO    ]: 15:14:58 | Cleaning up BootImageDracut instance
[  200s] [ INFO    ]: 15:14:58 | Cleaning up BootLoaderConfigGrub2 instance
[  200s] 
[  200s] obs01p failed "build appliance.kiwi" at Fri Apr  7 15:14:58 UTC 2023.
```

## Expected behaviour
by kiwi 9.24.41 built fine

## OS and Software information

* KIWI version:  9.24.57
* Operating system host version: 
* Operating system target version:  Oracle Linux 7 & 8
* Open Build Service version (N/A if not using OBS):  2.10.15
* Koji version (N/A if not using Koji):

**Comment by zohourih** [comment]
I second this issue as we have the exact same issue and had to revert to Kiwi 9.24.36 and lock that version or else all our image builds were failing for all versions above that version that are available in SUSE's repository, with the error mentioned above.

**Comment by schaefi** [comment]
I assume you suffer from the partx vs kpartx change. Does the build work if you set the following in ```/etc/kiwi.yml```

```yaml
mapper:
  - part_mapper: kpartx
```

Let me know if this makes a difference. Thanks

**Comment by black13ua** [comment]
/etc/kiwi.yml fixed build for me
@schaefi  thanks!

**Comment by zohourih** [comment]
@schaefi Is there some way we can fix the issue _without_ changing kiwi's default settings? Do we need to add/update some dependence package?

**Comment by schaefi** [comment]
> @schaefi Is there some way we can fix the issue _without_ changing kiwi's default settings? Do we need to add/update some dependence package?

It's interesting that partx did not work on your build host system. So partx comes from util-linux. (my system as an example has util-linux-2.36.2-150300.4.14.3.x86_64 / Leap 15.3). You might want to check on your util-linux package

**Comment by schaefi** [comment]
Hi @t-ru there are some reports that ```partx``` is failing. I also see different versions of partx with fundamental different feature sets on different distributions. This makes it really hard to come up with a stable partition mapper. Thus I agree with you let's change back the default to ```kpartx```. I will come up with a PR today

**Comment by schaefi** [comment]
Hi, it seems not so easy to change the default ;) There is an ongoing conversation on the open PR. I will bring up the defect report details you shared here for further inspections. We might need your input to clarify why it does not work with partx on your system when it does build for leap and TW for us here:

* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:leap/test-image-disk
* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:tumbleweed/test-image-disk

Thank you
