### ISSUE TITLE
OEM ISO fails to build with systemd-boot

### ISSUE THREAD

**Issue by alexandrevicenzi** [OSInside/kiwi#2281]
## Problem description

It is not possible to build an OEM ISO (self install) if systemd-boot is used as the bootloader.

## Expected behavior

OEM ISO builds with systemd-boot.

## Steps to reproduce the behavior

Have an OEM image install ISO.
Switch the bootloader from grub2 to systemd_boot.
Set EFI partition size, as the kernel will be copied to it.

Example:

```xml
<preferences profiles="self-install" arch="x86_64,aarch64">
    <version>0.0.3</version>
    <packagemanager>zypper</packagemanager>
    <rpm-excludedocs>true</rpm-excludedocs>
    <locale>en_US</locale>
    <keytable>us</keytable>
    <timezone>Europe/Berlin</timezone>
    <bootloader-theme>openSUSE</bootloader-theme>
    <bootsplash-theme>bgrt</bootsplash-theme>
    <type
        image="oem"
        installiso="true"
        installboot="install"
        install_continue_on_timeout="false"
        initrd_system="dracut"
        filesystem="btrfs"
        fsmountoptions="compress=lzo,autodefrag"
        btrfs_root_is_snapshot="true"
        btrfs_quota_groups="true"
        bootpartition="false"
        firmware="efi"
        efipartsize="200"
        bootkernel="custom"
        devicepersistency="by-uuid"
        bundle_format="%N-VM.%A-%M.%m.%p-%I">
        <bootloader name="systemd_boot" timeout="10"/>
        <systemdisk>
            <volume name="home"/>
            <volume name="root"/>
            <volume name="tmp"/>
            <volume name="opt"/>
            <volume name="srv"/>
            <volume name="boot/efi" mountpoint="boot/efi"/>
            <volume name="usr/local"/>
            <volume name="var" copy_on_write="false"/>
        </systemdisk>
    </type>
</preferences>
```

Error:

```plain
[  115s] [ INFO    ]: 16:28:36 | Creating squashfs embedded disk image
[  115s] [ DEBUG   ]: 16:28:36 | EXEC: [cp -l /usr/src/packages/KIWI-oem/ALP-Automotive.x86_64-0.0.3.raw /usr/src/packages/KIWI-oem/kiwi_install_squashfs.a5v88t6f/ALP-Automotive.raw]
[  115s] [ DEBUG   ]: 16:28:36 | EXEC: [mksquashfs /usr/src/packages/KIWI-oem/kiwi_install_squashfs.a5v88t6f /usr/src/packages/KIWI-oem/ALP-Automotive.raw.squashfs -noappend -b 1M -comp xz -Xbcj x86]
[  185s] [ DEBUG   ]: 16:29:45 | EXEC: [mv /usr/src/packages/KIWI-oem/ALP-Automotive.raw.squashfs /usr/src/packages/KIWI-oem/kiwi_install_media.vsjfobpn]
[  185s] [ INFO    ]: 16:29:45 | Setting up install image bootloader configuration
[  185s] [ DEBUG   ]: 16:29:45 | "grub2-install": in paths "/usr/src/packages/KIWI-oem/build/image-root/sbin:/usr/src/packages/KIWI-oem/build/image-root/usr/sbin:/usr/src/packages/KIWI-oem/build/image-root/usr/local/sbin:/usr/src/packages/KIWI-oem/build/image-root/root/bin:/usr/src/packages/KIWI-oem/build/image-root/usr/local/bin:/usr/src/packages/KIWI-oem/build/image-root/usr/bin:/usr/src/packages/KIWI-oem/build/image-root/bin" exists: "False" mode match: not checked
[  185s] [ INFO    ]: 16:29:45 | Creating grub2 bootloader images
[  185s] [ DEBUG   ]: 16:29:45 | EXEC: [mkdir -p /usr/src/packages/KIWI-oem/kiwi_install_media.vsjfobpn/EFI/BOOT]
[  185s] [ INFO    ]: 16:29:45 | --> Creating identifier file 0x27f114f3
[  185s] [ DEBUG   ]: 16:29:45 | EXEC: [mkdir -p /usr/src/packages/KIWI-oem/kiwi_install_media.vsjfobpn/boot/grub]
[  185s] [ DEBUG   ]: 16:29:45 | Searching grub file: unicode.pf2
[  185s] [ DEBUG   ]: 16:29:45 | --> /usr/src/packages/KIWI-oem/build/image-root/usr/share/grub2/unicode.pf2
[  185s] [ DEBUG   ]: 16:29:45 | --> /usr/src/packages/KIWI-oem/build/image-root/usr/lib/grub2/unicode.pf2
[  185s] [ DEBUG   ]: 16:29:45 | --> /usr/src/packages/KIWI-oem/build/image-root/usr/share/grub/unicode.pf2
[  185s] [ DEBUG   ]: 16:29:45 | --> /usr/src/packages/KIWI-oem/build/image-root/usr/lib/grub/unicode.pf2
[  185s] [ ERROR   ]: 16:29:45 | KiwiBootLoaderGrubFontError: Setting up unicode font failed with grub path unicode.pf2 not found in ['/usr/src/packages/KIWI-oem/build/image-root/usr/share/grub2/unicode.pf2', '/usr/src/packages/KIWI-oem/build/image-root/usr/lib/grub2/unicode.pf2', '/usr/src/packages/KIWI-oem/build/image-root/usr/share/grub/unicode.pf2', '/usr/src/packages/KIWI-oem/build/image-root/usr/lib/grub/unicode.pf2']
[  185s] [ INFO    ]: 16:29:45 | Cleaning up FileSystemSquashFs instance
[  185s] [ INFO    ]: 16:29:45 | Cleaning up BootLoaderConfigGrub2 instance
[  185s] [ INFO    ]: 16:29:45 | Cleaning up BootImageDracut instance
[  185s] [ INFO    ]: 16:29:45 | Cleaning up BootImageDracut instance
[  185s] [ DEBUG   ]: 16:29:45 | EXEC: [mountpoint -q /usr/src/packages/KIWI-oem/build/image-root/dev]
[  185s] [ DEBUG   ]: 16:29:45 | EXEC: [mountpoint -q /usr/src/packages/KIWI-oem/build/image-root/proc]
[  185s] Failed to write wtmp record, ignoring: Read-only file system
[  185s] Failed to write utmp record: Read-only file system
[  185s] Powering off.
[  185s] [  180.826511][T10872] reboot: Power down
```

As shown in the error, even if the bootloader is not grub2, Kiwi still attempts to create a grub2 image, and it will fail because grub2 is not installed, nor the fonts.

## OS and Software information

* KIWI version: Project 9.24.57 Machine 9.24.43
* Operating system host version: Leap 15.4
* Operating system target version: ALP
* Open Build Service version (N/A if not using OBS): openSUSE OBS (API version 2.11~alpha.20230414T134408.a17d0230)
* Koji version (N/A if not using Koji): N/A

**Comment by schaefi** [comment]
yep ISO boot support through sd boot is not yet implemented as I wrote on the matrix channel.

Thanks for reporting

**Comment by schaefi** [comment]
As @Conan-Kudo said this might be not so easy to achieve because the sd-boot EFI module will probably not able to read the iso9660 filesystem. In case of grub, grub has support for reading it and so the grub EFI binary can do it. In case of sd-boot an EFI driver will be needed to natively support reading from the ISO. We don't have that and it is also outside of the kiwi scope to provide one.

**Comment by schaefi** [comment]
> Is there a way to create an ISO image with ISOLinux to boot, but once the installation happens, it would use sd-boot?

our fallback here is grub. Your build failed because no grub is installed. I know why you don't want grub because it's GPL3 but using systemd-boot means you want to boot via EFI (or the uboot that loads an efi binary on arm process). isolinux or syslinux don't boot in EFI mode only in legacy CSM or BIOS mode. Therefore the fallback with ```firmware="efi"``` is grub and the fallback with ```firmware="bios"``` is isolinux. Also isolinux does not exist on arm it's a pure x86 loader. Overall you would limit yourself with isolinux a lot. I'm sorry we are not changing that loader strategy for ISOs

**Comment by Conan-Kudo** [comment]
The only fully supported bootloader at this time is GRUB. Please use that.

**Comment by schaefi** [comment]
During hackweek I worked on trying to make systemd-boot to fly on ISO images but failed for the following reasons:

1. bootctl install requires a FAT filesystem to put data in /boot/efi. There is afaik no option to say, don't check it. If you add EFI boot to an ISO it works in a way that you add an alternative boot image to xorriso which is a FAT image that contains the EFI layout and binary. With some trickery this might be possible with bootctl too

```
qemu-img create fakedisk 20M
gdisk fakedisk
==> create a partition
==> set EF00 code
kpartx -a fakedisk
mkdosfs -n BOOT /dev/mapper/loop0p1
mount /dev/mapper/loop0p1 /mnt
sudo bootctl install --esp-path /mnt/ --no-variables

---
Created "/mnt/EFI".
Created "/mnt/EFI/systemd".
Created "/mnt/EFI/BOOT".
Created "/mnt/loader".
Created "/mnt/loader/entries".
Created "/mnt/EFI/Linux".
Copied "/usr/lib/systemd/boot/efi/systemd-bootx64.efi" to "/mnt//EFI/systemd/systemd-bootx64.efi".
Copied "/usr/lib/systemd/boot/efi/systemd-bootx64.efi" to "/mnt//EFI/BOOT/BOOTX64.EFI".
Created "/mnt/bc8499a73619491cb692083ffb3c3c24".
Random seed file /mnt//loader/random-seed successfully written (512 bytes).
---

umount /mnt
dd if=/dev/mapper/loop0p1 of=efifat.img
```

2. And use this in xorriso as alternative loader, but then the next problem starts. There is no code in systemd-boot that can read from iso9660 natively. So if the alt loader in the ISO loads the embedded efi binary it will not be able to read anything from the ISO, kernel, initrd, config... grub provides support for all these but systemd-boot doesn't at the moment and to my knowledge

At this point I stopped investigating and I also find it very cumbersome to work work with systemd-boot regarding ISO boot. I'm sure there will be something in the future that makes this more straight forward.

**Comment by Conan-Kudo** [comment]
cc: @DaanDeMeyer @davide125

**Comment by DaanDeMeyer** [comment]
systemd-boot is only ever going to read from FAT which is the only thing that UEFI supports natively. Last time I looked at this, the idea would be to use the appended_partition stuff in xorriso to append a FAT partition to the ISO image and boot from that with El Torito. I don't remember the specifics though.

**Comment by schaefi** [comment]
> systemd-boot is only ever going to read from FAT which is the only thing that UEFI supports natively. Last time I looked at this, the idea would be to use the appended_partition stuff in xorriso to append a FAT partition to the ISO image and boot from that with El Torito. I don't remember the specifics though.

yes this is the way we support in kiwi and which I tried to adapt to the systemd-boot provided EFI binary, see the above snippet. It also works in a way that the produced ISO loads the EFI binary embedded into the fat image. But the systemd-boot provided binary that I used had no support reading from iso9660 filesystem, so the thing does not continue to boot

**Comment by schaefi** [comment]
But I have another idea and there is also the risk that I made a mistake. I'll give it another try and report back

**Comment by schaefi** [comment]
I got it to work :) pushed a work branch and need to finalize the code prior pull request
