### ISSUE TITLE
Repository type and flags are ignored If obsrepositories as source path is used

### ISSUE THREAD

**Issue by glaubway** [OSInside/kiwi#2310]
## Problem description
When I setup project repository like this:
```
    <repository type="apt-deb">
        <source path="obsrepositories:/"/>
    </repository>
```
In kiwi logs I observed that the type of repository was set as rpm-md, but not apt-deb
```
[   99s] [ INFO    ]: 13:53:37 | Setting up repository dir:///./repos/Ubuntu:/20.04/main
[   99s] [ INFO    ]: 13:53:37 | --> Type: rpm-md
[   99s] [ INFO    ]: 13:53:37 | --> Priority: 7
[   99s] [ INFO    ]: 13:53:37 | --> Translated: /repos/Ubuntu:/20.04/main
[   99s] [ INFO    ]: 13:53:37 | --> Alias: 86efffc5b454cbf11106cb20438bde91
[   99s] [ DEBUG   ]: 13:53:37 | EXEC: [mkdir -p /usr/src/packages/KIWI-oem/build/image-root/repos/Ubuntu:/20.04/main]
[   99s] [ DEBUG   ]: 13:53:37 | EXEC: [mountpoint -q /usr/src/packages/KIWI-oem/build/image-root/repos/Ubuntu:/20.04/main]
[   99s] [ DEBUG   ]: 13:53:37 | EXEC: [mount -n --bind /repos/Ubuntu:/20.04/main /usr/src/packages/KIWI-oem/build/image-root/repos/Ubuntu:/20.04/main]
```
Also, seems even if I add `repository_gpgcheck="false"` flag, it won't be added into apt config as I have faced with unsigned repository error
```
[   99s] [ ERROR   ]: 13:53:37 | KiwiCommandError: apt-get: stderr: E: The repository 'file:/repos/Ubuntu:/20.04/main ./ Release' is not signed.
[   99s] Get:8 file:/repos/Ubuntu:/20.04/main ./ InRelease
[   99s] Ign:8 file:/repos/Ubuntu:/20.04/main ./ InRelease
[   99s] Get:19 file:/repos/Ubuntu:/20.04/main ./ Release [468 B]
[   99s] Get:30 file:/repos/Ubuntu:/20.04/main ./ Release.gpg
[   99s] Ign:30 file:/repos/Ubuntu:/20.04/main ./ Release.gpg
```
## Expected behaviour
Repository type and flags should be passed correctly 

## Steps to reproduce the behaviour
Create debian/ubuntu kiwi project with obsrepositories as repo source and build it with OBS

## OS and Software information

* KIWI version: 
* Operating system host version: 9.24.60
* Operating system target version: Ubuntu Focal (20.04)
* Open Build Service version (N/A if not using OBS): 2.10
* Koji version (N/A if not using Koji):

**Comment by glaubway** [comment]
Hmm, okay, seems it mostly OBS issue, not KIWI, I have found similar closed issue at their GitHub https://github.com/openSUSE/open-build-service/issues/9079

**Comment by schaefi** [comment]
Your observations are correct but I'm afraid we won't be able to fix that in the kiwi scope. OBS reads partially the kiwi config and applies its own internal repository management as you probably found out yourself in the meantime.

You can control the repo settings when building with OBS at best if you place them in your OBS prjconf and in the kiwi file you then only add that obsrepositories entry as you did.

There are however, downsides especially when building for non rpm based distributions. In that case you need to place the repositories in the kiwi file and keep the prjconf repo list empty. Here is an example:

* https://github.com/OSInside/kiwi/blob/master/build-tests/x86/ubuntu/test-image-live-disk/appliance.kiwi#L54

Hope this helps

**Comment by itoffshore** [comment]
* For anyone else coming across this - you can build outside OBS if you add `live-add-yast-repos` to the `xml` as a package
* To also add the `oss` repo:
```
    <!--default repos added via live-add-yast-repos which is removed in config.sh-->
    <repository type="rpm-md" alias="repo-oss" priority="2" imageinclude="false">
        <source path="https://download.opensuse.org/tumbleweed/repo/oss"/>
    </repository>
```

* building on `zram` volumes is fast:

```
[ INFO    ]: 23:33:24 | --> installation_image: /build/kiwi-build/MicroOS-k0s.x86_64-17.0.2-10gb.install.iso

real    4m6.238s
user    15m55.652s
sys     1m34.695s
Tue Sep 16 23:33:24 UTC 2025

```
