### ISSUE TITLE
isoschematron got removed from lxml on Rawhide

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi#2314]
## Problem description

https://src.fedoraproject.org/rpms/python-lxml/c/9d95f5a04edc386313fa854541971b3af07bcae1?branch=rawhide
https://gitlab.com/fedora/legal/fedora-license-data/-/issues/154

As seen above reasons are a license issue. However, this breaks kiwi completely

We need to find a solution. One solution is to turn the schematron validation into a dynamic loadable code point.
However, I wonder because we are using schematron rules since years and if possible I'd like to get the module back instead of hacking around it

**Comment by Conan-Kudo** [comment]
cc: @davide125

**Comment by davide125** [comment]
https://bugs.launchpad.net/lxml/+bug/2024343 is trying to address this upstream, but having read the license review ticket (https://gitlab.com/fedora/legal/fedora-license-data/-/issues/154) this doesn't look good. Unless upstream is somehow able to relicense this to something compliant, we will have to find an alternative.

**Comment by schaefi** [comment]
re-open just for conversation at the community meeting

**Comment by schaefi** [comment]
@Conan-Kudo if you can send the libxml people a message as we discussed it would be great. Maybe there is an option in the future

**Comment by Conan-Kudo** [comment]
I sent the message, we'll see what happens next.

**Comment by Conan-Kudo** [comment]
[The message made it to the list](https://mail.python.org/archives/list/lxml@python.org/thread/XZZAANG3Y2EMTVTQ66AH7WKB7N4VILUP/) with no replies that I can see, but it seems to have triggered discussion in [the LP bug](https://bugs.launchpad.net/lxml/+bug/2024343).

The result is that lxml 5.0 allows schematron to work without the actual rng file that is afflicted with the license issue now.

cc: @hroncok, @davide125

**Comment by Conan-Kudo** [comment]
[The message made it to the list](https://mail.python.org/archives/list/lxml@python.org/thread/XZZAANG3Y2EMTVTQ66AH7WKB7N4VILUP/) with no replies that I can see, but it seems to have triggered discussion in [the LP bug](https://bugs.launchpad.net/lxml/+bug/2024343).

The result is that [a fix has been committed for lxml 5.0 that allows schematron to work without the actual rng file that is afflicted with the license issue](https://github.com/lxml/lxml/commit/4bfab2c821961fb4c5ed8a04e329778c9b09a1df) now.

cc: @hroncok, @davide125

**Comment by Conan-Kudo** [comment]
A pull request to update things has been submitted by @hroncok for Rawhide: https://src.fedoraproject.org/rpms/python-lxml/pull-request/28
