### ISSUE TITLE
Grub menu problem with live isos in EFI mode

### ISSUE THREAD

**Issue by slowpeek** [OSInside/kiwi#2320]
## Problem description

When I press Esc in the top level grub menu of leap/tumbleweed live isos booted in EFI mode, grub shell screen is shown without an evident way to get back to the menu

## Expected behaviour

Esc in the top level grub menu in EFI mode should do nothing, like when the same iso is booted in BIOS mode.

## Steps to reproduce the behaviour

- create a new EFI vm
- attach a leap/tumbleweed live iso to it. I tried leap 15.5 and tumbleweed 20230705
- power the vm up, wait for grub menu to appear
- press Esc
- try to get back to the menu like press Esc once more

Repeat it in a BIOS vm and notice there is no such problem.

## OS and Software information

* KIWI version: the problem supposedly dates back to this commit https://github.com/OSInside/kiwi/commit/3255264d4c57678c2f6cd5b1243de340e76230ed
* Operating system host/target version: irrelevant

## Research

The origin of the problem are these lines:

https://github.com/OSInside/kiwi/blob/16a703cd98b8c543bb5e2848e7b5203275472a09/kiwi/bootloader/config/grub2.py#L1078

https://github.com/OSInside/kiwi/blob/16a703cd98b8c543bb5e2848e7b5203275472a09/kiwi/bootloader/config/grub2.py#L1099

Was there any particular reason to use `configfile` instead of `source` there? With `source` the problem goes away: the top level menu is not nested into some scope, there is nowhere to return with Esc, hence it does nothing.

shim-install also creates such transit grub config and it uses `source`:

```
428 cat <<EOF
429 search --fs-uuid --set=root ${cfg_fs_uuid}
430 set prefix=(\${root})`${grub_mkrelpath} ${grub_cfg_dirname}`
431 source "\${prefix}/${grub_cfg_basename}"
432 EOF
```

**Comment by Vogtinator** [comment]
Using `source` sounds like the right way, would you open a PR?

**Comment by slowpeek** [comment]
> Using `source` sounds like the right way, would you open a PR?

https://github.com/OSInside/kiwi/pull/2337

**Comment by slowpeek** [comment]
Just fixed the problems with the PR, feel free to evaluate it now
