### ISSUE TITLE
Is there a way to run Kiwi without root (in podman)???

### ISSUE THREAD

**Issue by control-c-cloud** [OSInside/kiwi#2323]
## Problem description
For Security reasons i do not have root access...but i must run kiwi-ng. But this fails ...maybe the fileystem-RPM is a Problem
## Expected behaviour
call kiwi-ng with normal user....like in buildah with no error
## Steps to reproduce the behaviour
call kiwi-ng with normal user
## OS and Software information
Suse 15.1
* KIWI version: 
* Operating system host version: 
* Operating system target version: 
* Open Build Service version (N/A if not using OBS): 
* Koji version (N/A if not using Koji):

**Comment by schaefi** [comment]
* For root less builds I usually go with the boxbuild plugin. It builds inside of a VM using kvm. So the user needs to be in the kvm group and must be able to access /dev/kvm. More information here: https://osinside.github.io/kiwi/plugins/self_contained.html

* Building as non root user in podman should be possible via rootless podman, and then as user ```podman run -ti --rm --privileged ...```. More about rootless podman here: https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md

Hope this helps
