### ISSUE TITLE
CentOS 9 Images in the staging project are unresolvable

### ISSUE THREAD

**Issue by dcermak** [OSInside/kiwi#2335]
## Problem description

All CentOS 9 images from https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:centos/test-image-live-disk-v9 are unresolvable:
```
 unresolvable: nothing provides kbd-legacy = 2.4.0-9.el9 needed by kbd, (got version 2.4.0-8.el9) 
```

**Comment by Conan-Kudo** [comment]
That sounds like OBS is failing to sync the repos internally again. 

cc: @adrianschroeter

**Comment by schaefi** [comment]
yes something is wrong. I sent an e-mail  to the OBS list, no answer so far. Let's wait. This one should self heal and is not something we can do much about it other than reporting

**Comment by schaefi** [comment]
@Conan-Kudo We are getting ignored on that one... no idea how to fix it
