### ISSUE TITLE
Wrong partition mounted when booting live iso

### ISSUE THREAD

**Issue by Vogtinator** [OSInside/kiwi#2338]
This is https://bugzilla.opensuse.org/show_bug.cgi?id=1213595, just posted here for better visibility.

When the iso boots with `root=live:CDLABEL=foobar`, then `/dev/disk/by-label/foobar` is mounted as live image source. However, due to the way the live system is set up with its hybrid ISO layout (1st partition in the MBR points to the ISO9660 volume), both the full drive (e.g. `/dev/sda`) as well as the first partition (`/dev/sda1`) have this label. It's essentially random which block device wins here and it looks like on Leap this race is now won by `/dev/sda`. Mounting the whole block device however means that it's marked as busy by the kernel and thus the creation of the COW partition for persistence fails.

## OS and Software information

* KIWI version: 9.24.43
* Operating system host version: Leap 15.5
* Operating system target version: Leap 15.5
* Open Build Service version (N/A if not using OBS): git

**Comment by schaefi** [comment]
Hmm, I did the following test with the integration test from here:

* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:leap/test-image-live

```
qemu-img create mydisk 10g
sudo dd if=kiwi-test-image-live.x86_64-1.15.3-Build73.13.iso of=mydisk conv=notrunc
kvm -hda mydisk
```

The overlay could be created and the block devices looks like this

```
localhost:~ # lsblk 
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
fd0      2:0    1     4K  0 disk 
loop0    7:0    0 204.7M  1 loop /run/overlay/squashfs_container
loop1    7:1    0   1.1G  1 loop /run/overlay/rootfsbase
sda      8:0    0    10G  0 disk 
├─sda1   8:1    0 280.8M  0 part /run/overlay/live
├─sda2   8:2    0    20M  0 part 
└─sda3   8:3    0   9.7G  0 part /run/overlay/overlayfs
sr0     11:0    1  1024M  0 rom
```

For mounting the label based mount is used which always points to the partition device as I think udev does not take devices with a PTTYPE into account for by-label maps. If the device is the same, always the ISO there is actually only one major:minor for the exact same endpoint.

```
ls -l /dev/disk/by-label/CDROM
lrwxrwxrwx 1 root root 10 Feb 27 20:50 /dev/disk/by-label/CDROM -> ../../sda1
```

if the boot happens through a writable block device major:minor differs for the whole disk and its partitions.
At least it did work that way so far.

However, the leap integration tests builds against openSUSE:Leap:15.4:Update. I will give the test a try with 15.5 as you used this for your test.

**Comment by schaefi** [comment]
I build the integration test image from the kiwi git checkout as follows:

```
sudo ./.tox/unit_py3_11/bin/kiwi-ng system build --description build-tests/x86/leap/test-image-live/ --set-repo http://download.opensuse.org/distribution/leap/15.5/repo/oss/ --target-dir /tmp/mytest
```

and dumped the ISO into a mydisk image as before and booted from it via ```kym -hda mydisk```

The write overlay also worked on 15.5 for me

```
localhost:~ # lsblk 
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
fd0      2:0    1     4K  0 disk 
loop0    7:0    0 257.3M  1 loop /run/overlay/squashfs_container
loop1    7:1    0   1.4G  1 loop /run/overlay/rootfsbase
sda      8:0    0    10G  0 disk 
├─sda1   8:1    0 334.7M  0 part /run/overlay/live
├─sda2   8:2    0    20M  0 part 
└─sda3   8:3    0   9.7G  0 part /run/overlay/overlayfs
sr0     11:0    1  1024M  0 rom  

localhost:~ # touch /foo
localhost:~ # rm /foo

localhost:~ # uname -a

Linux localhost 5.14.21-150500.53-default #1 SMP PREEMPT_DYNAMIC Wed May 10 07:56:26 UTC 2023 (b630043) x86_64 x86_64 x86_64 GNU/Linux

localhost:~ # cat /etc/os-release 
NAME="openSUSE Leap"
VERSION="15.5"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.5"
PRETTY_NAME="openSUSE Leap 15.5"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.5"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap"
```

**Comment by schaefi** [comment]
@Vogtinator So I cannot reproduce the issue so far. Do you see differences compared to your env where it failed ?

Thanks

**Comment by Vogtinator** [comment]
> For mounting the label based mount is used which always points to the partition device as I think udev does not take devices with a PTTYPE into account for by-label maps.

In the case when it broke for me it did, the by-label symlink pointed to the whole block device.

I'll try to reproduce it by changing the fslabel of the partition inside, to force it to fail.

**Comment by Vogtinator** [comment]
This was probably caused by https://github.com/systemd/systemd/issues/28468 which is meanwhie supposedly fixed.

So I'll close this until it happens again, which is hopefully never.
