### ISSUE TITLE
Questions on writing AL2023 recipe, including needed docs clarification

### ISSUE THREAD

**Issue by stewartsmith** [OSInside/kiwi#2339]
## Problem description
I am working on producing a base Kiwi recipe for building Amazon Linux 2023 based images.

In constructing this recipe, I've faced a couple of questions that I could not readily discern the answers to from the Kiwi documentation. I'm happy to make pull requests to the docs, but would appreciate some pointers as to the right things to do for each of these cases so that I can make the appropriate changes in a PR.

## Expected behaviour

1. Easily enabling RPM signature verification on package or repository level (but not repo metadata signing)
  Amazon Linux RPMs are GPG signed, with the key available in most RPM distributions due to their presence in the `distribution-gpg-keys` package (see https://github.com/xsuchy/distribution-gpg-keys/tree/main/keys/amazon-linux ). While I could figure out where I *think* I should add a path to the GPG key (installed from that package), it appeared the documentation at https://osinside.github.io/kiwi/image_description/elements.html#repository-source ended up with validation errors, while https://osinside.github.io/kiwi/image_description/elements.html#repository would check for repository metadata signing.
  What is the right way to do this?
2. Using `$releasever` and `$basearch` in `yum` repository configuration?
 The examples I could find in `build-tests/` all seemed to point to OBS, while I wanted to point to our yum repos on the CDN. I couldn't immediately work out how to substitute in different things for architectures. Am I missing something?
  We also have `releasever` used to enable our [Deterministic updates through versioned repositories](https://docs.aws.amazon.com/linux/al2023/ug/deterministic-upgrades.html) feature. i.e. if you set `releasever` to `2023.0.20230315` you will **always** get **exactly** what the first GA release was, and will not get *any* update since 15th March 2023 unless you take some other action. It would be good to have the recipe default to `latest`, but be able to accept an option where we set `releasever` and point to the appropriate mirror list, but I couldn't quite work out how to make that happen.
  What am I Missing?
2. Where to submit new base recipes?
  Is this something to PR here? Something in the `build-tests/` hierarchy?
2. Ability to install bootstrap packages in a bootstrap environment.
   It appears that the bootstrap set of packages are installed using the host packaging system (in this case `dnf`). Is there any provision for a https://rpm-software-management.github.io/mock/Feature-bootstrap.html like environment where a container could be specified which contains the appropriate tools to be able to do the bootstrap install? This would mean we could use more modern hosts to build images for prior versions of Amazon Linux, without needing a close match between host and target.
  It appears that https://osinside.github.io/kiwi/plugins/self_contained.html#self-contained *may* be along these lines, but needing KVM is a bit overkill for this purpose, and rules out image building on non-metal EC2 instance types.
3. The difference between `efi` and `uefi` was not easy to find out. For AL2023, we do support UEFI Secure Boot in EC2, but not quite in the way that Linux distributions typically do for use on bare metal systems. i.e. we don't have a shim. Thus the "err... I don't want secure boot" issue cropped up when using `uefi`, but solved by using `efi` (which I think I only worked out by grepping for `uefi` through the source code and then reading some `if` conditions
4. Different `root` overlay for different image types. For the images we produce, we have a couple of differences in files we copy into the the resulting image based on image type. The ones below are for the `onprem` type, but for, say an EC2 AMI, we have a configuration to skip `cloud-init-local` which improves launch times. Arguably the ideal situation is that this should all be RPMs, but if reality was the ideal world other things would be different too :)

## Steps to reproduce the behaviour
The following produced a booting-to-Login image:

You'll need this at `root/etc/default/grub`
```
GRUB_CMDLINE_LINUX_DEFAULT="console=ttyS0,115200n8 console=tty0 rd.emergency=poweroff rd.shell=0 selinux=1 security=selinux quiet"
GRUB_TIMEOUT=0
GRUB_DISABLE_RECOVERY="true"
GRUB_TERMINAL="ec2-console"
GRUB_ENABLE_BLSCFG="true"
GRUB_X86_USE_32BIT="true"
GRUB_DEFAULT=saved
GRUB_UPDATE_DEFAULT_KERNEL=true
```

and this at `root/etc/cloud/cloud.cfg.d/02-onprem.cfg`
```
datasource_list: [ NoCloud, AltCloud, ConfigDrive, OVF, None ]
```

and then your `appliance.kiwi` can look like:

```
<?xml version="1.0" encoding="utf-8"?>

<image schemaversion="7.5" name="amazonlinux-2023">
    <description type="system">
        <author>Stewart Smith</author>
        <contact>trawets@amazon.com</contact>
        <specification>Example Amazon Linux 2023 kiwi config</specification>
    </description>
    <profiles>
        <profile name="Virtual" description="Virtual image of Amazon Linux 2023"/>
    </profiles>
    <preferences>
        <version>2.0.0</version>
        <packagemanager>dnf</packagemanager>
        <keytable>us</keytable>
        <timezone>UTC</timezone>
        <rpm-check-signatures>true</rpm-check-signatures>
    </preferences>
    <preferences profiles="Virtual">
      <type image="oem" filesystem="xfs" kernelcmdline="console=ttyS0" firmware="efi" format="qcow2">
            <oemconfig>
                <oem-resize>false</oem-resize>
            </oemconfig>
            <bootloader name="grub2" console="serial" timeout="10"/>
        </type>
    </preferences>
    <repository imageinclude="false" sourcetype="mirrorlist">
      <source path="https://cdn.amazonlinux.com/al2023/core/mirrors/latest/x86_64/mirror.list"/>
    </repository>
    <packages type="bootstrap" patternType="onlyRequired">
      <package name="dnf"/>
      <package name="curl-minimal"/>
      <package name="gnupg2-minimal"/>
    </packages>
    <packages type="image" patternType="onlyRequired">
      <namedCollection name="onprem"/>
      <namedCollection name="onprem-minimal"/>
      <package name="kernel"/>
      <package name="grub2-pc"/>
      <package name="grub2-pc-modules"/>
      <package name="grub2-efi-x64-modules"/>
      <package name="grub2-efi-x64-ec2"/>
      <package name="zstd"/>
      <package name="systemd-networkd"/>
    </packages>
</image>
```

Built on a Fedora 38 instance, and tested with `qemu-system-x86_64 -boot c -net nic -net user  -m 4G -cpu max -smp 4 -hda testboot -bios /usr/share/edk2/ovmf/OVMF_CODE.fd  -nographic` *just* to booting to a Login prompt, and not a moment further.

## OS and Software information

* KIWI version: 55984933437e212c10e0b3ab0f5f6b3913ad6424
* Operating system host version: Fedora 38
* Operating system target version: Amazon Linux 2023
* Open Build Service version (N/A if not using OBS): N/A
* Koji version (N/A if not using Koji): N/A

**Comment by schaefi** [comment]
In reply to item 4)

> It appears that https://osinside.github.io/kiwi/plugins/self_contained.html#self-contained may be along these lines, but needing KVM is a bit overkill for this purpose, and rules out image building on non-metal EC2 instance types.

You are right, if a privileged container does not match your workload requirements the kiwi box plugin is a way to fully isolate the procedure. Access to ```/dev/kvm``` needs to be granted but also the non-accelerated emulation will work... but slow as you can imagine.

Regarding EC2, you should be able to directly build the image on an ec2 instance that has kiwi on board. I regularly use even t2-micro instances to build images there and since the instance provides isolation you don't need container or VM workloads.

**Comment by schaefi** [comment]
In reply to item 6)

> Different root overlay for different image types. For the images we produce, we have a couple of differences in files we copy into the the resulting image based on image type. The ones below are for the onprem type, but for, say an EC2 AMI, we have a configuration to skip cloud-init-local which improves launch times. Arguably the ideal situation is that this should all be RPMs, but if reality was the ideal world other things would be different too :)

yeah the world is not an ideal place :) For managing different root overlays I use different archives. For example I built cloud images for AWS, GCE and Azure. All of them need different overlays for the provisioning data. So I have three tarballs:

* ec2.tar.gz
* azure.tar.gz
* gce.tar.gz

and in kiwi I can differentiate them via profiles:

```xml
<profiles>
    <profile name="EC2" description="EC2 stuff"/>
    <profile name="Azure description="Azure stuff"/>
    <profile name="GCE" description="GCE stuff"/>
</profiles>

...


<packages type="image" profiles="EC2">
    <archive name="ec2.tar.gz"/>
</packages>
<packages type="image" profiles="Azure">
    <archive name="azure.tar.gz"/>
</packages>
<packages type="image" profiles="GCE">
    <archive name="gce.tar.gz"/>
</packages>
```

I think you got the idea.

But from my experience with maintenance of image descriptions; The best solution is if all data comes from package repos which have maintainers ;) So you are not alone with all this

**Comment by schaefi** [comment]
@stewartsmith does this answer your questions ?

**Comment by schaefi** [comment]
I assume yes ;)
