### ISSUE TITLE
Misleading "Could not parse setfiles output" warning

### ISSUE THREAD

**Issue by Vogtinator** [OSInside/kiwi#2350]
```
[   76s] [ INFO    ]: 15:08:49 | Check/Fix File Permissions
[   76s] [ DEBUG   ]: 15:08:49 | EXEC: [chroot /usr/src/packages/KIWI-vmx/build/image-root chkstat --system --set]
[   76s] [ INFO    ]: 15:08:49 | Processing SELinux file security contexts
[   76s] [ DEBUG   ]: 15:08:49 | EXEC: [chroot /usr/src/packages/KIWI-vmx/build/image-root setfiles --help]
[   76s] [ WARNING ]: 15:08:49 | Could not parse setfiles output
[   76s] [ DEBUG   ]: 15:08:49 | EXEC: [chroot /usr/src/packages/KIWI-vmx/build/image-root setfiles -F -p -c /etc/selinux/targeted/policy/policy.33 -e /proc -e /sys -e /dev /etc/selinux/targeted/contexts/files/file_contexts /]
```

FWICT kiwi checks whether `setfiles` supports a particular option. It's not an error if that one isn't supported, it just uses an alternative one instead. The warning implies that some parsing failed which is not the case.

## OS and Software information

* KIWI version: 9.24.61
* Operating system host version: openSUSE Tumbleweed 20200809
* Operating system target version: openSUSE MicroOS 2020809
* Open Build Service version (N/A if not using OBS): N/A
* Koji version (N/A if not using Koji): N/A

**Comment by schaefi** [comment]
yes this can be misleading
