### ISSUE TITLE
Question, how to implement a run_dialog that save to built image

### ISSUE THREAD

**Issue by talk2drys** [OSInside/kiwi#2351]
## Problem description
I was wondering is there is a way to add something like a  user prompt to input text field or drop down option will deploying OEM images similar to dracut-run-interactive  something like the screenshot bellow. my reason is i have to build several appliance that just build the base image and on first book runs a python program that provision the server with specific configuration.

## Something like this
![image](https://github.com/OSInside/kiwi/assets/32944188/e3633e57-dc7b-414e-8018-10757764f898)

the result would be to save the  result somewhere inside the built image

**Comment by schaefi** [comment]
If I understand you correctly you want a custom boot hook. This  can be done by a custom dracut module which you hook in. We documented how to do this here:

* https://osinside.github.io/kiwi/concept_and_workflow/customize_the_boot_process.html#boot-image-hook-scripts
