### ISSUE TITLE
Kiwi's override of the Grub commands when booting with EFI mode don't work in Grub in Ubuntu 23.10

### ISSUE THREAD

**Issue by IsaacJT** [OSInside/kiwi#2354]
## Problem description

Kiwi adds the following snippet to the beginning of `grub.cfg`:

```
set linux=linux
set initrd=initrd
if [ "${grub_cpu}" = "x86_64" -o "${grub_cpu}" = "i386" ]; then
    if [ "${grub_platform}" = "efi" ]; then
        set linux=linuxefi
        set initrd=initrdefi
    fi
fi
export linux initrd
```

This overrides the commands used for loading the initrd and linux binaries when booting in EFI mode. This worked in previous versions of Ubuntu, but since the upgrade to Grub 2.12 this command has been dropped in Ubuntu (compare the list of files: https://packages.ubuntu.com/jammy/amd64/grub-efi-amd64-bin/filelist lists `linuxefi.mod`, while https://packages.ubuntu.com/mantic/amd64/grub-efi-amd64-bin/filelist does not have this file).

This snippet is generated by the following file: https://github.com/OSInside/kiwi/blob/master/kiwi/bootloader/template/grub2.py#L52

This causes the system to fail to boot with the following error:

```
error: can't find command `linuxefi'.
error: can't find command `initrdefi'.
```

As a workaround, the following script can be added to `root/etc/grub.d/01_fix_linuxefi` to override this behaviour and set the `linux` and `initrd` variables:

```
#!/bin/sh

echo "set linux=linux"
echo "set initrd=initrd"
```

After adding this to the image, the system boots without any issues in EFI mode.

## Expected behaviour

The system should boot in EFI mode using Grub as the bootloader.

## Steps to reproduce the behaviour

Generate an EFI-based image using Ubuntu 23.10 and Grub 2.12.

## OS and Software information

* KIWI version:  9.25.11
* Operating system host version: Ubuntu 22.04
* Operating system target version: Ubuntu 23.10
* Open Build Service version (N/A if not using OBS): N/A
* Koji version (N/A if not using Koji): N/A

**Comment by schaefi** [comment]
Hi Isaac, yeah I was thinking if we not entirely drop this linux vs. linuxefi handling. It's just a pita on many ends

**Comment by Conan-Kudo** [comment]
@iammattcoleman and I have been digging into this and we're pretty sure it's no longer needed anymore.

For CentOS Stream live images being done with @tdawson in the CentOS Alternative Images SIG, we ship our own template that doesn't include that anymore: https://pagure.io/centos-sig-alt-images/kiwi-descriptions/blob/c9s/f/grub.cfg.iso-template
