### ISSUE TITLE
Incorrect subvolume configuration with btrfs

### ISSUE THREAD

**Issue by davide125** [OSInside/kiwi#2356]
## Problem description

In the Fedora Asahi Remix we're seeing an issue with `/var` where the `var` subvolume itself is empty and the contents are installed under `/var` in the `root` subvolume itself.

See `root.img` in https://fedora-asahi-remix.org/os/fedora-38-server-202308191708.zip (or https://fedora-asahi-remix.org/os/fedora-38-server-202308191708.raw.zst if you prefer the full raw image). The build logs for that are at https://fedora-asahi-remix.org/os/fedora-38-server-202308191708.logs.zip . You can see the config we used at https://pagure.io/fedora-asahi/kiwi-descriptions/blob/a37f7758c2d9ecc108935456520632f97fdac587/f/platforms/server.xml which specifically does

```
<systemdisk name="fedora">
    <volume name="@root=root"/>
    <volume name="home" parent="/"/>
    <volume name="var" parent="/"/>
</systemdisk>
```

## Expected behaviour
The `/var` subvolume should be populated correctly.

## Steps to reproduce the behaviour
Doing a build with the same config should repro this.

## OS and Software information

* KIWI version: 9.25.12
* Operating system host version: Fedora Cloud 38
* Operating system target version: Fedora Linux 38
* Open Build Service version (N/A if not using OBS): N/A
* Koji version (N/A if not using Koji): N/A

**Comment by Conan-Kudo** [comment]
For now this has been worked around for production builds until this is fixed: https://pagure.io/fedora-asahi/kiwi-descriptions/c/b48721a82a5d5401dd229b23eb7e44c4fa89b5b4

To reproduce, check out the [fedora-asahi/kiwi-descriptions](https://pagure.io/fedora-asahi/kiwi-descriptions) repo at a92c810463c99ecd1462f9fe97b792fd11fb040f (which is prior to the workaround commit).

**Comment by schaefi** [comment]
I found the bug and fixed it for the case here. I have to double check on the after effects of other btrfs layouts and variants though. Thus I need a bit more time before I open the pull request

**Comment by schaefi** [comment]
I'm also going to extend the integration test which uses /home that was empty by default and not critical to the system. So we didn't catch this error :/
