### ISSUE TITLE
Useless python-future in dependencies?

### ISSUE THREAD

**Issue by frenzymadness** [OSInside/kiwi#2361]
Hello. I see that the project depends on future but I cannot find a single usage of it in the codebase.

https://github.com/OSInside/kiwi/blob/9c2c10b3de8d007dbd8190e70ae5610d71526ad4/package/python-kiwi-pkgbuild-template#L24

Do you think it's still useful? I'm asking because future is broken with the latest Python 3.12 and will be even more with 3.13 so it might be a good idea to get rid of it.

**Comment by Conan-Kudo** [comment]
We haven't used `future` since we dropped Python 2 support: https://github.com/OSInside/kiwi/commit/1566750242019353e437699a5e3c9f9e11a4aac8

The PKGBUILD is out of date.
