### ISSUE TITLE
Transactional system images have wrong subvol= set in /etc/fstab

### ISSUE THREAD

**Issue by Vogtinator** [OSInside/kiwi#2366]
## Problem description
The subvol for `/` as indicated by `/etc/fstab` is wrong:

```
localhost:~ # cat /etc/fstab 
UUID=879f672c-585d-4742-84ab-8f94bba1980c / btrfs ro,defaults,subvol=@/.snapshots/1/snapshot 0 0
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^
UUID=879f672c-585d-4742-84ab-8f94bba1980c /.snapshots btrfs defaults,subvol=@/.snapshots 0 0
UUID=879f672c-585d-4742-84ab-8f94bba1980c /home btrfs defaults,subvol=@/home 0 0
...
localhost:~ # findmnt /
TARGET
  SOURCE                              FSTYPE OPTIONS
/ /dev/vda3[/@/.snapshots/3/snapshot] btrfs  ro,relatime,seclabel,space_cache=v2,subvolid=270,subvol=/@/.snapshots/3/snapshot
```

This is probably caused by f8f1c0056e711f9d7ceef7b6057768a29d63af91.

## Expected behaviour

There should not be any `subvol=` set for the `/` mount. The default subvol indicates what `/` is.
(This isn't actually fully true if a "Boot into read-only snapshot" option is used, but hardcoding the first snapshot is almost always wrong).

## OS and Software information

* KIWI version: 9.25.12
* Operating system host version: openSUSE Tumbleweed
* Operating system target version: openSUSE Tumbleweed
* Open Build Service version (N/A if not using OBS): build.opensuse.org
* Koji version (N/A if not using Koji): N/A

**Comment by schaefi** [comment]
>  The default subvol indicates what / is.

correct. With the changes to also allow other "non SUSE" btrfs architectures there was a new attribute introduced called
```btrfs_set_default_volume="true|false"```. Not everyone wants to specify a default volume and that's where this regression comes from.

Thanks for reporting I'm going to fix it today
