### ISSUE TITLE
Reduce XSL transformation list

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi#2368]
## Problem description

So far we support transformation of XML schema versions from the beginning of time. These transformation steps takes time in reading as they are all based on XSL recursions. I think with the next major release we can consider to reduce the
entry version for supported schemas

**Comment by Vogtinator** [comment]
You could also read the schema version programatically and then only apply the xsl files needed for that version.

**Comment by schaefi** [comment]
> You could also read the schema version programatically and then only apply the xsl files needed for that version.

The xsl list is implemented like that. So any transformation starts with something like

```
<xsl:choose>
        <!-- nothing to do if already at 8.0 -->
        <xsl:when test="@schemaversion > 7.6">
            <xsl:copy-of select="/"/>
        </xsl:when>
        <!-- otherwise apply templates -->
        <xsl:otherwise>
            <image schemaversion="8.0">
                <xsl:copy-of select="@*[local-name() != 'schemaversion']"/>
                <xsl:apply-templates  mode="conv76to80"/>
            </image>
        </xsl:otherwise>
    </xsl:choose>
```

That does what you suggested in XSL.

But we carry these checks for since the beginning of the first kiwi version back in 2012 and I think with the move to the v10.x.x we can reduce the list just because I think it's dead coding
