### ISSUE TITLE
Reduce supported distributions to 2024-era options

### ISSUE THREAD

**Issue by Conan-Kudo** [OSInside/kiwi#2369]
Our supported distribution matrix is so wide that it's becoming difficult for us to reason the code around a lot of core functions.

In the community meeting today, we discussed supporting the latest distributions available in 2024. That basically means:

- CentOS Stream 9+
- Fedora Linux 40+
- SUSE ALP
- Debian 12+
- Ubuntu 24.04+

**Comment by schaefi** [comment]
I also like to add the software components to match with the distros:

* bootloader
   - isolinux (should be imho dropped)
   - grub2 (should be supported only in latest version, get rid of all the linuxefi stuff for example)
   - EFI vs UEFI (there should be only one EFI path, secure boot preferred over non secure boot)
   - MBR boot (should this still be supported)

* python version
   - decide on the min python version

* selinux version and tools
   - what is the right way to use selinux and in which version

* container toolkit, umoci, skopeo, buildah
   - min version for these tools ?

* get rid of tool calls which differentiate on parameter capabilities, search for CommandCapabilities and delete no longer needed checks according to the above mentioned distro list

.... there is more

**Comment by Conan-Kudo** [comment]
For the Python version, I think setting our minimum version to Python 3.9 should be fine.

**Comment by schaefi** [comment]
Status update:

- [ ] grub2 (should be supported only in latest version, get rid of all the linuxefi stuff for example) [done in #2424]
- [ ] MBR boot (should this still be supported) [yes stays supported]
- [ ] For the Python version, I think setting our minimum version to Python 3.9 should be fine, done [3.9+ in workflows on main]

**Comment by Conan-Kudo** [comment]
I will be doing this final transition as part of #2370.

**Comment by schaefi** [comment]
> Well, actually, there's still also dropping syslinux/isolinux support...

done in #2439
