### ISSUE TITLE
Regression in new builds: ISO always auto-boots to disk if there is already an OS installed

### ISSUE THREAD

**Issue by zohourih** [OSInside/kiwi#2389]
## Problem description
We recently updated from KIWI v9.24.36 to the latest v9.25.17. Now all of our newly-built SLES 15 SP3 images fail to boot if there is a disk on the system and there is already an OS installed on that disk. In this case, the ISO install menu never comes up and after choosing to boot from the ISO, the boot process, after a certain delay, directly goes to the disk bootloader. This is NOT a BIOS boot option issue as the same issue happens even if we disable all boot options except the ISO/CDROM, or manually choose the ISO/CDROM through the boot menu. Also, the problem won't happen if there is a disk on the system but the disk is empty. This has been reproduced on both actual hardware and VMware. On the exact same environment, ISOs built with the exact same config.xml file but using KIWI v9.24.36 boot up just fine in all of the scenarios described above.

It seems something has changed somewhere in KIWI that now, either the ISO is always auto-choosing the "Boot from disk" option from the install menu without showing the menu at all if there is a valid bootloader on the disk, or when we boot from the ISO, the disk is being incorrectly mounted instead of the ISO.

**Note:** This seems to only happen with systems that have SATA disks. This does **_not_** happen with systems with NVMe drives. Seems like maybe /dev/sdX disk path (which is no longer static/deterministic in new Linux kernels) is being used to mount the ISO, and that somehow ends up choosing the SATA disk on the system instead of the ISO, but since NVMe drives get mounted under /dev/nvmeXXXX, this conflict does not happen in that case.

## Expected behaviour
When booting from an ISO built using KIWI, we expect to get an install menu with options to choose to boot from an existing bootloader on the disk, or boot from the ISO itself.

## Steps to reproduce the behaviour
1. Build an SLES 15 SP3 ISO using KIWI v9.25.17. Example minimal config is at [config.zip](https://github.com/OSInside/kiwi/files/13210831/config.zip). Replace *REPO_SERVER* with your desired server. Build log is at [build.zip](https://github.com/OSInside/kiwi/files/13210852/build.zip)

2. Mount the ISO via IPMI on a real server, or mount it in VMWare (Virtual Box should probably be fine, as well). Make sure the server/VM has at least one SATA disk that would show up under /dev/sdX.
3. Boot from the ISO. It will boot fine since there are no OSes installed on the disk.
4. Install the OS on the SATA disk.
5. Reboot.
6. Try booting from the ISO again: the ISO boot menu will never be shown and you will directly end up at the bootloader on the disk
7. Optional: Repeat previous steps using KIWI v9.24.36. The ISO will correctly boot into its boot menu.

## OS and Software information

* KIWI version: v9.25.17
* Operating system host version: SLES 15 SP3
* Operating system target version: SLES 15 SP3
* Open Build Service version (N/A if not using OBS): N/N
* Koji version (N/A if not using Koji): N/A

**Comment by fnordic** [comment]
I observed the same behavior with KIWI v9.25.12.
If i wipe the MBR of the newly installed system with "dd if=/dev/random of=/dev/sda bs=512 count=1", the ISO install menu shows up again.

**Comment by schaefi** [comment]
Sounds like a really strange issue. So far I cannot imagine what part in kiwi could have caused this. If I understand you correctly you don't see any boot menu under the conditions you described ? If yes this means the code in grub to display the menu is not reached. Before I look closer to this issue I have several questions:

1. how do you boot ? EFI or legacy BIOS
2. Is there any chance that you can provide your build result: /tmp/tmp.H0YMmK50hW/TEST.x86_64-1.0.0.install.iso ?
3. Can you change your image description type setup to the following:

    ```xml
    <type image="oem" filesystem="ext4" initrd_system="dracut" installiso="true" kernelcmdline="splash console=ttyS0 rd.debug" firmware="efi">
            <bootloader name="grub2" console="serial" timeout="30"/>
            <oemconfig>
                <oem-boot-title>Unity Common Host</oem-boot-title>
                <oem-swapsize>2048</oem-swapsize>
                <oem-swap>true</oem-swap>
                <oem-device-filter>/dev/ram</oem-device-filter>
                <oem-multipath-scan>false</oem-multipath-scan>
            </oemconfig>
        </type>
    ```

    See the changes for the console. Can you rebuild your image and repeat the boot process. Is there any information displayed on serial when you run into the error condition ?

Thanks

**Comment by zohourih** [comment]
Yes, we don't see the ISO boot menu at all if there is a working bootloader on a SATA disk on the system.

1. We are booting in legacy mode.
2. Unfortunately, no. The file is too large to attach to the Github issue, and company policy does not allow using standard file sharing methods. I will have to go through IT verification and approval to be able to share large files externally. I would expect it to be fairly simple to reproduce this problem as it seems to be a general bootloader problem.
3. It made no difference; nothing is shown during the ISO boot at all. It seems as soon as the ISO boot is selected, instead of loading the bootloader on the ISO, the existing bootloader on the disk gets loaded.

The most obvious difference I am seeing in the bootloader files between older versions of KIWI, which work, and the newer version is the content of the earlyboot.cfg file.

KIWI v9.24.55 (working):
```
set btrfs_relative_path="yes"
search --file --set=root /boot/0x3444f25b
set prefix=($root)/boot/grub2
configfile ($root)/boot/grub2/grub.cfg
````

KIWI v9.25.17 (broken):
```
set btrfs_relative_path="yes"
search --file --set=root /boot/mbrid
set prefix=($root)/boot/grub2
configfile ($root)/boot/grub2/grub.cfg
```

Not sure if this is the actual source of the problem, though.

Also, I forgot to share my KIWI config file earlier:

```
xz:
  - options: '--threads=8'
container:
  - compress: xz
mapper:
  - part_mapper: kpartx
```

**Comment by schaefi** [comment]
Great catch :+1: yes that could be the issue. If the grub earlyboot script searches for /boot/mbrid that is no longer a unique target and can exist on multiple places :sob: This is a bad bug. I'm looking into it

**Comment by schaefi** [comment]
@zohourih Hi, I have created a pull request to address this issue and did some tests in qemu. Could you please check the change and maybe apply in your environment ? Thanks much

**Comment by zohourih** [comment]
@schaefi I applied the [change](https://github.com/OSInside/kiwi/pull/2391/files) from the merge request to `/usr/lib/python3.6/site-packages/kiwi/bootloader/config/grub.py` in my environment. However, now I am getting a build failure as follows:

```
[ INFO    ]: 17:45:53 | Preparing boot system
[ INFO    ]: 17:45:53 | Precalculating required disk size
[ DEBUG   ]: 17:45:53 | EXEC: [du -s --apparent-size --block-size 1 --exclude /root/kiwi-minimal-test/dist/build/image-root/proc --exclude /root/kiwi-minimal-test/dist/build/image-root/sys --exclude /root/kiwi-minimal-test/dist/build/image-root/dev /root/kiwi-minimal-test/dist/build/image-root]
[ DEBUG   ]: 17:45:54 | EXEC: [bash -c find /root/kiwi-minimal-test/dist/build/image-root | wc -l]
[ INFO    ]: 17:45:54 | --> system data with filesystem overhead needs 886 MB
[ INFO    ]: 17:45:54 | --> swap partition adding 2048 MB
[ INFO    ]: 17:45:54 | --> legacy bios boot partition adding 2 MB
[ INFO    ]: 17:45:54 | --> EFI partition adding 20 MB
[ INFO    ]: 17:45:54 | Using calculated disk size: 2956 MB
[ INFO    ]: 17:45:54 | Creating raw disk image /root/kiwi-minimal-test/dist/TEST.x86_64-1.0.0.raw
[ DEBUG   ]: 17:45:54 | EXEC: [qemu-img create /root/kiwi-minimal-test/dist/TEST.x86_64-1.0.0.raw 2956M]
[ DEBUG   ]: 17:45:54 | EXEC: [losetup -f --show /root/kiwi-minimal-test/dist/TEST.x86_64-1.0.0.raw]
[ ERROR   ]: 17:45:54 | KiwiBootLoaderConfigSetupError: Support for grub2 bootloader config not implemented
[ INFO    ]: 17:45:54 | Cleaning up LoopDevice instance
[ DEBUG   ]: 17:45:54 | EXEC: [losetup -d /dev/loop0]
[ INFO    ]: 17:45:54 | Cleaning up BootImageDracut instance
```

The full log is at: [log.txt](https://github.com/OSInside/kiwi/files/13314443/log.txt)


Aside from this, looking back in the commit log, this is where the change you reverted in the merge request above was originally done:

0a35e64810fd44d3a31b45f5672efbe5fab08a7f

Any idea why this change was does in the first place, and if reverting it is expected to break what was added in 0a35e64810fd44d3a31b45f5672efbe5fab08a7f?

**Comment by zohourih** [comment]
@schaefi  I manually applied the fix from your merge request and indeed the problem is resolved. Looking back in the commit log, this is where the change you reverted in the merge request above was originally done:

0a35e64810fd44d3a31b45f5672efbe5fab08a7f

Any idea why this change was does in the first place, and if reverting it is expected to break what was added in 0a35e64810fd44d3a31b45f5672efbe5fab08a7f?

**Comment by schaefi** [comment]
:) nothing escapes your eyes. You are right I was looking why this change was done in the first place. The reason was a niche case for read-only systems like the one here: https://build.opensuse.org/package/show/home:marcus.schaefer:EOS/suse-eos. If the entire system including /boot is on a read-only fs (squashfs) kiwi cannot write the 0x... number to /boot because it's read-only at the time of the writing. That was the reason for the change. But this change, as you know, caused a regression in a broader scope and so I reverted it. The niche case described is solved by the image description itself such that no breakage appeared on my side

Nevertheless this is the reason why I still did not create new release and investigating if we can change the code in kiwi to provide all metadata files even in the read-only case.

**Comment by zohourih** [comment]
I see, thank you for the clarification.
