### ISSUE TITLE
SelfInstall image should create uEFI boot entry

### ISSUE THREAD

**Issue by jsrain** [OSInside/kiwi#2402]
## Problem description

When deploying a SelfInstall image on an uEFI system, the installer just dumps the image to the selected device. However, I have seen various users who expect that - as it is seen as an installer - it makes sure that the image is booting afterwards without any interaction, which is (depending on the firmware) not always the case. 

## Expected behaviour

The SelfInstall image creates the uEFI entry to boot the just dumped system. Kiwi has all the knowledge needed (number of the partition when building the image, the disk when deploying, path to the uEFI loader can be bistro-specific and therefore may need to be specified in the kiwi image description, similar to the label of the uEFI entry.

## Steps to reproduce the behaviour

Deploy any SelfInstall image on an uEFI system 

## OS and Software information

* KIWI version: any recent
* Operating system host version: SUSE 
* Operating system target version:  SUSE
* Open Build Service version (N/A if not using OBS): any
* Koji version (N/A if not using Koji): N/A

**Comment by schaefi** [comment]
yes makes sense to me. I would call ```efibootmgr``` in case we found an EFI partition on disk as follows

```
efibootmgr -c -d $DISK -p 2 -L "$NAME" -l '\EFI\BOOT\$EFIBINARYNAME.efi'
```

values for DISK, NAME and EFIBINARYNAME are known to kiwi.

However I'm not sure how we should deal with existing entries in the EFI stub ? Also consider installing the same system twice it might end up with several boot entries.

Should there be a cleanup beforehand ? also dangerous.

Any advice on this topic would be appreciated. Thanks

**Comment by jsrain** [comment]
I don't think we should clean existing entries, that could be dangerous. However, the new created one should become the default.

Perhaps one more note: while the partition number is known to kiwi (it creates the partition table), the path on the partition should be configurable in the kiwi config, as different distributions may use different path.

**Comment by Vogtinator** [comment]
IMO this is something the image should do itself on the first boot, using a systemd unit with `ConditionFirstBoot=true` or similar. Making kiwi responsible for this will only result in duplication and eventually divergences in behaviour which will cause issues.

**Comment by schaefi** [comment]
I agree to what @Vogtinator said

**Comment by schaefi** [comment]
Let's do this the way suggested by @Vogtinator
