### ISSUE TITLE
RFE: Flag to tell kiwi to create UEFI-only images for x86_64

### ISSUE THREAD

**Issue by Conan-Kudo** [OSInside/kiwi#2407]
## Problem description
As part of the effort to support [UKIs in Fedora Cloud](https://fedoraproject.org/wiki/Changes/Unified_Kernel_Support_Phase_2), we need to be able to create images that are not hybrid UEFI+BIOS, but instead are UEFI-only. Currently, when setting an image firmware to `efi` or `uefi`, we produce hybrid images and image builds fail if we do not provide GRUB2 for BIOS boot. 

One way to solve this would be to add a `uefi_nocsm` variant to not produce hybrid boot images would resolve this issue. Another way would be to add a `csm=` flag that defaults to `on` but when set to `off` would not produce hybrid images.

## OS and Software information

* KIWI version: 9.25.16
* Operating system host version: Fedora Linux 40
* Operating system target version: Fedora Linux 40
* Open Build Service version (N/A if not using OBS): N/A
* Koji version (N/A if not using Koji): 1.33.1

**Comment by Conan-Kudo** [comment]
cc: @davdunc

**Comment by Conan-Kudo** [comment]
cc: @davdunc @kraxel

**Comment by Conan-Kudo** [comment]
cc: @davide125 @DaanDeMeyer

**Comment by Conan-Kudo** [comment]
I'm personally leaning toward adding a `csm=` flag rather than another weird uefi mode, especially since we want to simplify the uefi firmware modes for kiwi 10.

**Comment by kraxel** [comment]
grub is no problem, it is not used anyway ...
`<bootloader name="custom"/>`
editbootconfig = https://pagure.io/fork/kraxel/fedora-kiwi-descriptions/blob/kraxel/f/uki-setup.sh

**Comment by Conan-Kudo** [comment]
Having `csm=off` would also allow us to disable creating the BIOS boot partition when it's unneeded.
