### ISSUE TITLE
Stop using __del__ for cleanup and switch to context managers

### ISSUE THREAD

**Issue by dcermak** [OSInside/kiwi#2412]
## Problem description

Currently, the kiwi code is relying on `__del__` for cleanup. While this is a typical idiom in C++ (RAII), it is highly uncommon in Python or garbage collected languages in general, as there are generally no guarantees when or if a deleter is ever run. We ensure this in kiwi at the moment via explicit calls to `del foo`.

This is undesirable for multiple reasons:
- unpythonic, i.e. API users will simply not think about explicitly deleting the object, because it is atypical
- thrown exceptions result in cleanup code never running or running in the wrong order

I would thus suggest that we switch to context managers instead.

As this is a potentially breaking API change, we might have to defer this to kiwi 10

**Comment by schaefi** [comment]
Definitely a kiwi-10 topic

I disagree with what you said on "no guarantees when or if a deleter is ever run". Python is an OO language and it's clearly defined when the destructor (__del__) is called and that also works in the designed way. The cases in code where we intentionally call ```del``` on the object instance have their reason because we want the destructor to run prior it going out of scope by the flow of code. You can argue that the implementation which requires an explicit ```del``` is questionable and I would agree with you on that point but the OO design pattern in python works well :)

**Comment by dcermak** [comment]
> I disagree with what you said on "no guarantees when or if a deleter is ever run". Python is an OO language and it's clearly defined when the destructor (`__del__`) is called and that also works in the designed way. 

This is incorrect: https://docs.python.org/3/reference/datamodel.html#object.__del__:
> It is not guaranteed that [__del__()](https://docs.python.org/3/reference/datamodel.html#object.__del__) methods are called for objects that still exist when the interpreter exits.
 
> The cases in code where we intentionally call `del` on the object instance have their reason because we want the destructor to run prior it going out of scope by the flow of code.

This only invokes `__del__` if the reference count reached zero (see the above link). Hopefully that's the case wherever we use finalizers, but it is **not** guaranted.

> You can argue that the implementation which requires an explicit `del` is questionable and I would agree with you on that point but the OO design pattern in python works well :)

Good that we agree, but note that this type of design pattern is explicitly discouraged in Python due to reliance on GC running. In Python Context Managers were added for RAII, relying on finalizers is too brittle.

**Comment by schaefi** [comment]
> relying on finalizers is too brittle.

ok, thanks for the pointers, makes sense

**Comment by schaefi** [comment]
I started to work on this issue. There are many classes based on destructors, I will start with the one used first in the chain of building which is the ```LoopDevice``` class and move it to context manager.
