### ISSUE TITLE
kiwi issue when repo_clone and boot_clone are set

### ISSUE THREAD

**Issue by mfatrez** [OSInside/kiwi#2456]
## Problem description

This error happen when repo_clone and boot_clone are set in the kiwi file

```
Failed with stderr: WARNING: it's recommended to run 'btrfs check --readonly' before this operation.
The whole operation must finish before the filesystem can be mounted again.
If cancelled or interrupted, run 'btrfstune -u' to restart.
ERROR: UUID change canceled+
ERROR: btrfstune failed
, stdout: We are going to change UUID, are your sure? [y/N]: 
```

## Expected behaviour

having a copy of the deployed image in the alternate partition.

## Steps to reproduce the behaviour

Need to have target BTRFS and set root_clone="1" boot_clone="1"

```
       <type image="oem" root_clone="1" boot_clone="1" filesystem="btrfs" fsmountoptions="noatime,compress=lzo" firmware="uefi" kernelcmdline="plymouth.enable=0 swiotlb=512 cma=64M console=ttyS0" bootpartition="true" devicepersistency="by-label" btrfs_root_is_snapshot="true"  efipartsize="16" editbootinstall="editbootinstall_rpi.sh" bootfilesystem="ext4">
            <bootloader name="grub2" console="serial" timeout="10"/>
            <systemdisk name="RaspberryPi">
                <volume name="home"/>
                <volume name="root"/>
                <volume name="tmp"/>
                <volume name="opt"/>
                <volume name="srv"/>
                <volume name="boot/grub2/arm64-efi" mountpoint="boot/grub2/arm64-efi"/>
                <volume name="usr/local"/>
                <volume name="var" copy_on_write="false"/>
            </systemdisk>
            <oemconfig>
                <oem-swap>true</oem-swap>
                <oem-swapsize>500</oem-swapsize>
                <oem-skip-verify>true</oem-skip-verify>
            </oemconfig>
            <partitions>
                <partition name="app_data" size="6G" mountpoint="/opt/myapp" filesystem="xfs"/>
                <partition name="app_logs" size="4G" mountpoint="/var/log/myapp" filesystem="xfs"/>
            </partitions>
            <size unit="G">32</size>
        </type>
```

## OS and Software information

* KIWI version: kiwi version from OBS 2.10
* Operating system host version: openSUSE Leap 15.5
* Operating system target version: openSUSE Leap 15.5
* Open Build Service version (N/A if not using OBS): 2.10
* Koji version (N/A if not using Koji): N/A

**Comment by mfatrez** [comment]
Trying to modify kiwi/filesystem/btrfs.py with : 

```
--- kiwi/filesystem/btrfs.py	2024-02-12 12:09:28.262108432 +0000
+++ kiwi/filesystem/btrfs.py	2024-02-12 12:09:47.262108432 +0000
@@ -67,5 +67,5 @@
         """
         device = self.device_provider.get_device()
         Command.run(
-            ['btrfstune', '-u', device]
+            ['btrfstune', '-f', '-u', device]
         )
``` 

Stay tuned

**Comment by schaefi** [comment]
Interesting, I think I remember that this worked some time ago. Thanks for testing I'll stay tuned :)

**Comment by mfatrez** [comment]
adding '-f' solve the problem
The thing is python3-kiwi is installed in my qemu-aarch64 but doesn't contain the patch.
I made a workaround to set the option directly in the root image, but the change is not permanent.
Thanks for adding the modification in OBS 2.10 if you can.

**Comment by schaefi** [comment]
Thanks, I created a pull request and once it is merged it will become available soon. We are currently in the process of creating a new major release of kiwi (v10.x.x). Part of the move is also the move to poetry for development. I need to wait with the release until this change is done. There is a draft PR open here #2441 ... so it will take a little longer to make the change effective
