### ISSUE TITLE
Switch to new sphinx

### ISSUE THREAD

**Issue by Vogtinator** [OSInside/kiwi#2462]
While working on the documentation I found that sphinx-build always reread and recreated all documentation files, even if nothing changed:

`updating environment: 0 added, 96 changed, 0 removed`

This was due to broken dependency calculation for python .egg files and was fixed in later versions apparently. After `pip install --upgrade sphinx` (currently v7.2.6), incremental builds works as expected.

**Comment by schaefi** [comment]
I think I sticked with sphinx v5.0.0 because newer versions broken the rtd theme (no search possible on the page). Also see #a2dad893fcd0a8fc6a4b19dbc13f58e03815f942

If you can confirm it does not break the current rtd theme I'm happy to switch

**Comment by Vogtinator** [comment]
It did break the search functionality, but I fixed that and some more issues: https://github.com/OSInside/kiwi/pull/2465
