### ISSUE TITLE
Missing support for ZIPL for s390x

### ISSUE THREAD

**Issue by Conan-Kudo** [OSInside/kiwi#2481]
## Problem description
When working on porting Fedora s390x images to KIWI, I discovered we do not support ZIPL directly and thus can't create s390x images that boot.

Fedora (and RHEL) use [ZIPL with Bootloader Spec to boot the system since Fedora 30](https://fedoraproject.org/wiki/Changes/BootLoaderSpecByDefault) and there is no `grub2-emu` for s390x available.

`zipl` bootloader should be supported for s390x, and it should support working with BLS configuration.

## OS and Software information

* KIWI version: 9.25.21
* Operating system host version: Fedora 40
* Operating system target version: Fedora 40
* Open Build Service version (N/A if not using OBS): N/A
* Koji version (N/A if not using Koji): N/A

**Comment by Conan-Kudo** [comment]
Here's code from Anaconda that shows how it's done there: https://github.com/rhinstaller/anaconda/blob/master/pyanaconda/modules/storage/bootloader/zipl.py

**Comment by schaefi** [comment]
I can do the implementation based on: https://www.ibm.com/docs/en/linux-on-z?topic=zipl-bls-files

Problem is that I need a bit of time and I can't make any estimate right now. It's not difficult though

**Comment by schaefi** [comment]
All code of the direct zipl support (not BLS compliant) was removed in 836633c7b2b9b4aa31c1501c2e9817dc00af290d
I'm adding that information as a reference since some parts of it will come back in the implementation for this one
