### ISSUE TITLE
documentation error

### ISSUE THREAD

**Issue by zyndok** [OSInside/kiwi#2483]
## Problem description
doc/source/working_with_images/custom_volumes.rst

show example that is faulty

    <type image="oem" filesystem="btrfs" preferlvm="true">
       <systemdisk name="vgroup">

## Expected behaviour
The following is the correct xml entry.

    <type image="oem" filesystem="btrfs" >
       <systemdisk name="vgroup" preferlvm="true" >

## Steps to reproduce the behaviour

try to run kiwi with the preferlvm on the wrong node

## OS and Software information

* KIWI version: commit 6dc4ef2570889942d289b9b042200fccc9a6ccdd (HEAD -> main, origin/main, origin/HEAD)
* Operating system host version: fedora, but it doesn't matter
* Operating system target version: 
* Open Build Service version (N/A if not using OBS): na
* Koji version (N/A if not using Koji): na

**Comment by schaefi** [comment]
Thanks for reporting, fixed in main. As soon as #2441 gets merged the doc change will become effective
