### ISSUE TITLE
Implement global options for kiwi system create

### ISSUE THREAD

**Issue by ampresent** [OSInside/kiwi#2486]
## Problem description
Run `kiwi system create --root /path/to/root --target /path/to/target --logfile /path/to/logfile`.
`--logfile` option is rejected and so are other global options.

## Expected behaviour
Log is written to /path/to/logfile

## Steps to reproduce the behaviour
`kiwi system create --root /path/to/root --target /path/to/target --logfile /path/to/logfile`.

## OS and Software information

* KIWI version:  9.25.22
* Operating system host version:  RockyLinux 9.2
* Operating system target version:  ANY
* Open Build Service version (N/A if not using OBS):  N/A
* Koji version (N/A if not using Koji):  N/A

**Comment by schaefi** [comment]
So the kiwi caller semantic is

```
 kiwi-ng --help
usage: kiwi-ng [global options] service <command> [<args>]
```

That should allow you to call

```
kiwi  --logfile /path/to/logfile system create --root /path/to/root --target /path/to/target
```

**Comment by ampresent** [comment]
It works. Thanks.
