### ISSUE TITLE
Allow customization of attributes that determine image file names via `result bundle`

### ISSUE THREAD

**Issue by AdamWill** [OSInside/kiwi#2509]
## Problem description
We have recently switched to using Kiwi to build Fedora Cloud and Container images. One problem that has transpired is that we want different image names for "candidate" composes versus "nightly" composes, for our development branch. For instance, we are currently working on Fedora 40 Beta. We want the images we build for release candidates for the Beta to have the word "Beta" in them, to make it clear that they are not final release images. However, we don't want the filenames for images built as part of Fedora 40 nightly composes to have the word "Beta" in them (because they are not part of the Beta process, and could not practically be mistaken for final release images as their filename is generally in a different format).

For reference, compare https://kojipkgs.fedoraproject.org/compose/40/Fedora-40-20240312.0/compose/Cloud/x86_64/images/ (images built with our old tool, with `40_Beta` in the name) and https://kojipkgs.fedoraproject.org/compose/40/Fedora-40-20240317.1/compose/Cloud/x86_64/images/ (images built by Kiwi, with only `40` in the name). The latter images look a lot like final release images, just from the filenames.

The way we have always achieved this is to have "pungi" - the tool that orchestrates Fedora composes - pass these values into the build process. When building Beta composes, the compose's "version" is [set in the pungi configuration to "40_Beta"](https://pagure.io/pungi-fedora/blob/70acd4a388ac6467e23b480ba4a612577b66d2b9/f/fedora-beta.conf#_204). When building nightly composes, [the "version" is set to "40"](https://pagure.io/pungi-fedora/blob/70acd4a388ac6467e23b480ba4a612577b66d2b9/f/fedora.conf#_202).

At present, though, we don't have a mechanism to get this value through to Kiwi. The Kiwi build process ignores Pungi's "version" value and instead uses one defined [in our Kiwi image descriptions](https://pagure.io/fedora-kiwi-descriptions/blob/9ecebea5f21098bea30b0c69e14fb65a807a0c62/f/config.xml#_10). But this is both a duplication of the value set in Pungi, and makes it awkward to have differing values for the "candidate" and "nightly" composes, as we would then need to have two branches of the image descriptions repo, and keep syncing them so they were identical in all respects other than the "version" value, which would be awkward.

@Conan-Kudo suggested using the `result bundle` mechanism as a way to make it possible for an orchestrator like Pungi to 'inject' a version value on the fly for each compose, so this ticket is to request something along those lines, if possible.

## Expected behaviour
It should be possible to specify/override the "version" value (and possibly other attributes that wind up in the produced image filenames) at compose time, somehow

## Steps to reproduce the behaviour
Well, try doing it, I don't think you can :)

## OS and Software information
Fedora 40 official compose process

* KIWI version: 
* Operating system host version: Fedora 39/40
* Operating system target version: Fedora 40
* Open Build Service version (N/A if not using OBS): N/A
* Koji version (N/A if not using Koji): current

**Comment by AdamWill** [comment]
btw, another thing that might be interesting is the ability to pass in *entire filenames*, or at least the entire filename aside from the format extension. Pungi does generally have an idea of how *every* image ought to be named. Doing that might be more difficult, though.

**Comment by AdamWill** [comment]
I guess it's also worth considering the semantics of the "version" a bit. I looked into it a little and found it's *mainly* used as an input when constructing filenames, but there is also a function `add_bundle_format` in `kiwi/system/result.py` that assumes it will be a semantic version (which we are already not respecting in Fedora). There's also a bit in `kiwi/tasks/result_bundle.py` that uses it as the "Version" for an RPM package, if you run `result bundle --package-as-rpm`. That's only looking at things that call `get_image_version()` to find it, it was much harder to try and look for anything that might access it any other way, since obviously grepping a source tree for the string "version" is...rather noisy.

**Comment by schaefi** [comment]
I think you can achieve what you want with the current kiwi. So I took your reference image naming as an example. We want ```Fedora-Cloud-Base-40_Beta-1.1.x86_64.qcow2```. To achieve this in kiwi you can set the following bundle_format

```xml
<type ... bundle_format="Fedora-Cloud-Base-40_Beta-1.1.%A">
    ...
</type>
```

After you have built the image you can then create this bundle via

```
kiwi-ng result bundle --target-dir /tmp/mytest/ --bundle-dir /tmp/mytest-bundle --id some
```

and it will tell you something like this

```
[ INFO    ]: 13:11:30 | Bundle build results from /tmp/mytest
[ INFO    ]: 13:11:30 | Creating Fedora-Cloud-Base-40_Beta-1.1.x86_64.raw
[ INFO    ]: 13:11:31 | --> XZ compressing
[ INFO    ]: 13:12:31 | --> Creating SHA 256 sum
[ INFO    ]: 13:12:32 | Creating Fedora-Cloud-Base-40_Beta-1.1.x86_64.changes
[ INFO    ]: 13:12:32 | --> XZ compressing
[ INFO    ]: 13:12:35 | Creating Fedora-Cloud-Base-40_Beta-1.1.x86_64.packages
[ INFO    ]: 13:12:35 | Creating Fedora-Cloud-Base-40_Beta-1.1.x86_64.verified
```

Depending on your type specification more or less files will be produced but I think you get the idea of the naming

The ```bundle_format``` attribute supports several macros which can be used in the format to take information from the image description or from the host like the arch name. All these macros are documented here:

* https://osinside.github.io/kiwi/image_types_and_results.html#image-bundle-format

The use of them is completely optional, so you can also see some arbitrary string as your bundle_format and the images gets named like that when you create the bundle.

From that perspective I think you have all options that you need at hand

Let me know if this solves it for you

Thanks

**Comment by Conan-Kudo** [comment]
We cannot have it in the XML, it needs to be done externally, because this is driven by how our tooling invokes build tasks and expects the outputs to be in a particular form. Changing the XML means that it affects everyone, including people not making Fedora images through our compose tooling.

But that said, it seemed when I looked at changing the bundle filename format in the XML, the `%V` version thing expects SemVer, even though that's not what we do.

**Comment by Conan-Kudo** [comment]
For some context here, we use a tool called [Pungi](https://pagure.io/pungi) to gather up repositories and use them as inputs to invoke artifact builds and publish them. The settings for Pungi are defined in [its own configuration repository](https://pagure.io/pungi-fedora). We have configuration for [the beta release](https://pagure.io/pungi-fedora/blob/f40/f/fedora-beta.conf) and [the final release](https://pagure.io/pungi-fedora/blob/f40/f/fedora.conf) that set _slightly_ different properties.

We want these properties to be able to be propagated on-demand without breaking the descriptions themselves for local builds.

**Comment by schaefi** [comment]
ok but if you have your complete own composer with Pungi why does the naming of the result files of the kiwi build matter ? You take what it builds and let the composer do the job. Sorry I think I can't follow you ?

**Comment by Conan-Kudo** [comment]
I don't know too much here (that's more @AdamWill's thing), but my understanding is that Pungi _really cares_ about the filenames for sorting and publishing. Right now, the important part is being able to override the version property through the commandline. The rest can be figured out later.

**Comment by schaefi** [comment]
> I don't know too much here (that's more @AdamWill's thing), but my understanding is that Pungi _really cares_ about the filenames for sorting and publishing. Right now, the important part is being able to override the version property through the commandline. The rest can be figured out later.

This is a problem for kiwi. We have a strict policy for the naming of the result files and how the version with major.minor.patch is processed into the filenames. Also the documentation describes this and users can rely on this output policy. If I add an option that messes with the version and changes every builder to produce different results according to some version option I would break the entire policy. I would break the bundler because that code relies on the output formats and I would open the door for breakage at many other places. We provided the bundler for exactly that reason to give users a way to transform the standard result files into an output bundle of their choice. 

What I can offer is that the bundle format can be passed to the bundle call instead of being part of the image description. So you would be able to add something like

```
kiwi-ng result bundle --target-dir /result/from/kiwi/build --bundle-dir /result/suitable/for/pungi --bundle-format "..." 
```

Would that be an option ?

**Comment by schaefi** [comment]
> That would work, I think. We could have the Koji plugin construct the format then.

ok great I will come up with a PR for this

**Comment by AdamWill** [comment]
So this is actually quite nice in theory - I mentioned it as a 'stretch goal' - but there is a bit of a complication. We do want the filenames to vary for the 'type' of image, or else we'll get dupes. So, look at https://kojipkgs.fedoraproject.org/compose/40/Fedora-40-20240319.2/compose/Cloud/x86_64/images/ again - note we have `Fedora-Cloud-Base-AmazonEC2`, `Fedora-Cloud-Base-Azure` and so on. I believe the `Cloud-Base-AmazonEC2` and `Cloud-Base-Azure` part is the "profile" in Kiwi terms. Can we specify that as a format string in the `bundle_format`?

In an absolutely ideal world I'd like the format to be something like `$DISTRO-$PROFILE-$VERSION_$LABEL`, for candidate composes, where $DISTRO is "Fedora", $PROFILE is the Kiwi profile, $VERSION is this "40_Beta" string, and $LABEL is the "1.1" or "1.2" or "1.9" bit, whatever that's called in Kiwi terms.

**Comment by Conan-Kudo** [comment]
Yes, this should already be possible, it'd be `%N-%P-<VERSION>-%I.%A.%T` where `<VERSION>` would be filled in by the Koji plugin directly.

**Comment by AdamWill** [comment]
OK, great, let's get that figured out once Beta is signed off. Thanks a lot, everyone.
