### ISSUE TITLE
discoverable partitions support is broken

### ISSUE THREAD

**Issue by kraxel** [OSInside/kiwi#2517]
## Problem description
Commit 67bf130cd1da5372079810f87445dd70f26b3a24 has a bug, it sets the wrong uuid.

The gpt partition entries have /two/ guids. The partition uuid (which shows up in /dev/disk/by-partuuid), and the partition /type/ uuid. The discoverable partition uuids should go to the latter, the patch sets the former though.

## Steps to reproduce the behaviour
```
fdisk -lx
[ ... ]
Device       Start      End Sectors Type-UUID                            UUID                                 Name     Attrs
/dev/sda1     2048     6143    4096 21686148-6449-6E6F-744E-656564454649 F77EF7E3-7096-4DC1-BB0D-F234380ACA27 p.legacy 
/dev/sda2     6144   210943  204800 C12A7328-F81F-11D2-BA4B-00A0C93EC93B C12A7328-F81F-11D2-BA4B-00A0C93EC93B p.UEFI   
/dev/sda3   210944  2258943 2048000 0FC63DAF-8483-4772-8E79-3D69D8477DE4 BC13C2FF-59E6-4262-A352-B275FD6F7172 p.lxboot 
/dev/sda4  2258944 10485726 8226783 0FC63DAF-8483-4772-8E79-3D69D8477DE4 4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709 p.lxroot 
```
The `4F68...` discoverable partition uuid for the x86_64 root filesystem is in the `UUID` not the `Type-UUID` column

## OS and Software information

* KIWI version: 10.0.8
* Operating system host version:  Fedora 39
* Operating system target version: Fedora 40
* Open Build Service version (N/A if not using OBS): N/A
* Koji version (N/A if not using Koji): N/A

**Comment by schaefi** [comment]
will fix it. I was not aware that the GUID setting is not enough
