### ISSUE TITLE
Shim support for Debian needs fixing/updating

### ISSUE THREAD

**Issue by udf2457** [OSInside/kiwi#2525]
I think I have encountered a similar scenario to #1743

I am seeing `KiwiBootLoaderGrubSecureBootError: Signed grub2 efi loader not found` despite `shim-signed` and `grub-efi-arm64-signed` being part of the installed package list.

Current debian shim for arm64 is at `/usr/lib/shim/shimaa64.efi.signed` (`shim-signed`) or various `/usr/lib/grub/arm64-efi-signed` locations (`grub-efi-arm64-signed`) and I think this is being missed by your pattern matching

https://packages.debian.org/bookworm/arm64/shim-signed/filelist
https://packages.debian.org/bookworm/arm64/grub-efi-arm64-signed/filelist

**Comment by schaefi** [comment]
Thanks, I feel it is turning into a mess, that shim setup in kiwi ;)
