### ISSUE TITLE
Introduce a way to generate a Dockerfile's STOPSIGNAL directive ?

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [OSInside/kiwi#2543]
## Problem description

We plan on moving to  "ubi9/ubi9-init" image internally so we can manage some of the service we use in containers currently via systemd rather than manually. Trying to look at a fedora equivalent (as we want to also try to foresee a bit RHEL future by using fedora) I couldn't find any equivalent "fedora-init" equivalent. I believe it shall be possible to provide a kiwi description for it given that the dockerfile equivalent on RHEL side isn't so complex (see https://catalog.redhat.com/software/containers/ubi9-init/6183297540a2d8e95c82e8bd?architecture=amd64&image=6628e0eb78340766d38d023f&container-tabs=dockerfile). However I see no way with Kiwi right now to issue a Dockerfile's STOPSIGNAL directive like it is done in the ubi9-init dockerfile.

Would it make sense to implement such an <containerConfig> attribute/child tag in Kiwi to manage the OCI image stop signal ?

@Conan-Kudo Since you recently re-worked the fedora OCI image creation, do you think it would make sense to add a "fedora-init" image in addition to "fedora" and "fedora-toolbox" ?

**Comment by schaefi** [comment]
>Would it make sense to implement such an attribute/child tag in Kiwi to manage the OCI image stop signal ?

yep does make a lot sense :) I opened a PR

**Comment by Conan-Kudo** [comment]
> @Conan-Kudo Since you recently re-worked the fedora OCI image creation, do you think it would make sense to add a "fedora-init" image in addition to "fedora" and "fedora-toolbox" ?

Sure, reach out to the Fedora Cloud folks to ask for this.

**Comment by Romain-Geissler-1A** [comment]
Wow thanks, that was fast !

For the Fedora image, I will try to write it myself and submit it to fedora clouds folks.
