### ISSUE TITLE
KiwiCommandError: mcopy: stderr: Disk full

### ISSUE THREAD

**Issue by MouseZhangZh** [OSInside/kiwi#2577]
## Problem description

I encountered this error when making an image(KDE-Live) with kiwi-build (https://pagure.io/fedora-kiwi-descriptions/tree/rawhide),
![image](https://github.com/OSInside/kiwi/assets/42853944/1c7b85e9-fbc2-42f5-b5cb-7c542d9e9511)

## Expected behaviour

...
qemu create xxxxx 20M
...
KiwiCommandError: mcopy: stderr: Disk full

## Steps to reproduce the behaviour

1. clone fedora-kiwi-descriptions and && cd fedora-kiwi-descriptions
2. sudo ./kiwi-build --debug --image-type=iso --image-profile=KDE-Live --output-dir ./outdir (Just follow README)
3. KiwiCommandError: mcopy: stderr: Disk full
4. modify `EFI_FAT_IMAGE_SIZE` from 20 to 31 https://github.com/OSInside/kiwi/blob/7f317a5d0aed26bd9a7db75f2e1230e5c8c26fdf/kiwi/bootloader/config/grub2.py#L969
5. it works

ps. why change EFI_FAT_IMAGE_SIZE to 31?

<img width="573" alt="image" src="https://github.com/OSInside/kiwi/assets/42853944/6bfbb97c-3735-48df-9a6a-e66f6d0357ca">

## OS and Software information

* KIWI version: KIWI (next generation) version 10.0.21
* Operating system host version: 
NAME="Fedora Linux"
VERSION="40 (Server Edition)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (Server Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="Server Edition"
VARIANT_ID=server
* Operating system target version: 
* Open Build Service version (N/A if not using OBS): N/A
* Koji version (N/A if not using Koji): N/A

**Comment by schaefi** [comment]
I believe we clarified this issue on the matrix chat. In you particular case you can add the following to your image description

```xml
<type ... efifatimagesize="31" .../>
```

The eltorito limitation still persists and I could not yet find a way to overcome it. We had some conversations with Dan and I reading through the UEFI spec which says if we put the EFI partition to the end and specify a boot-load-size of 0 it would read until the end of the blockdevice, but all these tests failed for me so far.

Maybe we find a way to overcome the eltorito load size limit in the future
