### ISSUE TITLE
Use `apt` instead of `debootstrap` for bootstrapping Debian/Ubuntu environments

### ISSUE THREAD

**Issue by Conan-Kudo** [OSInside/kiwi#2599]
## Problem description
We currently use `debootstrap` to construct Debian/Ubuntu environments in the first stage, then use `apt` for the second stage.

This has some annoying consequences: 
* there's extra complexity around sources used to build the environment
* single stage images are not quite what people expect
* we're relying on two "package manager" tools with completely different configuration

@DaanDeMeyer let me know that `mkosi` figured out how to use `apt` for everything:
* https://github.com/systemd/mkosi/blob/main/mkosi/distributions/debian.py
* https://github.com/systemd/mkosi/blob/main/mkosi/installer/apt.py

We should consider doing the same.

**Comment by schaefi** [comment]
```
# Next, we invoke apt-get install to download all the essential packages. With DPkg::Pre-Install-Pkgs,
# we specify a shell command that will receive the list of packages that will be installed on stdin.
# By configuring Debug::pkgDpkgPm=1, apt-get install will not actually execute any dpkg commands, so
# all it does is download the essential debs and tell us their full in the apt cache without actually
# installing them.
```

Nice concept, and yes much much better than debootstrap
