### ISSUE TITLE
namedCollection cannot be tagged as arch specific like package can

### ISSUE THREAD

**Issue by Conan-Kudo** [OSInside/kiwi#2600]
## Problem description

When declaring an arch-specific `namedCollection`, the `arch=` constraint is ignored, causing it to request something that doesn't exist on some arches.

## Expected behavior

`<namedCollection name="arm-tools" arch="aarch64"/>` should only evaluate on aarch64.

## Steps to reproduce the behaviour

Add the sample line above to a Fedora kiwi description and build it on x86_64. It will fail because `arm-tools` doesn't exist there.

## OS and Software information

* KIWI version: 10.0.24
* Operating system host version: Fedora 40
* Operating system target version: Fedora 41
* Open Build Service version (N/A if not using OBS): N/A
* Koji version (N/A if not using Koji): N/A

**Comment by schaefi** [comment]
going to fix this today

**Comment by schaefi** [comment]
darn I accidentally pushed the change to main instead of a PR branch. Referencing the commit here as #e866bc5832bf6a2f28f166ee7f24c3dec9207835

**Comment by schaefi** [comment]
Closed

**Comment by schaefi** [comment]
Done
