### ISSUE TITLE
kiwi-ng 10.X.X support on RHEL 8.X and RockyLinux 8.X

### ISSUE THREAD

**Issue by mehulgogri-hpe** [OSInside/kiwi#2620]
This is the follow-up question on the issue I filed earlier https://github.com/OSInside/kiwi/issues/2616

It must be documented that EPEL repo should be installed on Fedora machines to install kiwi-cli.

Secondly, EPEL8 has kiwi-cli package version 9.25.21. How can I use the latest kiwi-cli 10.1.X on RHEL 8.X or RockyLinux 8.X?

**Comment by Conan-Kudo** [comment]
EPEL is not required for Fedora machines, it's only required for Enterprise Linux systems. It is included in the main Fedora repositories.

Additionally, You cannot run kiwi 10 on RHEL 8, you need CentOS/RHEL 9 or newer. You can produce RHEL 8 images from a RHEL 9 host, though.
