### ISSUE TITLE
EROFS output type support

### ISSUE THREAD

**Issue by davide125** [OSInside/kiwi#2633]
## Problem description
Kiwi doesn't currently support creating [EROFS](https://docs.kernel.org/filesystems/erofs.html) images. This would be useful for the [FEX RootFS](https://pagure.io/fedora-kiwi-descriptions/pull-request/83) in Fedora, among other things, as EROFS is more efficient than squashfs.

## Expected behaviour
`<type image="erofs"/>` is supported

## Steps to reproduce the behaviour
This is a feature request

## OS and Software information

* KIWI version: 10.1.2
* Operating system host version: Fedora Linux 40
* Operating system target version: Fedora Linux 42
* Open Build Service version (N/A if not using OBS): N/A
* Koji version (N/A if not using Koji): N/A

**Comment by Conan-Kudo** [comment]
This needs to be supported not just for rootfs but also for when we use dmsquash for live images as an alternative to squashfs.
