### ISSUE TITLE
erofscompression does not seem to work

### ISSUE THREAD

**Issue by davide125** [OSInside/kiwi#2647]
## Problem description
I updated https://pagure.io/fedora-kiwi-descriptions/pull-request/83 to use erofs, but it looks like `erofscompression` isn't being passed properly, as this results in

```
[ DEBUG   ]: 21:03:56 | EXEC: [mkfs.erofs --exclude-regex=image --exclude-regex=.kconfig --exclude-regex=run/* --exclude-regex=tmp/* --exclude-regex=.buildenv --exclude-regex=var/cache/kiwi /home/dcavalca/src/fedora-kiwi-descriptions/outdir/Fedora.x86_64-Rawhide.erofs /home/dcavalca/src/fedora-kiwi-descriptions/outdir/build/image-root]
```

where as you can see the `-z` option isn't set.

## Expected behaviour
Compression should be enabled as requested

## Steps to reproduce the behaviour
See the linked PR for an example

## OS and Software information

* KIWI version: 10.1.11
* Operating system host version:  Fedora Linux 40
* Operating system target version: Fedora Linux Rawhide
* Open Build Service version (N/A if not using OBS): N/A
* Koji version (N/A if not using Koji): N/A

**Comment by schaefi** [comment]
Hmm, I don't see this in the integration test:

https://build.opensuse.org/package/live_build_log/Virtualization:Appliances:Images:Testing_x86:rawhide/test-image-live-disk:LiveEroFS/images/x86_64

```
[  122s] [ DEBUG   ]: 22:52:30 | Looking for mkfs.erofs in /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
[  122s] [ DEBUG   ]: 22:52:30 | EXEC: [mkfs.erofs -z zstd,level=12 /var/tmp/kiwi_g97k4t9t /usr/src/packages/KIWI-iso/build/image-root/]
```

Can you share your image description ?

Thanks

**Comment by schaefi** [comment]
Ah I found it, in the filesystem builder not in the live builder

yes we forgot to handle the attribute there. I'll fix it
