### ISSUE TITLE
vagrant.libvirt/vagrant.virtualbox image suffixes don't match

### ISSUE THREAD

**Issue by nirik** [OSInside/kiwi#2656]
From https://pagure.io/releng/issue/12339

Fedora is making these and they are buildin, but the suffixes aren't as expected.

Hopefully @Conan-Kudo has more info on whats going on here.

**Comment by Conan-Kudo** [comment]
The issue is that with custom bundle formats, it's not being preserved. It's a variation of #2628.

**Comment by schaefi** [comment]
> The issue is that with custom bundle formats, it's not being preserved.

@Conan-Kudo Hrm, another one, ok. Can you give me the used bundle_format ?

**Comment by Conan-Kudo** [comment]
The format is this: `%N-%v-%I.%A`

**Comment by Conan-Kudo** [comment]
Would `%N-%v-%I.%A.%T` fix this (we use this for container images already)?

**Comment by schaefi** [comment]
@Conan-Kudo Hmm, I need more clarification on the issue. So I build an image with the `bundle_format="%N-%v-%I.%A"`
I built a vagrant box for the virtualbox target. The result file in question is named

```
kiwi-test-image-vagrant.x86_64-1.0.1.vagrant.virtualbox.box
```

After the bundle call with `--id foo` the result file is named

```
kiwi-test-image-vagrant-1.0.1-foo.x86_64.box
```

Looking at the bundler code we did that change on the suffix from `vagrant.virtualbox.box` to just `.box` intentionally. We can certainly change that and I also believe we should but what name exactly do you expect ?

Thanks

**Comment by Conan-Kudo** [comment]
We should keep the full `vagrant.virtualbox.box` rather than just chopping it down to `.box`.

**Comment by schaefi** [comment]
ok, that confirms what I thought.

I'm going to change it
