### ISSUE TITLE
Plugin installation dependency conflicts

### ISSUE THREAD

**Issue by gavinltomra** [OSInside/kiwi#2662]
## Problem description
I'm having trouble installing Kiwi with the StackBuild plugin; there seems to be disagreement about the package names, causing conflicts in zypper.

With the commands below I get:
```
Problem: 1: the to be installed python3-kiwi-9.24.43-150100.3.87.2.x86_64 requires 'kiwi-systemdeps-core = 9.24.43-150100.3.87.2', but this requirement cannot be provided
not installable providers: kiwi-systemdeps-core-9.24.43-150100.3.87.2.x86_64[repo-sle-update]

 Solution 1: Following actions will be done:
  do not install python3-kiwi-9.24.43-150100.3.87.2.x86_64
  do not install python3-kiwi_stackbuild_plugin-1.0.10-lp155.1.2.noarch
 Solution 2: do not install kiwi-systemdeps-iso-media-10.1.11-lp155.1.1.x86_64
 Solution 3: break python3-kiwi-9.24.43-150100.3.87.2.x86_64 by ignoring some of its dependencies
```

Part of the problem seems to be that `python3-kiwi` is 9.24 from repo-sle-update, while in kiwi-builder the 10.1 package is called `python311-kiwi` instead.  (The [installation instructions](https://osinside.github.io/kiwi/installation.html) suggest that the package name change was not intended.)

But if I try to install that package, the stackbuild plugin now hates it:
```
Problem: 1: the to be installed python3-kiwi_stackbuild_plugin-1.0.10-lp155.1.2.noarch requires 'python3-kiwi >= 9.21.21', but this requirement cannot be provided
not installable providers: python3-kiwi-9.24.43-150100.3.56.3.x86_64[repo-oss]
                   python3-kiwi-9.24.43-150100.3.59.1.x86_64[repo-sle-update]
                   python3-kiwi-9.24.43-150100.3.62.1.x86_64[repo-sle-update]
                   python3-kiwi-9.24.43-150100.3.65.1.x86_64[repo-sle-update]
                   python3-kiwi-9.24.43-150100.3.68.1.x86_64[repo-sle-update]
                   python3-kiwi-9.24.43-150100.3.71.1.x86_64[repo-sle-update]
                   python3-kiwi-9.24.43-150100.3.76.1.x86_64[repo-sle-update]
                   python3-kiwi-9.24.43-150100.3.81.1.x86_64[repo-sle-update]
                   python3-kiwi-9.24.43-150100.3.84.1.x86_64[repo-sle-update]
                   python3-kiwi-9.24.43-150100.3.87.2.x86_64[repo-sle-update]

 Solution 1: Following actions will be done:
  do not install kiwi-systemdeps-iso-media-10.1.11-lp155.1.1.x86_64
  do not install python311-kiwi-10.1.11-lp155.1.1.x86_64
 Solution 2: do not install python3-kiwi_stackbuild_plugin-1.0.10-lp155.1.2.noarch
 Solution 3: break python3-kiwi_stackbuild_plugin-1.0.10-lp155.1.2.noarch by ignoring some of its dependencies
```

If I don't add the kiwi-builder repo, then I can successfully install kiwi-ng 9.24, but this does not appear to include the stackbuild plugin.

This issue likely affects the boxed plugin too.

Side note: the kiwi-systemdeps packages don't appear to install all required system deps; in particular I found I had to additionally install `gptfdisk kpartx gzip xz gfxboot` before builds would succeed.

## Expected behaviour
It just works.

## Steps to reproduce the behaviour
```
sudo zypper addrepo 'http://download.opensuse.org/repositories/Virtualization:/Appliances:/Builder/openSUSE_Leap_$releasever' kiwi-builder
sudo zypper --non-interactive --gpg-auto-import-keys ref
sudo zypper in python3-kiwi python3-kiwi_stackbuild_plugin kiwi-systemdeps-iso-media
```

## OS and Software information

* KIWI version: 10?
* Operating system host version: OpenSUSE Leap 15.5
* Operating system target version: N/A
* Open Build Service version (N/A if not using OBS): N/A
* Koji version (N/A if not using Koji): N/A

**Comment by schaefi** [comment]
yes you are right the stackbuild and boxplugin builds for Leap needs to fix the spec file requirements to move to python 3.11

**Comment by gavinltomra** [comment]
From a Leap 15.5 host:
```
zypper -n addrepo \
       'http://download.opensuse.org/repositories/Virtualization:/Appliances:/Builder/openSUSE_Leap_$releasever' \
       kiwi-builder
zypper -n in python311-kiwi python311-kiwi_boxed_plugin
```

Results in:
```
Problem: 1: nothing provides 'python311-Cerberus' needed by the to be installed python311-kiwi_boxed_plugin-0.2.38-lp155.2.1.noarch
Solution 1: do not install python311-kiwi_boxed_plugin-0.2.38-lp155.2.1.noarch
Solution 2: break python311-kiwi_boxed_plugin-0.2.38-lp155.2.1.noarch by ignoring some of its dependencies
```

**Comment by schaefi** [comment]
@gavinltomra ok seems like there is no proper py 3.11 build for Cerberus in Leap. I reported the issue to the package maintainer and added the target for this package to build in Virt:App:Builder also for Leap 15.5/15.6 as long as it's not fixed. 

The packages are currently building, once done you should finally be able to get it installed

Thanks and sorry for any inconvenience

**Comment by gavinltomra** [comment]
It looks like it's been added to the 15.6 repository but not the 15.5 repository that I've been using.  Is that intended?

**Comment by schaefi** [comment]
Looking at https://build.opensuse.org/package/show/Virtualization:Appliances:Builder/python-Cerberus it seems to be built and published for 15.6 but for 15.5 I see a blocked state at least for aarch64. I believe there is little we can do here

**Comment by gavinltomra** [comment]
I'm getting the error shown in https://github.com/OSInside/kiwi-boxed-plugin/issues/73#issuecomment-2442797226 now.

**Comment by schaefi** [comment]
Also updated the progressbar2 packages to build against py3.11 on Leap. @gavinltomra How about it now ?

**Comment by gavinltomra** [comment]
Still not working for me (same error).

Oddly, it appears to be [listed as succeeded](https://build.opensuse.org/package/show/Virtualization:Appliances:Builder/python-progressbar2) but I don't see it in the [download repository](https://mirrorcache-au.opensuse.org/repositories/Virtualization:/Appliances:/Builder/openSUSE_Leap_15.5/noarch/).  Is there an upload delay?

**Comment by schaefi** [comment]
a delay on the publishing is possible, did you also refresh the repo metadata ? `zypper refresh`

**Comment by schaefi** [comment]
I refreshed the repos and could install on Leap as follows

```
sudo zypper in python311-kiwi python311-kiwi_stackbuild_plugin
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 3 NEW packages are going to be installed:
  python311-kiwi python311-kiwi_stackbuild_plugin python311-mock
```

Because Leap provides the python3.6 stack and still has 3.6 as the default but everything in Virt:App:Builder switched to 3.11 you need to express that in your install command.
