### ISSUE TITLE
Container installation during image build

### ISSUE THREAD

**Issue by rjschwei** [OSInside/kiwi#2663]
## Problem description

When building a VM image with kiwi there is no feature that supports the inclusion of containers in the image build unless any specific container is wrapped in a package. A use case exists where it is desirable to be able to include containerized application, SUSE Multi Linux Manager for example in an image such that upon startup of an instance the container application can be started without having to pull the container from a registry first. This will reduce the custom work a user of kiwi has to do.

## Expected behaviour

Specify a <registry> element in the kiwi config file
Specify a container to pull into the image with a <container> element in the kiwi config file

During build kiwi will pull the container using skopeo or some other suitable tool. When an instance of the image is booted a kiwi service will automatically import the container present in the image into the container runtime (podman or docker) local repository. This should happen prior to a service the use may include that starts the containerized application. Users would have the requirement to add a service with "After: kiwi-container-load.service" or whatever name may be chosen.

## OS and Software information

* KIWI version: 
* Operating system host version: 
* Operating system target version: 
* Open Build Service version (N/A if not using OBS): 
  - Will need new OBS integration
* Koji version (N/A if not using Koji):

**Comment by schaefi** [comment]
@rjschwei thanks, going to come up with an solution suggestion soon
