### ISSUE TITLE
Add support for building GPT-labelled ISOs with xorriso

### ISSUE THREAD

**Issue by AdamWill** [OSInside/kiwi#2685]
## Problem description
Kiwi's current implementation of xorriso support does not allow you to produce GPT-labelled ISOs (that is, ISOs with a GPT disk label / partition table as opposed to an MBR one). This is a problem for Fedora, as our ISOs were hybrid MBR/GPT from Fedora 17 to Fedora 36, and have been pure GPT since Fedora 37. Switching to Kiwi for existing ISOs (as we're starting to experiment with) thus makes them suddenly MBR-labelled, which can cause problems - see https://bugzilla.redhat.com/show_bug.cgi?id=2328590 , where we discovered this.

I wrote a pretty simple patch which makes Kiwi *always* use a GPT disk label when producing an EFI-capable ISO with xorriso:
```
commit d1e6a14037cb7f5862c3a0b108448b7e230c7427 (HEAD -> live-gpt-test)
Author: Adam Williamson <awilliam@redhat.com>
Date:   Fri Nov 29 11:12:38 2024 -0800

    TEST DO NOT MERGE: build hybrid live as GPT not MBR
    
    Signed-off-by: Adam Williamson <awilliam@redhat.com>

diff --git a/kiwi/iso_tools/xorriso.py b/kiwi/iso_tools/xorriso.py
index 39eab4f32..f33cd11e5 100644
--- a/kiwi/iso_tools/xorriso.py
+++ b/kiwi/iso_tools/xorriso.py
@@ -157,6 +157,7 @@ class IsoToolsXorrIso(IsoToolsBase):
         bootloader/config/grub2.py
         """
         self.iso_loaders += [
+            '-boot_image', 'any', 'appended_part_as=gpt',
             '-append_partition', '2', '0xef', loader_file,
             '-boot_image', 'any', 'next',
             '-boot_image', 'any',
```
But I suspect it wouldn't be wanted as-is as we might not want to suddenly flip the disk label on existing Kiwi-built ISOs. We probably want this to be configurable. But I kinda gave up on figuring out the best way to do that, Kiwi is fairly big and this code is a long way from the config stuff, I feel like an experienced Kiwi dev can figure out the best approach to implementing a config toggle for this much more easily than I can.

## Expected behaviour
It should be possible to specify a Kiwi template for an ISO image such that the resulting image is GPT-labelled.

## Steps to reproduce the behaviour
Build a live image with Kiwi. Note it has an MBR disk label (`gdisk -l` and `fdisk -l` will tell you this). Note there's no way to make it use GPT instead.

## OS and Software information

* KIWI version: 10.2.0
* Operating system host version: Fedora Rawhide
* Operating system target version: Fedora Rawhide
* Open Build Service version (N/A if not using OBS):  N/A
* Koji version (N/A if not using Koji): irrelevant

**Comment by schaefi** [comment]
Thanks much. I believe this is a bug in kiwi also connected to the eficsm attribute that we added some time ago. See #2590 
The mentioned xorriso settings should have taken effect if `eficsm="false"` is set and the user builds an EFI only image.
I mark this as a bug and will come up with a PR soon.

Also the connected conversation on the fedora bugzilla is interesting and might lead to further changes

* https://bugzilla.redhat.com/show_bug.cgi?id=2328590
 
Thanks much for all the debugging effort to everyone involved

**Comment by AdamWill** [comment]
That doesn't sound right. We still expect these images to boot on UEFI systems booting CSM mode, in most cases. Such systems *should* still be able to read and boot from GPT partition tables. See https://fedoraproject.org/wiki/Changes/GPTforBIOSbyDefault - we switched to GPT partition tables even for BIOS installs in F37, and we expect this works in *most* cases. We know there are *some* cases where a BIOS booted system (whether real BIOS or CSM) cannot read GPT labels, but we don't think it's normal.

So, I don't think we can simply say "if the image is not meant to be BIOS bootable, label should be GPT; if the image is meant to be BIOS bootable, it should be MBR". It's messier than that. In *most* cases, you can BIOS boot from GPT, and UEFI boot from MBR. But there are *some* exceptions to both. What disk label you use is basically a judgment call about which exceptions you want to hurt.

I'd say on the whole we should assume that if we're not intending to be BIOS bootable at all we should use a GPT label unless told otherwise, yeah. And it's probably fine to (continue to) default to MBR for an image that *is* intended to be BIOS bootable. But both should be overrideable by configuration, particularly the "GPT labelled but BIOS bootable" config should be available as that is exactly how Fedora images are meant to be.

When I get time I'll go back to the patch I posted in bugzilla and see if I can tweak it based on this discussion. and test it...

**Comment by schaefi** [comment]
> So, I don't think we can simply say "if the image is not meant to be BIOS bootable, label should be GPT; if the image is meant to be BIOS bootable, it should be MBR". It's messier than that.

ok I agree to that :) 

In the current code we have no setting to influence the partition table type for the ISO build. There is an attribute in kiwi to control the partition table type which we currently only evaluate for disk image types: 

```
k.type.efiparttable.attribute =
        ## For images with an EFI firmware specifies the partition
        ## table type to use. If not set defaults to gpt partition
        ## table type.
        attribute efiparttable { "msdos" | "gpt" }

```

I suggest we add a patch that adds a similar attribute to use when building an ISO image e.g. `isoefiparttable`

Thoughts ?

**Comment by AdamWill** [comment]
I think we could just have the ISO path respect *that* setting. I already wrote an untested patch to do this, it's [in the downstream bug](https://bugzilla.redhat.com/attachment.cgi?id=2060441), I will test it and work on it more (e.g. default to GPT if the image is not BIOS-bootable) when I get a chance.

I also got a [response from xorriso upstream](https://lists.gnu.org/archive/html/bug-xorriso/2024-11/msg00012.html) about the issues fdisk reports, which I need to read three more times to try and understand. :D

**Comment by schaefi** [comment]
My first thought was also to use the setting for `efiparttable` but as I said it's been used in the context of disk images. As you can combine a disk image build `oem` with the creation of an installation media `iso` you would not have an opportunity to differentiate the setting for the table in the disk image and the table embedded to the ISO. If this limitation would be acceptable we can go with the existing attribute. However, my gut feeling says it would be better to have individual attributes.

Thanks for looking into all this, much appreciated :)

**Comment by AdamWill** [comment]
so, working on this, I've realized that adding a new attribute causes a bit of an awkward logic flow problem. It's all to do with the `legacy_bios_mode` setting.

`LiveImageBuilder.create` takes a bunch of info from `self.firmware` - which is an instance of `FirmWare` - and passes it to the `IsoToolsXorrIso` instance, which uses it to decide the args to pass to xorriso. Included in that list are `self.firmware.efi_mode()` and `self.firmware.legacy_bios_mode()`.

`FirmWare`'s calculation of `legacy_bios_mode()` is based, in part, on the result of `get_partition_table_type()`, which is in turn partly based on `self.efi_partition_table`, which is determined by the `efiparttable` config value.

So if we add `isoefiparttable` but keep using `legacy_bios_mode` as currently implemented in `IsoToolsXorrIso`, in effect, *some* of its behavior will be determined by the `efiparttable` value and *some* by the `isoefiparttable` value. In *practice* I suspect it would be quite unusual to run into a problem here, but now I know about it it feels so awful I'd refuse to send a PR with this issue, and it would probably be at least *possible* for it to cause some real-life weirdness.

If we do need the separate attribute, I think what we'd have to do is add an arg to `FirmWare.__init__` which tells it whether this instance is related to an ISO image; if it is, `get_partition_table_type` would use the `isoefiparttable` value rather than the `efiparttable` one. `live.py` could set that arg appropriately when creating its `FirmWare` instance. Or, possibly, `FirmWare` could figure this out from the `xml_state` it's passed? I'm not sure whether that's doable.

If we don't need the separate attribute, I don't have to deal with this little thicket :D So I'll wait for @schaefi 's reply to @Conan-Kudo 's suggestion that it's unnecessary before proceeding further.

**Comment by schaefi** [comment]
@AdamWill I had some conversations with Thomas during the weekend about the settings and the way we can build the ISO to be correct for EFI and compatible with CSP (BIOS) too.

Key changes proposed in my PR are:
* in case EFI is requested switch to the GPT table `appended_part_as=gpt`
* in case EFI is requested stay MBR compatible by using a bearer partition for the boot flag. This is the same trick we use for disk images. `mbr_force_bootable=on` in xorriso

I also added the system area report to the log file of kiwi

An image building with this settings can be found here

* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:tumbleweed/test-image-live

Would be great if you can test it

Thanks

**Comment by Conan-Kudo** [comment]
I would prefer the current Fedora style over the Ubuntu style, but if there's a way we can make both variants supported, I'd like to see that.

**Comment by AdamWill** [comment]
I can finish that up and send it when I'm back from PTO, if you can give me a definitive line on whether to add a new config option or reuse efiparttable.

**Comment by Conan-Kudo** [comment]
Reuse `efiparttable`.

**Comment by schaefi** [comment]
> Oh. I already had a PR for this more or less ready to go, and just waiting on clarification of whether we needed a new config option or not. Shame about the duplication.

@AdamWill I'm sorry but I think your work is not lost as I only added the needed bits to use a GPT table in case EFI is requested.

I'm a bit confused about the attribute conversation. So we were discussing to allow a specific table setting that can overwrite the logic of the firmware setting. I'm not sure if we still need that. With the current PR open the setup is as follows:
* firmware type is EFI, leads to a GPT table plus BIOS compatibility (add-on boot bearer partition like we do for disk images)
* firmware type is EFI and eficsm="false" is set, leads to a GPT table and no BIOS boot options, EFI only ISO
* firmware type is msdos, leads to a standard dos table and no EFI is possible, BIOS only ISO

So I wonder which condition we want to support that requires a specific table setting with `efiparttable` ?

@Conan-Kudo 
>What? Since efiparttable is part of the type structure, it can be set individually for each type of image. That is, oem type and iso type cannot share the same setting, it would have to be set for each type.

This is only half correct imho. You can specify something like this

```xml
<type image="oem" firmware="efi" installiso="true" .../>
```

This will built you an oem disk image which is GPT based and it will build you an install ISO which is (with the current PR) also GPT based. If you now set `efiparttable="msdos|gpt"` it will apply the setting for the disk and the ISO image. I don't see where you could separate the request to build an install image from the disk in two distinct type sections. Therefore if we really need an attribute to configure the table layout for the ISO it should be done with a new attribute

But again I'm currently thinking if we really need it. For reference please give the built ISO binaries from here a test

* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:tumbleweed/test-image-live

it builds different profiles for EFI only, EFI+BIOS and BIOS only

I got quite confused while coding on this topic, it might well be that I overlooked, forgot or misunderstood some parts :)

Thanks

**Comment by Conan-Kudo** [comment]
I think even with `installiso="true"` it would be fine, because we would just chain the same setting anyway. It would be reasonable to say that with a GPT disk we are fine with a GPT ISO.

**Comment by schaefi** [comment]
>It would be reasonable to say that with a GPT disk we are fine with a GPT ISO.

yes I agree to that and in this case using the existing `efiparttable` attribute is fine with me, in case we really need it

**Comment by AdamWill** [comment]
@schaefi I'm fine with "firmware type is EFI and eficsm="false" is set, leads to a GPT table and no BIOS boot options, EFI only ISO" and "firmware type is msdos, leads to a standard dos table and no EFI is possible, BIOS only ISO", in my PR those work the same. The case I'm concerned with is "firmware type is EFI [and eficsm is not false], leads to a GPT table plus BIOS compatibility (add-on boot bearer partition like we do for disk images)"

This is the most complex case, and the hardest to reason about, because it all comes down to how real firmwares in the real world behave and we just don't have enough solid data on this, only fragments of "this image doesn't boot on this machine" reports.

In *theory* it should be fine to give such images only an MBR, as the UEFI spec says UEFI firmwares should be capable of booting from MBR-labelled disks. But we found out, at least in the past, that this wasn't true in the real world - we found at least some real case where a real UEFI firmware won't boot a disk which only has an MBR. But still, if I get a [current openSUSE live image *right now*](https://download.opensuse.org/tumbleweed/iso/openSUSE-Tumbleweed-GNOME-Live-x86_64-Current.iso), this is the layout it has.

Another option is to make the image the way the UEFI spec says it should be: with a GPT partition table, and a "protective" MBR, which has [*very specific qualities that are laid out in the spec*](https://uefi.org/specs/UEFI/2.10/05_GUID_Partition_Table_Format.html#protective-mbr). Which UEFI firmware engineers, at least allegedly, should have read. Or run through ChatGPT or something. This *ought* to be bootable on any UEFI firmware, and real world experience suggests it's also bootable in "BIOS mode" (whether native BIOS, or UEFI CSM) in most cases, or else there'd be bigger torch-burning mobs attacking Fedora, probably. But there...probably?...are real-world systems (very old native BIOS ones, or wonky CSM implementations) which won't boot in BIOS mode from such an image. If you get [an official Fedora live image *right now*](https://download.fedoraproject.org/pub/fedora/linux/releases/41/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-41-1.4.iso), this is the layout it has.

Another option is to make the image with a GPT partition table and an MBR which is *not* a valid "protective MBR" according to the UEFI spec, but has a second partition with the "bootable" flag, with the goal of making it boot on the very old BIOS systems/wonky CSMs which won't boot strictly UEFI spec-compliant GPT+pMBR images. This is the option you're going for in this PR. But it seems at least theoretically possible that some UEFI firmware might be confused by such an image - because it does *not* comply with the UEFI spec - and refuse to boot it. Is this a real world problem? I don't actually know! AFAIK nobody has done any exhaustive testing around this area. We're really all just fumbling about in the dark a bit. If you get [an official Ubuntu live image *right now*](https://releases.ubuntu.com/24.04.1/ubuntu-24.04.1-desktop-amd64.iso), this is the layout it has.

My point is we have three possible approaches here which are each *currently used* by one of the major distros, and we don't have any really hard evidence that one of them is clearly The Best. We might have a soft, hopes-and-dreams *sense* that the third, Ubuntu-style approach is maybe the best, but we don't (AFAIK) have some kind of "I test booted USB sticks on 60,000 systems and this is what I found" type of study to point to that proves it.

Given this, it seems sensible to me to make it possible for Kiwi to produce *each* of those three layouts in the case where we're building an image that's intended to support both UEFI and BIOS boot, and let the entity building the image choose. This gives each distro (if it chooses to use Kiwi to build images) the option to continue using its current layout, or *choose* to switch to one of the others. If we don't do that, then we are effectively forcing them (except Ubuntu) to accept a change of layout if they want to build images with Kiwi after this change. Maybe they all choose the Ubuntu-style layout and we can deprecate the choice in a few years? It just seems premature to pre-decide it for them.

I guess another option would be to talk to the major distros and see if we can all agree that one of the styles would be the best going forward, then only do that one?

**Comment by Conan-Kudo** [comment]
I think you're right and we need to support all the different ways. I would be fine with integrating the Fedora way in now, since I don't think it's terribly invasive, and then adding the Ubuntu way after that, too.

**Comment by AdamWill** [comment]
ugh, so I'm back in this, and I have more questions, I guess. In his PR, @schaefi wrote "In addition to that setting also make sure the CSM boot flag for the embedded MBR table is provided through an extra bearer partition in the same way as it's done for EFI capable disk images", but is that actually true? I am trying to make this consistent with what is done for disk images, but I'm confused. AFAICT, for disk images, there is the `gpt_hybrid_mbr` attribute. If this is set, what we wind up doing is `set_hybrid_mbr` in kiwi/partitioner/gpt.py , which calls `sgdisk -h`.

The docs for that say:
```
       -h, --hybrid
              Create  a  hybrid MBR. This option takes from one to three partition numbers, separated by colons, as arguments. You may optionally specify a final partition "EE" to indicate
              that the EFI GPT (type 0xEE) should be placed last in the table, otherwise it will be placed first, followed by the partition(s) you specify.  Their type codes are  based  on
              the  GPT  fdisk  type  codes divided by 0x0100, which is usually correct for Windows partitions. If the active/bootable flag should be set, you must do so in another program,
              such as fdisk. The gdisk program offers additional hybrid MBR creation options.
```
So that sounds rather different to this, and to how @schaefi described it in his PR. It doesn't seem to just add a single additional kinda 'spoof' partition with the bootable flag; it tries to write 'realistic' entries for up to three specified real partitions, plus an entry for the EFI GPT, and it explicitly does not set the bootable flag.

I started out wanting to add "hybrid" as a valid option for `efiparttable` here, but that maps awkwardly onto its use on this other codepath. So we could instead use the `gpt_hybrid_mbr` attribute to decide whether to do an Ubuntu-style hybrid layout for ISOs, but it would not be the same kind of GPT/MBR hybridization we do for disk images. Is that too awkward? Thoughts?

**Comment by Conan-Kudo** [comment]
It should be fine. Again, the option currently does nothing for ISOs, so plumbing it to do something is reasonable.
