### ISSUE TITLE
cannot build appliances on a FIPS enforcing host

### ISSUE THREAD

**Issue by dirkmueller** [OSInside/kiwi#2696]
## Problem description

`kiwi-ng system build --description kiwi-main/build-tests/x86/leap/test-image-disk --set-repo obs://openSUSE:Leap:15.6/standard --target-dir /tmp/myimage`

gives

```
[ INFO    ]: 12:45:27 | Creating disk image checksum
[ ERROR   ]: 12:45:27 | Unexpected error:
Traceback (most recent call last):
  File "/usr/bin/kiwi-ng", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/kiwi/kiwi.py", line 68, in main
    App()
  File "/usr/lib/python3.11/site-packages/kiwi/app.py", line 35, in __init__
    task_class().process()
  File "/usr/lib/python3.11/site-packages/kiwi/tasks/system_build.py", line 352, in process
    result = image_builder.create()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/kiwi/builder/disk.py", line 277, in create
    result = self.create_install_media(result)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/kiwi/builder/disk.py", line 510, in create_install_media
    install_image.create_install_iso()
  File "/usr/lib/python3.11/site-packages/kiwi/builder/install.py", line 175, in create_install_iso
    checksum.md5(self.squashed_contents.name + '/' + self.md5name)
  File "/usr/lib/python3.11/site-packages/kiwi/utils/checksum.py", line 84, in md5
    hashlib.md5(), self.source_filename
    ^^^^^^^^^^^^^
_hashlib.UnsupportedDigestmodError: [digital envelope routines] unsupported
```

can you please add `usedforsecurity=False` in the appropriate places if python is new enough? see https://docs.python.org/3/library/hashlib.html#hashlib.new

## Expected behaviour

building works and succeeds

## Steps to reproduce the behaviour

see above

## OS and Software information

* KIWI version: KIWI (next generation) version 10.1.16
* Operating system host version: SUSE Linux Enterprise Server 16.0 (Beta1)
* Operating system target version: openSUSE 15.6
* Open Build Service version (N/A if not using OBS): 
* Koji version (N/A if not using Koji):

**Comment by dirkmueller** [comment]
actually I think `usedforsecurity=False` is actually wrong here because that is used for security here (content integrity checksum). can we update this to something sensible like sha256 or sha512 ?

**Comment by schaefi** [comment]
yes let's get rid of md5 entirely. I will create a fix

**Comment by dcermak** [comment]
Can we get this backported to SLE 15 as well please?

**Comment by dirkmueller** [comment]
> Can we get this backported to SLE 15 as well please?

this should have read "SLE 16" not SLE 15.

**Comment by dcermak** [comment]
> > Can we get this backported to SLE 15 as well please?
> 
> this should have read "SLE 16" not SLE 15.

Why? We ship kiwi as part of SLE 15 too
