### ISSUE TITLE
Support for U-Boot based ARM images (non EFI/Grub2)

### ISSUE THREAD

**Issue by ggardet** [OSInside/kiwi#683]
As reported here: https://lists.opensuse.org/opensuse-arm/2018-04/msg00003.html 
kiwi does not support ARM image builds if they do not support EFI/Grub2.
We cannot convert all boards to EFI/Grub2 unfortunately. So, standard U-Boot support is mandatory.

You can check build logs of JeOS-chromebook or JeOS-sabrelite from https://build.opensuse.org/package/show/openSUSE:Factory:ARM/JeOS

What is missing to support standard U-Boot? I guess we need to add it to https://github.com/SUSE/kiwi/tree/master/kiwi/bootloader maybe something else?

**Comment by schaefi** [comment]
One reason for not having u-boot as loader was that it can't be done in a generic way. So if this needs to be re-added in kiwi-ng it must be done with a better concept than what we have in kiwi v7.

Let's open a discussion together with Alex how that could be done

**Comment by ggardet** [comment]
I think using external scripts (as done partially in EFI/Grub2 mode, I guess), kiwi can still be generic.
Cc: @agraf

**Comment by agraf** [comment]
IIRC the conclusion we had back then was exactly the "custom" firmware attribute which simply does nothing. Any U-Boot specifics would then be handled in external scripts.

**Comment by ggardet** [comment]
One thing is blocking me ATM is bootargs. How to get bootargs in the external script from kiwi?

**Comment by agraf** [comment]
Can you just grab them from /etc/default/grub?

**Comment by ggardet** [comment]
You mean /boot/grub2/grub.cfg ? It would be nice to get it through kiwi vars instead of parsing a file.

**Comment by agraf** [comment]
No, I mean the source file that grub uses to generate grub.cfg: /etc/default/grub

**Comment by ggardet** [comment]
In /etc/default/grub, you do not have all needed info, such as "root=UUID=XXX".

**Comment by schaefi** [comment]
when using the scripts assigned in editbootconfig and editbootinstall the following parameters are passed to the script when kiwi calls them:

* editbootconfig filesystem boot_part_id working_directory
  filesystem: the name of the boot filesystem
  boot_part_id: the partition number of the boot partition
  working_directory: the directory the script is called from

* editbootinstall diskname boot_device_node working_directory
  diskname: path to the image file
  boot_device_node: the device node the boot device is currently mapped to
  working_directory: the directory the script is called from

This information was sufficient back in the old days and I ported that from the old kiwi to the new one. You should see this data in your script as $1, $2, $3 variables in the shell env

**Comment by ggardet** [comment]
I managed to get it working. You can check changes here: https://build.opensuse.org/request/show/593980
But here are a few things which are not very good:
* We need to copy /boot/boot.scr from partition 2, to /boot.scr on partition 1. 
* We have an EFI partition and Grub2 installed, but not used.

Both may confuse user, especially if they want to update boot parameters.

**Comment by schaefi** [comment]
Great that you manage to get it working. I had a recap on this issue together with David and currently we think there is no high demand on arm related changes for boards that can't boot the EFI/Grub2 way.

I agree the superfluous EFI partition is not nice but you can keep it to a minimum with
```efipartsize="xMB"```

Regarding grub, you could uninstall the package as part of the editbootinstall script

If the number of boards we have to support with native uboot and business relevance is
growing please re-open the issue. Thanks
