### ISSUE TITLE
oemboot code incompatiblity with xorriso

### ISSUE THREAD

**Issue by davidcassany** [OSInside/kiwi#903]
## Problem description

OEM images build with old oemboot initrd images seams to not work well with ISO installation images done with xorriso. Images done with xorriso and oemboot early fail at boot time with:

```
Searching for boot device in Application ID.................................[ 58.242885] Failed to find MBR identifier !
```

At a glance it looks like the code that checks and searches the ApplicationID in oemboot code is not compatible with images produced by xorriso.

I might also be related to some issue with the ISO heards that xorriso produces, see https://bugzilla.suse.com/show_bug.cgi?id=1117499

## Expected behaviour

oemboot installation ISO images can boot regardless being build using the cdrtools or xorriso.

## Steps to reproduce the behaviour

Build a an image with `boot="oemboot/SLE12" installiso="true"` in host that makes use of xorriso tool.

**Comment by artur-shaik** [comment]
I have the same `systemException` with `oemboot/suse-leap15.0`. Is there any way to build installable iso file?

**Comment by artur-shaik** [comment]
Ok. It worked fine after I created file: `/etc/kiwi.yml`, with this content:

```yml
iso:
  - tool_category: cdrtools
```

**Comment by davidcassany** [comment]
@artur-shaik thanks for raising it.

I guess that now we can confirm the issue exists. Up to now it was just an impression I had while doing some unrelated testing in late 2018, but I didn't have the chance to dig it by then.

@artur-shaik , just for the records, as this is a tooling related issue, which host distro are you using? which kiwi version you used?

**Comment by artur-shaik** [comment]
I use `OpenSUSE Leap 15.0` and `KIWI 9.17.13`.

**Comment by schaefi** [comment]
Thanks for testing and the reference information. I will do a test build on Leap15.1 and see if this problem still persists. As we have a workaround in switching to cdrtools and the bug (if any) will be on the xorriso side I'm gonna close this one here and come back with an issue report for xorriso if needed
